### ISSUE TITLE
Unable to query snapshots by date

### ISSUE THREAD

**Issue by DataDecay** [googleapis/google-api-python-client#1001]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
  - Python version: `python --version` Python 3.6.10
  - pip version: `pip --version` pip 20.1 from /Users/philipkrauss/miniconda3/envs/dev_auto24/lib/python3.6/site-packages/pip (python 3.6)
  - `google-api-python-client` version: `pip show google-api-python-client` Version: 1.8.2

#### Steps to reproduce

  1. create a client connection and discovery the normal compute service.
  2. attempt to query the creationTimestamp with a "greater than" or "less than", i used >, <, gt, lt, le, ge 

#### Code example

```
>>> mts = conn.gcp_sdk_client.snapshots().list(project='a project name', filter="creationTimestamp eq '2019-08-22T10:25:32.341-07:00'").execute()
>>> for mt in mts["items"]:
...     mt
...
{'id': '12345678...', 'creationTimestamp': '2019-08-22T10:25:32.341-07:00', 'name': 'snapshot-1', 'status': 'READY', ...., 'kind': 'compute#snapshot'}
```

however when you try and filter with a comparison of "greater than" or "less than"

```
>>> mts = conn.gcp_sdk_client.snapshots().list(project='a project name', filter="creationTimestamp gt '2019-08-22T10:25:32.341-07:00'").execute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philipkrauss/miniconda3/envs/dev_gcp24/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/philipkrauss/miniconda3/envs/dev_gcp24/lib/python3.6/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/a project name/global/snapshots?filter=creationTimestamp+gt+%272019-08-22T10%3A25%3A32.341-07%3A00%27&alt=json returned "Invalid value for field 'filter': 'creationTimestamp gt '2019-08-22T10:25:32.341-07:00''. Invalid list filter expression.">
```

#### Stack trace
```
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> mts = conn.gcp_sdk_client.snapshots().list(project='a project name', filter="creationTimestamp gt '2019-08-22T10:25:32.341-07:00'").execute()
INFO:googleapiclient.discovery:URL being requested: GET https://compute.googleapis.com/compute/v1/projects/a project name/global/snapshots?filter=creationTimestamp+gt+%272019-08-22T10%3A25%3A32.341-07%3A00%27&alt=json
DEBUG:google_auth_httplib2:Making request: POST https://oauth2.googleapis.com/token
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philipkrauss/miniconda3/envs/dev_gcp24/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/philipkrauss/miniconda3/envs/dev_gcp24/lib/python3.6/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/a prokect name/global/snapshots?filter=creationTimestamp+gt+%272019-08-22T10%3A25%3A32.341-07%3A00%27&alt=json returned "Invalid value for field 'filter': 'creationTimestamp gt '2019-08-22T10:25:32.341-07:00''. Invalid list filter expression.">
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @DataDecay,

Are you unable to get any filter expressions to work, or is it just "greater than" and "less than"? 

Could you also try this operation with [gcloud](https://cloud.google.com/sdk/gcloud/reference/compute/snapshots/list)? This will help narrow down if the issue is with the library.

Thanks!

**Comment by DataDecay** [comment]
eq/ne and =/!= both work fine, it seems to be the other comparison operators I mentioned. I dont have gcloud installed, nor do I have intentions of using it in my day to day. However, if its needed for comparison, I will see what I can do.

**Comment by DataDecay** [comment]
Filter did not function using gcloud either.

**Comment by busunkim96** [comment]
Hi @DataDecay,

From your experimentation it looks like the source of the problems is the API itself.

Please take a look at https://cloud.google.com/compute/docs/getting-support and raise the issue in one of those channels. That will get visibility from folks who work on the Compute API backend.

Thanks!
