### ISSUE TITLE
Issues with batch readme example

### ISSUE THREAD

**Issue by fabtjar** [googleapis/google-api-python-client#1002]
On the batch readme there are examples on how to make a batch request:
https://github.com/googleapis/google-api-python-client/blob/master/docs/batch.md

One of the lines is: `batch.execute(http=http)`
I'm not sure where the `http` is coming from.

**Comment by busunkim96** [comment]
HI @fabtjar, the `http` argument is optional. I've opened a PR to remove it.

**Comment by fabtjar** [comment]
Cheers @busunkim96 👍
