### ISSUE TITLE
Keep getting "Rate Limit Exceeded" Error

### ISSUE THREAD

**Issue by fabtjar** [googleapis/google-api-python-client#1004]
I'm not sure if it's that I've made too many requests before. I kept getting rate limit errors and have tried to add batching and adding a delay between request but still no luck. Every time now I get the same error.

https://github.com/jqbltd/dev-holiday-calendar/tree/fix-rate-limit-error

Is there anything there that looks wrong to you? Not sure if I'm doing something completely wrong.

**Comment by busunkim96** [comment]
"Rate limit exceeded" means you've made too many requests in a fixed amount of time. https://developers.google.com/calendar/v3/errors#403_user_rate_limit_exceeded explains the steps you should take.

For questions about a specific API it's best to look in the docs and support channels the API provides. https://developers.google.com/calendar/support
