### ISSUE TITLE
Typo in Chrome UX Report batch URI

### ISSUE THREAD

**Issue by fxbtr** [googleapis/google-api-python-client#1010]
Hi, 

I am referring to [new_batch_http_request](http://googleapis.github.io/google-api-python-client/docs/dyn/chromeuxreport_v1.html#new_batch_http_request) where it appears that the built-in URI is https://chromeuxreport.googleapis.com/batch instead of https://chromeuxreport.googleapis.com/batch/

```
from googleapiclient.discovery import build
from googleapiclient.http import BatchHttpRequest

origin_list = [{'origin': 'https://www.google.com'},{'origin': 'https://www.amazon.com'}]

def main():
  def print_origin(req_id, response, exception):
    if exception is not None:
      print('sthing went wrong')
    else:
      print(response['record']['key']['origin'])

  crux_service = build('chromeuxreport', 'v1', developerKey='API_KEY')
   records = crux_service.records()

  #not working 
   batch = crux_service.new_batch_http_request(callback=print_origin)

  #working
  #batch = BatchHttpRequest(callback=print_origin, batch_uri='https://chromeuxreport.googleapis.com/batch/')
  
  req_list = []

  for body in origin_list:
    http_req = records.queryRecord(body=body)
    req_list.append(http_req)

  for req in req_list:
    batch.add(req)

  batch.execute()

if __name__ == "__main__":
    main()
```

returns 

> Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 31, in main
    batch.execute()
  File "/home/x/monitoring-chrome-UX/.venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/x/monitoring-chrome-UX/.venv/lib/python3.8/site-packages/googleapiclient/http.py", line 1528, in execute
    self._execute(http, self._order, self._requests)
  File "/home/x/monitoring-chrome-UX/.venv/lib/python3.8/site-packages/googleapiclient/http.py", line 1462, in _execute
    raise HttpError(resp, content, uri=self._batch_uri)
googleapiclient.errors.HttpError: <HttpError **404** when requesting https://chromeuxreport.googleapis.com/batch returned "Not Found">

but if `batch = BatchHttpRequest(callback=print_origin, batch_uri='https://chromeuxreport.googleapis.com/batch/')` instead of `batch = crux_service.new_batch_http_request(callback=print_origin)`

then it works as expected

> https://www.google.com
https://www.amazon.com

Best regards,
FX

**Comment by busunkim96** [comment]
Hi @fxbtr, thanks for filing an issue.

I'm fairly sure *both* should be accepted by the backend.  For comparison I tried the api `websecurityscanner` with both `batch` and `batch/` and both seem to be acceptable (I get 400's instead of 404).

```
busunkim-macbookpro1% curl -X POST https://websecurityscanner.googleapis.com/batch/
{
  "error": {
    "code": 400,
    "message": "Failed to get multipart boundary.",
    "status": "INVALID_ARGUMENT"
  }
}
busunkim-macbookpro1% curl -X POST https://websecurityscanner.googleapis.com/batch
{
  "error": {
    "code": 400,
    "message": "Failed to get multipart boundary.",
    "status": "INVALID_ARGUMENT"
  }
}
```

I've filed an issue on the Chrome UX Report API's team's internal issue tracker. 

Googlers see 167207413.

**Comment by busunkim96** [comment]
Fix has been applied internally and should rollout within the next few days.
