### ISSUE TITLE
Download file as of a certain timestamp

### ISSUE THREAD

**Issue by dannysepler** [googleapis/google-api-python-client#1013]
Hi all! Is it possible to download a Gsuite file (specifically a spreadsheet) as of a given date? Perhaps using the "Version History" of the document?

I'm trying to plug a spreadsheet into a scheduled job in a way that I can rerun a historic job and still achieve the same results. Something like...

```
sheet.values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID,
                                range=SAMPLE_RANGE_NAME,
                                by=TIMESTAMP).execute()
```

Thanks!

**Comment by busunkim96** [comment]
Hi @dannysepler,

I think you can accomplish something similar via`Revisions` in the Drive API. I don't think you can query for a specific time, but you can filter through the revisions and select the one closest one,

- https://developers.google.com/drive/api/v3/reference/revisions
- http://googleapis.github.io/google-api-python-client/docs/dyn/drive_v3.revisions.html

**Comment by dannysepler** [comment]
thanks @busunkim96!
