### ISSUE TITLE
Token pickle issue

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1014]
Google Calendar API Bug
#### Environment details
python 3.8.3
google-cloud==0.34.0
#### Code example
```
class CalendarIntentHandler(AbstractRequestHandler):
    def handle(self, handler_input):
        event = {
        'summary': 'Test',
        'location': 'At home',
        'description': 'A chance to hear more about Google\'s developer products.',
        'start': {
            'dateTime': '2020-07-29T12:12:10',
            'timeZone': 'America/Los_Angeles',
        },
        'end': {
            'dateTime': '2020-07-29T12:32:47',
            'timeZone': 'America/Los_Angeles',
        }
        }
        creds = None
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        # If there are no (valid) credentials available, let the user log in.
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                #Alexa way of retrieving user's access token
                creds = handler_input.request_envelope.context.system.user.access_token
            # Save the credentials for the next run
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)

```
#### Error:
```
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 118, in dispatch
    output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
    output = supported_handler_adapter.execute(
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
    return handler.handle(handler_input)
  File "/var/task/lambda_function.py", line 280, in handle
    with open('token.pickle', 'wb') as token:
OSError: [Errno 30] Read-only file system: 'token.pickle'END RequestId
```
Running this on Lambda. Not sure how I shall tackle this error. Followed [quickstart](https://developers.google.com/calendar/quickstart/python)

**Comment by busunkim96** [comment]
Is `creds` the credentials represented in JSON? If that's the cause I believe you want [`from_authorized_user_info`](https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html?highlight=from#google.oauth2.credentials.Credentials.from_authorized_user_info). That function will turn the JSON back into a credentials object.

The pickling is used in the quickstart to save the token for future use, but it's unnecessary if they're already being saved.

**Comment by danieldhz** [comment]
Hi @busunkim96 Thanks for your reply!
The `creds` is actually retrieving the user's access token via `handler_input.request_envelope.context.system.user.access_token` and not the json file. To be honest, I am really lost whether I shall use the json file or the user's access token. If it were to be the JSON, I am not sure how would the code be able to identify a user when it's reading the hardcoded credentials of mine in the .json file.

**Comment by busunkim96** [comment]
In that case you can construct `google.oauth2.Credentials` object from the access token. If you provide a refresh token the library can refresh the token for you. https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html

```py
import google.oauth2.credentials

creds = google.oauth2.credentials.Credentials(
    token=handler_input.request_envelope.context.system.user.access_token,
    refresh_token="..."
)
```


https://developers.google.com/identity/protocols/oauth2 provides a high level overview of the OAuth2 flow for Google APIs.

**Comment by danieldhz** [comment]
@busunkim96 Thanks for your response. You mean if I provide an access token, the library...?
As well as, I think i got the error here. 
If you look at the code, I replaced:
```
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
```
with 
`creds = handler_input.request_envelope.context.system.user.access_token`
As can be seen, even though I did retrieve the user's access token & later on serialize it, I haven't inputted the SCOPES part nor know where I can input.
Because once I ran the fist code as indicated by the quickstart I get:

```
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 118, in dispatch
    output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
    output = supported_handler_adapter.execute(
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
    return handler.handle(handler_input)
  File "/var/task/lambda_function.py", line 291, in handle
    flow = InstalledAppFlow.from_client_secrets_file('creds.json', SCOPES)
  File "/opt/python/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 199, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 158, in from_client_config
    raise ValueError(
ValueError: Client secrets must be for a web or installed app.END RequestId
```

**Comment by danieldhz** [comment]
@nikhilym

**Comment by danieldhz** [comment]
on a sepereate note, @busunkim96 is there a way I can pass the SCOPES and json file without calling             
```
flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
```
I believe that's what hindering progress. At the same time, the [module](https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html) you provided doesn't;t have an arg for the json file.

**Comment by parthea** [comment]
Hi @DaniyalDhz ,

I'm going to close this issue as guidance was provided in #1032. If you're still having trouble please re-open this issue with additional information.

**Comment by kyawsanoo528528-beep** [comment]
google token pickle command give me
