### ISSUE TITLE
Event not being created despite no error. Debugging advice?

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1017]
#### Environment details
python 3.8.3
google-cloud==0.34.0

#### Code example
```py
import os
import pickle
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'Timer_Hello_Layered/creds.json'        
            
event = {
'summary': 'Test',
'location': 'At home',
'description': 'A chance to hear more about Google\'s developer products.',
'start': {
    'dateTime': '2020-07-29T12:12:10',
    'timeZone': 'America/Los_Angeles',
},
'end': {
    'dateTime': '2020-07-29T12:32:47',
    'timeZone': 'America/Los_Angeles',
}
}
#way of retrieving access token with alexa skill
creds = handler_input.request_envelope.context.system.user.access_token
#have to add /tmp/ when dealing with AWS lambda
SCreds = pickle.dump(creds, open("/tmp/save.pickle","wb")) 
service = build('calendar', 'v3', credentials= SCreds, cache_discovery=False)    
event = service.events().insert(calendarId='primary', body=event).execute()
```
#### Error: Nothing.

Yet when I check my calendar as a user, I don't see the event in my calendar. Any debugging advice? what shall i do?

**Comment by busunkim96** [comment]
Hi @danieldhz,

It might be worth checking that the credentials are the ones you expect -- `primary` is shorthand for "currently logged in user".  If you're not seeing any errors, one possibility is that the event is being added to some other calendar.

You can also try passing an explicit calendarId to see if that succeeds. To fetch a list of calendarIds, use [`CalendarList.list`](https://developers.google.com/calendar/v3/reference/calendarList/list).

**Comment by danieldhz** [comment]
Hi @busunkim96 
Thank you so much for your thoughtful response. I logged into the OAuth with my personal email and thought that would be considered as the only and primary email for API connections, as it received my access token. Am I wrong? can it go to another email despite not loginig in the Oauth of the app?

**Comment by busunkim96** [comment]
It looks like you're referencing three different credentials files/tokens so I'm not quite sure what's happening there. If there are no errors I assume it's working though.

If the user credentials were created from your personal account than the calendar should also be for that account.

Can you try passing a specific `calendarId`? You can fetch a list of calendarIds via the UI on the right hand side of https://developers.google.com/calendar/v3/reference/calendarList/list (Try this API).

**Comment by danieldhz** [comment]
@busunkim96 are you counting calendarID as a credential too? I am not even using `os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'Timer_Hello_Layered/creds.json'  ` as I am not sure whether .json should inputted in the `credentials=` or the user access token retrieved by `creds`. Which one do you advise me to input for my voice app?
I will try the CalendarId now.

**Comment by busunkim96** [comment]
No, calendarId is separate from credentials (a calendarId identifies a specific calendar). 

If your app is going to be used by multiple users you'll need to make sure you're getting credentials from each user. You cannot pass a raw json or string as a credential. The library expects a credentials object.  For user credentials you would use https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html.

**Comment by danieldhz** [comment]
Ohh I see. I mean once I called 'handler_input.request_envelope.context.system.user.access_token' I get:

			```
"user": {
				"userId": "amzn1.ask.account.AGXW6V44I4Q....LDY2I7CXAY",
				"accessToken": "ya29.a0AfH6SMBxMhLs7n....-ge8PrOu72qVg",
				"permissions": {
					"consentToken": "eyJ0eXAiOiJKV1QiLCJ...PgMPxdLmVi-iqabZJGpvmnYkPolJMeA"
				}
```
Thus, I thought retrieving the accessToken and then converting it to an object via pickling (just like the quickstart) would do the job. Please let me know if I am wrong? if so, how?
As well as, once I called              `calendar_list_entry = service.calendarList().get(calendarId='calendarId').execute()
`
I got back:

```
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 118, in dispatch
    output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
    output = supported_handler_adapter.execute(
  File "/opt/python/lib/python3.8/site-packages/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
    return handler.handle(handler_input)
  File "/var/task/lambda_function.py", line 294, in handle
    calendar_list_entry = service.calendarList().get(calendarId='calendarId').execute()
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/python/lib/python3.8/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/users/me/calendarList/calendarId?alt=json returned "Not Found">
```

**Comment by busunkim96** [comment]
Are you using credentials from Amazon? That's not something we support at the moment. You'll need to fetch a Google supplied auth token.

**Comment by danieldhz** [comment]
I believe I am using google's credential as the acccessToken **only** comes when I authorize amazon through OAuth and it gives me a success message. Therefore, I believe at the end of the day it's google accessToken or at least google is giving permission? or are you implying that even if the accessToken shows up & the user has authorized via redirection, that accessToken is coming from Amazon & not google?

**Comment by parthea** [comment]
Hi @DaniyalDhz ,

I'm going to close this issue as guidance was provided in #1032. If you're still having trouble please re-open this issue with additional information.
