### ISSUE TITLE
TypeError: Got an unexpected keyword argument for documented arguments while working with the admin directory_v1 users.watch function

### ISSUE THREAD

**Issue by nheimann1** [googleapis/google-api-python-client#1018]
I'm using the admin directory_v1 API, via the this library.

The code worked well for 18 months, and suddenly stopped working at August 21 without any change in the code in our end.

The following code produce the bug: (more details can be found on [this](https://stackoverflow.com/questions/63656799/the-users-watch-function-in-google-admin-directory-sdk-suddenly-throws-exceptio) Stackoverflow question)

```
import googleapiclient.discovery
        
adminDirectoryService = googleapiclient.discovery.build('admin', 'directory_v1', credentials = gsuiteCredentials, cache_discovery=False)

result = adminDirectoryService.users().watch(body=watchBody, projection=projection, event=eventType, maxResults=1, customer=gSuiteCutomerId, viewType=viewType).execute()
```
The result is:

```
result = adminDirectoryService.users().watch(body=watchBody, projection=projection, event=eventType, maxResults=1, customer=gSuiteCutomerId, viewType=viewType).execute()
File "/env/lib/python3.7/site-packages/google_api_python_client-1.7.8-py3.7.egg/googleapiclient/discovery.py", line 723, in method
    raise TypeError('Got an unexpected keyword argument "%s"' % name)
TypeError: Got an unexpected keyword argument "projection"

```
The error was tested also with the latest google_api_python_client 1.11.0

Further testing show that the same happens with some of the other arguments like _maxResults_ and _viewType_.

The source of the issue is from the json (comes from [here](https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest)) the discovery.build is using to wrap the Admin SDK API. The json doesn't describe those arguments, and therefore the exception is being raised from the client library code.

I never seen the version which did supported those arguments, but I assume they appeared there.

This change was made without notifications to the users, and I still don't see anywhere that those arguments are not supported. Even currently in the API [documentation](https://google-api-client-libraries.appspot.com/documentation/admin/directory_v1/python/latest/admin_directory_v1.users.html#watch) they appear.

Please note,
I have filed the [same issue](https://issuetracker.google.com/issues/167259201) to the Google Admin SDK team, but was directed to file the issue here.

Based on the answer in [this issue](https://github.com/googleapis/google-api-python-client/issues/733)  and reading [this comment](https://github.com/googleapis/google-api-python-client/issues/733#issuecomment-518425646) I assume the Google Admin SDK team should fix the documentation or the JSON file.

Thank you

**Comment by busunkim96** [comment]
Hi @nheimann1,

Your understanding is correct - the library is built by parsing the JSON so the backend team will need to make that change. It appears the change was unintentional and a fix is in progress.

**Comment by busunkim96** [comment]
Changes have been rolled out. @nheimann1 could you check if things are working as expected now?

**Comment by nheimann1** [comment]
Thank you @busunkim96 . I'll test it let you know.

**Comment by busunkim96** [comment]
The library appears to no longer raise an error when "projection" is passed.

```py
>>> from googleapiclient import discovery
>>> service = discovery.build("admin", "directory_v1")
>>> service.users().watch(body="a", projection="basic")
```
