### ISSUE TITLE
Update event overrides *all* previous details

### ISSUE THREAD

**Issue by orar7598** [googleapis/google-api-python-client#1019]
Hi everyone,
Please take a look at my code:
```
body = {'attedees': [{'email': attendee_email}], 'start': {'dateTime': '2020-09-12T16:30:00+03:00'}, 
'end': {'dateTime': '2020-09-12T17:30:00+03:00'}}

        try:
            update_event = calendar_service.events().update(calendarId=cal_id,
                                                                  eventId=event_id,
                                                                  body=body).execute()
            return update_event

        except Exception as updateEVTerror:
            return updateEVTerror
```
It just deletes all the previous data of the event (including summary, title, attendees, which wasn't even mention in the body request) instead of just adding the new attendees from the JSON.
Am I missing something?
Thanks.

**Comment by busunkim96** [comment]
Hi @orar7598,

`.patch()` will update only the fields you have passed. `.update()` replaces the existing event with whatever is passed. 

https://developers.google.com/calendar/v3/reference/calendars/patch
https://developers.google.com/calendar/v3/reference/calendars/update
