### ISSUE TITLE
Example needed: Directory API user creation

### ISSUE THREAD

**Issue by karlosss** [googleapis/google-api-python-client#1021]
Hello!

Sorry in advance for a newbie question. I followed the tutorial at https://developers.google.com/admin-sdk/directory/v1/quickstart/python and managed to get the list of users. I am now trying to create a new user and so far I've failed to find an example or a piece of docs which would help me. Looking into the code, I found out that `service.users().insert(...).execute()` would probably do it, however I don't know how to pass the body holding the name, password and email. Any help is appreciated!

**Comment by busunkim96** [comment]
Hi,

http://googleapis.github.io/google-api-python-client/docs/dyn/admin_directory_v1.users.html#insert has the information you need.

Note that the JSON body is the same as what you'd pass to the API directly. The documentation on developers.google.com has better formatting and also provides the "Try this API" UI: https://developers.google.com/admin-sdk/directory/v1/reference/users/insert.
