### ISSUE TITLE
GenerateMediationReportResponse result parsing

### ISSUE THREAD

**Issue by dtiwar** [googleapis/google-api-python-client#1023]
Admob - How do we parse the GenerateMediationReportResponse in python? the new AdMob API return the list and looks we need an additional parser. 
we are using Adsense API where the execute method returns the dict and lot easier to work with.

**Comment by busunkim96** [comment]
Hi,

Folks in the [AdMob Developer Forum](https://groups.google.com/forum/#!forum/google-admob-api-developer-forum) should be able to help you with that. Please create a post there.

Thanks!
