### ISSUE TITLE
How add user to group existent with Python

### ISSUE THREAD

**Issue by KelvinFerraz** [googleapis/google-api-python-client#1024]
Hello,

How I can add user to an specific group?

I tryed this:
`content = {  'groupKey': 'mygroup@example.com', "email": "new.user@example.com" }`
`add_group = service.members().insert(content=content).execute()`

But i receive this error:

**`env/lib/python3.8/site-packages/googleapiclient/discovery.py", line 872, in method raise TypeError('Got an unexpected keyword argument "%s"' % name)`**

My **new.user** is added normaly, just add that user to a group that is not working.

Thanks

**Comment by busunkim96** [comment]
Hi @KelvinFerraz,

Which API are you using? Could you show us a bit more of your code?

**Comment by KelvinFerraz** [comment]
Hi @busunkim96 

This my code:

```
creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('admin', 'directory_v1', credentials=creds)

    # Passwd from create_passwd
    passwd = create_passwd(32)

    # Parameters from argv ex: python script.py name surname
    name = str(sys.argv[1])
    surname = str(sys.argv[2])

    print('........................................................')

    print('Add User')
    body = { "name": 
          {"familyName": "{surname}".format(surname=surname).title(), "givenName": "{name}".format(name=name).title()}, 
         "password": "{passwd}".format(passwd=passwd), 
         "primaryEmail": "{firstname}.{secondname}@example.com".format(firstname=name, secondname=surname),
         "changePasswordAtNextLogin": "true", 
       }

    # Execute Add User
    user_add = service.users().insert(body=body).execute()

    body_group = {"email": "{firstname}.{secondname}@example.com".format(firstname=name, secondname=surname)}
    add_group = service.members().insert(body_group=body_group).execute()
```

**Comment by busunkim96** [comment]
It looks like the error is coming from:

```py
add_group = service.members().insert(body_group=body_group).execute()
```

The method `insert` expects the kwarg `body`.

```py
add_group = service.members().insert(body=body_group).execute()
```

http://googleapis.github.io/google-api-python-client/docs/dyn/admin_directory_v1.users.html#insert

**Comment by KelvinFerraz** [comment]
@busunkim96 

Thaks,

I'm just tried but now i received another error:

```
googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/groups/name%40example.com/members?alt=json returned "Request had insufficient authentication scopes.">
```

**Comment by busunkim96** [comment]
What scopes are you providing? https://developers.google.com/identity/protocols/oauth2/scopes#admin-directory lists all the scopes for Admin Directory.

If you're just working with users `https://www.googleapis.com/auth/admin.directory.user` should be enough.

**Comment by KelvinFerraz** [comment]
@busunkim96 

I don't configured nothing about  oauth2

I'm just follow this documentation:

https://developers.google.com/admin-sdk/directory/v1/quickstart/python

And tried testing

**Comment by KelvinFerraz** [comment]
@busunkim96 

I'm check and I use admin.directory.user:


```
# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/admin.directory.user']

```

**Comment by KelvinFerraz** [comment]
@busunkim96 


Thank you very much!

I did configure again, used this configuration:

![image](https://user-images.githubusercontent.com/12374339/92952628-ad3ba500-f436-11ea-9cef-387a12d96cd8.png)

It's working now
