### ISSUE TITLE
Classroom API students create google calendar bug

### ISSUE THREAD

**Issue by ahmadbeirkdar** [googleapis/google-api-python-client#1028]
#### Environment details

  - OS type and version: macOS Catalina
  - Python version: `python --version` 3.8

#### Steps to reproduce

  1.  Use the service.courses().students().create() method to directly add a student to the classroom

When the student is added, and shows up in the classroom. The student can not see the google classroom's calendar in google calendar... Not sure why this is happening, when adding the user normally without the API it shows up. 
Thanks

**Comment by busunkim96** [comment]
Hi @ahmadbeirkdar,

This issue tracker is for the google-api-python library. It looks like this issue is with the API itself. Please use one of the Calendar API support channels. https://developers.google.com/calendar/support

Thanks!

**Comment by ahmadbeirkdar** [comment]
> Hi @ahmadbeirkdar,
> 
> This issue tracker is for the google-api-python library. It looks like this issue is with the API itself. Please use one of the Calendar API support channels. https://developers.google.com/calendar/support
> 
> Thanks!

Thanks! Will do.

For now I have found a way around this by simply using the acl calendar api
