### ISSUE TITLE
googleapiclient.discovery.build fails with module 'six.moves' has no attribute 'collections_abc' since version 1.12.0

### ISSUE THREAD

**Issue by jqll** [googleapis/google-api-python-client#1029]
#### Environment details

  - OS type and version: 18.04.1-Ubuntu
  - Python version: Python 3.6.9
  - pip version: `pip --version` pip 9.0.1
  - `google-api-python-client` version: `pip show google-api-python-client`: Version: 1.12.0

#### Code example
googleapiclient.discovery.build() fails with message: module 'six.moves' has no attribute 'collections_abc'

We only see this problem with google-api-python-client 1.12.0. 1.11.0 is fine.

**Comment by tomthorogood** [comment]
This affects my team also, and now all of our Travis builds are failing.

**Comment by kalyanac** [comment]
Our probers failed, which is how we stumbled up on this. I am also curious why this was not caught in unit tests before it got merged and released.

**Comment by busunkim96** [comment]
Hi @jqll,

Thanks for filing an issue. It looks like this is a result of not advancing the lower bound on `six`. `collections_abc` is only available in `six>=1.13.0`. See [six's changelog](https://github.com/benjaminp/six/blob/c0be8815d13df45b6ae471c4c436cce8c192245d/CHANGES#L25-L36).

https://github.com/googleapis/google-api-python-client/blob/5eff2d2e6173b3018361851c91b7b565b07ea608/setup.py#L37-L47

@kalyanac At the moment tests always install the latest version of dependencies. We're going to move to having explicit `requirements.txt` for tests runs so we catch lower bound issues like this automatically in the future.

For now, you can use `1.11.0` or upgrade `six`. A new release `1.12.1` should be released later today with the adjusted pin on `six`.

**Comment by kalyanac** [comment]
Thank you for the detailed response and the quick action.

**Comment by jqll** [comment]
Thanks for the quick fix!
