### ISSUE TITLE
Alternative to quick start's code snippet?

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1032]
#### Environment details
python 3.8.3
google-cloud==0.34.0
#### Issue
Is there a way I can pass the SCOPES, access token( or creds) and json file without calling

```
flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
```
?
As i can't run a local server on an Alexa skill. At the same time, the [module ](https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html) doesn't have an arg for the .json file to be inputted. if I were to use instead.

**Comment by busunkim96** [comment]
If you are accessing resources on behalf of a user, you need to obtain access tokens. `run_local_server` is a method provided to make that convenient when developing locally. If using that is not possible, you'll have to obtain the access and refresh tokens some other way. See https://developers.google.com/identity/protocols/oauth2.

You would then create `Credentials` objects using the class constructor.

If you're not accessing the API on behalf of user account, you can use a service account instead.

https://cloud.google.com/docs/authentication/production

**Comment by parthea** [comment]
Hi @DaniyalDhz,

I'm going to close this issue as guidance was provided in the last comment. If you're still having trouble please re-open this issue with additional information.
