### ISSUE TITLE
module 'six.moves' has no attribute 'collections_abc'

### ISSUE THREAD

**Issue by celsooliveiraTBDE** [googleapis/google-api-python-client#1033]
module 'six.moves' has no attribute 'collections_abc'

File "/admob/auth_flow.py", line 52, in create_service
--
15-Sep-2020 11:11:03 | return googleapiclient.discovery.build(svc, version, http=http)
15-Sep-2020 11:11:03 | File "/usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
15-Sep-2020 11:11:03 | return wrapped(*args, **kwargs)
15-Sep-2020 11:11:03 | File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery.py", line 286, in build
15-Sep-2020 11:11:03 | adc_key_path=adc_key_path,
15-Sep-2020 11:11:03 | File "/usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
15-Sep-2020 11:11:03 | return wrapped(*args, **kwargs)
15-Sep-2020 11:11:03 | File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery.py", line 455, in build_from_document
15-Sep-2020 11:11:03 | if isinstance(client_options, six.moves.collections_abc.Mapping):
15-Sep-2020 11:11:03 | AttributeError: module 'six.moves' has no attribute 'collections_abc'

**Comment by busunkim96** [comment]
Hi @celsooliveiraTBDE,

This looks like #1029 Are you using `1.12.1` (the latest release?).

**Comment by yellowladder** [comment]
Having this issue as well, using 1.12.1.
Is the six module wrapped? We've never had to install it explicitly, first I've heard of it.

**Comment by samellas** [comment]
@yellowladder Had the same problem this morning.

six is one of the libraries installed by default based on your DBR verison. 6.6 and below use 1.12.0. https://docs.databricks.com/release-notes/runtime/6.6.html#installed-python-libraries

I updated to 7.0 and the issue was gone.

**Comment by yellowladder** [comment]
@samellas that worked, thank you for that.

**Comment by celsooliveiraTBDE** [comment]
Pinning version to 1.11.0 for now based on #1029. Thanks, @busunkim96
