### ISSUE TITLE
"The purchase is not in a valid state to perform the desired operation." Callback

### ISSUE THREAD

**Issue by umityayla** [googleapis/google-api-python-client#1034]
Hello,

We're confirming receipts using `SERVICE.purchases().products().acknowledge()` method. But there are countless receipts that return with "The purchase is not in a valid state to perform the desired operation." when we contacted the Google Support channel, they didn't help us at all. Is there any chance that we could get a proper explanation regarding this callback?

**Comment by busunkim96** [comment]
Hi @umityayla,

This sounds like a question for the service team. Which API are you using?

**Comment by umityayla** [comment]
We use the Play Services API. And yes, you are definetily right, but we got so little help from the support team that they even misread(?) the callback string and sent us the link to a Stackoverflow [question](https://stackoverflow.com/questions/193154/the-operation-is-not-valid-for-the-state-of-the-transaction-error-and-transact) regarding a SQL Server issue.

**Comment by busunkim96** [comment]
Hi,

Just to confirm, you're using the Google Play Developer API (https://developers.google.com/android-publisher) and reached out via one of the channels listed at https://support.google.com/googleplay/android-developer/answer/7218994?

**Comment by umityayla** [comment]
Yes, unfortunately that's correct.

**Comment by umityayla** [comment]
Any update on the issue? @busunkim96

**Comment by busunkim96** [comment]
> per the message in the issue ("The purchase is not in a valid state to perform the desired operation."), they can try doing a "get" first to see if "acknowledge" is a valid transition.

The engineer says they'd need a `purchaseToken` to do any further debugging. I think you can open an issue [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and they will take a look.

**Comment by umityayla** [comment]
Thank you for your help and have a nice day!

**Comment by umityayla** [comment]
Sorry for not posting a follow up. Contacted Google through issue tracker and their answer was the following way;

> This may happen when you're trying to acknowledge or consume an item that is pending (not this case) or already marked acknowledged or consumed (likely this case).
