### ISSUE TITLE
Issues about "AttributeError: module 'six.moves' has no attribute 'collections_abc'"

### ISSUE THREAD

**Issue by kasumi515** [googleapis/google-api-python-client#1039]
I encountered this error message when I was trying to use google analytics API in python

**AttributeError: module 'six.moves' has no attribute 'collections_abc'**

Here is my python code:

> from oauth2client.service_account import ServiceAccountCredentials
> from apiclient.discovery import build
> import httplib2
>  
> credentials = ServiceAccountCredentials.from_json_keyfile_name('client_secrets.json', ['https://www.googleapis.com/auth/analytics.readonly'])
>   
> http = credentials.authorize(httplib2.Http())
> service = build('analytics', 'v4', http=http, discoveryServiceUrl=('https://analyticsreporting.googleapis.com/$discovery/rest'))

I noticed that someone might have filed the same issue couple days ago, but I still ran into this issue. 
Here is the version info of google-api-python-client:

> google-api-python-client-1.12.1 (by **pip show google-api-python-client**)
> google-api-core-1.22.2 
> google-api-python-client-1.12.1 
> google-auth-1.21.2 
> google-auth-httplib2-0.0.4 
> httplib2-0.18.1 
> six-1.15.0

I am wondering if there is any revision I need to do to fix this issue?
Thank you in advance.

**Comment by busunkim96** [comment]
`collections` was added to six in 1.13.0, so if you are using 1.1.50 it should be available. https://github.com/benjaminp/six/blob/c0be8815d13df45b6ae471c4c436cce8c192245d/CHANGES#L25-L36

Can you try in a new virtualenv?
```
python3 -m venv env
source env/bin/activate
python3 -m pip install ...
python3 -m name_of_script.py
```

In addition, oauth2client is no longer maintained so you should use [google-auth](https://googleapis.dev/python/google-auth/latest/user-guide.html).

```python
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/path/to/key.json')

scoped_credentials = credentials.with_scopes(
    ['https://www.googleapis.com/auth/cloud-platform'])
```

**Comment by kasumi515** [comment]
@busunkim96 
Thank you so much for your reply! 
I tried to install the packages in a new virtualenv and it worked! 
Here is the code I used for others' reference:

```
from google.oauth2 import service_account
from googleapiclient.discovery import build
 
credentials = service_account.Credentials.from_service_account_file('client_secrets.json')
scoped_credentials = credentials.with_scopes(['https://www.googleapis.com/auth/cloud-platform'])

#Create a service object
service = build('analytics', 'v3', credentials=scoped_credentials)
```

**Comment by afaghm** [comment]
I still have this problem. Six is updated to 1.15.0 and google api client is updated to 1.12.2. I have also tried installing packages in a new environment but to no avail. Is anyone able to help please?

**Comment by keepcool13** [comment]
I get the same error, but I'm using the Earth Engine Python API. I need it for for a plugin in a third-party software, so I don't think I can use a virtual environment. I filed the error in that project of the plugin: https://github.com/gee-community/qgis-earthengine-plugin/issues/67 but when I looked closer I realized that the bug actually comes from here. So this bug affects not only the Analytics API, but multiple Google APIs.

**Comment by busunkim96** [comment]
I've confirmed that `setup.py` is correctly requiring >=1.13.0. Please check where your version pins and bump to a sufficiently new version of `six`.

https://github.com/googleapis/google-api-python-client/blob/2d076b87cff4029a243357dad19564767bbf8751/setup.py#L45
