### ISSUE TITLE
Upload result "Raw file: Unknown"

### ISSUE THREAD

**Issue by SnoOpyMinhThang** [googleapis/google-api-python-client#104]
With API v2 I can upload with sample python script, and "Raw file" always same with file name.
But with API v3, "Raw file" always is "unknown".
I tried both sample python: https://github.com/youtube/api-samples/tree/master/python script and youtube-upload tool: https://github.com/tokland/youtube-upload, but no luck :"/

This property play important role in video SEO ranking.
![screenclip](https://cloud.githubusercontent.com/assets/10328775/8122616/94dd69fa-10e6-11e5-9a02-602879e2d0c7.png)

Any workaround, please!

**Comment by mcdonc** [comment]
Triaging.

I verified that the description of the symptom is accurate via:

```
bin/python /home/chrism/projects/gcloud/youtube-api-samples/python/upload_video.py --file wickedgame.mp4 --title "Wicked Game" --description "Wicked game recording"
```
"Raw file" field is indeed "unknown".

Not sure about whether this is a feature or a bug.

**Comment by mcdonc** [comment]
The v2 API is gone, apparently:

https://youtube-eng.googleblog.com/2015/04/bye-bye-youtube-data-api-v2.html

**Comment by busunkim96** [comment]
Uploads via the API still produce a raw field name or "unknown". The raw filename _does not_ play a role in SEO ranking. If you have another reason for wanting accurate filenames from API uploads, please try adding the 'Slug' header as a temporary workaround. 

```
  query = service.videos().insert(
    body=resource,
    media_body=media_body,
    **kwargs
  )
  query.headers['Slug'] = 'raw_filename_here.flv'
  results = query.execute()
```
