### ISSUE TITLE
googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters  version: v3

### ISSUE THREAD

**Issue by iamsaurabhgupt** [googleapis/google-api-python-client#1042]
OS macOS: 10.15.4
Python version: python 3.8.1
pip version: pip 19.0.3
google-api-python-client version: 1.12.1

Code example
from googleapiclient.discovery import build
build('webmasters', "v3", developerKey="developer_key")
Stack trace
googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters version: v3

Hi Team,

While trying to get data from Search Console API and get this error UnknownApiNameOrVersion.
I tried the discovery API and it showed the the discoveryRestUrl as
`https://www.googleapis.com/discovery/v1/apis/webmasters/v3/rest`
![image](https://user-images.githubusercontent.com/43205009/93962585-c6b6e800-fd78-11ea-888c-9363c7de85b2.png)
But, the same url on web is down:
![image](https://user-images.githubusercontent.com/43205009/93962640-e51ce380-fd78-11ea-8b90-08e9154f34c3.png)
Please rectify immediately.
All our reports are breaking.

**Comment by ngodinhnhien** [comment]
I have the same issue with the api
`raise UnknownApiNameOrVersion(“name: %s  version: %s” % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters  version: v3`

It worked fine yesterday, but this morning the issue has came

**Comment by pualien** [comment]
same issue for me, started three hours ago

**Comment by IreneSoligno** [comment]
We are experiencing the same issue as well

**Comment by laura-barkauskaite** [comment]
We have the same issue.

**Comment by aethemba** [comment]
We are also running into this issue

**Comment by sloev** [comment]
we are seeing this too, 
using reqbin you can check its an issue from both US, DE and us in DK 

https://reqbin.com/c-4rgtzhsk

> curl 'https://www.googleapis.com/webmasters/v3/'

gives 404

related issues:

* https://github.com/googleapis/elixir-google-api/issues/6399

**Comment by sloev** [comment]
@busunkim96 have you heard anything?

somebody tweet about it, crossing fingers for fast solution
https://twitter.com/davidiwanow/status/1308675174003245057

**Comment by franloza** [comment]
Same issue for me, 1 hour ago

**Comment by paddie** [comment]
We are seeing the same issue, since 2 in the morning and as recent as 10 minutes ago, from `europe-west1`

**Comment by Jonnyblacklabel** [comment]
I'm also running into this issue. Data pipelines started at 2 in the morning. All were running into this problem.
Tried localy, and it was working for 5 minutes. Now it's broken again.

**Comment by olycats** [comment]
Same here. Started some time within 24 hours.

**Comment by raimondast** [comment]
this issue is region related. https://webmasters.googleapis.com/$discovery/rest?version=v3 is reachable from US, but not in major EU.

**Comment by Jonnyblacklabel** [comment]
https://twitter.com/Jonnyblacklabel/status/1308686798474838016?s=20

tweeted about it

**Comment by sloev** [comment]
a very unscientific test involving https://proxy-ams.hidemyass-freeproxy.com/ showed the following http responses based on different locations (right now)

NY: 404
seattle: 200
frankfurt: 200
amsterdam: 404
praque: 200

**Comment by paddie** [comment]
> edit hi @paddie 🤗
hello darling @sloev - what are you doing here?

**Comment by sloev** [comment]
grocery shopping some sweet lookin' data but google wont give it to me after i paid for it :trollface: 
....and firing off mischievous jokes of course ;-)

**Comment by paddie** [comment]
> grocery shopping some sweet lookin' data but google wont give it to me after i paid for it :trollface:
> ....and firing off mischievous jokes of course ;-)

Doing god's work here bud :)

**Comment by Jonnyblacklabel** [comment]
It seems that `discovery.build('searchconsole', 'v1')` is working. Can somebody verify that? 
According to the documentation this is only the beta endpoint for the url testing tool
https://developers.google.com/webmaster-tools/search-console-api/reference/rest

**Comment by raimondast** [comment]
> It seems that `discovery.build('searchconsole', 'v1')` is working. Can somebody verify that?
> According to the documentation this is only the beta endpoint for the url testing tool
> https://developers.google.com/webmaster-tools/search-console-api/reference/rest

I just tried that and it seems to work, but not sure if this is the one to use

**Comment by Jonnyblacklabel** [comment]
Google said here already https://webmasters.googleblog.com/2020/08/search-console-api-announcements.html that they would change the API. However, they have set the date as 31 Dec.

_"If you’re querying the Search Console API using an external API library, or querying the Webmasters API discovery document directly you will need to take action as we’ll drop the support in the Webmasters discovery document. Our current plan is to support it until December 31, 2020 - but we’ll provide more details and guidance in the coming months."_

**Comment by ngodinhnhien** [comment]
It works properly again in SEA, but I am not sure if it will collapse again or not

**Comment by olycats** [comment]
This issue seem to be resolved now.

**Comment by masarliev** [comment]
Not for me

**Comment by paddie** [comment]
> Google said here already https://webmasters.googleblog.com/2020/08/search-console-api-announcements.html that they would change the API. However, they have set the date as 31 Dec.
> 
> _"If you’re querying the Search Console API using an external API library, or querying the Webmasters API discovery document directly you will need to take action as we’ll drop the support in the Webmasters discovery document. Our current plan is to support it until December 31, 2020 - but we’ll provide more details and guidance in the coming months."_

So, I'm not really seeing, from this article _which_ actions are actually required, but updating the build step to use `discovery.build('searchconsole', 'v1')` instead of the old `discovery.build('webmasters', 'v3')` resolved the issue for me, and also seems to be actually using the old `webmasters/v3` endpoint with the `rest` document:

https://www.googleapis.com/discovery/v1/apis/searchconsole/v1/rest
```
    "sites": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.sites.list",
          "parameterOrder": [],
          "path": "webmasters/v3/sites",
          "description": " Lists the user's Search Console sites.",
          "httpMethod": "GET",
          "flatPath": "webmasters/v3/sites",
          "response": {
            "$ref": "SitesListResponse"
          },
          "parameters": {}
        },
```

working off of that assumption now at least.

**Comment by iamsaurabhgupt** [comment]
both webmasters/v3 and searchconsole/v1 are working now.
Seems better to shift to searchconsole/v1 for future consistency.
Closing this now.

**Comment by prykon** [comment]
> > It seems that `discovery.build('searchconsole', 'v1')` is working. Can somebody verify that?
> > According to the documentation this is only the beta endpoint for the url testing tool
> > https://developers.google.com/webmaster-tools/search-console-api/reference/rest
> 
> I just tried that and it seems to work, but not sure if this is the one to use

This also worked for me! Thanks!
