### ISSUE TITLE
webmaster service is failing

### ISSUE THREAD

**Issue by tavleenk13** [googleapis/google-api-python-client#1043]
https://www.googleapis.com/discovery/v1/apis/webmasters/v3/rest returns 404.

The webmaster v3 is failing and returning error `UnknownApiNameOrVersion: name: webmasters  version: v3` all of a sudden.

**Comment by sloev** [comment]
we are seeing this too, 
using reqbin you can check its an issue from both US, DE and us in DK 

https://reqbin.com/c-4rgtzhsk

> curl 'https://www.googleapis.com/webmasters/v3/'
