### ISSUE TITLE
Cloudrun Domain Mapping API

### ISSUE THREAD

**Issue by arvindwill** [googleapis/google-api-python-client#1048]
Is it possible to use this library to create Cloudrun Doman Mapping? 
![image](https://user-images.githubusercontent.com/2239985/94348578-0e7c8e80-005b-11eb-8cb5-0d57d9adce00.png)

If yes, is there a sample/demo script to explain how to perform it?

**Comment by busunkim96** [comment]
Hi, this issue tracker is for `google-api-python-client` issues.

Documentation about Cloud RunDomain Mapping is at https://cloud.google.com/run/docs/mapping-custom-domains. If that documentation is unclear please open an issue by following the `Send Feedback` link at the bottom of the page.

**Comment by grant** [comment]
Not sure about this library, but in general you should be able to programmatically do this.

Try the gcloud commands, get that working, then use the API client equivalent to do the same.

Example command:

```
gcloud beta run domain-mappings describe --domain foo.com --log-http
```

**Comment by averikitsch** [comment]
This library should have the capabilities to create domain mappings, see the [REST API reference](https://cloud.google.com/run/docs/reference/rest/v1/namespaces.domainmappings/create) and [client library docs](http://googleapis.github.io/google-api-python-client/docs/dyn/run_v1.namespaces.domainmappings.html). We are currently working on generating samples for this library; however here is an example:

```
from googleapiclient.discovery import build

project="PROJECT"
parent = f"namespaces/{project}"

service = build("run", "v1") # Authenticates using GOOGLE_APPLICATION_CREDENTIALS env var
response = service.namespaces().domainmappings().create(parent=parent)
print(response.to_json())
```

**Comment by parthea** [comment]
Hi @arvindwill,

I'm going to close this issue as sample code was provided in the last comment. If you're still having trouble please re-open this issue with additional information.
