### ISSUE TITLE
Method to get subresource can shadow actual methods on the resource

### ISSUE THREAD

**Issue by henribru** [googleapis/google-api-python-client#1054]
#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.7.1
  - pip version: 10.0.1
  - `google-api-python-client` version: 1.12.3

#### Steps to reproduce

  1. Create a resource that has both a subresource and a method with the same name.
  2. Call the method on the resource. This will get you the subresource, not call the actual method. 

In a case like this there's no way to call the actual method, from what I can tell, apart from manually extracting the relevant parts from `_add_basic_methods` and adding it with another name myself. This should probably be done automatically when a method gets shadowed by a subresource.

I ran through all the discovery documents with a script and found that this occurs in four places, all in the Apigee API:
- organizations.apiproducts.attributes
- organizations.developers.apps.keys.create
- organizations.developers.apps.attributes
- organizations.developers.attributes

#### Code example

```python
resource = build("apigee", "v1", credentials=...)
apiproducts = service.organizations().apiproducts()
print(apiproducts.attributes()) # <googleapiclient.discovery.Resource object at 0x0000028217FDD208>
# No way to call https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.apiproducts/attributes
```

**Comment by busunkim96** [comment]
Hi @henribru,

Thanks for filing an issue. The duplicate resource/method naming also causes issues in other languages (NodeJS, for example). It looks like we reached out to the Apigee folks in July to see if the discovery doc itself could be changed. I've pinged that thread and will post an update once I hear back.

**Comment by busunkim96** [comment]
The API team is aware of the issue but has not made progress towards a fix. Googlers, see 164895071.

**Comment by parthea** [comment]
b/172643712 is related where the is a compatibility issue with the Apigee method and the autogenerated clients, which can't be easily solved. It is recommended to use the REST endpoint directly using the link you provided : https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.apiproducts/attributes . I'm going to close this issue but please feel free to re-open it if you have additional questions. If you'd like to send feedback directly to the Apigee team, please click the Send Feedback button on the support page [here](https://cloud.google.com/apigee/docs/support). Googlers see b/172643712.
