### ISSUE TITLE
Retry after timeout fails due to protection range already present

### ISSUE THREAD

**Issue by Woytek-Polnik** [googleapis/google-api-python-client#1064]
#### Environment details

  - Python version: `3.6.8`
  - pip version: `20.0.2`
  - `google-api-python-client` version: `google-api-python-client==1.10.0`

#### Steps to reproduce

  1. Request to google API to addprotection sheets
  2. Eventually you hit fail - protection range is already present

I've hit this issue a couple of times, in August, September, October (basically from time to time when since I started using it)

// I've faced also once 
// `returned "Invalid requests[0].deleteProtectedRange: No protected range with id: 2092627652`
// but cannot be 100% sure for this one

#### Code example

```python
return request.execute(num_retries=5)
```

#### Stack trace
```
    return request.execute(num_retries=5)
  File "python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "python3.6/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/[cleared]:batchUpdate?alt=json returned "Invalid requests[0].addProtectedRange: Sheet "Domains" already has sheet protection.">
```

Logs
```
06/Aug/2020 08:15:41 AM - SheetManager - DEBUG - Cleaned all ranges I could have ever put here before
06/Aug/2020 08:16:41 AM - googleapiclient.http - WARNING - Sleeping 0.68 seconds before retry 1 of 5 for request: POST https://sheets.googleapis.com/v4/spreadsheets/[cleared]:batchUpdate?alt=json, after The read operation timed out
06/Aug/2020 08:17:36 AM - root - ERROR - <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/[cleared]:batchUpdate?alt=json returned "Invalid requests[0].addProtectedRange: Sheet "Domains" already has sheet protection.">
```

Comments
```
06/Aug/2020 08:15:41 AM - In the app, I 1st remove all ranges - in case my program crashed or anything - just to have clean stage
after
06/Aug/2020 08:15:41 AM till 08:16:41 AM - default 60s http timeout. Put protection range on Sheet(Tab) "Domains"
06/Aug/2020 08:17:36 AM - failed in the library handled retry
```

**Comment by busunkim96** [comment]
Hi @Woytek-Polnik,

If I'm understanding correctly, you've removed all the protection ranges but still see errors about the protection range already existing? Does this error happen every single time or is there some other pattern?

**Comment by Woytek-Polnik** [comment]
I started to see this almost every day, even 2 times a day....

1 more time while in wrapper _helpers.py for retries, request timeouts after n-th try, in next retry it gets invalid request

**Comment by busunkim96** [comment]
Hi @Woytek-Polnik,

It looks like this is an issue at the API level rather than in the library. Please use one of the Google Sheets support channels. https://developers.google.com/sheets/api/support

**Comment by Woytek-Polnik** [comment]
Submitted ticket to the API support https://issuetracker.google.com/issues/172737443

**Comment by fronzag** [comment]
solved? 
Same issue happening here.

**Comment by sanja7s** [comment]
and here

**Comment by glavince** [comment]
+1
