### ISSUE TITLE
healthcare.projects.locations.datasets.fhirStores.fhir.search_next does not exist

### ISSUE THREAD

**Issue by cascadianblue** [googleapis/google-api-python-client#1068]
I tried following this API's [documentation](https://github.com/googleapis/google-api-python-client/blob/master/docs/pagination.md) for iterating through paginated results, but it appears there is no `search_next()` method, as one would expect there to be for the `healthcare.projects.locations.datasets.fhirStores.fhir.search` method/action. Here is part of what I attempted:

```python
fhir = service.projects().locations().datasets().fhirStores().fhir()
request = fhir.search(parent=DEID_STORE, body=body)
while request is not None:
    result = request.execute()
    entries.extend(result['entry'])  # This line is not relevant
    request = fhir.search_next(request, result)
```

but I get this error:

```
Traceback (most recent call last):
  File "/my/home/dir/project-dir/script.py", line XX, in <module>
    request = fhir.search_next(request, result)
AttributeError: 'Resource' object has no attribute 'search_next'
```

**Comment by cascadianblue** [comment]
I had this problem regardless of whether `service = build('healthcare', 'v1')` or `service = build('healthcare', 'v1beta1')`

**Comment by parthea** [comment]
I read through the docs for the Healthcare API [here](https://googleapis.github.io/google-api-python-client/docs/dyn/healthcare_v1.projects.locations.datasets.fhirStores.fhir.html) and I can confirm that the `search_next()` method is not available for this API, however the `search()` method supports pagination to retrieve the next page as mentioned below. 

> The maximum number of search results returned defaults to 100, which can be overridden by the `_count` parameter up to a maximum limit of 1000. If there are additional results, the returned `Bundle` will contain pagination links. Resources with a total size larger than 5MB or a field count larger than 50,000 might not be fully searchable as the server might trim its generated search index in those cases. Note: FHIR resources are indexed asynchronously, so there might be a slight delay between the time a resource is created or changes and when the change is reflected in search results. For samples and detailed information, see [Searching for FHIR resources](/healthcare/docs/how-tos/fhir-search) and [Advanced FHIR search features](/healthcare/docs/how-tos/fhir-advanced-search).

There is a section in the [how-to docs](https://cloud.google.com/healthcare/docs/how-tos/fhir-search#pagination_and_sorting) that mentions how to retrieve the next page of the bundle that is returned when the number of search results are greater than 100. I also found this link helpful for understanding more about [bundles](https://www.hl7.org/fhir/bundle-definitions.html).

From how-to-docs:
> If the search found more resources than fit on one page, the response will include a pagination URL in the Bundle.link field. There might be multiple values returned in this field; the value with Bundle.link.relation = next indicates that the corresponding Bundle.link.url can be used to retrieve the next page. 

Please feel free to re-open this issue if you have additional questions. If you'd like to submit feature request for changes to the underlying API which is maintained internally at Google, please open an issue on the Cloud Platform public issue tracker [here](https://issuetracker.google.com/issues/new?component=187065&template=1380951).
