### ISSUE TITLE
Add user_info api in the documentation

### ISSUE THREAD

**Issue by nishantwrp** [googleapis/google-api-python-client#1071]
I was able to retrieve user profile of the user using their credentials i.e. accessToken by the following code

```python
from googleapiclient.discovery import build

def get_user_email_from_credentials(credentials):
    user_info_service = build('oauth2', 'v2', credentials=credentials)
    user_info = user_info_service.userinfo().get().execute()
    return user_info['email']
```

But I couldn't find it in the docs here https://github.com/googleapis/google-api-python-client/blob/master/docs/dyn/index.md

**Comment by parthea** [comment]
Thanks for suggesting an update to the docs! I've opened PR to add the code you suggested. Please review #1088 if you have a chance.

Additionally, I've opened a thread internally to see if we can include a link to the oauth2 docs in our [API Library Reference Documentation](https://github.com/googleapis/google-api-python-client/blob/master/docs/dyn/index.md).

The People V1 api also has a [people.get()](https://developers.google.com/people/api/rest/v1/people/get) method which has information about the authenticated user. See the python docs [here](https://googleapis.github.io/google-api-python-client/docs/dyn/people_v1.people.html#get). The following sample code also provides the authenticated user's email address but your sample is more intuitive :).
```
people_service = build('people', 'v1', credentials=credentials)
result = people_service.people().get(resourceName='people/me', personFields='emailAddresses').execute()
result.get('emailAddresses')[0].get('value')
```

**Comment by nishantwrp** [comment]
Hi @parthea,

#1088 looks good to me. Yup it would be nice to have this documented [here](https://github.com/googleapis/google-api-python-client/blob/master/docs/dyn/index.md).

> The People V1 api also has a people.get() method which has information about the authenticated user. See the python docs here. The following sample code also provides the authenticated user's email address but your sample is more intuitive :).

This might work but this doesn't seem to be a good idea because I would need to request additional `people` access from the user, right?
