### ISSUE TITLE
Proxy config httplib2

### ISSUE THREAD

**Issue by SergioMunozGam** [googleapis/google-api-python-client#1078]
Hey, 

As you well know, the library currently makes calls to the endpoint https://www.googleapis.com/discovery/v1/apis using HttpRequest and a httplib2 object (httplib2.Http()). httplib2 library doesn't take into account HTTPS_PROXY and HTTP_PROXY env variables, so if you are in an offline environment that routes requests through a proxy you will not be able to reach the endpoint.

You can set the proxy conf using httplib2 library:

```
http = httplib2.Http(proxy_info=httplib2.ProxyInfo(
            httplib2.socks.PROXY_TYPE_HTTP, PROXY_IP, PROXY_PORT
))
```

but currently there is no option using google-api-python-client to set proxy config. Could you study the feasibility of introducing some parameter that allows adding proxy settings for discovery calls?.

Thanks in advance.

**Comment by busunkim96** [comment]
Hi,

It's possible to pass a custom httplib2 object to the constructor. Can you check if this works for you?

```py
import httplib2
import google_auth_httplib2

http = httplib2.Http(proxy_info=httplib2.ProxyInfo(
            httplib2.socks.PROXY_TYPE_HTTP, PROXY_IP, PROXY_PORT
))

authorized_http = google_auth_httplib2.AuthorizedHttp(credentials, http=http)

service = discovery.build(http=authorized_http)
```

https://github.com/googleapis/google-api-python-client/blob/8430faca51ff8df24b5dd186ceba16e29ec41411/googleapiclient/discovery.py#L205

**Comment by SergioMunozGam** [comment]
It works!

Thank you so much!!
