### ISSUE TITLE
Status parameter not working when using python blogger api client

### ISSUE THREAD

**Issue by madtyn** [googleapis/google-api-python-client#1084]
I'm trying to use google-api-python-client 1.12.5 with Service account auth under Python 3.8. It seems to me that the when specifying the status parameter, Google responds with a 404 HTTP code. I can't figure out why. I also looked in the docs but I can't relate anything to this error.

I have pasted my code. The error is happening in the third call.

This is the code:

```
from google.oauth2 import service_account
from googleapiclient.discovery import build

SCOPES = ['https://www.googleapis.com/auth/blogger']
SERVICE_ACCOUNT_FILE = 'new_service_account.json'
BLOG_ID = '<your_blog_id>'

credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)

service = build('blogger', 'v3', credentials=credentials)
p = service.posts()

# FIRST
promise = p.list(blogId=BLOG_ID)
result = promise.execute()

# SECOND
promise = p.list(blogId=BLOG_ID, orderBy='UPDATED')
result = promise.execute()


#THIRD
promise = p.list(blogId=BLOG_ID, orderBy='UPDATED', status='DRAFT')
result = promise.execute()  # <===== ERROR HAPPENS HERE!!!!

service.close()
```

And this is the traceback:

```
Traceback (most recent call last):
  File "/home/madtyn/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.7660.27/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/madtyn/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.7660.27/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/madtyn/PycharmProjects/blogger/main.py", line 24, in <module>
    result = promise.execute()
  File "/home/madtyn/venvs/blogger/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/madtyn/venvs/blogger/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://blogger.googleapis.com/v3/blogs/<blog_id>/posts?orderBy=UPDATED&status=DRAFT&alt=json returned "Not Found">
python-BaseException
```

**Comment by busunkim96** [comment]
Hey @madtyn,

Would you mind trying `status=['DRAFT']` instead? (I see the generated docs list this as a 'repeated parameter') although it's possible that's incorrect.

https://googleapis.github.io/google-api-python-client/docs/dyn/blogger_v3.posts.html#list

**Comment by madtyn** [comment]
Hi busunkim96. I did it and got this error with this traceback:

```
<Response [401]>
Traceback (most recent call last):
  File "/home/madtyn/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.7660.27/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/madtyn/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/202.7660.27/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/madtyn/PycharmProjects/blogger/main.py", line 41, in <module>
    result = promise.execute()
  File "/home/madtyn/venvs/blogger/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/madtyn/venvs/blogger/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://blogger.googleapis.com/v3/blogs/2270688467086771731/posts?orderBy=UPDATED&status=DRAFT&alt=json returned "Not Found">
python-BaseException
```

**Comment by parthea** [comment]
Hi @madtyn ,

I was able to re-produce the problem using your code. Initially, I used the code below which authenticates using oauth2 flow and the code didn't raise an exception.  My initial thought is that possibly the Blogger API does not support authenticating with a service account. On an unrelated note for the YouTube API, I have read that [Service Accounts do not work with the YouTube API](https://developers.google.com/youtube/v3/guides/moving_to_oauth#service-accounts-do-not-work-with-the-youtube-api). If this is also the case with the Blogger API, then at the very least the error message that is returned should be improved. I have read from public unofficial sources that the Blogger API does not support service accounts, so you could also try opening a feature request on the issue tracker if you are unable to find an adequate solution: https://issuetracker.google.com

Working code with oauth flow:
```
from googleapiclient.discovery import build

SCOPES = ['https://www.googleapis.com/auth/blogger']
client_secrets_file = 'client_secrets_file.json'
BLOG_ID = '<your_blog_id>'

flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
    client_secrets_file, SCOPES)
credentials = flow.run_console()

service = build('blogger', 'v3', credentials=credentials)
p = service.posts()

# FIRST
promise = p.list(blogId=BLOG_ID)
result = promise.execute()

# SECOND
promise = p.list(blogId=BLOG_ID, orderBy='UPDATED')
result = promise.execute()


#THIRD
promise = p.list(blogId=BLOG_ID, orderBy='UPDATED', status='DRAFT')
result = promise.execute()  # <===== ERROR HAPPENS HERE!!!!

service.close()
```

I'll keep this issue open while do a bit of digging internally to try to obtain more information about using service accounts with the Blogger API. I'll also create an internal ticket to improve the error message.

**Comment by madtyn** [comment]
Thank you @parthea . I will take a look ASAP and try that code, although using service account would be my ideal scenery, given that this is for a bot which should have no interaction with the user, at least not for doing thing at blogger.

Thanks again. I will try to adapt this useful code and think if I can adapt it to my needs

**Comment by parthea** [comment]
Thanks! I checks with a few folks here via our internal ticketing system and we are in agreement that is not possible to share a user's blog with a service account. 

In case it is helpful, our docs has a section on delegating domain wide authority to a service account but it may not be applicable to the Blogger API: https://github.com/googleapis/google-api-python-client/blob/master/docs/oauth-server.md#delegating-domain-wide-authority-to-the-service-account

 I'm going to close off this issue but feel free to re-open it if you'd like to discuss further options.

**Comment by madtyn** [comment]
Thanks @parthea . I'm reading the docs at the link you provided and will answer.

**Comment by madtyn** [comment]
@parthea Is there some way to know if that thing about delegating domain wide authority is applicable to Blogger API? I would prefer not doing a whole amount of work for nothing. Where can I ask or read about this?

**Comment by parthea** [comment]
I wasn't able to get confirmation that delegating domain wide authority to a service account is applicable to Blogger API but I was able to get confirmation internally that you cannot use a service account to get details of a blog. My initial thought is it likely won't work as a service account cannot be added as an admin or author of a blog. Your best option would be to open an issue at https://issuetracker.google.com . You can read more about the issue tracker in general [here](https://cloud.google.com/support/docs/issue-trackers). I still have an internal ticket open, so if you have specific questions about the Blogger API I'm happy to help attempt to find answers but generally issues and feature requests should go in https://issuetracker.google.com so they can be prioritized.
