### ISSUE TITLE
API retrieving only one type of calendar

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1086]
#### Environment details

  - OS type and version: Windows 10
  - Python version: `python --3.8.3`
  - pip version: `pip --20.2.3`
  - `google-api-python-client - 1.12.2` 

#### Code example

```
    service = build('calendar', 'v3', credentials=creds)
    # Call the Calendar API
    now = datetime.utcnow().isoformat() + 'Z'  # 'Z' indicates UTC time
    utc_dt = datetime.now(timezone.utc).astimezone().isoformat()
    events_result = service.events().list(calendarId='primary', timeMin='2020-11-05T18:58:24.127438-05:00', timeMax=utc_dt,
                                          maxResults=10, singleEvents=True,
                                          orderBy='startTime').execute()
    events = events_result.get('items', [])
    print(events)
```

#### Problem

![image](https://user-images.githubusercontent.com/58639693/98581296-451b0b00-228f-11eb-8cb6-45a04bbb530b.png)
Only **one** event (in my case the ENTR4700 calender) gets called _not_ the rest. How can we retrieve the events of **all** calendar types?

Thanks!

**Comment by parthea** [comment]
Hey @danieldhz,

Looking at the [Events: list](https://developers.google.com/calendar/v3/reference/events/list) reference page for the calendar API, I don't see a way to get all events for all calendar types in a single call to `service.events().list()`. You need a separate call for each `calendarId`. When the `calendarId` parameter is set to `'primary'` you will see the calendar of the currently logged in user. If you want to list events for another calendar, you'll need to set the `'calendarId`' parameter to the `'id'` corresponding to the specific calendar to see events for only that calendar. To get the `'id'` of all the calendars that you see in Google Calendar, check the [CalendarList: list ](https://developers.google.com/calendar/v3/reference/calendarList/list) reference page. I was able to get my list of calendars by calling `service.calendarList().list().execute()`.

Let me know if you have any questions!

**Comment by DaniyalDhz** [comment]
Hi, fellow citizen @parthea! :)

Thank you for getting back to me,

I believe you meant `service.calendarList().list().execute()` to get each calendar's property to then call each calendar event. Initially, I was going to question the rationale of such workflow but now I see/admire the added flexibility and customization it provides. Make sense and thanks for your help!

**Comment by DaniyalDhz** [comment]
My only question is that when I retrieve all the calendar IDs:
Is it possible to call all of them in one 
```
    events_result = service.events().list(calendarId='primary, id, id', timeMin=Yes, timeMax = now
                                        ,singleEvents=True,
                                        orderBy='updated').execute()  
```
or should there be one for each and then have to merge all together?

**Comment by parthea** [comment]
Unfortunately, you need to have separate calls to `service.events().list()` for each `calendarId`. Please follow the steps outlined on the [Google Calendar API Help Site](https://developers.google.com/calendar/support) if you'd like to submit a feature request to show events from all calendars in a single call to `service.events().list()`. Follow the steps under the [missing features](https://developers.google.com/calendar/support#missing_features) section. I found an existing [feature request](https://issuetracker.google.com/issues/135376206) that is may be related. Please feel free to comment on the existing feature request if it is related. You can also click on the star to express interest in the feature.

I'm going to close off this issue but please feel free to open a new issue or comment on this issue if you have related questions!
