### ISSUE TITLE
[Question] What other OAuth2 scopes can I access apart from the API scopes

### ISSUE THREAD

**Issue by arnitdo** [googleapis/google-api-python-client#1089]
In some sample code snippets, the OAuth2 scope has been set to something like ["user, "profile"].

[For example](https://github.com/googleapis/google-api-python-client/blob/master/docs/oauth.md#installed-app-flow), the sample code snippet has scopes ["profile", "email"]. 

 Is there any documentation about non API OAuth scopes like mentioned above?

**Comment by parthea** [comment]
Great question! In the [Getting Started](https://github.com/googleapis/google-api-python-client/blob/master/docs/start.md#getting-started) guide, we have a link in [section 2 Authorized API access (OAuth 2.0)](https://github.com/googleapis/google-api-python-client/blob/master/docs/start.md#2-authorized-api-access-oauth-20) that points to the [OAuth2](https://developers.google.com/identity/protocols/OAuth2) page. From there you can click on [OAuth 2.0 Scopes](https://developers.google.com/identity/protocols/oauth2/scopes).

It would probably be helpful to have some text with a link under the Scopes bullet point in [section 2 Authorized API access (OAuth 2.0)](https://github.com/googleapis/google-api-python-client/blob/master/docs/start.md#2-authorized-api-access-oauth-20) that directs the user on where to find the OAuth 2.0 Scopes. Are you by any chance interested in opening a pull request to improve [getting started guide](https://github.com/googleapis/google-api-python-client/blob/master/docs/start.md) doc?

**Comment by arnitdo** [comment]
Sure! I've opened PR #1090 .

One side question - 

It seems that the ["profile", "email"] scope I was referring to is part of the [Google OAuth2 API v2](https://developers.google.com/identity/protocols/oauth2/scopes#oauth2) - 
i.e "profile" refers to userinfo.profile, and "email" refers to userinfo.email

My question is, how do i access this information from a built API service, and what service name do i use?

**Comment by arnitdo** [comment]
Ah! After some digging around, I've found [this SO Question](https://stackoverflow.com/questions/19473250/how-to-get-user-email-after-oauth-with-google-api-python-client), and the first answer seems to use serviceName "oauth2" and access user information using further functions.

The "oauth2" service name is not seen [on this page](https://googleapis.github.io/google-api-python-client/docs/dyn/). I'm assuming that it has been deprecated, or is no longer available from google-api-python-client.

**Comment by arnitdo** [comment]
Sorry for the long wall of replies. 
After some more digging around, I've found #1088  and #1071 , and that has answered all my questions! :-D

I've also found out that one can get user information from the peoples API!

Thank you very much!
