### ISSUE TITLE
We are really trying to make 'google-api-python-client' to work

### ISSUE THREAD

**Issue by jeroenhamel** [googleapis/google-api-python-client#1097]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hello, 

We have been trying to get the python script running in Jupiter Notebooks. We think we came really far but for some reason we can't get it to run properly. There are 2 error messages that I would like to check and get feedback on:

1. " NameError: name '__file__' is not defined". We don't know what it truly means but did a 'work around' declaring 
"from pathlib import Path
cwd = Path.cwd()" 
before running the script and rename '__file__' to 'cwd'. It seem to have fixed the issue but once we run it again. We cot the following error.

2. The error massage we received is: 
usage: ipykernel_launcher.py [-h] [--auth_host_name AUTH_HOST_NAME]
                             [--noauth_local_webserver]
                             [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                             [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
                             property_uri start_date end_date
ipykernel_launcher.py: error: the following arguments are required: start_date, end_date
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

Perhaps we need to use the code in the console: python search_analytics_api_sample.py https://www.example.com 2015-05-01 2015-05-30 but also this doesn't seem to do the trick. 

Hope somebody can help us out as we really want to use the code and GSC opportunity. 

Thanks in advance!!

Cheers, 
Jeroen

**Comment by parthea** [comment]
Hi @jeroenhamel,

Are you able to share more code to allow me to reproduce the error `NameError: name 'file' is not defined`? Were you running the [sample search_analytics_api_sample.py](https://github.com/googleapis/google-api-python-client/blob/master/samples/searchconsole/search_analytics_api_sample.py)? Please provide as much detail as possible. 

Regarding the error from `ipykernel_launcher`, it looks like it's referring to missing the command line arguments. Please check to make sure that you've provided the necessary arguments. You can also share the code that you're using.  If you're trying to integrate with jupyter notebooks, you may also consider running the python code directly in a jupyter notebook rather than trying to run the sample from command line within the notebook but that would require changing the sample code.

**Comment by jeroenhamel** [comment]
Hi @parthea 

Thanks for you for you answer and indeed I was thinking it has likely to do with missing command line arguments as we wanted run it directly in the jupyter notebooks. 

This is the code we used: 
`from __future__ import print_function
import argparse
import sys
from googleapiclient import sample_tools

# Declare command-line flags.
argparser = argparse.ArgumentParser(add_help=False)
argparser.add_argument('property_uri', type=str,
                       help='https://www.elsevier.com')
argparser.add_argument('start_date', type=str,
                       help=('Start date of the requested date range in '
                             'YYYY-MM-DD format.'))
argparser.add_argument('end_date', type=str,
                       help=('End date of the requested date range in '
                             'YYYY-MM-DD format.'))

def main(argv):
    service, flags = sample_tools.init(
        argv, 'searchconsole', 'v1',__doc__,cwd,parents=[argparser],
        scope='https://www.googleapis.com/auth/webmasters.readonly')
  
    request = {
      'startDate': flags.start_date,
      'endDate': flags.end_date,
      'dimensions': ['date']
  }
    response = execute_request(service, flags.property_uri, request)
    print_table(response, 'Available dates')

# Get totals for the date range.
    request = {
        'startDate': flags.start_date,
        'endDate': flags.end_date
    }
    response = execute_request(service, flags.property_uri, request)
    print_table(response, 'Totals')

# Get top 10 pages for the date range, sorted by click count, descending.
    request = {
        'startDate': flags.start_date,
        'endDate': flags.end_date,
        'dimensions': ['page'],
        'rowLimit': 10
    }
    response = execute_request(service, flags.property_uri, request)
    print_table(response, 'Top Pages')

# Get the top 10 queries in India, sorted by click count, descending.
    request = {
        'startDate': flags.start_date,
        'endDate': flags.end_date,
        'dimensions': ['query'],
        'dimensionFilterGroups': [{
            'filters': [{
                'dimension': 'country',
                'expression': 'ind'
            }]
        }],
        'rowLimit': 10
    }
    response = execute_request(service, flags.property_uri, request)
    print_table(response, 'Top queries in India')

# Group by both country and device.
    request = {
        'startDate': flags.start_date,
        'endDate': flags.end_date,
        'dimensions': ['country', 'device'],
        'rowLimit': 10
    }
    response = execute_request(service, flags.property_uri, request)
    print_table(response, 'Group by country and device')

# Group by total number of Search Appearance count.
# Note: It is not possible to use searchAppearance with other
# dimensions.
    request = {
        'startDate': flags.start_date,
        'endDate': flags.end_date,
        'dimensions': ['searchAppearance'],
        'rowLimit': 10
    }
    response = execute_request(service, flags.property_uri, request)
    print_table(response, 'Search Appearance Features')

def execute_request(service, property_uri, request):
    
    return service.searchanalytics().query(
      siteUrl=property_uri, body=request).execute()

def print_table(response, title):
    print('\n --' + title + ':')
    if 'rows' not in response:
        print('Empty response')
        return
    
    rows = response['rows']
    row_format = '{:<20}' + '{:>20}' * 4
    print(row_format.format('Keys', 'Clicks', 'Impressions', 'CTR', 'Position'))
    for row in rows: 
        keys = ''
        # Keys are returned only if one or more dimensions are requested.
        if 'keys' in row:
            keys = u','.join(row['keys']).encode('utf-8').decode()
    print(row_format.format(
        keys, row['clicks'], row['impressions'], row['ctr'], row['position']))
    
if __name__ == '__main__': 
    main(sys.argv)`

It would be great if we can run python script directly in Jupiter Notebooks. 
As mentioned we tried to resolve the issue with __file__ by declaring CWD. 

We also updated the start and end date in to: 
argparser.add_argument('start_date', type=str,
                       help=('2020-09-01'))
argparser.add_argument('end_date', type=str,
                       help=('2020-10-01'))

That however also didn't work. 
Please let me know if there is any other info you need that could be helpful. 

Thanks again. 
Regards, 

Jeroen

**Comment by parthea** [comment]
Hi @jeroenhamel,

Thanks for providing the notebook. It looks like you're not providing arguments as expected. I found a related issue here !94 where a user added the sample to an existing notebook. 

I managed to use code from the sample in a colab notebook by following these steps.

1) Copy the python code from the [sample](https://github.com/googleapis/google-api-python-client/blob/master/samples/searchconsole/search_analytics_api_sample.py) into a cell in a Colab or Jupyter notebook.
2) Run the following code: 
```
from google_auth_oauthlib import flow
from apiclient.discovery import build

client_id = "X"
client_secret = "X"
scopes = ["https://www.googleapis.com/auth/webmasters.readonly"]
client_config = {
    "installed": {
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob"],
        "client_id": client_id,
        "client_secret": client_secret
    }
}

app_flow = flow.InstalledAppFlow.from_client_config(
    client_config, scopes=scopes
)

credentials = app_flow.run_console()
service = build('searchconsole', 'v1', credentials=credentials)
request = {
  'startDate': '2020-11-01',
  'endDate': '2020-11-20',
  'dimensions': ['query']
}
response = execute_request(service, 'https://domain.com/', request) 
```

Let me know if the above code works.

**Comment by jeroenhamel** [comment]
Hi @parthea ,

Thanks for providing the code. We did the following: 
1) Added the sample in Jupiter notebook and included our client_id, client_secret and updated the domain to contain the correct domain. 
2) Run the code and filled in the authorization code. 
3) we received the following error message: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-179f756bb238> in <module>
     20 
     21 credentials = app_flow.run_console()
---> 22 service = build('searchconsole', 'v1', credentials=credentials)
     23 def get_all_keywords(service):
     24     request = {

NameError: name 'build' is not defined


4) we run the same code in Google Colab but receive the same error message. 
5) after some investigation we can't seem to figure out what we need to change to resolve the 'build' issue. 

If you have any suggestions, please let me know. 

Thanks again. 
Regards, 
Jeroen

**Comment by parthea** [comment]
Hi Jeroen,

Based on that error, it looks like `build` was not imported properly. One thing I noticed is that  I incorrectly had `from apiclient.discovery import build` in my example due to a copy and paste error.  The correct import should be `from googleapiclient.discovery import build`. I updated my example. Please can you try again and make sure to run `from googleapiclient.discovery import build` before you run the sample?

**Comment by parthea** [comment]
Hi @jeroenhamel,

I'm following up to see if you've had a chance try the test again. Please let me know.

**Comment by parthea** [comment]
@jeroenhamel , I'm going to close off this issue. Please re-open it if you're still having trouble!

**Comment by jeroenhamel** [comment]
Hi @parthea, 

First of all I'd like to thank you for all your contribution here. It is working now and we are smiling :-) 
When running the code we found that the limit is 25k rows. 

So when running the script we run in until the end of the amount of rows. In our case a little over 26k rows for one day of Google Search Console results. When summing the clicks and impressions the amount of the code run via Google Colab is much lower. 

Is this something that is known? We are aware that there is a limit per API call but were expecting when running within these limits the data would match. 

Thanks again.
Regards, 

Jeroen

**Comment by parthea** [comment]
Hi @jeroenhamel,

I'm glad that it's working! Since this is a question specific to the Search Console API rather than the library `google-api-python-client`, I would recommend to post the question in the community page [here](https://support.google.com/webmasters/community) to get help from someone with Search Console API expertise.
