### ISSUE TITLE
googleapiclient discovery.py six.moves has no attribute 'collections_abc'

### ISSUE THREAD

**Issue by edwit1971** [googleapis/google-api-python-client#1098]
The code runs just fine on the PC.  It works PERFECT.  But after I compile it with Buildozer (which uses Python-For-Android) it successfully creates an APK file.  After I install this APK file onto my Tablet and run it, the App crashes when I try to Authenticate.  When the code calls gauth.LocalWebserverAuth() it launches the Web Browser App (I use Firefox) and although the Authentication is successful when I return to my App it crashed.  This does NOT happen on the PC.  It only happens on the Android Tablet.

The Error is:
"/googleapiclient/discovery.py" line 466, in build_from_document
[WARNING] stderr: AttributeError: module 'six.moves' has no attribute 'collections_abc'

#### Environment details

  - OS type and version: Android OS 7.1.1
  - Python version: 3.8.6
               hostpython3==3.8.6,
               python3==3.8.6,
               sdl2_ttf==2.0.15,
               kivy==2.0.0rc4,
               kivymd==0.104.1,
               sqlite3==3.33.0,
               pygments==2.7.2,
               requests==2.25.0,
               pydrive==1.3.1,
               google-api-python-client==1.12.5,
               google-api-core==1.22.2,
               google-auth==1.23.0,
               google-auth-httplib2==0.0.4,
               googleapis-common-protos==1.52.0,
               pyasn1==0.4.8,
               pyasn1-modules==0.2.8,
               rsa==4.6,
               pyyaml==5.3.1,
               matplotlib==3.1.2

#### Steps to reproduce

  1. at the top of my python file I have 
from pydrive.auth  import GoogleAuth
from pydrive.drive import GoogleDrive

  2. Then I have a function that Authenticates.

#### Code example
            gauth = GoogleAuth()
            # Try to load saved client credentials
            strMyCred = os.path.join('./database/', 'mycreds.txt')
            gauth.LoadCredentialsFile(strMyCred)
            if gauth.credentials is None:
                # Authenticate if they're not there
                gauth.LocalWebserverAuth()
            elif gauth.access_token_expired:
                # Refresh them if expired
                gauth.Refresh()
            else:
                # Initialize the saved creds
                gauth.Authorize()
            # Save the current credentials to a file
            gauth.SaveCredentialsFile(strMyCred)
            GDrive = GoogleDrive(gauth) # Google Drive Class Object

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by xenonstride** [comment]
@edwit1971 I had the same issue. I downgraded google-api-python-client to version 1.11.0 and I no longer have the error.

**Comment by parthea** [comment]
@edwit1971 @edwit1971 An improvement was made in `six >= 1.13.0` . `google-api-python-client` already requires `six >= 1.13.0` so you should have it but can you please check to make sure you are on `six` version >= 1.13.0 ?  See `six` changelog here https://github.com/benjaminp/six/blob/master/CHANGES#L30

**Comment by edwit1971** [comment]
The suggestion was to make sure I was using six >=1.13.0 and downgrade google-api-python-client to 1.11.0 so I went into the Buildozer Spec File and changed the requirements section to the following:
requirements = hostpython3==3.8.6,
               python3==3.8.6,
               sdl2_ttf==2.0.15,
               kivy==2.0.0rc4,
               kivymd==0.104.1,
               sqlite3==3.33.0,
               pygments==2.7.2,
               requests==2.25.0,
               six==1.15.0,
               pydrive==1.3.1,
               httplib2==0.18.1,
               oauth2client==4.1.3,
               uritemplate==3.0.1,
               google-api-python-client==1.11.0,
               google-api-core==1.22.2,
               google-auth==1.23.0,
               google-auth-httplib2==0.0.4,
               googleapis-common-protos==1.52.0,
               pyasn1==0.4.8,
               pyasn1-modules==0.2.8,
               rsa==4.6,
               pyyaml==5.3.1,
               matplotlib==3.1.2

and it worked!!!
The Crash no longer happens!  Now it authenticates in the web App and when I return to the Android App that started the Authenticate that App did NOT crash and now works just like it does on the PC.

Thank You!!!

**Comment by parthea** [comment]
I'm glad it's working! I'll close off this issue but please let me know if you experience an issue with the latest version.
