### ISSUE TITLE
Can we get calendar's event color by passing an identifier?

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1133]
Hi there,

Since calendars's description is presented in such JSON format, where the color of the event isn't part of the nested json, I was wondering how can we retrieve the colorid of each event and know **which** color is for **which** event?
Sample event JSON:
```
{
    'kind': 'calendar#event',
    'etag': '"3211301669508000"',
    'id': '3ts0nd8l1..50000Z',
    'status': 'confirmed',
    'htmlLink': 'https://www.google.com/calendar/event?eid=M3RzMG5kOGw..Bn',
    'created': '2020-11-17T22:06:44.000Z',
    'updated': '2020-11-17T22:07:14.754Z',
    'summary': 'Check email, news, articles',
    'creator': {
        'email': 'daniyaldehleh@gmail.com'
    },
    'organizer': {
        'email': 'a24..14k@group.calendar.google.com',
        'displayName': 'ToDo',
        'self': True
    },
    'start': {
        'dateTime': '2020-11-25T10:00:00-05:00',
        'timeZone': 'America/Toronto'
    },
    'end': {
        'dateTime': '2020-11-25T10:30:00-05:00',
        'timeZone': 'America/Toronto'
    },
    'recurringEventId': '3ts0nd8...qdefa',
    'originalStartTime': {
        'dateTime': '2020-11-25T10:00:00-05:00',
        'timeZone': 'America/Toronto'
    },
    'iCalUID': '3t..lbcqdefa@google.com',
    'sequence': 1,
    'reminders': {
        'useDefault': True
    }
```

I was wondering if one of the ways would be to pass an identifier such as `ICalUID` to `colors = service.colors().get().execute()` per [doc](https://developers.google.com/calendar/v3/reference/colors/get#python) to get the event's color? if not, curious to know how we can?

**Comment by busunkim96** [comment]
Hi,

It looks like this is primarily a question about the Calendar API rather than the library `google-api-python-client`. Please use one of the support channels listed on [this page](https://developers.google.com/calendar/support) to get help from someone with Calendar API expertise.

Thanks!
