### ISSUE TITLE
How to retrieve user's profile image url after calendar authentication

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1149]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS type and version: MacOS Big Sur
  - Python version: `python 3.8`
  - pip version: `pip --20.2.4`
  - `google-api-python-client` version: ` 1.12.8`

#### Steps to reproduce

  1. I have built google-OAuth with calendar being retrieved in flask by following [Google's doc](https://developers.google.com/calendar/quickstart/python)
  2. Not sure how I can retrieve user's profile picture too. Only found a doc for [js](https://developers.google.com/identity/sign-in/web/people)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by monoueka** [comment]
Hi

**Comment by busunkim96** [comment]
Hi,

This issue tracker is for issues related to the google-api-python-client library. For API usage questions, please use the API's support channels.  https://developers.google.com/calendar/support

In this case I believe you'll need to use the Admin Directory API. 

https://developers.google.com/admin-sdk/directory/v1/quickstart/python
https://googleapis.github.io/google-api-python-client/docs/dyn/admin_directory_v1.users.photos.html
