### ISSUE TITLE
Getting AttributeError: module 'six.moves' has no attribute 'collections_abc' on raspberry pi

### ISSUE THREAD

**Issue by benaldhouse** [googleapis/google-api-python-client#1151]
I can run the Google quickstart.py example script from Visual Studio successfully in Windows using googleapiclient version 1.12.8 but on my Raspberry Pi running Raspbian (version 10 on Pi4b) I get the 'no attribute 'collections_abc'' error with version 1.12.8. I saw a comment from someone saying this problem went away for them when they reverted to version 1.11 (in Ubuntu). I tried this but it made no difference.

https://developers.google.com/sheets/api/quickstart/python
https://www.gitmemory.com/issue/googleapis/google-api-python-client/1029/692229742

**Comment by parthea** [comment]
Please make sure that `six` is at least version 1.13.0

See this entry from the `six` change log: https://github.com/benjaminp/six/blob/master/CHANGES#L30
> - Issue #155: Add `six.moves.collections_abc`, which aliases the `collections`
  module on Python 2-3.2 and the `collections.abc` on Python 3.3 and greater.  

I'm going to close off this issue as `google-api-python-client` already requires `six >= 1.13.0`, but please re-open this issue with additional information if you're still experiencing the problem after upgrading `six`.

**Comment by mjr4917** [comment]
having exactly the same issue, and upgrading six to 1.15.0 made no difference unfortunately. Am very confused

**Comment by benaldhouse** [comment]
I have just checked. My six is at 1.15.0, too.

**Comment by mjr4917** [comment]
i somehow managed to fix this by installing the df2gspread libary which looks like it forced an update to six. Also running a virtual enviroment seems to help!

**Comment by benaldhouse** [comment]
Thanks mjr4917 I'll have a go at that when I get a moment.

**Comment by benaldhouse** [comment]
Sadly installing df2gspread hasn't fixed anything for me. What do you mean by a virtual environment? This is all at the very edge of my experience...

**Comment by benaldhouse** [comment]
I have fixed it! I ran 'pip3 check' which declared 'df2gspread 1.0.4 has requirement google-api-python-client==1.6.7, but you have google-api-python-client 1.12.8.' and so I ran 'pip3 install google-api-python-client==1.6.7' which worked.

**Comment by Om-ar** [comment]
Thank you so much, it really helped me a lot. :)
df2gspread 1.0.4
