### ISSUE TITLE
Retrieving a user's google calendar at the point in time not always working

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1152]
#### Environment details

  - OS type and version: 11.1
  - Python version: `python --3.8.5`
  - pip version: `pip --20.2.4`
  - `google-api-python-client` version: `1.12.8`

#### Steps to reproduce

  1. followed google calendar quickstart docs
  2. retrieved calendar across all the calendars
  3. loop through them to find the nearest one with respect to the point in time

#### Code example

I am trying to retrieve user's current google calendar event (i.e at the point in time). As you can see, I had to make a nested loop to loop through every google calendar of the user. Yet, I don't always get the right event. I am not sure what's my mistake nor if there's a better/conciser way of doing so.

```
    utc_dt = datetime.now(timezone.utc).astimezone().isoformat()
    service = build('calendar', 'v3', credentials=credentials)
    events_result =service.calendarList().list().execute()
    events = events_result.get('items', [])
    Ids = [item['id'] for item in events] #getting more colors because events is not taking the time AlCals is taking
    import pytz
    utc=pytz.UTC
    AllCals = [service.events().list(calendarId=id, timeMin=utc_dt, maxResults=1, singleEvents=True).execute() for id in Ids ]
    calEvent = []
    now = datetime.now()
    for calendar in AllCals:
        for item in calendar["items"]:
            if "dateTime" in item["start"] and item["end"]:
                if datetime.strptime(item["start"]["dateTime"], "%Y-%m-%dT%H:%M:%S%z"):
                    calEvent.append(item)
    now = datetime.now(pytz.utc)
    name = max(dt['summary'] for dt in calEvent if datetime.strptime(dt["start"]["dateTime"], "%Y-%m-%dT%H:%M:%S%z") < now)
    return {'current event':name}
```

It would be awesome if we could _please_ have a feature to access _all_ the calendars simultaneously in a much more concise way as others have mentioned too.

Thanks!

**Comment by parthea** [comment]
Hi @DaniyalDhz,

Please can you share examples of the output that you're seeing vs the output that you're expecting? This specific question may be better suited for StackOverflow as it does not appear to be specific to the `google-api-python-client` library.

**Comment by DaniyalDhz** [comment]
Hi @parthea ! 
Thanks for getting back.
In fact, I did post it on [SO](https://stackoverflow.com/questions/65546203/retrieving-a-users-google-calendar-at-the-point-in-time/65560127?noredirect=1#comment115930266_65560127) & got it solved. 
Sorry for not closing it earlier than I should've.
