### ISSUE TITLE
Blogger API V3 Search Description

### ISSUE THREAD

**Issue by jimmyxp01** [googleapis/google-api-python-client#1155]
I can't find how to add the Search Description using the Blogger API V3. Is it possible to add search description using blogger API ?

**Comment by parthea** [comment]
Hi @jimmyxp01,

According to [this](https://support.google.com/blogger/thread/65615084?hl=en#) community discussion, it's not possible to add a search description using the Blogger API. 

You can create a feature request for the Blogger API by opening an issue [here](https://issuetracker.google.com). You can read more about the issue tracker in general [here](https://cloud.google.com/support/docs/issue-trackers).

In addition, you can send feedback to the Blogger team by clicking on the question mark icon, then clicking 'Send Feedback' button on the blogger site [here](https://www.blogger.com/).

I'm going to close this issue but please re-open it if you have additional questions.
