### ISSUE TITLE
Profile image url with python Authentiction

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1156]
I'm not sure if this feature exists but I couldn't find one for python Authentication. 

I am using [google Oauth](https://developers.google.com/identity/protocols/oauth2/web-server#example) to authenticate my users. I'd like to have access to their profile image URL from the same authentication instead of reasking them to sign in to their google account (when they are already signed in) to get their profile picture from [google sign in button](https://developers.google.com/identity/sign-in/web/sign-in#get_profile_information).

**Comment by parthea** [comment]
Hi @DaniyalDhz ,

You should be able to obtain a user's profile information using the [People API](https://developers.google.com/people/v1/how-tos/authorizing). See the `profile` scope under the heading [Profile Scopes](https://developers.google.com/people/v1/how-tos/authorizing#profile-scopes). 

> Requests that your app be given read access to the authenticated user's basic profile information: name, photo, and language preference.

 I'm going to close this issue but please feel free to re-open it if you have additional questions.
