### ISSUE TITLE
ZeroTouch Enrollment apply configuration for multiple devices in one call

### ISSUE THREAD

**Issue by mBouamama** [googleapis/google-api-python-client#1160]
# My Problems
One call is arround 1s so if i got 1000 devices i need to call this function 1000 times and it will take arrond 1000s.

**Current result**:
```python
for device_reference in my_list_of_devices_references:
  service.customers().devices().applyConfiguration(
    parent=customer_account,
    body={"device": device_reference, "configuration": configuration["name"]}
  ).execute()
```

# Feature request
We can apply one configuration for one device, it's possible to create a call which get list of device reference and apply configuration for all devices.

**Expected**:
```python
service.customers().devices().applyConfiguration(
  parent=customer_account,
  body={"devices": my_list_of_devices_references, "configuration": configuration["name"]}
).execute()
```
# Link
[doc i use for this call](https://developers.google.com/zero-touch/reference/customer/rest/v1/customers.devices/applyConfiguration)

**Comment by parthea** [comment]
Hi @mBouamama ,

Please could you create a feature request for this feature using the zero-touch [contact page](https://developers.google.com/zero-touch/support/contact)? 

You can submit feature requests through the [zero-touch community](https://zt.androidenterprise.dev/s/) or the send feedback button in [this portal](https://partner.android.com/zerotouch).

I'm going to close off this issue as zero-touch is an upstream API that lives outside of `google-api-python-client`.
