### ISSUE TITLE
Getting action required from google OAuth verification when my app already has those

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1177]
Less than a week ago, I thoroughly read both Google and third-party docs multiple times on how to prepare the app for verification. I've done all the steps:

I now see at my developer console:

[![enter image description here][1]][1]

Which makes no sense as I have a clear & obviously accessible homepage with a robust privacy policy that I've downloaded from a third-party app after filling in my app requirements.

Also, despite the review sent, my privacy policy is extremely visible on the homepage as it's in the navbar.

What shall I do? **More importantly**, how can I even explain this to the officials? as not only I am not sure what changes to make at the present but also not sure if I should make a SO question out of any review that doesn't make sense.

P.S: I received no emails from them. I also tried [Google Support hub][2] which was quite impractical if you're a free member (at least in my condition). 

Lastly, when i go to make edit:
I get:
[![enter image description here][3]][3]
So I don't know if the app is undergoing verification or is waiting for me to make changes. I am so lost.

  [1]: https://i.stack.imgur.com/yt3xq.png
  [2]: https://cloud.google.com/support-hub
  [3]: https://i.stack.imgur.com/KbCWl.png

**Comment by busunkim96** [comment]
Hi @DaniyalDhz,

I'm not too familiar with this verification process, but I assume you're following https://support.google.com/cloud/answer/9110914

Follow-up emails from the verification team appear to be sent from `api-oauth-dev-verification@google.com`. Can you check that this isn't being filtered out on accident?

If you don't find any emails, please try reaching out to `oauth-feedback@google.com` about the status of your project.

And as a reminder, it looks like the process can take up to a few weeks depending on what scopes are being requested. https://support.google.com/cloud/answer/9110914#how-long

**Comment by DaniyalDhz** [comment]
Hi @busunkim96 
Thanks for getting back.
I actually got the email the day after stating It looks like your project  is a development or staging app. Development/staging projects, which I am not sure why they would think that.

**Comment by busunkim96** [comment]
@DaniyalDhz Please continue to use that email thread to reach out to the team that handles OAuth verification. Since this issue cannot be resolved in the library, I'm going to go ahead and close out this issue.
