### ISSUE TITLE
service object gives error on closing

### ISSUE THREAD

**Issue by Sunshine95** [googleapis/google-api-python-client#1200]
New developer here.
service.close() gives an error as detailed below.

#### Environment details

  - OS type and version: Ubuntu 20.04
  - Python version: 3.8.5
  - pip version: 21.0.1
  - `google-api-python-client` version: 1.12.8

#### Steps to reproduce

  1. Follow Read Me, to first code snippet, where a service object is created.

#### Code example

```python
# from googleapiclient.discovery import build
# service = build('youtube', 'v3')
# ...
# service.close()
```
```
Traceback (most recent call last):
  File "--.py", line --, in <module>
    service.close()
  File "/home/user/path/to/file/API/lib/python3.8/site-packages/googleapiclient/discovery.py", line 1335, in close
    self._http.http.close()
AttributeError: 'Http' object has no attribute 'http'
```

**Comment by busunkim96** [comment]
Hi @Sunshine95,

Thanks for the report. I think https://github.com/googleapis/google-auth-library-python-httplib2/pull/14/ needs to be merged/released for this to be resolved. I'll work on getting that PR updated.

**Comment by Sunshine95** [comment]
Dear Bu Sun Kim,

I am glad that you found it useful. I was worried about that my comment
would be a faux pas.

Thank You
Tony

**Comment by busunkim96** [comment]
It turns out this is a duplicate of #1046, so closing this one to continue tracking on the older issue. I've updated https://github.com/googleapis/google-auth-library-python-httplib2/pull/14. The next version of google-auth-httplib2 (expected release next week) should fix the issue.
