### ISSUE TITLE
blogger post thumbnail not showin

### ISSUE THREAD

**Issue by tomahocbc** [googleapis/google-api-python-client#1201]
please how I can upload blogger post-thumbnail using python

**Comment by busunkim96** [comment]
Hi,

I'm not familiar with the blogger API, so I have a few questions/asks:

(1) Which version of the API are you working with (v2 or v3)? https://developers.google.com/blogger 
(2) Are you working off of a specific sample? If you have existing code, please share the snippet with us. :)  If you don't have existing code, please identify the specific [method](https://developers.google.com/blogger/docs/3.0/reference) you are trying to work with.

**Comment by parthea** [comment]
Hi @tomahocbc,
I'm going to close off this issue due to inactivity. If you're still having trouble, please re-open it with more information.
