### ISSUE TITLE
UnknownApiNameOrVersion while uploading video on youtube in googleapiclient.discovery.build

### ISSUE THREAD

**Issue by dc-creator** [googleapis/google-api-python-client#1203]
#### Environment details

  - OS type and version: windows 10 x64
  - Python version: 3.8.5
  - pip version: 21.0.1 
  - google-api-python-client version: 1.12.8

#### Code example 1

```
from googleapiclient.discovery import build
build("youtube", "v3")
```

https://kminito.tistory.com/5
full code which i was trying to execute is here

#### Stack trace 1
```
Traceback (most recent call last):
  File "C:\Users\tasoo\PycharmProjects\record-youtube\venv\lib\site-packages\google_api_python_client-1.12.8-py3.8.egg\googleapiclient\discovery.py", line 274, in build
    content = _retrieve_discovery_doc(
  File "C:\Users\tasoo\PycharmProjects\record-youtube\venv\lib\site-packages\google_api_python_client-1.12.8-py3.8.egg\googleapiclient\discovery.py", line 388, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: youtube  version: v3

```

#### Code example 2

```
from googleapiclient.discovery import build_from_document
build_from_document("youtube")
```

#### Stack trace 2

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

https://kminito.tistory.com/5
full code which i was trying to execute is here

I was trying to upload a video on youtube.
I watched issues about this and none of it worked
I tried changing "v3" into "v2" or "v1"
Please help

**Comment by parthea** [comment]
Hi @dc-creator, I'm not able to reproduce the problem. I'm wondering if it is a network problem.

Please check the following:

- Can you try to see if you can visit [this page](https://www.googleapis.com/discovery/v1/apis/drive/v3/rest) in your browser?
- Can you try running the following command in terminal and post the output?
`curl https://www.googleapis.com/discovery/v1/apis/`
- Are you using a proxy?

**Comment by dc-creator** [comment]
![제목 없음](https://user-images.githubusercontent.com/74556389/109507941-a0913300-7ae2-11eb-9ba9-3004998bb064.png)
I successfully visited the site.


those curl results were so long so i pasted it in pastebin
https://pastebin.com/bJjwmCr8


and I tried turning off https://github.com/ValdikSS/GoodbyeDPI but it didn`t worked

thanks @parthea

**Comment by parthea** [comment]
Hi @dc-creator ,

I'm unable to re-create the problem. Can you please share more code? Please make sure to remove any credential information.
