### ISSUE TITLE
`instances` doesn't display the `items[0].attendees` field

### ISSUE THREAD

**Issue by georgettica** [googleapis/google-api-python-client#1211]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick fixes":

  - [x] Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - [x]  Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version` 
  ``` Python 3.9.2 ```
  - pip version: `pip --version` - 
  ``` pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9) ```
  - `google-api-python-client` version: `pip show google-api-python-client`
  ```
Name: google-api-python-client
Version: 1.12.8
Summary: Google API Client Library for Python
Home-page: https://github.com/googleapis/google-api-python-client/
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: google-auth, six, google-api-core, httplib2, uritemplate, google-auth-httplib2
Required-by:
```
  

#### Steps to reproduce

  1.  create a recurring event and add one person as an attendee to ONE event (let's say the first)
  2.  from the `instances` endpoint, look at this event and see if in `.items[0].attendees` has a value

#### Code example

```python
def get_attendees(service, recurring_event_id, calendar_id)
       instances_result = service.events().instances(calendarId=calendar_id,
            eventId=recurring_event_id, maxResults=1).execute()
        events = instances_result.get('items',[])
        if not events:
            return []
        first_event = events[0]
        import json
        print(json.dumps(first_event))
        attendees = first_event.get('attendees',[])
        print(f"attendees ::: {attendees}")
        if not attendees:
            return []
        return attendees
print(len(get_attendees(service, recurring_event_id, calendar_id))
0
```

### Additional notes
when running the same command on the `events` endpoint, I can see the attendees for only one event

also, when I set the attendace to `all events` I can see the attendance show up..

IIUC the `instances` is supposed to show the underlying events for a specific recurring events, and it seems some of the data doesn't bubble up correctly

**Comment by georgettica** [comment]
the issue was the `timeMin` field was not set, added it and the issue was solved

**Comment by parthea** [comment]
Hi @georgettica , Please could you try out a similar request in the 'Try this API' interface on this [page](https://developers.google.com/calendar/v3/reference/events/instances). This helps confirm if this is a client library issue or a API issue. If it is an API issue, we'll redirect you to the API support channel so you can get better quality answers. For the Calendar API please see https://developers.google.com/calendar/support.

**Comment by georgettica** [comment]
I verified and the issue still persists

took the calendar ID from https://developers.google.com/calendar/v3/reference/calendarList/list
took the recurring event ID from https://developers.google.com/calendar/v3/reference/events/list
added the `timeMin` and `maxResults` so the UI won't break

and I didn't get the recurrence


funny thing, when I use https://developers.google.com/calendar/v3/reference/events/list, I see the 2 recurring events and 2 singular events.
the singular events are created after I added myself as an attendant. the general attendance didn't change

**Comment by parthea** [comment]
Thanks for verifying, @georgettica! As this is an issue with the underlying Calendar API, which lives outside of this repo, please follow the instructions [here](https://developers.google.com/calendar/support#bugs) to file a bug.
