### ISSUE TITLE
Unable to access private APIs

### ISSUE THREAD

**Issue by habibutsu** [googleapis/google-api-python-client#1225]
There is no possibility to use `earthengine` api with default behavior (static_discovery=True), because corresponded file is missed in discovery_cache. 

In addition this changes broke **earthengine-api**, see [issues/157](https://github.com/google/earthengine-api/issues/157)

**Comment by busunkim96** [comment]
Hi,

I think from the perspective of this library things are working as intended. `static_discovery=True` can only be used with APIs listed in the public directory of Google APIs: https://www.googleapis.com/discovery/v1/apis.

If an API is outside that list, there are two options:

**1.  Use `discovery.build_from_document()` with a copy of a discovery doc JSON for the API.**  

It looks like https://github.com/google/earthengine-api/blob/114dcad4bdd2edd7cf604c39e33019baab15436d/python/ee/_cloud_api_utils.py#L156-L179 does this, but only for tests.

Pros:
- Library will not change unexpectedly.
- No dependency on the live discovery document being available.

Cons:
- Need to update the JSON file manually.

**2. Use `discovery.build()` and pass *both* `discovery_url` and `static_discovery=False`.** 

This results in behavior equivalent to 1.x of this library. 

Pros:
- Library always matches the latest version of the API.

Cons:
- If the discovery doc is unavailable for some period of time, you cannot use the Python library.
- The discovery doc may change in unexpected ways, resulting in different results from running the same code with the same dependencies multiple times. 


@parthea Would you mind adding some information to the docs clarifying which APIs are available with `static_discovery=True`?

**Comment by parthea** [comment]
Will do. In addition, there is an internal inquiry open for making the EarthEngine API discovery document public. Googlers see b/179047744

**Comment by busunkim96** [comment]
Googlers,

If you're an API owner and your users are broken by v2 please make sure:

1.  The discovery document [is public](https://g3doc.corp.google.com/google/g3doc/oneplatform/discovery.md?cl=head#making-your-discovery-document-public)
2.  The API [is listed](https://g3doc.corp.google.com/google/g3doc/oneplatform/discovery.md?cl=head#discovery-directory) in the discovery directory. 


As an added bonus you will get client libraries in the other languages with Discovery-based generators. :)

**Comment by Ark-kun** [comment]
> If you're an API owner and your users are broken by v2 please make sure:
> 
> 1. The discovery document [is public](https://g3doc.corp.google.com/google/g3doc/oneplatform/discovery.md?cl=head#making-your-discovery-document-public)

What can we do for private APIs?

**Comment by busunkim96** [comment]
Hi @Ark-kun,

Please see https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-791045487. 


_Right now_, you would do something like this to call a private API:

```py
from googleapiclient import discovery

client = discovery.build(
    "myapi",
    "v1alpha1",
    discoveryServiceUrl="https://myapi.googleapis.com/$discovery/rest?version=v1alpha1",
    static_discovery=False,
)
```

@parthea and I were discussing automatically setting `static_discovery=False` if `discoveryServiceUrl` is passed. With that change folks would do something like this:

```py
from googleapiclient import discovery

client = discovery.build(
    "myapi",
    "v1alpha1",
    discoveryServiceUrl="https://myapi.googleapis.com/$discovery/rest?version=v1alpha1",
)
```

**Comment by wyk9787** [comment]
@busunkim96 Is there an ETA on when we can call private API without specifying `static_discovery=False` (i.e. entirely backward compatible for client library 2.0 in terms of building the discovery client) ?

**Comment by busunkim96** [comment]
@wyk9787 I think by the end of this month. It should be a relatively small change in `discovery.build()`.
