### ISSUE TITLE
Increase library size

### ISSUE THREAD

**Issue by dcamdupe** [googleapis/google-api-python-client#1239]
google-api-python-client 2.0.2 is a roughly 10x increase in size over 1.12.8, when installed through pip.

To reproduce:
pip install google-api-python-client

Earlier version:
google-api-python-client==1.12.8

It's not a massive issue, but it's a surprising increase. In our case it broke a build + deploy to AWS Lambda by adding ~15Mb to the built package.

**Comment by 93million** [comment]
It appears that 2.0.2 is 125x larger than 2.0.1.

Discovered debugging a docker image that grew 50+MB

2.0.1 is 432 KB:
```
/certbot/venv/lib # du -sk python3.8/site-packages/googleapiclient/
432	python3.8/site-packages/googleapiclient/
```

2.0.2 is 54,220 KB:
```
/certbot/venv/lib # du -sk python3.8/site-packages/googleapiclient/
54220	python3.8/site-packages/googleapiclient/
```

**Comment by dcamdupe** [comment]
Thanks for clarifying. The Cloud client libraries looks like a good direction to explore.
