### ISSUE TITLE
Links in pip page are broken

### ISSUE THREAD

**Issue by dcamdupe** [googleapis/google-api-python-client#1240]
Links in the body of the description page for the project are broken:
https://pypi.org/project/google-api-python-client/

The following links are broken:

- "docs folder" - under section Google API Client
- "Migration Guide" - under section Version 2.0 Release
- "docs folder" - under section Documentation
- "Contribution Guide" - under section Contributing

**Comment by parthea** [comment]
Hi @dcamdupe,

Thanks for reporting this! This will be fixed in #1251
