### ISSUE TITLE
Using through a proxy

### ISSUE THREAD

**Issue by mef1stofel** [googleapis/google-api-python-client#1260]
Is there a described way to use the library via a proxy server?
I just found that I can pass `proxies` parameter in auth_flow:
```python
auth_flow.fetch_token(code=code, proxies=proxy_dict)
```
But I have no idea how to set proxy to the  Resource object (`googleapiclient.discovery.build()`)
It has HTTP parameter - An instance of httplib2.Http and I can prepare this  instance and set proxy to it, but I can't use credentials in that case.
There is a way with an env variable, but it is not an appropriate way for me: `os.environ['HTTP_PROXY'] = ...`

How it is possible to set proxy for Resource object?

**Comment by parthea** [comment]
Hi @mef1stofel ,

https://github.com/googleapis/google-api-python-client/issues/1078#issuecomment-718919158 shows how to create an `AuthorizedHttp` instance using [google_auth_httplib2](https://github.com/googleapis/google-auth-library-python-httplib2). I pasted it here for convenience. I also added code to create the `credentials` object from [here](https://github.com/googleapis/google-api-python-client/blob/master/docs/oauth-server.md#preparing-to-make-an-authorized-api-call). Please let me know if you encounter an issue.

```
import httplib2
import google_auth_httplib2
from google.oauth2 import service_account

http = httplib2.Http(proxy_info=httplib2.ProxyInfo(
            httplib2.socks.PROXY_TYPE_HTTP, PROXY_IP, PROXY_PORT
))

SCOPES = ['xxx']
SERVICE_ACCOUNT_FILE = 'xxx'

credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)

authorized_http = google_auth_httplib2.AuthorizedHttp(credentials, http=http)

service = discovery.build(http=authorized_http)
```

**Comment by mef1stofel** [comment]
That it!
Thank you very much!
