### ISSUE TITLE
googleapiclient.errors.UnknownApiNameOrVersion: name: networkconnectivity  version: v1alpha1

### ISSUE THREAD

**Issue by geojacobm6** [googleapis/google-api-python-client#1289]
Unable to build service for networkconnectivity v1alpha1. Even though it's listed in the [Supported APIs](https://googleapis.github.io/google-api-python-client/docs/dyn/#networkconnectivity) page. 

`googleapiclient.discovery.build('networkconnectivity', 'v1alpha1')`

**Comment by parthea** [comment]
`networkconnectivity_ v1alpha1` will be added  in #1291 . I'm hoping to merge #1187 soon to automate the process of updating discovery artifacts.
