### ISSUE TITLE
Freebusy API not working with or w/o a key

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1290]
#### Environment details

  - OS type and version: Big Sur
  - Python version: `python --3.8.5`
  - pip version: `pip --21.0`
  - `google-api-python-client` version: `2.1.0`

#### Code example

```
def busyTimes():
    """
    returns busy time of the user in a day
    """
    body = {
    "timeMin":datetime.now(timezone.utc).astimezone().isoformat(),
    "timeMax": '2021-03-27T21:27:58.945714-04:00',
        "items": [
        {
        "id": "...@group.calendar.google.com"
        }
    ]
    }
    req = requests.post(url='https://www.googleapis.com/calendar/v3/freeBusy', data = body) 
    req_ = req.json()
    return str(req_)
```
#### Stack trace

```
{'error': {'code': 403, 'message': 'The request is missing a valid API key.', 'errors': [{'message': 'The request is missing a valid API key.', 'domain': 'global', 'reason': 'forbidden'}], 'status': 'PERMISSION_DENIED'}}

```
& if I were to include API key along the `request.post()` parameter I would get: 

    TypeError: request() got an unexpected keyword argument 'key'

and if I include it after the link like:

    https://www.googleapis.com/calendar/v3/freeBusy?<apiKey>

I would get:

    {'error': {'errors': [{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}], 'code': 400, 'message': 'Bad Request'}}

I am not sure if the problem is that I am missing an API key even though the [doc](https://developers.google.com/calendar/v3/reference/freebusy) didn't mention to include it or it's because I've not been granted access to the scope despite applying for the nonsensitive scope for almost a month now but getting no response or sign of processing back :(

P.S: I assume I haven't been granted the permission to the scope as the green check isn't displayed beside the freebusy api too. 
<img width="281" alt="Screen Shot 2021-04-12 at 10 51 37 AM" src="https://user-images.githubusercontent.com/58639693/114434226-c6edc800-9b90-11eb-8a0c-96a990319120.png">

Thanks!

**Comment by parthea** [comment]
Hi @DaniyalDhz , Please could you try out a similar request in the 'Try this API' interface on [this page](https://developers.google.com/calendar/v3/reference/freebusy/query) and post the result here? This helps confirm if this is a client library issue or a API issue. If it is an API issue, we'll redirect you to the API support channel so you can get better quality answers. For the Calendar API please see https://developers.google.com/calendar/support.

**Comment by ByBilal** [comment]
Hello, Iv'e raised a similar issue here (https://github.com/googleapis/google-api-python-client/issues/1294)

What was the issue keeping you from access? Thank you for the clarity.
