### ISSUE TITLE
"Request had insufficient authentication scopes." despite the docs word

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1296]
#### Environment details

  - OS type and version: Big Sur
  - Python version: `python --3.8.5`
  - pip version: `pip --21.0`
  - `google-api-python-client` version: `2.1.0`

#### Code example

```    
    credentials = google.oauth2.credentials.Credentials(
        **flask.session['credentials'])
    service = build('calendar', 'v3', credentials=credentials)
    events_result =service.calendarList().list().execute()
    events = events_result.get('items', [])
```

#### Stack trace
```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/users/me/calendarList?alt=json returned "Request had insufficient authentication scopes.". Details: "Request had insufficient authentication scopes.">
```
I downgraded my app scope from 'https://www.googleapis.com/auth/calendar' to 'https://www.googleapis.com/auth/calendar.events.readonly' as I realized I am just going to read & not write. When I ran the same code to retrieve the user's calendar events, I got faced with the error mentioned about _even  though_ the [doc](https://developers.google.com/calendar/v3/reference/events/list#auth) you're able to execute such code with both of the scopes. 

I am confused. I tried making reducing the scope of my usage for the sake of user safety but now I can no longer use anything. 

Thanks!

**Comment by busunkim96** [comment]
Hi,

It looks like the code you proivded uses the method `calendarList.list`. 
REST API docs: https://developers.google.com/calendar/v3/reference/calendarList/list 

That method requires one of the following scopes:

* https://www.googleapis.com/auth/calendar.readonly
* https://www.googleapis.com/auth/calendar

**Comment by DaniyalDhz** [comment]
Hi there,
That solved my problem. Thank you so much!
