### ISSUE TITLE
from apiclient import __version__

### ISSUE THREAD

**Issue by jpoehnelt** [googleapis/google-api-python-client#13]
Running into an issue with import version

```
File "/app/.heroku/python/lib/python2.7/site-packages/apiclient/http.py", line 50, in <module> 
 from model import JsonModel 
File "/app/.heroku/python/lib/python2.7/site-packages/apiclient/model.py", line 30, in <module> 
 from apiclient import __version__ 
 ImportError: cannot import name __version__
```

Issue Mentions: 
http://xmodulo.com/2013/12/integrate-google-calendar-linux-desktop.html
https://github.com/insanum/gcalcli/issues/123

**Comment by giancarloap** [comment]
Great work. And the Oscar goes to AlexanderPease, best performance. https://www.youtube.com/watch?v=W_gYRFDb8_A

**Comment by RobinIsTheBird** [comment]
$ sudo pip install --upgrade googleapiclient
Downloading/unpacking googleapiclient
  Real name of requirement googleapiclient is googleapiclient
  Could not find any downloads that satisfy the requirement googleapiclient
Cleaning up...
No distributions at all found for googleapiclient
Storing debug log for failure in /home/rschaufler/.pip/pip.log

and still getting
$ gcalcli agenda
ERROR: Missing module - No module named discovery

**Comment by craigcitro** [comment]
there's a name mismatch; you want `google-api-python-client` for the `pip` command.

**Comment by RobinIsTheBird** [comment]
@craigcitro I was trying to follow the 8/1/2014 instructions above from @AlexanderPease.

I had already done `pip google-api-python-client`, and was getting the discovery module not found error.

Moot point, I somehow got past the discovery issue and ran into another issue, leading me to give up entirely on trying to install gclical. If it had this many problems with just installation, I'm not going to trust it to touch my calendar.

**Comment by elijahcarrel** [comment]
@RobinIsTheBird how did you get past the discovery issue?

**Comment by RobinIsTheBird** [comment]
@elijahcarrel I'm sorry, but I forget now. It was a couple weeks ago, and since there was a later showstopper, I gave up entirely. Binding my google calendar to a separate chrome window is a sufficient solution to reducing my Chrome tab count, while presenting a unique icon to the application switcher, which is what I mainly cared about.

**Comment by chromafunk** [comment]
I am also having this problem. Calling googleapiclient.discovery also throws me a "No module named" error....

**Comment by robmorehead** [comment]
@chromafunk,

After many frustrating hours, I finally got my build to import.  Be sure that you have the library googleapiclient within the lib folder in your appengine-flask-skeleton-master directory.  If you do not, you should be able to copy it from the Python Frameworks.  You might as well take this time to copy over any other import libraries that are not already there (this could be apiclient, httplib2, oauth2client, simplejson, six, uritemplate, urllib3, etc.).  I recall having issues with all of them.

On my mac, you can find the Python libraries within:
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

Now regarding the import call.

from googleapiclient.discovery import build

I could only get this to work when it was within a flask method.  for example:

@app.route('/oauth2callback')
def oauth():
	from googleapiclient.discovery import build

This was the only way I could get it to work!  Hope it helps.  Feel free to reach out if you would like to discuss.

**Comment by shawnhero** [comment]
@robmorehead It seems your answer was from years ago, but it did fix my problem. thx

**Comment by pedrocaseiro** [comment]
I just had the same problem and @robmorehead trick worked 💯

**Comment by AnanyaChandraker** [comment]
Please use:
pip install --upgrade google-api-python-client

This worked perfectly for me in python 2.7 and with python 3.6.5

**Comment by ArtinBog** [comment]
does anybody know what to do if pip install --upgrade google-api-python-client doesn't help?

**Comment by jfrazee216** [comment]
I have the same issue with python 3.6.5 in 2020......
