### ISSUE TITLE
Duplicated bundled discovery documents

### ISSUE THREAD

**Issue by henribru** [googleapis/google-api-python-client#1330]
It seems like some of the static discovery documents have ended up being duplicated under ever so slightly different names. One example is https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/admin.datatransfer_v1.json and https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/admin.datatransferv1.json. Another is https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/dfareporting.v3.3.json and https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/dfareporting.v33.json. There seems to be around 12 of these pairs. Just figured I'd let you know in case it was an accident.

**Comment by parthea** [comment]
Thanks for reporting this, @henribru !
