### ISSUE TITLE
apigee list environments method not found

### ISSUE THREAD

**Issue by himasagaratluri** [googleapis/google-api-python-client#1338]
`environment_api = apigee_org.environments()`
`>>> environment_api.`
environment_api.analytics(
environment_api.get(
environment_api.queries(
environment_api.testIamPermissions(
environment_api.apis(
environment_api.getDebugmask(
environment_api.references(
environment_api.traceConfig(
environment_api.caches(
environment_api.getDeployedConfig(
environment_api.resourcefiles(
environment_api.unsubscribe(
environment_api.close(
environment_api.getIamPolicy(
environment_api.setIamPolicy(
environment_api.update(
environment_api.create(
environment_api.getTraceConfig(
environment_api.sharedflows(
environment_api.updateDebugmask(
environment_api.delete(
environment_api.keystores(
environment_api.stats(
environment_api.updateEnvironment(
environment_api.deployments(
environment_api.keyvaluemaps(
environment_api.subscribe(
environment_api.updateTraceConfig(
environment_api.flowhooks(
environment_api.optimizedStats(
environment_api.targetservers(

I'm using `google-api-python-client 2.3.0`

As per the API reference there should be a `list` in the `organizations.environments` method [link](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments/list)

**Comment by parthea** [comment]
Hi @himasagaratluri,

Thanks for reporting this issue! I found a similar issue mentioned in https://github.com/googleapis/google-api-go-client/issues/742 . I'll update this issue once I have more information.

**Comment by parthea** [comment]
I've heard back from the API team. There is a compatibility issue with this specific Apigee method and the autogenerated clients, which can't be easily solved. It is recommended to use the REST endpoint directly using the link you provided : https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments/list . I'm going to close this issue but please feel free to re-open it if you have additional questions. If you'd like to send feedback directly to the Apigee team, please click the Send Feedback button on the support page [here](https://cloud.google.com/apigee/docs/support). Googlers see b/172643712.
