### ISSUE TITLE
Custom attribute not given when searching user

### ISSUE THREAD

**Issue by M0NsTeRRR** [googleapis/google-api-python-client#1339]
Hello,

I've mapped discord user ID and pseudo to gsuite account, unfortunately when I search people by their discord_id the API does not return always the discord_id sometimes yes sometimes not

Request :
```
admin_sdk.users().list(
      query=f"custom.discord_id={discord_id}",
      customer="my_customer",
      projection="full",
      viewType="admin_view",
  )
```

Response :
```
{'kind': 'admin#directory#user', 'id': '0000000000000000', 'etag': '"000000000000000000"', 'primaryEmail': 'first.last@example.com, 'name': {'givenName': 'first', 'familyName': 'last', 'fullName': 'first last'}, 'isAdmin': False, 'isDelegatedAdmin': False, 'lastLoginTime': '2021-05-05T18:41:18.000Z', 'cre
ationTime': '2021-05-05T18:39:15.000Z', 'agreedToTerms': True, 'suspended': False, 'archived': False, 'changePasswordAtNextLogin': False, 'ipWhitelisted': False, 'emails': [{'address':
 'first.last@example.com', 'primary': True}], 'organizations': [{'primary': True, 'customType': '', 'department': 'technique'}], 'customerId': '0000000', 'orgUnitPath': '/', 'isMa
ilboxSetup': True, 'isEnrolledIn2Sv': False, 'isEnforcedIn2Sv': False, 'includeInGlobalAddressList': True, 'customSchemas': {'custom': {'pseudo': 'pseudo'}}}
```

Pseudo is returned but there is no discord_id. I want to verify that the API is sending me the right user.

**Comment by parthea** [comment]
Hi @M0NsTeRRR,

Please could you try out a similar request in the 'Try this API' interface on [this page](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users/list) and check whether the issue exists? This helps confirm if this is a client library issue or a API issue. If it is an API issue, we'll redirect you to the API support channel so you can get better quality answers. For the Admin SDK API please see https://developers.google.com/admin-sdk/directory/support.

**Comment by M0NsTeRRR** [comment]
Same behaviour, I will open a new one on the other repository.

Thanks for your answer
