### ISSUE TITLE
I python  :  ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by JanickiJ** [googleapis/google-api-python-client#1358]
I am using buildoizer to run KivyMD app on Android, I performed installation steps :

pip install virtualenv
virtualenv <your-env>
source <your-env>/bin/activate
<your-env>/bin/pip install google-api-python-client

But the error still occures 
I python  :  ModuleNotFoundError: No module named 'google'

**Comment by parthea** [comment]
Hi @JanickiJ,

Please can you share more information using the template below?

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-api-python-client` version: `pip show google-api-python-client`

#### Steps to reproduce

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

**Comment by JanickiJ** [comment]
Sorry for not closing the issue. 
The sollution was to move google package from /usr/local/lib/python3.8/dist-packages where was installed, to the folder where i needed it myApp/.buldoizer/android/platform/build-armeabi-va7/build/python-installs/myapp.
Thanks for response!!!
