### ISSUE TITLE
Is it safe to make credentials.json publicly available?

### ISSUE THREAD

**Issue by exodojaffar** [googleapis/google-api-python-client#1362]
I have a python desktop application that uses the Google Tasks API, I was wondering if I can make available the credentials generated along with the application. (Google Translator)

**Comment by parthea** [comment]
Hi @exodojaffar,

No, I would not recommend to include `credentials.json` in the desktop application as it contains sensitive information. Please let me know if you have any other questions!

**Comment by parthea** [comment]
I'm going to close this issue but please feel free to re-open it if you have additional questions.
