### ISSUE TITLE
doubleclickbidmanager v1.1 : Systematic 403 Forbidden when discovery build

### ISSUE THREAD

**Issue by Just1B** [googleapis/google-api-python-client#1370]
#### Environment details

  - OS type and version: `Darwin or linux`
  - Python version: `3.9`
  - pip version: `21.1.1`
  - google-api-python-client: `2.5`
  - env : `Cloud Composer` ( KubernetesPodOperator ) or `localhost`

#### Issue 

Since yesterday, i got a systematic 403 Forbidden error when building a dicovery service ( was working before )

And no static_discovery available for `doubleclickbidmanager v1.1 `

```python 

    def authorize(self) -> google_auth_httplib2.AuthorizedHttp:

        credentials = service_account.Credentials.from_service_account_info(
            self.keyfile_dict,
            scopes=self.scopes,
        )

        http = build_http()
        authed_http = google_auth_httplib2.AuthorizedHttp(credentials, http=http)

        return authed_http

    def get_client(self):

        try:
            client = build(
                'doubleclickbidmanager',
                'v1.1',
                discoveryServiceUrl='https://www.googleapis.com/discovery/v1/apis/doubleclickbidmanager/v1.1/rest',
                http=self.authorize(),
                static_discovery=False,
            )

            return client

        except Exception as error:

            raise error
```
#### Error

`
<HttpError 403 when requesting https://www.googleapis.com/discovery/v1/apis/doubleclickbidmanager/v1.1/rest returned "Forbidden". Details: "<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>">
`

**Comment by parthea** [comment]
Hi @Just1B ,

Unfortunately, I'm not able to re-create the problem using the code that you provided. I'm getting `reply: 'HTTP/1.1 200 OK\r\n'` and the client successfully builds. Are you able to try the sample code you provided in another environment?

**Comment by Just1B** [comment]
Your are right, it's look like my problem is not related to the discovery build but the api directly.

Still got a 403 but with the query endpoint now, I will contact the DBM support

```
<HttpError 403 when requesting https://doubleclickbidmanager.googleapis.com/doubleclickbidmanager/v1.1/query?alt=json returned "Forbidden". Details: "<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>">
```
 
But happy to know that static_discovery is working with doubleclickbidmanager, i will save some http calls 👍

I was thinking static_discovery was not working because of this error.

```bash
ERROR : name:  doubleclickbidmanager  version: v1.1
```

It's occured when we are passing a dict key vs a string to the build method

The real code support both doubleclickbidmanager and displayvideo ( Trigger the error )

###### Not Working

```python
def get_client(use_new_api=False):

    try:

        DOUBLECLIC_API = {
            "API_NAME": " doubleclickbidmanager",
            "API_VERSION": "v1.1",
        }
    
        DV360_API = {
            "API_NAME": " displayvideo",
            "API_VERSION": "v1",
        }

        API = DOUBLECLIC_API if use_new_api == False else DV360_API

        client = build(
            API["API_NAME"],
            API["API_VERSION"],
        )

        return client

    except Exception as error:
        raise error
```

I updated my code and the build is working now 🤙 

###### OK

```python
def get_client(use_new_api=False):

    try:
        client = (
            build("doubleclickbidmanager", "v1.1")
            if use_new_api == False
            else build("displayvideo", "v1")
        )

        return client

    except Exception as error:
        raise error
```

**Comment by parthea** [comment]
I'm glad to hear that `discovery.build()` is working. Please re-open this issue if you have any questions.
