### ISSUE TITLE
HttpError 404 : Requested entity was not found

### ISSUE THREAD

**Issue by CharleoY** [googleapis/google-api-python-client#1378]
I have been debugging for the quickstart code here https://developers.google.com/apps-script/api/quickstart/python for a hole day.

I am really confused that code below can run smoothly( which to get the info of the script and push the new script): 
```
 pushBody = {
                        'files': [{
                            'name': 'new',
                            'type': 'SERVER_JS',
                            'source': code
                        }, {
                            'name': 'appsscript',
                            'type': 'JSON',
                            'source': manifest
                        }]
                        }
        
response = service.projects().get(scriptId=scriptID).execute()
pushResponse = service.projects().updateContent(body=pushBody,scriptId=scriptID).execute()
```
But it's wired that when I execute or deploy the script:
```
executeBody = {"function":"doPost","devMode": "true"}
executeResponse = service.scripts().run(scriptId=scriptID, body=executeBody).execute()
service.projects().deployments().create(scriptId=scriptId, body=body).execute()
```
it pops the exceptions : `googleapiclient.errors.HttpError: <HttpError 404 when requesting https://script.googleapis.com/v1/scripts/1-3Lsm8-w4qgkNzGwWRO08DgOznCVl9af8gJ2ezj89AZL_JMUhK_6WMx6:run?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">`

I have tried regenerate api tokens and re-grant the permission. But neither helps.

I'd appreciated if you can help.

**Comment by parthea** [comment]
Hi @CharleoY ,

I wasn't able to reproduce the problem. I ran through the quick start on my machine and it ran successfully. As mentioned in https://github.com/googleworkspace/python-samples/issues/179, please make sure that you're not running the sample on a remote machine. Also, please make sure that the Apps Script is enabled by visiting [here](https://script.google.com/home/usersettings). As the actual sample lives [here](https://github.com/googleworkspace/python-samples/blob/master/apps_script/quickstart/quickstart.py), please click [here](https://github.com/googleworkspace/python-samples/issues/new) to open a new issue in that repo.
