### ISSUE TITLE
'OSError' object has no attribute 'authorize'

### ISSUE THREAD

**Issue by paritosh-upadhyay** [googleapis/google-api-python-client#1383]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: ```PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```
  - Python version: 3.8.10 
  - pip version: `pip 21.1.1`
  - `google-api-python-client` version: Name: google-api-python-client
Version: 2.6.0
Summary: Google API Client Library for Python
Home-page: https://github.com/googleapis/google-api-python-client/
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.8/site-packages
Requires: httplib2, google-api-core, six, google-auth-httplib2, uritemplate, google-auth

#### Steps to reproduce

  1. run python quickstart.py

#### Code example

```python
service = build('drive', 'v3', credentials=creds)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/src/app/grow/services/daily_status_services.py", line 137, in create_and_share_folder
    service = build('drive', 'v3', credentials=creds)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 299, in build
    service = build_from_document(
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 584, in build_from_document
    http = _auth.authorized_http(credentials)
  File "/usr/local/lib/python3.8/site-packages/googleapiclient/_auth.py", line 119, in authorized_http
    return credentials.authorize(build_http())
AttributeError: 'OSError' object has no attribute 'authorize'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Can you share how the `cred` object is being created? It looks like it is not an expected credentials type.

If you haven't already, it may be helpful to reference the Python Quickstart for Drive for an auth flow example: https://developers.google.com/drive/api/v3/quickstart/python

**Comment by busunkim96** [comment]
Hmm. Does a browser get opened to auth?

It might be that `run_local_server()` doesn't work inside the container since it tries to open a browser.

Could you try `run_console()` instead? It provides a link that you visit to get the code.

```
creds = flow.run_console()
```

https://googleapis.dev/python/google-auth-oauthlib/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow.run_console

**Comment by paritosh-upadhyay** [comment]
No browser is not opened because I am using token.pickle file for auth. It is also not opening any browser on my local setup but authentication is working fine due to token.pickle file.

**Comment by busunkim96** [comment]
I see. Could you try dumping the credentials as JSON (see example below) instead of a pickle file?

(Copied from https://developers.google.com/drive/api/v3/quickstart/python)
```py
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

def main():
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json')
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

if __name__ == '__main__':
    main()
```

From the original error it looks like  either `OsError` is getting written to the pickle file or something is going wrong during the loading.

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please feel free to re-open it with more information.
