### ISSUE TITLE
HttpError 400: Request contains an invalid argument for factchecktools_v1alpha1 endpoint

### ISSUE THREAD

**Issue by trisongz** [googleapis/google-api-python-client#1422]
#### Environment details

  - OS type and version: MacOS Big Sur
  - Python version: Python 3.7 
  - `google-api-python-client` version: `2.9.0`

#### Steps to reproduce

  1. Domain-wide delegated Service Account with Valid ADC JSON
  2. Pass Credentials and Scopes to discovery.build
  3. Call `service.claims().search(query='..').execute()`

#### Code example

```python
from googleapiclient import discovery
from google.oauth2 import service_account


SCOPES = ['https://www.googleapis.com/auth/userinfo.email']
SERVICE_ACCOUNT_FILE = '/path/to/adc.json'

credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
credentials = credentials.with_subject('user@domain.com')

service = discovery.build('factchecktools', 'v1alpha1', credentials=credentials)
request = service.claims().search(query="example query")
response = request.execute()
print(response)

```

#### Stack trace
```
HttpError: <HttpError 400 when requesting https://factchecktools.googleapis.com/v1alpha1/claims:search?query=Covid+Can+be+transmitted returned "Request contains an invalid argument.". Details: "Request contains an invalid argument.">
```

**Comment by parthea** [comment]
Hi @trisongz,

Thanks for reporting this issue. I was able to reproduce the problem with curl if I add HTTP Header `"authorization: Bearer XXX"` to the request.

The following results in an HTTP 400 error `Request contains an invalid argument.`
```
curl --header "Authorization: Bearer XX" "https://factchecktools.googleapis.com/v1alpha1/claims:search?query=test&key=YYYYY"
```

Whereas the following succeeds
```
curl "https://factchecktools.googleapis.com/v1alpha1/claims:search?query=test&key=YYYYY"
```

I've filed an internal bug for the Fact Check Tools team to understand if this is an issue with the backend. (Googlers see b/191923860.)

In the meantime, if you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

**Comment by parthea** [comment]
I'm going to close this issue as it was an issue with the backend rather than the client library.

**Comment by pedroserrudo** [comment]
facing the same issue with Alert Center API
