### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by fisakhan** [googleapis/google-api-python-client#1424]
version of google-api-python-client and versions of tensorflow, google-colab, google-auth and six have no compatibility. How can I solve it? 
google-colab==1.0.0
tensorflow==2.5.0
tensorflow-cloud==0.1.16

Even after installing the latest version of google-auth, I get the following error.
```
$ pip install google_auth
Installing collected packages: google-auth
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth~=1.4.0, but you have google-auth 1.32.0 which is incompatible.
google-api-python-client 1.12.8 requires six<2dev,>=1.13.0, but you have six 1.12.0 which is incompatible.
google-api-core 1.30.0 requires six>=1.13.0, but you have six 1.12.0 which is incompatible.
Successfully installed google-auth-1.32.0
```
In order to solve this problem, I tried to install six==1.13.0 but got the following problem:
```
$ pip install six==1.13.0
Collecting six==1.13.0
  Downloading six-1.13.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires six~=1.15.0, but you have six 1.13.0 which is incompatible.
google-colab 1.0.0 requires google-auth~=1.4.0, but you have google-auth 1.32.0 which is incompatible.
google-colab 1.0.0 requires six~=1.12.0, but you have six 1.13.0 which is incompatible.
cookiecutter 1.7.3 requires requests>=2.23.0, but you have requests 2.21.0 which is incompatible.
apache-beam 2.30.0 requires requests<3.0.0,>=2.24.0, but you have requests 2.21.0 which is incompatible.
Successfully installed six-1.13.0
```
How can I make all of them working together? 
Relevant: https://github.com/googleapis/google-api-python-client/issues/933 , https://github.com/tensorflow/cloud/issues/344

**Comment by parthea** [comment]
Hi @fisakhan,

In `google-api-python-client` the requirement is `six>=1.13.0,<2dev` so any version 1.13.0 or higher but less than 2dev will work.

`google-colab` [which hasn't been updated since 2019](https://pypi.org/project/google-colab/#files), does not appear to be supported. Ignoring `google-colab`, you'll need:
`six` version >= 1.15.0
`requests` version >= 2.24.0

I'm going to close this issue but please free free to re-open it if you have additional questions.

**Comment by parthea** [comment]
Googlers see internal issue b/147454824 regarding `google-colab`.
