### ISSUE TITLE
Need to create contacts in "Directory" folder.

### ISSUE THREAD

**Issue by manirhel** [googleapis/google-api-python-client#1428]
Hi,

I need to share external contacts with my org so,, i tried to create the contacts in "Directory" Folder placed in admin contact console using people API. but, when i create the contact it's created only on "Contacts" Folder. please help me on this. i used the below code.

    newContact = {"metadata": {"sources": [{"type": "DOMAIN_PROFILE"}]}, "names": [{"givenName": "John", "familyName": "Doe"}]}
    results = service.people().createContact(body=newContact).execute()

if __name__ == '__main__':
    main()

![2021-07-05 08_53_36-Window](https://user-images.githubusercontent.com/50105566/124413650-b0f63a80-dd6e-11eb-9edd-a48c0d6aa8cc.png)

**Comment by parthea** [comment]
Hi @manirhel,

After reviewing the People API documentation for `createContact` at [this page](https://developers.google.com/people/api/rest/v1/people/createContact), my initial thought is that this is not a supported feature. I found related documentation for adding external contacts [here](https://support.google.com/a/answer/9281635?hl=en) for the Domain Shared Contacts API. If this is a feature that you'd like to see in the People API, please create a feature request in the public issue tracker [here](https://developers.google.com/people/support#missing_features). I'm going to close this issue but please feel free to re-open it if you have additional questions.

**Comment by manirhel** [comment]
Thanks @parthea
