### ISSUE TITLE
How to change codes of Resource().files().create() ?

### ISSUE THREAD

**Issue by nobodycaresme** [googleapis/google-api-python-client#1433]
Hey there,

How can I see and modify codes of this `service.files().create()`:

```
service = build('drive', 'v3', credentials=creds, cache_discovery=False)

media_body = MediaFileUpload(
    file_path,
    mimetype=mime_type,
    chunksize=150*1024*1024,
    resumable=True
  )
  
body = {"name": file_name, "mimeType": mime_type}
body["parents"] = [parent_id]

uploaded_file = service.files().create(body=body, media_body=media_body, fields='id', supportsTeamDrives=True).execute()
file_id = uploaded_file.get('id')
```

I checked the source code but I couldnt find them... Can anyone point me where I could see them and edit?
I am actually trying to edit a small part of code in this `create()`, but I couldnt find it...!

Thanks... <3

**Comment by parthea** [comment]
`google-api-python-client` generates methods dynamically using the [createMethod() here](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery.py#L976) for all APIs using the static discovery files [here](https://github.com/googleapis/google-api-python-client/tree/master/googleapiclient/discovery_cache/documents). 

[discovery.build()](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery.py#L181) returns the generated client [here](https://github.com/googleapis/google-api-python-client/blob/88096a5516196a0c3f1fbaebbcdf7fbd793ba001/googleapiclient/discovery.py#L653). [Here](https://github.com/googleapis/google-api-python-client/blob/88096a5516196a0c3f1fbaebbcdf7fbd793ba001/googleapiclient/discovery.py#L1338) is where the methods are created dynamically.

You can find more information about the `files().create()` method [here](https://developers.google.com/drive/api/v3/reference/files/create). There is also a `Try this API` section on the page in case you want to experiment with the API.

I'm going to close this issue but please feel free to re-open it if you have additional questions.
