### ISSUE TITLE
error400 授权错误

### ISSUE THREAD

**Issue by duyongchao1234** [googleapis/google-api-python-client#1443]
![image](https://user-images.githubusercontent.com/59679136/125571439-21661a92-021b-4688-b99a-a6b6c640d952.png)

**Comment by duyongchao1234** [comment]
可以问一下这个错误i怎么解决吗

**Comment by parthea** [comment]
Hi @duyongchao1234 ,

Please can you share sample code that you're using so I can try to create the problem locally?

**Comment by WHK102** [comment]
Talves con los logs de mensaje de depuración de error o el backtrace sea suficiente.

**Comment by parthea** [comment]
Hi @duyongchao1234 ,
I'm going to close this issue as there is not enough information to help troubleshoot. Please feel free to re-open the issue with more information.
