### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by Dwalinnewyork** [googleapis/google-api-python-client#1468]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by dandhlee** [comment]
Hi @Dwalinnewyork, since there's nothing filled out I'll be closing this issue. If you have any issues with regards to the repository content here feel free to re-open this issue and let us know what issue you're experiencing.
