### ISSUE TITLE
Cannot update some file types/formats

### ISSUE THREAD

**Issue by Cha5machou** [googleapis/google-api-python-client#1471]
Hi everyone,

I am trying to update some files in my drive using the following piece of code 
```
from apiclient.discovery import build
from apiclient.http import MediaIoBaseDownload, MediaFileUpload
from oauth2client.service_account import ServiceAccountCredentials
from httplib2 import Http
import io
import pandas as pd

PATH_FOLDER = './'

scopes = ['https://www.googleapis.com/auth/drive']

credentials = ServiceAccountCredentials.from_json_keyfile_name('credentials.json', scopes)

http_auth = credentials.authorize(Http())
drive = build('drive', 'v3', http=http_auth)

def upload_file(file_name):
    files = drive.files().list().execute()['files']
    for file in files:
        if file['name'] == file_name:
            file_id = file['id']
            break
    file_metadata = {
    'name': file_name,
    'mimeType': file['mimeType']
    }
    media = MediaFileUpload(PATH_FOLDER + file_name, mimetype=file['mimeType'], resumable=True)
    drive.files().update(
    fileId=file_id,
    body=file_metadata, 
    media_body=media, 
    ).execute()
```

When I try to upload certain file type (pkl, csv), the code runs without any error but nothing changes in my drive whereas when I apply the same function for a different type (xlsx, txt), it works fine and my file gets updated. Did anyone face the same problem? and if so what was the solution?

Thanks.

**Comment by busunkim96** [comment]
Hi @Cha5machou,

It sounds like this is primarily a question about the Drive API rather than `google-api-python-client`. Please use one of the support channels listed on this page to get help from someone with Drive API expertise: https://developers.google.com/drive/api/v3/support 

Thanks!
