### ISSUE TITLE
Add "import" API to sqladmin

### ISSUE THREAD

**Issue by leberknecht** [googleapis/google-api-python-client#1476]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
I want to have python lambda function that trigger an import into my postgres DB whenever a csv file is uploaded to a bucket. 
I basically want to have the functionality described here https://cloud.google.com/sql/docs/mysql/import-export/importing available through the python client
>import the file:
>gcloud sql import csv INSTANCE_NAME gs://BUCKET_NAME/FILE_NAME \
--database=DATABASE_NAME \
--table=TABLE_NAME

But at the moment the `sqladmin` service doesnt have `import` available:
```python
service = discovery.build('sqladmin', 'v1')
[method_name for method_name in dir(service)  if callable(getattr(service, method_name)) and method_name[:1] != '_'] 
=>
result = {list: 12} ['backupRuns', 'close', 'connect', 'databases', 'flags', 'instances', 'new_batch_http_request', 'operations', 'projects', 'sslCerts', 'tiers', 'users']
 00 = {str} 'backupRuns'
 01 = {str} 'close'
 02 = {str} 'connect'
 03 = {str} 'databases'
 04 = {str} 'flags'
 05 = {str} 'instances'
 06 = {str} 'new_batch_http_request'
 07 = {str} 'operations'
 08 = {str} 'projects'
 09 = {str} 'sslCerts'
 10 = {str} 'tiers'
 11 = {str} 'users'
```

 **Describe the solution you'd like**
Please add the `import` API to the client
 **Describe alternatives you've considered**
I guess i will do something half-ugly to bring the `gcloud` cli command into the env and then spawn a shell-exec
 **Additional context**
python 3.8 with google-api-python-client==2.15.0

**Comment by parthea** [comment]
Hi @leberknecht,

Please can you try `service.instances.import()`? See the REST API [here](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/import), and corresponding docs for `google-api-python-client` [here](https://googleapis.github.io/google-api-python-client/docs/dyn/sqladmin_v1.instances.html#import_). Please let me know if you have additional questions.

**Comment by leberknecht** [comment]
```
service.instances().import_
```
seems to do the trick :)
