### ISSUE TITLE
PKCE Flow Example

### ISSUE THREAD

**Issue by phatmandrake** [googleapis/google-api-python-client#1492]
The Example: https://github.com/googleapis/google-api-python-client/blob/master/docs/oauth-installed.md, doesn't follow the guidance from the website about using PKCE, as described here: https://developers.google.com/identity/protocols/oauth2/native-app. I haven't gone looking, but does the python client not support a PKCE Workflow?

**Comment by parthea** [comment]
Hi @arithmetic1728 , Please could you take a look?

**Comment by arithmetic1728** [comment]
I don't think there is any plan to support new workflows.

**Comment by phatmandrake** [comment]
So is this library deprecated? Seems odd to allow a security concern go unanswered.

**Comment by parthea** [comment]
PKCE is supported in oauth2client [version 4.0.0](https://github.com/googleapis/oauth2client/releases/tag/v4.0.0) and higher: https://github.com/googleapis/oauth2client/pull/588/files
