### ISSUE TITLE
Missing youtubePartner.v1.json API definition

### ISSUE THREAD

**Issue by MichalVasut** [googleapis/google-api-python-client#1508]
In documentation for Content ID API, there are examples mentioning `youtubePartner` service / API, but doesn't work

https://developers.google.com/youtube/partner/upload_claim_sample#obtain-services

#### Code example

```python
# credentials: google.oauth2.credentials.Credentials
# these credentials are valid, can access `youtube/v3` API and load data with these

googleapiclient.discovery.build("youtubePartner", "v1", credentials=credentials)
```

#### Stack trace
```
File "/usr/local/lib/python3.9/site-packages/googleapiclient/discovery.py", line 398, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: youtubePartner  version: v1
```

#### Note

Also cannot locate the file in repository
https://github.com/googleapis/google-api-python-client/tree/main/googleapiclient/discovery_cache/documents

**Comment by parthea** [comment]
Hi @MichalVasut ,

The `youtubePartner` API is not intended to be accessible to all users based on the note at the top of the page in the link you provided:
> Note: The YouTube Content ID API is intended for use by YouTube content partners and is not accessible to all developers or to all YouTube users. If you do not see the YouTube Content ID API as one of the services listed in the Google API Console, see the YouTube Help Center to learn more about the YouTube Partner Program.

Please can you try setting the `static_discovery` argument of `googleapiclient.discovery.build` to `False`.  See https://github.com/googleapis/google-api-python-client/blob/main/UPGRADING.md#for-users-of-private-apis for more information on APIs that are not in the public discovery directory.

**Comment by MichalVasut** [comment]
> Please can you try setting the `static_discovery` argument of `googleapiclient.discovery.build` to `False`. See https://github.com/googleapis/google-api-python-client/blob/main/UPGRADING.md#for-users-of-private-apis for more information on APIs that are not in the public discovery directory.

Wow, thanks a lot @parthea , it wotks with `static_discovery = False`, I wish it was mentioned there in documentation - it would save me few hours.

**Comment by parthea** [comment]
Thanks for confirming @MichalVasut. I've proposed an improvement to the docs via internal cl/394006151. I'll keep this issue open until the docs are updated.

**Comment by parthea** [comment]
I've confirmed that the docs at https://developers.google.com/youtube/partner/upload_claim_sample#obtain-services have been updated to include `static_discovery=False`.

**Comment by MichalVasut** [comment]
Thanks @parthea - would be great if this was corected in every exaple (for Content ID docs), but even ONE is good as clue.

**Comment by parthea** [comment]
Thanks for following up @MichalVasut ! I've opened internal cl/394228651 to address additional examples.

**Comment by parthea** [comment]
I've confirmed that the docs have been updated.
