### ISSUE TITLE
Error if siteUrl is unicode

### ISSUE THREAD

**Issue by chripede** [googleapis/google-api-python-client#151]
This code

```
webmasters_service.searchanalytics().query(
  siteUrl="http://www.lånsms.dk/",
  body=body
).execute()
```

causes

```
UnicodeEncodeError
 'ascii' codec can't encode character u'\xe5' in position 12: ordinal not in range(128)
```

![image](https://cloud.githubusercontent.com/assets/406836/10665604/b08ae42c-78cc-11e5-8810-1144920d5280.png)

Same thing happens for a domain like `http://夜行バス予約ネット.com`

**Comment by mcdonc** [comment]
The latest uritemplate package version is 3.0.0, and its internal structure is a lot different than the version you're using.  I tried to recreate the symptom by doing e.g.

    siteUrl="http://www.lånsms.dk/{abc}"
    uritemplate.expand(siteUrl, {'abc':siteUrl})

And got a result ('http://www.lånsms.dk/http%3A%2F%2Fwww.l%C3%A5nsms.dk%2F' on py36 and 'http://www.l\xc3\xa5nsms.dk/http%3A%2F%2Fwww.l%C3%A5nsms.dk%2F%7Babc%7D' on py27), and no exception.

Can you try updating your version of uritemplate e.g. ``pip install --upgrade uritemplate`` and see if the error ceases?
