### ISSUE TITLE
Querying devices by asset tag "cloudidentity_v1" or "cloudidentity_v1beta1"

### ISSUE THREAD

**Issue by TonyCrespoMe** [googleapis/google-api-python-client#1518]
**Is your feature request related to a problem? Please describe.**

While creating "company owned" (Windows, Mac) device records through Cloud Identity API, serial number, device type and asset tag are provided. Trying to query for these records programmatically by asset tag appears to not be possible and would be very beneficial. 

 **Describe the solution you'd like**
Being able to query for recorded devices by their asset tag as it is possible with its serial number would be great.

**Comment by busunkim96** [comment]
Hi,

This issue tracker is for issues with the `google-api-python-client` library. Please use the [Cloud Identity API issue tracker]( https://issuetracker.google.com/issues/new?component=522910&template=1192013) for API feature requests. https://cloud.google.com/identity/docs/resources/support lists a few other support channels for questions and discussing the API.

Thanks!

**Comment by TonyCrespoMe** [comment]
@busunkim96 Apologies and thanks!!!
