### ISSUE TITLE
No mocks (or documentation) for testing batch requests.

### ISSUE THREAD

**Issue by mgilson** [googleapis/google-api-python-client#154]
The API Client library allows us to mock out most requests pretty easily for testing as explained in the [docs](https://developers.google.com/api-client-library/python/guide/mocks).  Unfortunately, there is no easy way to mock batch requests as far as I can tell.  For applications that make heavy use of batch requests, testing can become pretty cumbersome quite quickly.
1. Mocking out the calls so that it correctly calls the right callbacks is pretty complex when trying to do it with vanilla `unittest.mock`.
2. Formatting the requests/responses can also be a bit tricky when using the regular `HttpMock` class and I can't find it documented anywhere.

---

I'm not saying this is a great solution, but I've managed to get it working with the code below.  Maybe it will seed some ideas about how this can be accomplished in a more manageable way:

``` python
import collections
import itertools
class MockBatchHttpRequest(object):
    """An object that represents an HTTP request from the batch api."""
    def __init__(self, callback=None):
        self._callback = callback
        self._callbacks = collections.OrderedDict()
        self._counter = itertools.count()
        self._request_list = []

    def _new_id(self):
        """Generate a new id."""
        return next(self._counter)

    def add(self, request, callback=None, request_id=None):
        """Add a request to be executed as part of the batch."""
        request_id = request_id or self._new_id()
        self._callbacks[request_id] = callback
        self._request_list.append(request)

    def execute(self, http=None):
        """Execute the request."""
        for request, request_id in zip(self._request_list, self._callbacks):

            response = request.execute(http=http)
            callback = self._callbacks.get(request_id)
            if callback:
                # I'm currently being lazy and didn't test the exception case, so I didn't add handle that here either... :-)
                callback(request_id, response, None)
            if self._callback:
                self._callback(request_id, response, None)
```

so long as I monkey patched the `Resource` that I'm working with:

``` python
service = googleapiclient.discovery.build(*args, **kwargs)
service.new_batch_http_request = MockBatchHttpRequest
```

From here, I can use a regular `HttpMockSequence` to register the responses that I am expecting.

**Comment by jc0n** [comment]
@mgilson - Thanks for the solution -- saved me some time :) 

Made a couple small changes for exception handling:
```
    def execute(self, http=None):
        """Execute the request."""
        for request, request_id in zip(self._request_list, self._callbacks):
            response, exception = None, None
            try:
                response = request.execute(http=http)
            except Exception as e:
                exception = e

            callback = self._callbacks.get(request_id)
            if callback:
                callback(request_id, response, exception)
            if self._callback:
                self._callback(request_id, response, exception)
```

**Comment by jonparrott** [comment]
I'm happy to review any PRs to add this mocking functionality to http_mock.

**Comment by busunkim96** [comment]
I'm opting to close this as it's unlikely we will implement it in the future.

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.

**Comment by taraskuzyk** [comment]
thanks for your code. would be great if someone could write a few tests for it and post it as a pip lib
