### ISSUE TITLE
How to query the Custom Search Site Restricted JSON API?

### ISSUE THREAD

**Issue by Sm4o** [googleapis/google-api-python-client#1543]
Hi, the [documentation](https://developers.google.com/custom-search/v1/site_restricted_api) says you can use the this client to query the CSE Site Restricted JSON API. However I can't seem to figure out how to build() adding the correct endpoint: 
`https://www.googleapis.com/customsearch/v1/siterestrict?[parameters]`

I've tried to no avail:
``` python
service = build("customsearch", "v1", "siterestrict", developerKey=api_key)
```

**Comment by parthea** [comment]
Hi @Sm4o,

Please see the documentation [here](https://googleapis.github.io/google-api-python-client/docs/dyn/customsearch_v1.cse.html) which includes a list of methods available for the customsearch client. I've included sample code below for convenience which I found in https://github.com/googleapis/google-api-python-client/issues/635. There is also a [stackoverflow post](https://stackoverflow.com/questions/37083058/programmatically-searching-google-in-python-using-custom-search) linked in the same issue which looks helpful. I'm going to close this issue but please feel free to re-open it if you have additional questions.

```
service = build("customsearch", "v1", developerKey=<your_api_key>)

res = service.cse().siterestrict().list(
    q=query_word,
    cx=<your_custom_search_id>,
).execute()
```
