### ISSUE TITLE
Data Flow has not been interpreting arguments correctly

### ISSUE THREAD

**Issue by TheVini** [googleapis/google-api-python-client#1560]
Hello, since last week I've faced the following problem with GCP Dataflow.

Before last week, I was able to run a job from Dataflow template from console not using the argument "--project", so I guess there is a new release related to this command on GCP console, probably related to python lib google-api-python-client, version 2.24. But other arguments worked very well before this this release, including "--parameters" argument.
1 - Before this release the following example command was runned from console without any problem: "gcloud dataflow jobs run JOB_NAME --gcs-location TEMPLATE_PATH --worker-machine-type MACHINE_TYPE --parameters yyyymmdd=YY,justpubsub=ZZ". And inside the template code, I was able to use both: Python "argparse" lib and Apache Beam "PipelineOptions" lib. Now, just Apache Beam PipelineOptions works, when using Python "argparse" lib I face the following problem (even using the new argument "--project").
Problem: "ERROR: (gcloud.dataflow.jobs.run) INVALID_ARGUMENT: (eb17d490712dc58): The workflow could not be created. Causes: (eb17d490712d4d1): Found unexpected parameters: ['justpubsub' (perhaps you meant 'update'), 'yyyymmdd' (perhaps you meant 'dry_run')]".

2 - when I use PipelineOptions, it has a weird behavior with both Apache Beam parser methods: "add_argument" and "add_value_provider_argument". The code always assumes the arguments value that I used to run the file "source_file.py" in  my localhost (example: python3 source_file.py --YYYYMMDD 20210503), even when using 'DataflowRunner', and when I don't pass any argument it assumes a RuntimeValueProvider without any value.

**Comment by busunkim96** [comment]
Hello,

This issue tracker is for `google-api-python-client`. It looks like you are experiencing an issue with the gcloud SDK. As far as I know, the gcloud SDK does not use this library to make API calls. Please open an issue on the gcloud issue tracker. https://cloud.google.com/support/docs/issue-trackers

Than you!
