### ISSUE TITLE
webmasters V3 API down  googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters version: v3

### ISSUE THREAD

**Issue by kayamsmith** [googleapis/google-api-python-client#1592]
#### Environment details
OS macOS: 10.15.4
 Python version: python 3.8.1 
pip version: pip 19.0.3 
google-api-python-client version: 1.12.1

**Code example** 
```
from googleapiclient.discovery import build
 service = build(
        'webmasters',
        'v3',
        credentials=credentials
    )
```

Stack trace
 googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters version: v3

While trying to get data from Search Console API we get this error UnknownApiNameOrVersion.

URL on web is also down 
![404  That's an error](https://user-images.githubusercontent.com/70531226/140539062-207aec0c-07d5-4cad-8efc-62372d916fc9.png)

**Comment by susingh** [comment]
We are hitting the same issue. Please fix or revert

**Comment by edvakf** [comment]
I'm having the same issue.

FIY it happened once in September 2020.
https://github.com/googleapis/google-api-python-client/issues/1042

**Comment by oaydogan-au** [comment]
`googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters  version: v3
`
I have been looking for a solution in the last few days for this issue too.. 

Some of our airflow dag runs seems executed successfully for some days but data did not land for those days.. I highly recommend you guys to check out your data for 18th, 19th, 20th and 21st of October 2021.

Please leave a fix here if any of you guys can make it work.. Please let us know what package combination it works with and which version of Python.

Thank you!
Oz.

**Comment by spboxer3** [comment]
I encountered the same problem here, the solution given by #1042 seem doesn't work for me. After changing it to build('searchconsole', 'v1', http=http) will get 400 HTTP error.

**Comment by parthea** [comment]
`webmasters` `v3` is included in the static discovery artifacts that are shipped with `google-api-python-client>=2`. 

Please can you try the following?

```
from googleapiclient.discovery import build
service = build('webmasters','v3')
```

**Comment by richkoch** [comment]
We are facing similar issues with google-api-python-client version: 1.7.4. The UnknownApiNameOrVersion started showing up 3 days ago on several calls and now returns for all of our api calls.

`from googleapiclient import discovery
discovery.build('webmasters','v3','http=http,cache_discovery=False`

**Comment by yoursreejith** [comment]
Facing issue since last 4 days.. Kindly advise.

`googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters  version: v3`

```
service = build_from_document(
                content,
                base=discovery_url,
                http=http,
                developerKey=developerKey,
                model=model,
                requestBuilder=requestBuilder,
                credentials=credentials,
                client_options=client_options,
                adc_cert_path=adc_cert_path,
                adc_key_path=adc_key_path,
            )
```

**Comment by yoursreejith** [comment]
Facing issue since last 4 days.. Kindly advise.

`googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters version: v3`

```
service = build_from_document(
                content,
                base=discovery_url,
                http=http,
                developerKey=developerKey,
                model=model,
                requestBuilder=requestBuilder,
                credentials=credentials,
                client_options=client_options,
                adc_cert_path=adc_cert_path,
                adc_key_path=adc_key_path,
            )
```

**Comment by parthea** [comment]
Please update to `google-api-python-client` version 2.x in order to use static discovery artifacts which are included with the library. 

The following should work on `google-api-python-client` version 2.x
```

from googleapiclient.discovery import build
service = build('webmasters','v3')
```

**Comment by musuraj** [comment]
raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: webmasters  version: v3

Same issue, who will be able to let us know a fix ?

**Comment by DanReia** [comment]
@parthea google-api-python-client>=2 no longer supports Python2, any solution for legacy systems?

**Comment by busunkim96** [comment]
@DanReia You can use https://github.com/googleapis/google-api-python-client/blob/main/googleapiclient/discovery_cache/documents/webmasters.v3.json and [`build_from_document`](https://github.com/googleapis/google-api-python-client/blob/2a718c38d37f4eb7bbb65aee2f34188b57ed1dc1/googleapiclient/discovery.py#L438-L451) if you are unable to upgrade to the latest version.

Internal issue 204972401 indicates this API (webmasters V3) is deprecated. I'm checking with that team to see what they recommend as an alternative.

**Comment by kayasmith106** [comment]
It seems using:
```
from googleapiclient.discovery import build
 service = build(
        'searchconsole',
        'v1',
        credentials=credentials
    )
```


Seems to work, but I just notice most documentation on Search Console still references the webmasters V3 API.

**Comment by busunkim96** [comment]
Here's the response from the API team:

> Hey. So the [Python example in our devsite](https://developers.google.com/webmaster-tools/search-console-api-original/v3/quickstart/quickstart-python#step_3_set_up_the_sample) already contains the new API name and version. We also published this [blog post](https://developers.google.com/search/blog/2020/12/search-console-api-updates#discovery-doc-migration) a while back with the deprecation announcement and refactor instructions.


It looks like the recommended approach is to use `searchconsole v1` instead of `webmasters v3`.
https://developers.google.com/search/blog/2020/12/search-console-api-updates#discovery-doc-migration indicates the objects are the same so it should be a drop in replacement.

**Comment by parthea** [comment]
I'm going to close this issue as resolved but please feel free to re-open it or create a new issue if you're still having trouble.

**Comment by DanReia** [comment]
@busunkim96 I will give `searchconsole v1` a go, thank you for your help!

**Comment by oaydogan-au** [comment]
Thanks everyone.. It works with searchconsole v1. 
Documentation was confusing and made me think searchconsole is older than webmasters.
