### ISSUE TITLE
photoslibrary is not in the discovery_cache

### ISSUE THREAD

**Issue by dermasmid** [googleapis/google-api-python-client#1594]
It seems like the discovery document for the Google photos API is missing from the library, as a workaround you can set `static_discovery=False` when running `discovery.build()`, but it would be nice if the document can be added, thanks.

Here's an example:
```python
>>> from googleapiclient.discovery import build
>>> build("photoslibrary", "v1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cheskel/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/cheskel/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 287, in build
    content = _retrieve_discovery_doc(
  File "/home/cheskel/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 404, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: photoslibrary  version: v1
```
google-api-python-client version: `2.29.0`

**Comment by parthea** [comment]
Hi @dermasmid,

Thanks for reporting this issue. The `discovery_cache/documents` folder [here](https://github.com/googleapis/google-api-python-client/tree/main/googleapiclient/discovery_cache/documents) will automatically be updated to include the static discovery document once it is made available in the public directory [here](https://www.googleapis.com/discovery/v1/apis/). I searched the public directory but I could not find `photoslibrary` listed there. Please file a bug on the public issue tracker for the photoslibrary API [here](https://issuetracker.google.com/savedsearches/5156057) to request that the API be added.

In the meantime, please use the following code to fetch the discovery document from the internet.
```
from googleapiclient.discovery import build
build("photoslibrary", "v1", static_discovery=False)
```

Googlers, see [this link](https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-791058235).
