### ISSUE TITLE
Release a 1.x version compatible with `google-auth>2`, `google-api-core>2` for python 3 users

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-api-python-client#1611]
@kweinmeister reported some dependency conflicts and I think this is one part of it. 

Some Google packages (Kubeflow, Apache Beam, Tensorflow) require both a `google-cloud-*` library and a `google-api-python-client`. 

Some of these libraries are using a `google-api-python-client>1, <2` pin. We expanded the pin for `google-auth` and `google-api-core in 2.14.0`: https://github.com/googleapis/google-api-python-client/blob/main/CHANGELOG.md#bug-fixes-8, so users of those packages cannot use `google-auth` or `google-api-core` v2.

google-api-python-client v1 is technically compatible with google-auth and google-api-core v2. Releasing another 1.x version that _just_ expands those pins (conditional on Python 3.6+) should make it easier to sort out dependencies for those packages.

CC @parthea

**Comment by busunkim96** [comment]
Also see https://github.com/kubeflow/pipelines/pull/6939

**Comment by parthea** [comment]
Version 1.12.10 is available [here](https://pypi.org/project/google-api-python-client/1.12.10/#files).
