### ISSUE TITLE
.dat file expiration

### ISSUE THREAD

**Issue by iGCarroll** [googleapis/google-api-python-client#1612]
Hi!

I'm authenticating requests made to the Google My Business API using [sample_tools.init](https://github.com/googleapis/google-api-python-client/blob/main/googleapiclient/sample_tools.py) with a client_secrets.json and a discovery file.

When I run my script for the first time, it opens a browser window to authenticate the request. After that, a file called mybusiness.dat gets created. This file holds all the authentication information like “access_token”, “client-secret”, “token-expiry”, etc. This is used for all the subsequent requests made to the API.

Every time I run the script this file changes, and the expiration dates get reset. Will it ever expire/be invalid, making me have to go through the browser process again?

Thanks for the help!

**Comment by parthea** [comment]
Hi @iGCarroll,

The expiration date is for the access token. There is also a refresh token which doesn't have an expiration date however as per https://developers.google.com/identity/protocols/oauth2#expiration, you must write your code to anticipate the possibility that a granted refresh token might no longer work. The refresh token allows you to get a brand new access token and the library does that behind the scenes every time you get a 401 response (meaning your access token is no longer valid).

On another note, the sample_tools.init file uses [oauth2client](https://github.com/googleapis/oauth2client) which is no longer maintained. We have an open issue to drop support for oauth2client [here](https://github.com/googleapis/google-api-python-client/issues/1490) however we have paused that effort as there is language in the `google-auth` repo [here](https://github.com/googleapis/google-auth-library-python/blob/main/docs/oauth2client-deprecation.rst#post-deprecation-support) that mentions "google-api-python-client library supports oauth2client and google-auth and will continue to do so indefinitely". In the meantime, it is recommended to use [google-auth](https://github.com/googleapis/google-auth-library-python) for any new development. Please see example code [here](https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.id_token.html#google.oauth2.id_token.fetch_id_token_credentials).

I'm going to close this issue but please feel free to re-open it if you have additional questions.
