### ISSUE TITLE
googleapiclient.errors.UnknownApiNameOrVersion for sqladmin v1beta4 

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [googleapis/google-api-python-client#1613]
We have been using google-api-python-client==v1.7.11 to make api call for CloudSQL through [sql admin v1beta4](https://cloud.google.com/sql/docs/mysql/admin-api/rest)

After upgrading python client version to v2.31.0, the method call stops working and thowing below error:
`googleapiclient.errors.UnknownApiNameOrVersion: name: sqladmin  version: v1beta4`

Below is the code snipest
```py
from googleapiclient import discovery

def main()
   try:
            sql_service = discovery.build(
                'sqladmin', 'v1beta4', cache_discovery=False)
            req = sql_service.instances().get(project=project_id,
                                              instance=gcp_instance_name)
            resp = req.execute()
            return resp
        except Exception:
            log.fatal(
                f'Unable to retrieve the information for SQLInstance {instance_name} (GCP name: {gcp_instance_name}), details: {traceback.format_exc()}')
            exit(1)

if __name__ == '__main__':
   main()
```

**Comment by parthea** [comment]
Hi @CharmanderJieniJieni,

The discovery document for `sqladmin` `v1beta4` is shipped with the library and lives in the repo [here](https://github.com/googleapis/google-api-python-client/blob/main/googleapiclient/discovery_cache/documents/sqladmin.v1beta4.json). I'm not able to re-produce the error. The following code works for me locally: 

```
from googleapiclient import discovery
sql_service = discovery.build('sqladmin', 'v1beta4', cache_discovery=False)
```

If you would prefer to fetch the discovery document over the internet, which is the same behaviour as `google-api-python-client` version 1.x, you can set the `static_discovery` argument of  `discovery.build()` to `False`. For example the following code will fetch the discovery artifact over the internet: 

```
sql_service = discovery.build('sqladmin', 'v1beta4', static_discovery=False)
```

If you'd like to troubleshoot the issue further, please provide more information about the environment where this is failing. See the issue template [here](https://github.com/googleapis/google-api-python-client/issues/new?assignees=&labels=&template=bug_report.md).  I'm going to close this issue but please feel free to re-open it with more information.
