### ISSUE TITLE
docs: 404 error while accessing contribution guide

### ISSUE THREAD

**Issue by Aakash-Roy** [googleapis/google-api-python-client#1634]
When I was trying to access the contribution guide mentioned in `CONTRIBUTING.rst`, I am getting 404 error - https://googleapis.github.io/google-api-python-client/contributing.html

![how-to-contribute](https://user-images.githubusercontent.com/70377445/145891836-28113d3d-a01f-4279-ac49-1b7ef7ee810b.jpg)

![404](https://user-images.githubusercontent.com/70377445/145891868-d9057095-f390-4263-b03e-1701915bb8e7.jpg)

**Comment by parthea** [comment]
Hi @Aakash-Roy,

Thanks for reporting an issue with [the CONTRIBUTING.rst doc](https://github.com/googleapis/google-api-python-client/blob/main/CONTRIBUTING.rst)!
