### ISSUE TITLE
searchconsole: Adding domain via Python API does not work

### ISSUE THREAD

**Issue by mrichtarsky** [googleapis/google-api-python-client#1647]
#### Environment details

NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"

Name: google-api-python-client
Version: 2.33.0
Summary: Google API Client Library for Python
Home-page: https://github.com/googleapis/google-api-python-client/
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.9/dist-packages
Requires: google-auth-httplib2, google-api-core, httplib2, google-auth, uritemplate

#### Steps to reproduce
- Execute code below. It succeeds without an error.
- Log in to search console
- The domain added by the code is not shown.
- `sites.list()` also does not return any sites present in the console, it appears as the code is operating on some other instance

#### Code example

```python
from googleapiclient._auth import credentials_from_file

service = build('searchconsole', 'v1', credentials=credentials_from_file('/md/setup/domains/service_account_key.json'))
sites = service.sites()
sites.add(siteUrl='https://www.mydomaindfvfvui4fu9neriern.com').execute()
print(sites.list().execute())
service.close()
```

#### Notes

I have code for verifying a domain which uses the same authentication:

```python
service = build('searchconsole', 'v1', credentials=credentials_from_file('/md/setup/domains/service_account_key.json'))
veri = service.webResource()
veri.insert(verificationMethod='DNS', body={'owners': (ADMIN_EMAIL,), 'site': {'type': 'INET_DOMAIN', 'identifier': domain}}).execute()
service.close()
```

This code also works without error. When I then manually add the domain via web browser in the console, the dialog shows: "Ownership auto verified" - "Verification methods: Unknown" :

![image](https://user-images.githubusercontent.com/15377781/148356707-39b9a8c7-617c-4a09-a359-fe75797b42eb.png)

Am I doing anything wrong with permissions/granted access? It appears like my code is operating on a different instance of the search console than shown in the browser. The successful site verification in the browser also sounds like "someone else" verified the domain (hence the "Unknown" Verification Method)

**Comment by mrichtarsky** [comment]
I think the problem is that the credentials are for the service user, and it seems to have its own state of the search console. How can I add domains on behalf of my real Google account via the API?

**Comment by busunkim96** [comment]
Hi @mrichtarsky,

If you need to authenticate on behalf of an end user, you'll have to use the Oauth2 flow rather than a service account. https://cloud.google.com/docs/authentication#strategies has a list of authentication strategies based on the environment.

There's a full example on [this page](https://cloud.google.com/docs/authentication/end-user). 

Note that even if you use a service account, it's better to use the public methods in `google.auth` to avoid relying on code in the private module. https://cloud.google.com/docs/authentication/production#passing_code has a full example.

**Comment by mrichtarsky** [comment]
Thanks @busunkim96 for your help, that worked!
