### ISSUE TITLE
Google auth on heroku

### ISSUE THREAD

**Issue by kinshusharma0412** [googleapis/google-api-python-client#1650]
I have both files credentials.storage, client_secrets.json on github and deployment to heroku

But heroku give us authentication link in Views log section when I open link this is error comes

![Uploading Screenshot_2022-01-08-21-59-44-273_com.android.chrome.jpg…]()

**Comment by parthea** [comment]
Hi @kinshusharma0412 , The screenshot is not visible and I'm unable to see the error message. I'm going to close this issue as I don't have enough information to help. Please re-open this issue with more information.  Please use the issue template here: https://github.com/googleapis/google-api-python-client/issues/new?assignees=&labels=&template=bug_report.md
