### ISSUE TITLE
google-api-python-client== 2.35.0 package size  

### ISSUE THREAD

**Issue by e-lepilov** [googleapis/google-api-python-client#1668]
Hi there! 
I have updated the version from  google-api-python-client==1.10.0 to 2.35.0  
All went well in tests, but the automated build of the application crashed with an error on the maximum allowable file size. I started to look into it and saw that the new version takes (2.35.0) 58.9 MB (second underscore)

![image (1)](https://user-images.githubusercontent.com/89014825/150548385-3c766e05-e3d2-4b91-8ff5-6220216fdda1.png)

I looked at the size of the old version and its size is 190kb. The new version adds a documents folder, which takes up all the space. 

![Screenshot from 2022-01-21 14-57-52](https://user-images.githubusercontent.com/89014825/150548801-a3af8113-62ad-4e2d-9b37-75ea6b073fdf.png)

58.9 MB is a significant file size that has to be pulled onto the server. Did you add this folder on purpose? Is it possible to use the new version of the library but not pull the documentation with it?

**Comment by busunkim96** [comment]
Hi @e-lepilov,

Yes, there's now a directory that stores the discovery documents for all public Google APIs. You can read more about why it was added in [this section](https://github.com/googleapis/google-api-python-client#version-20-release) of the README.

**Comment by e-lepilov** [comment]
@busunkim96 thank you for your reply. So now we have to assume that the library will be ~50Mb in size anyway?

**Comment by parthea** [comment]
Hi @e-lepilov , Yes, that's correct for version 2.x as the discovery documents are shipped with the library. Version 1.x fetches discovery documents dynamically.
