### ISSUE TITLE
Why the documents().create ignore other feilds?

### ISSUE THREAD

**Issue by EhtishamSabir** [googleapis/google-api-python-client#1678]
then how we can get the object body & then change something inside the body & update the sheet?

**Comment by parthea** [comment]
Hello @EhtishamSabir,

Please note that there are no method-level parameters for [documents.create()](https://developers.google.com/docs/api/reference/rest/v1/documents/create). You'll need to add request body parameters instead. I've included a code snippet to use `documents.create()` below to create a document. Regarding updating the document itself, please try experimenting with the `Try this API` section on the [document.batchUpdates()](https://developers.google.com/docs/api/reference/rest/v1/documents/batchUpdate) page to test different ways that you can update a document. See the format of the [request](https://developers.google.com/docs/api/reference/rest/v1/documents/request) object here.



```
import google_auth_oauthlib
from googleapiclient.discovery import build

# Choose appropriate scope from https://developers.google.com/identity/protocols/oauth2/scopes#docs
SCOPES = ['https://www.googleapis.com/auth/documents']

client_secrets_file = "client_secret.json"

# Get credentials and create an API client for docs v1
flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
    client_secrets_file, SCOPES)
credentials = flow.run_console()
service = build('docs', 'v1', credentials=credentials)

# add request body parameters
request_dict = {"title":"test title"}

# create the document
document_create_response = service.documents().create(body=request_dict).execute()

print(document_create_response)
```

**Comment by EhtishamSabir** [comment]
How do I replace inline image from python?

Cause this is the problem 

Lets suppose we have template & we want to replace name & image we cna replace text thats in api but replacing of image is not possible no such methods.

Also it would be great if we read Doc & then replace something & update doc but Using Get we get dictionary format which is not same for using for batchupdate

**Comment by parthea** [comment]
Hi @EhtishamSabir, For the docs API, please visit the support page [here](https://developers.google.com/docs/api/support) to interact directly with the product team. For the docs API, please submit feature requests [here](https://developers.google.com/docs/api/support#missing_features). I'm going to close this issue as we cannot make any further changes in the python client itself.
