### ISSUE TITLE
files().list(q="name contains 'substr'") only matches when the substr at the beginning of name or after a space

### ISSUE THREAD

**Issue by michaelxwang** [googleapis/google-api-python-client#1685]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Darwin Kernel Version 21.2.0
  - Python version: Python 3.9.10
  - pip version: pip 22.0.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
  - `google-api-python-client` version: 
``` 
Name: google-api-python-client
Version: 2.36.0
Summary: Google API Client Library for Python
Home-page: https://github.com/googleapis/google-api-python-client/
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: google-api-core, google-auth, google-auth-httplib2, httplib2, uritemplate
Required-by: 
```

#### Steps to reproduce

  1. crate a folder named SMITH_JOHN TAYLER_DAVID
  2. try to list the folder with `service.files().list(q=f"mimeType = 'application/vnd.google-apps.folder' and name contains 'JOHN'")`
  3. It will not show the folder. It only shows when using SMITH or TAYLOR

#### Code example

```
import os
import yaml
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

creds = None
scopes = ["https://www.googleapis.com/auth/drive"]

if os.path.exists("token.json"):
     creds = Credentials.from_authorized_user_file("token.json", scopes)
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file("credentials.json", scopes)
        creds = flow.run_local_server(port=0)

with open("token.json", "w", encoding="utf-8") as token:
    token.write(creds.to_json())

service = build("drive", "v3", credentials=creds)

response = service.files().list(q=f"mimeType = 'application/vnd.google-apps.folder' and name contains 'SMITH'",
                                spaces = 'drive',
                                fields='nextPageToken, files(id, name)',
                                orderBy = 'name').execute()
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Hi @michaelxwang,

Please could you try out a similar request in the 'Try this API' interface on [this page](https://developers.google.com/drive/api/v3/reference/files/list) and check whether the issue still exists? This helps to confirm if this is a client library issue or a API issue. If it is an API issue, we'll redirect you to the API support channel so you can get better quality answers. For the Drive API please see https://developers.google.com/drive/api/v3/support.

**Comment by odoublewen** [comment]
I also ran up against this same issue today, and I can confirm that the issue still exists, and does seem to be an API issue.  (I get the same unexpected null result when searching via the python client, or from the "try this API" page linked above.)

**Comment by odoublewen** [comment]
I created a ticket over here: https://issuetracker.google.com/issues/225213315

**Comment by michaelxwang** [comment]
@odoublewen I created a bug, they say it is not a bug. Then I created a feature request: https://issuetracker.google.com/issues/220326928 , please star this feature request. Thanks.

**Comment by odoublewen** [comment]
Ah I see.  Thanks @michaelxwang , good to have that info and the reference here.

@parthea I think you can close this issue
