### ISSUE TITLE
Crash when getting refresh token

### ISSUE THREAD

**Issue by kewp** [googleapis/google-api-python-client#1695]
#### Environment details

  - OS type and version: MacOS Monterey 12.2
  - Python version: 3.9.10
  - pip version: 21.3.1

```
google-api-core                   2.5.0
google-api-python-client          2.37.0
google-auth                       2.6.0
google-auth-httplib2              0.1.0
google-auth-oauthlib              0.4.6
googleapis-common-protos          1.54.0
```

#### Code example

```python

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
             'https://www.googleapis.com/auth/drive']

KEYFILE = 'google_api_keyfile.json'
creds = ServiceAccountCredentials.from_json_keyfile_name(KEYFILE, scope)
service = build('sheets', 'v4', credentials=creds)
```

#### Console output
```
Attempting refresh to obtain initial access_token
Refreshing access_token
```

Then the console hangs.

Not only that, though - an osx task call `kernel_task` starts using the maximum
disc on my machine, thrashing my ssd and making my machine unusuable until
I force the console to terminate ??!?

**Comment by busunkim96** [comment]
Hi @kewp,

It looks like you're using `oauth2client` for auth, which is now deprecated. Could you try this instead (using `google-auth`?

**requirements.txt**
```
google-auth
google-api-python-client
```

**Code**
```py
from googleapiclient.discovery import build
from google.oauth2 import service_account

scope = ['https://spreadsheets.google.com/feeds',
             'https://www.googleapis.com/auth/drive']

KEYFILE = 'google_api_keyfile.json'
credentials = service_account.Credentials.from_service_account_file(
    KEYFILE, scope)
service = build('sheets', 'v4', credentials=creds)
```

In order to use a service account to access the API you must also perform domain-wide delegation. (https://support.google.com/a/answer/162106?hl=en#zippy=%2Cset-up-domain-wide-delegation-for-a-client)

Otherwise, the typical way to access this API is through a user's oauth2 credentials. https://developers.google.com/sheets/api/quickstart/python has a full example of this.

**Comment by kewp** [comment]
Hmm ok so the format of the call is a bit different:

```python
creds = service_account.Credentials.from_service_account_file(KEYFILE, scopes=scope)
```

but I still get the same problem as before when I try read values: `kernel_task`
starts hammering my hard drive (like 100MB per second read and write),
my computer slows down to a crawl and the python script just hangs:

```python
service = build('sheets', 'v4', credentials=creds)
result = service.spreadsheets().values().get(
        spreadsheetId=sheet_id, range=sheet_name).execute()
```

**Comment by kewp** [comment]
Ok, nevermind. Seems my code is the one that is freezing.

Still not sure why it froze before ... thank you for the help @busunkim96 . Sorry for the trouble!
