### ISSUE TITLE
Can I rollout a new release programmatically through Android Publisher API?

### ISSUE THREAD

**Issue by arieti** [googleapis/google-api-python-client#1704]
So far, my app is still in Internal Testing mode and I was able to upload a new version through this piece of code:

```
service = googleapiclient.discovery.build('androidpublisher', 'v3', credentials=credentials, cache_discovery=False)
edit_request = service.edits().insert(body={}, packageName=package_name)
result = edit_request.execute()
edit_id = result['id']

try:
    bundle_response = service.edits().bundles().upload(
        editId=edit_id,
        packageName=package_name,
        media_body=APP_BUNDLE,
        media_mime_type="application/octet-stream"
    ).execute()
except Exception as err:
    message = f"There was an error while uploading a new version of {package_name}"
    raise err

print(f"Version code {bundle_response['versionCode']} has been uploaded")

track_response = service.edits().tracks().update(
    editId=edit_id,
    track='internal',
    packageName=package_name,
    body={u'releases': [{
        u'versionCodes': [str(bundle_response['versionCode'])],
        u'status': u'draft',
    }]}
).execute()

print("The bundle has been committed to the internal track")

commit_request = service.edits().commit(
    editId=edit_id,
    packageName=package_name
).execute()
```

The problem is when I go to the Google Play console, the new app version is set as "draft" and I have to click through the UI "Edit Release -> Review Release -> Start Rollout to Internal Testing" if I want that version to be published. Is there a way to automate these last few steps? Is this procedure only for Internal Testing or do I have to do it for the production published app too?

I understand I am explicitly setting the status as "draft" in the python script but I wasn't able to find any other status or API call that worked for the upload.

**Comment by busunkim96** [comment]
Hi @arieti,

It looks like releases _should_ be possible through the API. The page linked below has a few examples of rolling out releases.

https://developers.google.com/android-publisher/tracks#apk_workflow_example

> Call the [Edits.tracks: update](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/update) method for each track that you want to release APKs on. In the request body, pass a [Edits.tracks resource](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks) containing the release you wish to rollout. For example, to release an APK with version code 88:

```
{
"releases": [{
  "versionCodes": ["88"],
  "status": "completed"
}]
}
```
> At this point, the APKs are still not available to users. As with other edits, the changes do not go live until you commit them.

I wasn't able to find any additional documentation explaining if this works differently for apps that are in internal testing.

 Please direct your question to Play Developer Support. https://support.google.com/googleplay/android-developer/answer/10357403?hl=en


Thanks!
