### ISSUE TITLE
Google Classroom API Returns 403 Permission Denied instead of 404 Not Found

### ISSUE THREAD

**Issue by RafaelZasas** [googleapis/google-api-python-client#1721]
#### Environment details

  - OS type and version: Any
  - Python version: Any
  - pip version: Any
  - `google-api-python-client` version: 2.31.0

#### Steps to reproduce

  1.  Authenticate 
  2.  Try to retrieve a user profile: `userProfiles().get(userId).execute()`

#### Code example

```python
service.userProfiles().get(userId).execute()
```
In the case where the requested resource exists and the user has permission, the resource requested will be returned.

In the case where the requested resource exists but, *the user does not have permission*, a 403 PERMISSION_DENIED will be returned.

Likewise, In the case where the requested resource *Does Not Exist*, a  403 PERMISSION_DENIED will be returned.

From the Docs: 
![image](https://user-images.githubusercontent.com/42390827/157995179-8f8ddb9a-c3a9-4618-9459-d00822c91fae.png)

This makes debugging really difficult for applications being built on or consuming the API. 

Ideally the API would return a 403 if the permissions are insufficient and a 404 if the permissions are in order but the resource does not exist.

This functionality does exist on other endpoints like `courses.get()` or `courses.courseWork.get()`

**Comment by busunkim96** [comment]
Hi @RafaelZasas,

It sounds like this is feedback for the underlying Classroom API. Please reach out to the Classroom API team using one of the support channels listed here: https://developers.google.com/classroom/support

Thanks!
