### ISSUE TITLE
discovery API return a non vlid response

### ISSUE THREAD

**Issue by fahedouch** [googleapis/google-api-python-client#1754]
Hi Folks,

I am facing an issue with  `googleapiclient.discovery`

My code is :

```
from googleapiclient.discovery import build
delegated_credentials = connectGSUITE()
service = build('admin', 'directory_v1', credentials=delegated_credentials)
foundit = service.members().hasMember(**params).execute()
````

When user exists the `foundit` return `true` and when it not exists the code throw an exception rather than a `false` value 

the exception is : 
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://admin.googleapis.com/admin/directory/v1/groups/*******/hasMember/******?alt=json returned "Invalid Input: memberKey". Details: "[{'message': 'Invalid Input: memberKey', 'domain': 'global', 'reason': 'invalid'}]">
```

**Expected behavior:**

return error when the user do not exists

**Comment by parthea** [comment]
Hi @fahedouch,

I found an existing issue in the public issue tracker for this API: https://issuetracker.google.com/issues/119221676 . 

Please use the API support channel so you can get better quality answers. For the Admin Directory API please see https://developers.google.com/admin-sdk/directory/support.

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response. I'm going to close this issue but please re-open it if you have additional questions.
