### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by migdall** [googleapis/google-api-python-client#1755]
Thank you for your assistance.

#### Environment details

  - OS type and version: Ubuntu 20.04
  - Python version: `python --version`: Python 3.8.10
  - pip version: `pip --version`: pip 20.0.2
  - `google-api-python-client` version: `pip show google-api-python-client`: google-api-python-client 2.43.0

#### Steps to reproduce

  1. Create Google Compute Engine instance with a service account install all necessary software
  2. Create a Google Sheet in my Google Work Account
  3. Add the service account's email to the Google Sheet permissions as Editor
  4. Get Sheet ID and add it to the code
  5. SSH into the Compute Engine VM and upload python program
  6. Run the python program

#### Code example

```python
from fileinput import filename
import google.auth
import json

from pprint import pprint

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient import discovery

scopes = ['https://www.googleapis.com/auth/spreadsheets.readonly']

credentials, project = google.auth.default(scopes=scopes)

credentials.refresh(Request())

service = discovery.build("sheets", "v4", credentials=credentials)

spreadsheet_id = "..."

ranges = []
include_grid_data = False

sheet = service.spreadsheets()
result = sheet.values().get(spreadsheetId=spreadsheet_id, range=ranges).execute()
values = result.get('values', [])
pprint(values)
```

#### Stack trace
```
python google_sheet.py 
Traceback (most recent call last):
  File "google_sheet.py", line 21, in <module>
    response = request.execute()
  File "/home/jesus/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/jesus/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/1MkZv0NH-e95t0-R-ADpKxaGPDwAtQY--KZc5340fVLg?includeGridData=false&alt=json returned "Request had insufficient authentication scopes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_SCOPE_INSUFFICIENT', 'domain': 'googleapis.com', 'metadata': {'method': 'google.apps.sheets.v4.SpreadsheetsService.GetSpreadsheet', 'service': 'sheets.googleapis.com'}}]">
```

How do I access a Google Sheet with a service account from a Compute Engine VM with the correct permissions?  

Thanks!

**Comment by parthea** [comment]
Hi @migdall,

Please could you try the steps in the following stackoverflow post?

https://stackoverflow.com/a/56534526

It is for the NodeJS client library but it is also applicable to the Python client.

**Comment by migdall** [comment]
Thank you for the response @parthea are you referring to this documentation https://github.com/googleapis/google-api-nodejs-client#using-the-client-library ? I just need to find the Python equivalent?

**Comment by migdall** [comment]
Ok this documentation worked https://github.com/googleapis/google-api-python-client/blob/main/docs/oauth-server.md#other-platforms I just needed to download a service account json key file.  

```python
from google.oauth2 import service_account

SCOPES = ['https://www.googleapis.com/auth/sqlservice.admin']
SERVICE_ACCOUNT_FILE = '/path/to/service.json'

credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)
```
