### ISSUE TITLE
Programable google search by image

### ISSUE THREAD

**Issue by lindsey98** [googleapis/google-api-python-client#1804]
Hi,
  May I know how to do a programable google search by image, i.e. I go to https://images.google.com, upload a local image, then get the search results? Thanks!

**Comment by parthea** [comment]
Hi @lindsey98 ,

Please use the [SearchType](https://developers.google.com/custom-search/v1/reference/rest/v1/SearchType) [query parameter](https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list#query-parameters) of the [cse.list](https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list) from the Custom Search API.

```
from googleapiclient.discovery import build
client = build('customsearch', 'v1', developerKey='xxxxxx')
client.cse().list().execute(q='<query>', searchType="image")
```

You'll also need an API key via the `developerKey` argument of `googleapiclient.discovery.build()`. I'm going to close this issue but please feel free to re-open it if you have additional questions.
