### ISSUE TITLE
Support for Workspace Admin SDK Directory API

### ISSUE THREAD

**Issue by lyricnz** [googleapis/google-api-python-client#1819]
It would be nice to have a proper client for Workspace Admin SDK, in particular (for me) users/groups/members

https://developers.google.com/admin-sdk/directory/reference/rest

Using the discovery interface is a bit clunky, not typeful, and not async.

**Comment by vam-google** [comment]
Hi @lyricnz 
According to [official documentation](https://github.com/googleapis/google-api-python-client#google-api-client) this library is in maintenance mode and is not supposed to take any new features:

> This library is considered complete and is in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.

Closing this issue as won't fix. Feel free to reopen if you still believe that the new API should be added.
