### ISSUE TITLE
Business Profile Performance serviceName throwing UnknownAPI error 

### ISSUE THREAD

**Issue by paws07** [googleapis/google-api-python-client#1849]
#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.8.10
  - pip version: pip 22.1.2
  - `google-api-python-client` version: Version: 2.33.0

#### Steps to reproduce

  1. Generate credentials.
  2. Build a discovery object using googleapiclient.discovery with serviceName businessprofileperformance and v1

#### Code Example
from googleapiclient.discovery import build, build_from_document
from google_auth_oauthlib.flow import InstalledAppFlow

...

credentials = flow.credentials
MyBusinessProfile = build('businessprofileperformance', 'v1', credentials=credentials)

**Comment by robinstauntoncollins** [comment]
Probably you need to update your google-api-python-client version

**Comment by paws07** [comment]
Looked at the versions and tried again, forced update using pip install --no-cache-dir --upgrade google-api-python-client and it works now. Thank you @robinstauntoncollins!

**Comment by paws07** [comment]
https://github.com/googleapis/google-api-python-client/issues/1849#issuecomment-1189205180

**Comment by vchudnov-g** [comment]
Glad you were able to update the install! In the future, another thing you can do is use
```
build(serviceName, version,…, discoveryServiceUrl="https://{api}/$discovery/rest?version={apiVersion}",…)
```
 which in turn also makes `status_discovery=False` by default. This combination will then fetch the latest API description from Google's Discovery service at the URL generated from the template and parameters above.

**Comment by hamideebrahimiyan** [comment]
Adding query parameters
`
    request = business_profile.locations().searchkeywords().impressions().monthly().list(
        parent = location_for_test,
        monthlyRange_endMonth_day=6,
        monthlyRange_endMonth_month=2,
        monthlyRange_endMonth_year=2022,
        monthlyRange_startMonth_day=1,
        monthlyRange_startMonth_month=1,
        monthlyRange_startMonth_year=2022,
        pageSize=20)
`
