### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.google.com/o/oauth2/token

### ISSUE THREAD

**Issue by aswinsuresh790** [googleapis/google-api-python-client#1857]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-api-python-client` version: `pip show google-api-python-client`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vam-google** [comment]
This bug seems like an accident (only bug template in the body). Closing

**Comment by vam-google** [comment]
About the bug's title:
`requests.exceptions.HTTPError: 400 Client Error:` - it is too generic to say anything specific, but 400 is always an indication of an invalid request being sent from client to server. Please make sure that the messageyou are sending is properly initialized and contains everything it should congtain in a proper format.
