### ISSUE TITLE
Can googleapis coordinate schedules of two third party users with each others calendar?

### ISSUE THREAD

**Issue by datatalking** [googleapis/google-api-python-client#1861]
Thanks for stopping by to let us know something could be better!

 **My feature request related to a user story**
We can schedule an appointment between one person who visits the site and one calendar, but how do we coordinate a customer who is matched with a partner... then sync their calendars to find time they can both meet each other?

 **Describe the solution you'd like**
Bob the contractor and Mike the homeowner were matched based on home depot website search, they enter their phone number and we send them an SMS txt or coordinated schedules between them and a neutral part google calendar. They both pick two or three times that work and the soonest time available gets chosen, they both get a notification and a link to "add to calendar" yes/no option comes up for google or iCal.

How could a dentist take customers on a wait list for time preferences and when one comes open they can msg a list of customers and they have x number of minutes to accept or they go to the next person in line or randomly chosen. What integration does a restaurant use for booking tables, other than requiring users to call in when they have a cancellation?

**Comment by vam-google** [comment]
Hi @datatalking I'm a bit confused by you request. It is not clear what you are requesting, but most importanly your the feature and described user story is related to google-api-python-client. Note, this repository is in maintenance mode only and is not accepting feature requests. Please use https://github.com/googleapis/google-cloud-python for any new development.

Closing this issue as feature requests are not accepted by this repository.
