### ISSUE TITLE
Need export function for sending custom ami to cloud storage

### ISSUE THREAD

**Issue by radhey-sen** [googleapis/google-api-python-client#1872]
**Is your feature request related to a problem? Please describe.**
I am creating a python function in which I want to export custom AMI to cloud storage. I searched  but didn't a python function for it.  
 **Describe the solution you'd like**
If possible, Just like we have the function service.images().**insert**(project=project, forceCreate="true", body=json),  We can have  service.images().**export**(project=project, forceCreate="true", body=json)
 **Describe alternatives you've considered**
I found that in backend, it's creating a cloudbuild **cloudbuild_v1.Build()** So, trying to use the same process. https://cloud.google.com/build/docs/api/reference/libraries#using_the_client_library

**Comment by vam-google** [comment]
Hi @radhey-sen,
Please for any new development use https://github.com/googleapis/google-cloud-python.
This repository is in maintenance mode and is not accepting feature requests. Closing this feature request.
If the issue you are experiencing is a bug or a security issue, please feel free to reopen the issue and provide extra detail and, idealy, reproduce steps. Thanks.
