### ISSUE TITLE
Search result from API and from web is different

### ISSUE THREAD

**Issue by vionemc** [googleapis/google-api-python-client#188]
So I tried to search "4dsiao" through Google Plus search API and from the search bar in Google Plus website. I got zero results from API, but I found Paul Goh from the website search bar. Why is that?

This is the API I use: `https://www.googleapis.com/plus/v1/people?query=4dsiao&alt=json&key=my-api-key`
![screenshot_021916_054856_pm](https://cloud.githubusercontent.com/assets/6565672/13173601/0d47cc1c-d731-11e5-9c15-b4e3b981d5ff.jpg)
![screenshot_021916_054933_pm](https://cloud.githubusercontent.com/assets/6565672/13173611/239dfbc6-d731-11e5-8594-ac237ab8f4f6.jpg)

**Comment by jeffreynghm** [comment]
This could be the reason, though unclear to me still:
https://support.google.com/customsearch/answer/70392?hl=en

**Comment by vionemc** [comment]
I don't think so. It's different with Google Search. It's Google Plus Search, inside Google Plus website

**Comment by sduskis** [comment]
Google plus is shutting down soon.  I'm going to close this issue as "obsolete"
