### ISSUE TITLE
What is the actual arguments of `create()` function in drive v3 api?

### ISSUE THREAD

**Issue by ooyamatakehisa** [googleapis/google-api-python-client#1891]
In the following example, `fields` argument is used in `create()` function.
https://developers.google.com/drive/api/guides/manage-uploads#python

However, I can't find `fields` argument in the following official doc.
https://googleapis.github.io/google-api-python-client/docs/dyn/drive_v3.files.html#create

Is the documentations outdated ?
I tried to find source code of `create()` function, but I couldn't.
Please tell me actual available arguments or `create()` implementation.

**Comment by parthea** [comment]
Hello @ooyamatakehisa,
You're right. The sample uses the `fields` argument but I don't see that in the [API documentation](https://developers.google.com/drive/api/v3/reference/files/create). I'm going to transfer this issue to the repository which has the source code for the sample to see if it can be improved.

https://github.com/googleworkspace/python-samples/blob/main/drive/snippets/drive-v3/file_snippet/upload_basic.py

**Comment by parthea** [comment]
Filed https://github.com/googleworkspace/python-samples/issues/367. I'm going to close this issue as a duplicate as the issue has been reported in the repository which has the samples.
