### ISSUE TITLE
'Resource' object has no attribute 'generatedapks'

### ISSUE THREAD

**Issue by Raisin-Man** [googleapis/google-api-python-client#1912]
I'm using the google api client for google play developer api, and it seems like [Resource](https://github.com/googleapis/google-api-python-client/blob/f7df7a2f8901f48d6b6f97f0dc33dac1f841a223/googleapiclient/discovery.py#L1318) doesn't have a method for [generatedapks](https://developers.google.com/android-publisher/api-ref/rest/v3/generatedapks). I'm wondering how to add this method to the class as it has others like `edit()`, `systemapks()`, etc.

**Comment by parthea** [comment]
`generatedapks` exists in the discovery artifact [here](https://github.com/googleapis/google-api-python-client/blob/bd290b1047c6170bda2f20746a218f4e6c50513e/googleapiclient/discovery_cache/documents/androidpublisher.v3.json#L1847). This feature was added to the discovery artifact for `androidpublisher` `v3` in https://github.com/googleapis/google-api-python-client/pull/1614 and is available in [version 2.32.0](https://github.com/googleapis/google-api-python-client/releases/tag/v2.32.0) and newer.
