### ISSUE TITLE
from is not an external or internal command

### ISSUE THREAD

**Issue by Dparks06** [googleapis/google-api-python-client#2020]
I am trying to import google client library using command prompt. I have installed python 3.11.1, added the path to the environment variable section, installed the update and I am still getting the same error message. I have also tried changing C:\Users\Username to C:\ Windows\System32 and that didn't work either. Has anyone else run into this problem? If so, what did you do to fix it? I tried everything ChapGPT suggested, and nothing worked.

**Comment by parthea** [comment]
It sounds like you're running python code directly in terminal. You'll need to that in a python terminal.

This command will install `google-api-python-client`
```
root@229b21e25f84:/# pip install -q google-api-python-client 
```

It seems like you're running the python import statement directly in terminal which will fail
```
root@229b21e25f84:/# from googleapiclient import discovery
bash: from: command not found
```

Instead you need to run it in a python script or python terminal
```
root@229b21e25f84:/# python3
Python 3.9.13 (main, Jan  4 2023, 17:27:55) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from googleapiclient import discovery
>>> 
```

**Comment by parthea** [comment]
I'm going to close this issue but please feel free to re-open it or open a new issue if you're still having trouble.

**Comment by Dparks06** [comment]
Not sure what you meant, but i did it both ways. In python and also in cmd prompt

![Screenshot (97)](https://user-images.githubusercontent.com/121982666/211171531-a2c5e5f9-63ae-4fb8-9423-040290f8fa08.png)
![Screenshot (96)](https://user-images.githubusercontent.com/121982666/211171534-96aa7b99-fefd-4ef1-8c1d-89c0454b8051.png)
