### ISSUE TITLE
Create Named Message Functionality Broken

### ISSUE THREAD

**Issue by JonH-Wex** [googleapis/google-api-python-client#2028]
#### Environment details

  - OS type and version: AWS Lambda Python 3.7 Runtime x86_64
  - Python version: 3.7
  - pip version: 22.2.2 
  - `google-api-python-client` version: 2.71

#### Steps to reproduce

  1. Complete prerequisites for a Chat app and GCP here: [Chat API Prerequisites](https://developers.google.com/chat/api/guides/crudl/messages#prerequisites)
  2. Follow the official guide with example for creating a named message here: [Create a Named Message](https://developers.google.com/chat/api/guides/crudl/messages#name_a_created_message)
  3.  Run the code to attempt to post the message to a space of your choosing. 
  4. Remove the `clientAssignedMessageId` parameter and run again to have it post a message as expected.

#### Code example

Exactly as written in the linked guide above.

#### Stack trace
```
File "/opt/python/lib/python3.7/site-packages/googleapiclient/discovery.py", line 1019, in method
raise TypeError('Got an unexpected keyword argument {}'.format(name))
TypeError: Got an unexpected keyword argument clientAssignedMessageId
```

Removing the `clientAssignedMessageId='client-CustomName',` makes it work immediately as a normal message. Only the named functionality isn't recognized by the API discovery.

**Comment by parthea** [comment]
Hi @JonH-Wex,

Thanks for reporting this issue. The `clientAssignedMessageId` parameter does not appear to be available in the public discovery document for the API. It's possible that this is either a documentation issue or a feature which is not public. I've filed an internal issue to update the documentation. 

https://github.com/googleapis/google-api-python-client/blob/f110f69ecbd8ce49a254a6484494ad5f2ebce0b1/googleapiclient/discovery_cache/documents/chat.v1.json#L284 

Public Discovery Document: https://www.googleapis.com/discovery/v1/apis/chat/v1/rest

I'm going to close this issue as the documentation issue is tracked internally.

Googlers see b/265159177
