### ISSUE TITLE
Encountered InvalidVersion on cluster creation using discovery.build().projects().zones.create().execute()

### ISSUE THREAD

**Issue by supreme-core** [googleapis/google-api-python-client#2038]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 20
  - Python version: 3.8.10
  - pip version:  20.0.2
  - pip package list:
  google-api-core          2.11.0    
  google-api-python-client 2.69.0     
  google-auth              2.15.0    
  google-auth-httplib2     0.1.0     
  google-cloud-compute     1.8.0     
  google-cloud-container   2.14.0    
  google-cloud-core        2.3.2     
  google-cloud-storage     2.7.0     
  google-crc32c            1.5.0     
  google-resumable-media   2.4.0     
  googleapis-common-protos 1.57.1    
  grpcio                   1.51.1   
  grpcio-tools             1.51.1    
  kubernetes               25.3.0    

#### Steps to reproduce

1. Use the discovery service to create a cluster. 
Cluster region: us-west1-a
Max nodes: 1000
Machine Type: n1-standard-1

2. Creating a cluster will return  **InvalidVersion("Invalid version: '1.24.7-gke.900")**

#### Code example

```python

    status = "https://www.googleapis.com/auth/"

    service = discovery.build(
        "container", "v1", credentials=GoogleCredentials.get_application_default()
    )
    zones = service.projects().zones()
    gcp_config = _get_server_config(cluster, zones)
    
    # cluster definition, please fill in your definition
    body = {}
    
    response = (
            zones.clusters()
            .create(projectId=Config.GCP_PROJECT, zone=cluster.Region, body=body)
            .execute()
     )

```
I am wondering if the way discovery.build is called is wrong? Should I change the version to something else?
Also, I am importing from google.cloud.container_v1  
Is that the right class to use? Should I use container_v1beta1?

```python
service = discovery.build(
        "container", "v1", credentials=GoogleCredentials.get_application_default()
    )
```

#### Stack trace
Return an error:
InvalidVersion("Invalid version: '1.24.7-gke.900'")
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vchudnov-g** [comment]
As the [README](https://github.com/googleapis/google-api-python-client#readme) mentions, this library is now in maintenance mode. I would suggest using the newer [google-cloud-container](https://pypi.org/project/google-cloud-container/) library by following the directions [here](https://cloud.google.com/kubernetes-engine/docs/reference/libraries#client-libraries-install-python). For creating as cluster, [this sample](https://github.com/googleapis/python-container/blob/main/samples/snippets/create_cluster.py) in the [source code repo](https://github.com/googleapis/python-container) may be helpful.
