### ISSUE TITLE
Changelog is largely useless

### ISSUE THREAD

**Issue by GergelyKalmar** [googleapis/google-api-python-client#2040]
The current changelog of `google-api-python-client` is mostly useless, it does not say _what_ has changed in the specific APIs. One would need to check the commit diffs to find out about this, but that would defeat the purpose of having a changelog in the first place.

Compare this to https://github.com/googleapis/python-secret-manager/blob/main/CHANGELOG.md or https://github.com/googleapis/google-auth-library-python/blob/main/CHANGELOG.md, where the changes are documented in a much more user-friendly way.

I also couldn't find any changelog for the individual APIs (e.g. at https://developers.google.com/sheets/api/guides/concepts or https://developers.google.com/sheets/api/reference/rest for the Sheets API). I'm wondering how can one find out about changes between versions.

**Comment by vchudnov-g** [comment]
Thanks for your suggestion! While this library is in maintenance mode (see the [README](https://github.com/googleapis/google-api-python-client#readme)), we have taken a note of your good idea and will keep it in mind as we work on our more modern Python client libraries in https://github.com/googleapis/google-cloud-python. Thank you!
