### ISSUE TITLE
Function to test whether or not a scope has been authorized

### ISSUE THREAD

**Issue by ArhanChaudhary** [googleapis/google-api-python-client#2041]
Recently, I've been using the Google Classroom API with the intention of retrieving my users' course work from classes. I need two scopes, `https://www.googleapis.com/auth/classroom.courses.readonly` for requesting my users' classes and `https://www.googleapis.com/auth/classroom.student-submissions.me.readonly` for actually retrieving course work from the first scopes' class ids.

If a user authorizes only the scope to retrieve course work from a class and leaves the scope to retrieve course work unchecked, subsequent api requests to retrieving course work crash. So, to implement some form of check, I wanted to test whether or not I could execute both of those scopes in my callback view. The problem is, the scope for course work *requires* a courseId parameter. I could just first check if the scope for requesting classes is enabled, while also saving the response to a variable, and then using one of the course ids in the response as the courseId parameter. But what if the user isn't enrolled in any classes? Then I would have no courseId to check whether or not the course work scope is enabled.

My solution is a hack. It requests a filler courseId `foo` and checks the response's status code. If it is a 403 or anything else, then the user hasn't enabled the scope. But if it is a 404 instead, then the user has enabled the scope, and the api call didn't find any class with the filler id `foo`.
```py
try:
    courses = service.courses().list().execute()
except OAuth2Error as e:
    return callback_failed()
courses = courses.get('courses', [])
if courses:
    try:
        service.courses().courseWork().list(courseId=courses[0]['id']).execute()
    except (HttpError, OAuth2Error) as e:
        return callback_failed()
else:
    try:
        service.courses().courseWork().list(courseId="foo").execute()
    except (HttpError, OAuth2Error) as e:
        if not (isinstance(e, HttpError) and e.resp.status == 404):
            return callback_failed()
```
I was wondering if it could be possible for a more formalized way to ensure scopes are enabled. Following extensive research, I was unable to find anything related to my problem in the documentation nor online. If such a change to the api is not possible through Google's perspective, then perhaps a utility function that makes a call with a similar filler courseId can be implemented for this feature so it can also be referenced in documentation.

**Comment by vchudnov-g** [comment]
Thanks for filing this bug report and suggesting a workaround. Unfortunately, as per the [README](https://github.com/googleapis/google-api-python-client#readme), "This library is considered complete and is in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features." I have reached out internally to the Classroom team, though, to make them aware of this issue.

**Comment by jamesor** [comment]
You can inspect the access token to see if the user has granted consent to the scopes you care about. See [Access token contents](https://cloud.google.com/docs/authentication/token-types#access-contents).

If they unchecked the scope during the consent screen, the scope won't be listed in the token.

**Comment by ArhanChaudhary** [comment]
> You can inspect the access token to see if the user has granted consent to the scopes you care about. See [Access token contents](https://cloud.google.com/docs/authentication/token-types#access-contents).
> 
> If they unchecked the scope during the consent screen, the scope won't be listed in the token.

Hello, and thank you for the guidance. Does a built-in functionality for requesting for this endpoint exist in this repository, or will I have to request for the URL manually? I can't seem to find anything referencing Access token contents in `docs`.

**Comment by ArhanChaudhary** [comment]
Upon further inspection, you can inspect `scope` from `flow.fetch_token` to receive the authorized scopes and thus determine whether or not a user has enabled all scopes.
