### ISSUE TITLE
 Google API Python client library for Google's discovery based APIs.

### ISSUE THREAD

**Issue by Mikksrund** [googleapis/google-api-python-client#2056]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-api-python-client` version: `pip show google-api-python-client`

#### Steps to reproduce

  1. $ pip install httplib2
> https://httplib2.readthedocs.io/en/latest/

  2. pip install pyOpenSSL
> https://pypi.org/project/pyOpenSSL/

#### Code example

```python
pip3 install virtualenv virtualenv <your-env> source <your-env>/bin/activate <your-env>/bin/pip install google-api-python-client
```

#### Stack trace
```
"""Retain apiclient as an alias for googleapiclient.""" 
  
 from googleapiclient import channel, discovery, errors, http, mimeparse, model 
  
 try: 
     from googleapiclient import sample_tools 
 except ImportError: 
     # Silently ignore, because the vast majority of consumers won't use it and 
     # it has deep dependence on oauth2client, an optional dependency. 
     sample_tools = None 
 from googleapiclient import schema 
  
 _SUBMODULES = { 
     "channel": channel, 
     "discovery": discovery, 
     "errors": errors, 
     "http": http, 
     "mimeparse": mimeparse, 
     "model": model, 
     "sample_tools": sample_tools, 
     "schema": schema, 
 } 
  
 import sys 
  
 for module_name, module in _SUBMODULES.items(): 
     sys.modules["apiclient.%s" % module_name] = module
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by atulep** [comment]
Please include valid stack trace.
