### ISSUE TITLE
Neither local flows work

### ISSUE THREAD

**Issue by pembo13** [googleapis/google-api-python-client#2147]
Referencing docs/oauth-installed.md and https://developers.google.com/sheets/api/quickstart/python

Both flows result in errors.

`flow.run_local_server` results in a `AttributeError: 'NoneType' object has no attribute 'replace'` error
`flow.run_console` results in `AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'`

#### Environment details

  - OS type and version: AlmaLinux 8
  - Python version: 3.8.2
  - pip version: 23.1.2
  - `google-api-python-client` version: 2.88.0

#### Steps to reproduce

  1. Try to connect use a local OAuth flow (see either references at the top)
  2. ?

#### Code example

```python
flow = InstalledAppFlow.from_client_secrets_file(creds_path, SCOPES)
creds = flow.run_local_server(port=8080)

flow = InstalledAppFlow.from_client_secrets_file(creds_path, SCOPES)
creds = flow.run_console()
```

**Comment by pembo13** [comment]
I see `flow.run_console` has been removed completely. 

The problem I was getting with `run_local_server` is being triggered by the fact that `handle_request` respects `socket.getdefaulttimeout()` over the timeout value being passed.

**Comment by LindaLawton** [comment]
> I see `flow.run_console` has been removed completely.
> 
> The problem I was getting with `run_local_server` is being triggered by the fact that `handle_request` respects `socket.getdefaulttimeout()` over the timeout value being passed.

The issue with that is that run_local_server  requires a webserver to be installed.   How will this work on colab?

**Comment by emericcolombe** [comment]
@LindaLawton to get the url that you can place in your browser, you can just do :
```
auth_url, _ = flow.authorization_url(prompt='consent')
print(f'Please go to this URL and authorize the application: {auth_url}')
```
