### ISSUE TITLE
Version upgrade is failing dfareporting APIs

### ISSUE THREAD

**Issue by qouyanggoogle** [googleapis/google-api-python-client#2185]
#### Environment details

  - `google-api-python-client` version: 2.91.0

#### Steps to reproduce

  1. Create a virtual environment with version 2.91.0
  2. Run a dfareporting API get() call with an entity id specified in integer --> 'int' object is not iterable error shows up
  3. Change the version back to 2.90.0
  4. Re-Run a dfareporting API get() call with an entity id specified in integer --> script will run successfully

#### Code example

```python
import google.auth
from google.auth import impersonated_credentials
from google.oauth2 import service_account
from googleapiclient import discovery

default_credentials, project_id = google.auth.default()
credentials = impersonated_credentials.Credentials(
    source_credentials=default_credentials,
    target_principal="{service_account_email}",
    target_scopes=["https://www.googleapis.com/auth/dfatrafficking"]
)
dcm = discovery.build("dfareporting", "v4", credentials=credentials)
response = dcm.creatives().get(profileId="{profile_id}",id=000000).execute()
```

#### Stack trace
```
File "/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py", line 1071, in method
    for pvalue in pvalues:
TypeError: 'int' object is not iterable
```

**Comment by ken999999999999999** [comment]
I encountered similar issue as well. I solved this error by changing the data type from integer to string. 
### Before
`response = dcm.creatives().get(profileId="{profile_id}",id=000000).execute()`
### After
`response = dcm.creatives().get(profileId="{profile_id}",id="000000").execute()`
