### ISSUE TITLE
Read JSON credentials from string instead of file

### ISSUE THREAD

**Issue by llamafilm** [googleapis/google-api-python-client#2197]
**Is your feature request related to a problem? Please describe.**
I'm storing the credentials.json data in an encrypted form which gets decrypted by my application on runtime.  It's risky to write this back to disk in plaintext, so I'd like to login using this string in memory instead.

 **Describe the solution you'd like**
How I authenticate now:
```
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'credentials.json'
```

How I'd like to authenticate:
```
GOOGLE_APPLICATION_CREDENTIALS = "string from variable"
```

 **Additional context**
For what it's worth, there is a similar feature request for Go: https://github.com/googleapis/google-api-go-client/issues/185

**Comment by parthea** [comment]
Hi @llamafilm, 

There was a feature added in https://github.com/googleapis/google-auth-library-python/pull/1326 to add support for `google.auth.load_credentials_from_dict()` to load credentials from a dictionary, however that does not change the behaviour of the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.

See
https://github.com/googleapis/google-auth-library-python/blob/a4135a3e9620a2cbf99957858c13780b92ff707c/google/auth/_default.py#L134

If you'd like to propose a feature request to change the behaviour of `GOOGLE_APPLICATION_CREDENTIALS`, please file a feature request for google-auth [here](https://github.com/googleapis/google-auth-library-python/issues/new/choose).

I'm going to close this issue as the handling for `GOOGLE_APPLICATION_CREDENTIALS` is specific to `google-auth` but pease feel free to open a new issue if you have additional questions.
