### ISSUE TITLE
googleapiclient.http.MAX_BATCH_LIMIT is inconsistent with server side soft limits

### ISSUE THREAD

**Issue by GuyOmer** [googleapis/google-api-python-client#2201]
`googleapiclient.http.MAX_BATCH_LIMIT` is set to [1,000](https://github.com/googleapis/google-api-python-client/blob/4069cf9de8871687f6804fa1e3f1672a450c9f96/googleapiclient/http.py#L71C1-L71C16). However, the [documentation](https://developers.google.com/drive/api/guides/performance#overview) states a batch should be limited to 100 calls.

#### Environment details

  - OS type and version: ubuntu 22.04
  - Python version: 3.10.6
  - pip version: 23.1.2
  - `google-api-python-client` version: 2.91.0

#### Steps to reproduce

  1. Create a batch request with 1000 calls.
  2. Send it

#### Example
```
 <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/XXXXX/permissions/YYYYY?supportsAllDrives=true&fields=id%2CdisplayName%2Ctype%2CemailAddress%2Crole%2Cdeleted&alt=json returned "Exceeds allowed inner batch requests soft limit. Please retry.". Details: "[{'message': ' Exceeds allowed inner batch requests soft limit. Pleas
e retry.', 'domain': 'global', 'reason': 'forbidden'}]">

**Comment by parthea** [comment]
Hi @GuyOmer,
`googleapiclient.http.MAX_BATCH_LIMIT` is the upper limit for all APIs. `google-api-python-client` is the client library for over 200+ APIs. Although the drive API has a limit of 100, as mentioned in the documentation page that you linked, there are APIs that have a limit of 1000 such as the API for `datacatalog`. For datacatalog, `You're limited to 1000 calls in a single batch request. If you need to make more calls than that, use multiple batch requests.` as mentioned in https://cloud.google.com/data-catalog/docs/http-batch.

Please feel free to send a PR if the wording can be improved in the exception message here:
https://github.com/googleapis/google-api-python-client/blob/4069cf9de8871687f6804fa1e3f1672a450c9f96/googleapiclient/http.py#L1442

**Comment by nickolay** [comment]
The thing that could be fixed in this repo is the documentation, which guided me to use `1000` initially:

https://github.com/googleapis/google-api-python-client/blob/5313113e489e40db2efa94fbc436d09383547f69/docs/batch.md?plain=1#L12-L13

The Drive's server-side error (_"Exceeds allowed inner batch requests soft limit. Please retry."_) could also be a tad clearer if what it's trying to say is "please split your request into chunks of no more than 100", but I guess that's off-topic for this issue.
