### ISSUE TITLE
Adding samples for calling the Cloud Support API

### ISSUE THREAD

**Issue by veliebm** [googleapis/google-api-python-client#2207]
## Is your feature request related to a problem? Please describe.

Users of my team's API, the Cloud Support API, need examples of how to call it using discovery doc Python libraries.

## Describe the solution you'd like.

We'd like to add examples of calling our API to this repository. Specifically, an example for every endpoint in [our REST reference](https://cloud.google.com/support/docs/reference/v2):

- caseClassifications.search
- cases.attachments.list
- cases.close
- cases.comments.create
- cases.comments.list
- cases.create
- cases.escalate
- cases.get
- cases.list
- cases.patch
- cases.search
- media.download
- media.upload

### Inlining scripts straight in our docs.

Summary: Add a Python script inline for the docs for each of our endpoints.

Pros:

- Fastest to do.
- Don't need to keep track of a new repository.
- Don't need to work with any other teams to do.

Cons:

- Hard to read.
- Adds clutter to the docs.
- Not searchable in snippets.
- Need to keep scripts very short.

Rejection reason: This would be too hard to read for our users, and we couldn't include all the details we'd want to include because the scripts would need to be so short.

### Making our own GitHub repository.

Summary: Make our own GitHub repository to place our example scripts in.

Pros:

- Don't need to work with any other teams to do this.
- Can choose what we merge.

Cons:

- Unknown how we'd do this, or whether we're allowed.
- Would need to structure the repo ourselves - including testing and GitHub actions.
- Not the canonical solution.

Rejection reason: It'd be a bigger lift than we'd like to set up a brand new repository. Also, I believe Google recommends that we place our scripts in the current repo anyway.

## Additional context.

None. 

Thanks for your time!

**Comment by parthea** [comment]
Hi @veliebm ,

Please could you file this issue in [GoogleCloudPlatform/python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples), the repository for GCP Python Samples? There are [many samples](https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fpython-docs-samples%20google-api-python-client&type=code) which use `google-api-python-client` there. Perhaps you can include samples for both `google-api-python-client` and [google-cloud-support](https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-support).

**Comment by parthea** [comment]
I had an offline discussion with @veliebm. An issue will be opened in [GoogleCloudPlatform/python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples) to continue the discussion.
