### ISSUE TITLE
Getting OAuth token POST request is extremely slow, as any other API requests (more than 1min for a single request)

### ISSUE THREAD

**Issue by vadimkantorov** [googleapis/google-api-python-client#2216]
I am following the tutorial https://developers.google.com/people/quickstart/python to access my own contacts via People API.

I created the credentials (have the `client_secret....json`) and everything required before running `quickstart.py`.

The `InstalledAppFlow.from_client_secrets_file` launches a web browser tab, I'm authorizing the app and getting `he authentication flow has completed. You may close this window.` message served from the local web server. The local OAuth flow then goes on to making a POST request to `https://oauth2.googleapis.com/token`, but this POST request hangs at https://github.com/requests/requests-oauthlib/blob/50472c9/requests_oauthlib/oauth2_session.py#L363

How do I fix this? Thanks :)

**Comment by vadimkantorov** [comment]
Oh, it just seems it's super slow. It took ~1 minute to get the token.

And this sample code also took ~1 minute to run 
```python
print('List 10 connection names')
    results = service.people().connections().list(
        resourceName='people/me',
        pageSize=10,
        personFields='names,emailAddresses').execute()
```

Why is it so slow? (my internet connection is absolutely fine, for that matter)

**Comment by archy-bold** [comment]
I have similar and if I ping oauth2.googleapis.com, it just hangs. I'm wondering if it's something to do with how my router handles IPv6 IP addresses.

**Comment by vadimkantorov** [comment]
This is clearly dependent on the router and routing. For me, this issue was present while at s coworking shop, but not at home wifi

**Comment by archy-bold** [comment]
Yes, for sure. I put the following in my /etc/hosts file to choose the google servers to connect based on IPv4 addresses and I got immediate connections:

142.250.179.202 oauth2.googleapis.com
142.250.179.138 compute.googleapis.com

Note: be wary of editing the hosts file!

I think it's an issue with IPv6 resolution with some routers.

**Comment by parthea** [comment]
I'm going to close this issue based on the comments that this is related to routing settings but please feel free to open a new issue with more information.

**Comment by vadimkantorov** [comment]
Could Python client include a method for benchmarking/testing/ diagnosing connectivity? 

E.g. it could access some heartbeat endpoint and maybe diagnose the used route / response times
