### ISSUE TITLE
Missing V1 api version for bigquery connections

### ISSUE THREAD

**Issue by nitishxp** [googleapis/google-api-python-client#2237]
Hi Team,

Bigquery connections has v1 version of API, but discovery document only has v1beta1 support can you please add it 
https://cloud.google.com/bigquery/docs/reference/bigqueryconnection/rest/v1/projects.locations.connections/create

**Comment by shollyman** [comment]
Is there a reason you need/want a discovery-based client?  The connection API has a generated idiomatic client: 

https://cloud.google.com/python/docs/reference/bigqueryconnection/latest
https://pypi.org/search/?q=google-cloud-bigquery-connection

**Comment by shollyman** [comment]
Going to go ahead and close this for now, given lack of feedback.  Feel free to reply with more info if you think this still needs further attention.
