### ISSUE TITLE
Projects Data Entry use Python to CSV format

### ISSUE THREAD

**Issue by ridharahma** [googleapis/google-api-python-client#2257]
import re
import csv
data_kotor = "john Doe,johndoe@gmail.com,25,82112345678,123 Main St"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "jane Smith,janesmith@gmail.com,30,5555678,456 Elm St"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "bob Brown,bob123yahoo.com,28,5557890,"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "Alice anderson,alice@gmail.com,35,82112345678,789 Oak St"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "siti Nur,sitinur@gmail.com,22,81234567890,,"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "Michael Johnson,mjohnson@gmail.com,25,812345,"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "elsa Lee,elsa@yahoo.com,29,81234567890,321 Pine St"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "muhammad ali,muhammad@gmail.com,,8112345678,,"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "lisa wong,lisawong@gmail.com,37,81234567890,,"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)
import re
import csv
data_kotor = "kevin White,kevin@hotmail.com,31,82178904567,,"
values = data_kotor.split(',')
nama = values[0].strip().title()
email = re.sub(r'\s+', '', values[1].strip().lower())
usia = int(values[2].strip()) if values[2].strip().isdigit() else 0
no_hp = '62' + re.sub(r'\D', '', values[3].strip()) if values[3].strip().isdigit() else '0'
alamat = values[4].strip() if values[4].strip() else 'tidak ada'

print(nama, email, usia, no_hp, alamat)

import csv

# Data bersih
data_bersih = [
    ["John Doe", "johndoe@gmail.com", 25, "6282112345678", "123 Main St"],
    ["Jane Smith", "janesmith@gmail.com", 30, "625555678", "456 Elm St"],
    ["Bob Brown", "bob123yahoo.com", 28, "625557890", "tidak ada"],
    ["Alice Anderson", "alice@gmail.com", 35, "6282112345678", "789 Oak St"],
    ["Siti Nur", "sitinur@gmail.com", 22, "6281234567890", "tidak ada"],
    ["Michael Johnson", "mjohnson@gmail.com", 25, "62812345", "tidak ada"],
    ["Elsa Lee", "elsa@yahoo.com", 29, "6281234567890", "321 Pine St"],
    ["Muhammad Ali", "muhammad@gmail.com", 0, "628112345678", "tidak ada"],
    ["Lisa Wong", "lisawong@gmail.com", 37, "6281234567890", "tidak ada"],
    ["Kevin White", "kevin@hotmail.com", 31, "6282178904567", "tidak ada"],
]

with open('data_bersih.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Nama", "Email", "Usia", "No_HP", "Alamat"]) 
    writer.writerows(data_bersih)

print("data_bersih.csv.")

**Comment by ohmayr** [comment]
Hey @ridharahma, it seems like `google-api-python-client` is not being used in the provided sample. Closing this issue for now since there's not enough information. Feel free to provide a better description on the issue, the error encountered, and re-open the issue, if needed.
