### ISSUE TITLE
`MediaIoBaseDownload` does not support downloading google sheet objects > 10MB

### ISSUE THREAD

**Issue by Ben-Epstein** [googleapis/google-api-python-client#2267]
~If you try to download a file that's larger than the default chunksize, you get an exception that it's too large. If you reduce the chunksize, it works. The default chunksize should be an allowable size for downloads.~

UPDATE: It turns our that no matter the chunksize, this API does not support downloading sheet objects > 10MB.
Is there a reason for this? It works with non-sheet objects just fine

#### Environment details

  - OS type and version:
  - Python version: `3.10.9`
  - pip version: `23.1.2`
  - `google-api-python-client` version: `pip show google-api-python-client`
```
google                                     3.0.0
google-api-core                     2.12.0
google-api-python-client      2.101.0
```

#### Steps to reproduce

  1. Add a google sheets > 10MB to google drive. This CANNOT be a regular csv. Must be a google sheet
  2. Try to download it with `MedialoBaseDownload` without modifying the default chunksize

#### Code example

```python
from googleapiclient.http import MediaFileUpload, MediaIoBaseDownload
from googleapiclient.discovery import build

creds = ...
drive_service = build("drive", "v3", credentials=creds)

file_id = "..."
destination_path = "my_file"
request = drive_service.files().export_media(fileId=file_id, mime_type="text/csv")
with io.FileIO(destination_path, 'wb') as local_file:
    downloader = MediaIoBaseDownload(local_file, request)
    done = False
    while not done:
        _, done = downloader.next_chunk()
```

#### Stack trace
```
HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1C7LNU9VJyu3A8sLhZwg2eL9uG2FTZ1cGJUoJdD9eMuY/export?mimeType=text%2Fcsv&alt=media returned "This file is too large to be exported.". Details: "[{'message': 'This file is too large to be exported.', 'domain': 'global', 'reason': 'exportSizeLimitExceeded'}]">
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by Ben-Epstein** [comment]
I found after more digging that i need to create a `sheets` build
```
sheets_service = build(sheets, "v4", creds)
result = sheet.values().get(spreadsheetId=sheet_id, range=sheet_name).execute()
columns = result["values"][0]
data = result["values"][1:]
df = pd.DataFrame(data, columns=columns)
df.to_csv(filename)
```

I would suggest adding this to the error message directly. `File is too large to export. Use the sheets build to get the data. See <links to docs>`

**Comment by ohmayr** [comment]
Hi @Ben-Epstein, it seems like the `Google Drive Rest API` has limited the exported content to be 10MB. See the method: [files.export](https://developers.google.com/drive/api/reference/rest/v3/files/export)

If you'd like the error message to be more informative, please directly report this issue on the [Google Drive API](https://developers.google.com/drive/api/reference/rest/v3) page by clicking on `Send Feedback`. 

Closing this issue now. Feel free to re-open this issue if you have any more concerns related to the python client!
