### ISSUE TITLE
User customSchemas patching or updating fails when attribute is not multivalued

### ISSUE THREAD

**Issue by Turin86** [googleapis/google-api-python-client#2269]
#### Environment details

  - OS type and version: Ubuntu 22.04.3
  - Python version: 3.10.12
  - pip version: 22.0.2
  - `google-api-python-client` version: 2.103.0

#### Steps to reproduce

  1. Have a single-value attribute.
  2. Try to manipulate in any way using the API. Both the update and patch method return 200, but user does not change.

#### Code example

Bug is present event using the API Explorer (https://developers.google.com/admin-sdk/directory/reference/rest/v1/users/update?hl=en)

**Comment by Turin86** [comment]
Ok, I did not see it documented, but when working with single-value attributes the attribute value MUST NOT be a dict with type and value. It MUST be just the value.

**Comment by ohmayr** [comment]
The above is documented in the [developer guide](https://developers.google.com/admin-sdk/directory/v1/guides/manage-schemas#:~:text=Single%2Dvalued%20custom%20fields%20are%20set%20as%20simple%20key%2Dvalue%20pairs%2C%20like%20%22field1%22%3A%20%22value1%22.%20Multi%2Dvalued%20custom%20fields%20are%20set%20as%20arrays%20of%20objects%2C%20like%20the%20standard%20multi%2Dvalue%20fields%20in%20the%20API%20such%20as%20addresses%20and%20phones.%20These%20value%20objects%20support%20the%20following%20keys%3A) as follows:

`"Single-valued custom fields are set as simple key-value pairs, like "field1": "value1". Multi-valued custom fields are set as arrays of objects"`

Closing this ticket now. Feel free to re-open this issue provide more information if the error persists!
