### ISSUE TITLE
when will this library be built again

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-python-client#2336]
I have been waiting for the dataportablity v1beta to be added to the pip package for two weeks

When is this going to be built?

[dataportablity v1beta](https://dataportability.googleapis.com/$discovery/rest?version=v1beta)

im still getting 

> googleapiclient.errors.UnknownApiNameOrVersion: name: dataportability  version: v1beta

**Comment by parthea** [comment]
Hi @LindaLawton,

[dataportability v1](https://github.com/googleapis/google-api-python-client/blob/main/googleapiclient/discovery_cache/documents/dataportability.v1beta.json) is available as of last week's release `google-api-python-client==2.117.0`. 

```
>>> import googleapiclient.version
>>> googleapiclient.version.__version__
'2.117.0'
```

```
(base) root@3665a2c607e1:/# python3
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from googleapiclient import discovery
>>> discovery.build("dataportability", "v1beta")
<googleapiclient.discovery.Resource object at 0x7f2b730969b0>
>>> 
```

I'm going to close this issue but please feel free to open a new issue if you have additional questions.
