### ISSUE TITLE
 Issue with Cloud Firestore API: listDocuments method and listing all collections in a database

### ISSUE THREAD

**Issue by GlodexperienceforU** [googleapis/google-api-python-client#2394]
Hello,
I am encountering two issues with the Cloud Firestore API:

**1.**According to the documentation for the projects.databases.documents.listDocuments method, collectionId is listed as an optional parameter. However, when I make a request without including this parameter, I receive an error stating "Missing required parameter 'collectionId'". This seems to contradict the documentation.

**2.**I am unable to find a way to list all collections in a Firestore database when only the database name is known. The Firestore data model is based on collections and documents, and it seems that there is no direct way to list all collections in a database without knowing at least one document path.

I would appreciate any guidance or clarification on these issues. Thank you for your time and assistance.

**Comment by ohmayr** [comment]
@GlodexperienceforU Thanks for reporting this.

1 - seems like an issue with the API documentation.
2 - seems like a question to the Firestore API team or possibly a feature request.

Kindly report this directly to the Firestore API team by submitting feedback [here](https://cloud.google.com/firestore/docs/reference/rest/v1beta1/projects.databases.documents/listDocuments).

Please re-open another issue if you have any concerns with the Python client.
