### ISSUE TITLE
Google admin sdk not accessible by non super admins.

### ISSUE THREAD

**Issue by joshnakinsugi** [googleapis/google-api-python-client#2462]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this bug.

### Summary of the issue

Hi ,

Currently I am trying to create google groups for adding members through the admin sdk api. I have created a service account in a project , enabled SDK API , enabled Domain wide delegation by providing the scopes. Here is the code below and the scopes used .

```
 with open(GCP_SECRET_FILE, "r") as f:
                gcp_secret = json.load(f)
             credentials = service_account.Credentials.from_service_account_info(
                gcp_secret, scopes=SCOPES
             )
  service = build("admin", "directory_v1", credentials=credentials)
  self.service = service
```
**Scopes are :** 

**SCOPES = [
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/admin.directory.group.member",
    "https://www.googleapis.com/auth/admin.directory.domain.readonly",
]**

Without including the **subject** , I am not able to create google groups. I tried with another approach as well with OAUTH credentials , 

```
creds = None
  current_dir = os.path.dirname(os.path.abspath(__file__))
  token_path = os.path.join(current_dir, "token.json")
  creds_path = os.path.join(current_dir, "credentials.json")
  if os.path.exists(token_path):
      creds = Credentials.from_authorized_user_file(token_path, SCOPES,
                                                  )
  if not creds or not creds.valid:
      if creds and creds.expired and creds.refresh_token:
          creds.refresh(Request())
      else:
          flow = InstalledAppFlow.from_client_secrets_file(
              creds_path, SCOPES
          )
          creds = flow.run_local_server(port=8080)
      # Save the credentials for the next run
      with open(token_path, "w") as token:
          token.write(creds.to_json())
  # Build the service
  service = build("admin", "directory_v1", credentials=creds)
  self.service = service
```
With both the above approaches , I am getting below error , 
`
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://admin.googleapis.com/admin/directory/v1/groups?alt=json returned "Not Authorized to access this resource/api". Details: "[{'message': 'Not Authorized to access this resource/api', 'domain': 'global', 'reason': 'forbidden'}]">` . 

I dont want to add super admin in the subject while using the service account credentials. I request you to please suggest another approach without using super admins.

### API client name and version

googleapiclient.discovery , google.oauth2

### Reproduction steps: code

file: main.py
```python
   def reproduce():
    # complete code here
```

<any additional py files>

### Reproduction steps: supporting files

file: mydata.csv
```
alpha,1,3
beta,2,5
```

<any additional supporting files>

### Reproduction steps: actual results

file: output.txtmydata.csv
```
Calculated: foo
```

### Reproduction steps: expected results

file: output.txtmydata.csv
```
Calculated: bar
```

**Comment by ohmayr** [comment]
@joshnakinsugi, thanks for reporting this. Can you follow the suggested resolution here https://github.com/googleapis/google-api-nodejs-client/issues/1884#issuecomment-2257137457 and see if it works?

From a quick glance, I can see that you're missing the following scope:

```
