### ISSUE TITLE
Django push notification support

### ISSUE THREAD

**Issue by jorenham** [googleapis/google-api-python-client#278]
What would be the best way to achieve push notification support in Django (e.g. https://developers.google.com/google-apps/calendar/v3/push)? Or is this already a (planned) feature?

**Comment by jonparrott** [comment]
What would you imagine that support would look like? From what I understand, push notifications just send an HTTP request to your webapp. This client library doesn't have to factor into that.

**Comment by jorenham** [comment]
I was thinking about something like service methods to subscribe to, and stop to the push notifications. Views as webhooks that receive the sync and notification messages and send out signals of those messages or perhaps save them into models. 
I'm not really sure how the renewing of a notification channel could be achieved as library functionality, though.

**Comment by jonparrott** [comment]
I'm open to the possibility of an external contributor doing this, but I don't think the maintainers of this library will take this on as a primary goal.

**Comment by busunkim96** [comment]
I'm opting to close this as it's unlikely we will implement it in the future.

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.
