### ISSUE TITLE
please decode data type to corresponding python data type

### ISSUE THREAD

**Issue by c0b** [googleapis/google-api-python-client#281]
the bq tool is an app from google cloud SDK, which is using this library

``` console
$ bq --apilog - query --use_legacy_sql=false 'SELECT 1 AS a'

INFO:root:user-agent: google-api-python-client/1.3.1 (gzip)

INFO:root:{
 "kind": "bigquery#getQueryResultsResponse",
 "etag": "\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"",
 "schema": {
  "fields": [
   {
    "name": "a",
    "type": "INTEGER",
    "mode": "NULLABLE"
   }
  ]
 },
 "jobReference": {
  "projectId": "XXXXXXXXX",
  "jobId": "bqjob_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
 },
 "totalRows": "1",
 "rows": [
  {
   "f": [
    {
     "v": "1"
    }
   ]
  }
 ],
 "totalBytesProcessed": "0",
 "jobComplete": true,
 "cacheHit": true
}

INFO:root:--response-end--
[
  {
    "a": "1"
  }
]

#### similar query for `SELECT 1 AS a, 2.3 AS b`

 "schema": {
  "fields": [
   {
    "name": "a",
    "type": "INTEGER",
    "mode": "NULLABLE"
   },
   {
    "name": "b",
    "type": "FLOAT",
    "mode": "NULLABLE"
   }
  ]
 },

 "totalRows": "1",
 "rows": [
  {
   "f": [
    {
     "v": "1"
    },
    {
     "v": "2.3"
    }
   ]
  }
 ],

 "totalBytesProcessed": "0",
 "jobComplete": true,
 "cacheHit": false
}

INFO:root:--response-end--
[
  {
    "a": "1", 
    "b": "2.3"
  }
]

```

with schema from the api output, you can do more to decode each value into its correct data type: from `"1"` to INTEGER `1`:

expected output

``` python
  {
    "a": 1, 
    "b": 2.3
  }

```

**Comment by c0b** [comment]
is this @google-api-python-client project in well maintained?

**Comment by mattwhisenhunt** [comment]
@c0b it is being maintained, now more-so than in the past. We have limited resources dedicated to it so feature requests such as this one are low priority at the moment.

**Comment by busunkim96** [comment]
@c0b, thank you for filing an issue! I'm opting to close this as it's unlikely we will implement it in the future.

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.

**Comment by c0b** [comment]
but is there alternative library still taking new features development?

**Comment by busunkim96** [comment]
Hi @c0b. It looks like you're using BigQuery. We'd recommend using the newer client under active development here: 

https://github.com/googleapis/google-cloud-python/tree/master/bigquery
