### ISSUE TITLE
Upload progress (resumable) on Drive API v3

### ISSUE THREAD

**Issue by ttv20** [googleapis/google-api-python-client#309]
I tried to do a resumable upload (with progress report) on Drive API v3 according this guide: [https://developers.google.com/api-client-library/python/guide/media_upload](url)
The guide use Drive API v2 references, but I change this to v3 references
I tried unsuccessfully to do that repeatedly, until I found out the way:
```media = MediaFileUpload('pig.png', mimetype='image/png', resumable=True)
request = service.files().create(media_body=media, body={'name': 'filename'})
media.stream() ### this line doesn't exist in the guide... ###
response = None
while response is None:
  status, response = request.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)
print "Upload Complete!"
```

insted:
```media = MediaFileUpload('pig.png', mimetype='image/png', resumable=True)
request = service.files().create(media_body=media, body={'name': 'Pig'})
response = None
while response is None:
  status, response = request.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)
print "Upload Complete!"
```

Can you explain me why I had to add this to the code?
Can you fix it or update the guide?
thanks

**Comment by Zoynels** [comment]
I get a sample from https://github.com/gsuitedevs/python-samples/tree/master/drive/driveapp and try it change. I need to know on what step of uploading is my file (0-100%). Examples for chunked upload in internet I found, But I get an error.

```
e:\Programming\Python\Apps\drive\driveapp>main3.py
Traceback (most recent call last):
  File "E:\Programming\Python\Apps\drive\driveapp\main3.py", line 28, in <module>
    status, response = request.next_chunk()
  File "e:\Programming\Python\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "e:\Programming\Python\Anaconda3\lib\site-packages\googleapiclient\http.py", line 990, in next_chunk
    return self._process_response(resp, content)
  File "e:\Programming\Python\Anaconda3\lib\site-packages\googleapiclient\http.py", line 1021, in _process_response
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Bad Request">
```

Python is Python 3.6.3

[driveapp.zip](https://github.com/googleapis/google-api-python-client/files/2752193/driveapp.zip)

**Comment by kylenstone** [comment]
@busunkim96 The problem in the documentation called out by @ttv20 four years ago is still a problem, and their suggested fix still solves the problem.

I can guarantee folks who are trying to upload media via API are getting stuck due to lack of up-to-date documentation -- a cursory internet search shows a few thousand people getting stuck here, and that's probably an underestimation.  

Any chance we could get an update to your docs that definitively stakes out which libraries to use, and sample code that shows how to upload media, and which APIs to use?

Happy to pinpoint where specific errors / outdated materials are (there's a lot) if your team will help fix them!

**Comment by busunkim96** [comment]
Hi @kylenstone,

I'd be happy to edit those pages or ping down the folks who own those specific repos/pages.

The current documentation for Media Upload is [here](https://github.com/googleapis/google-api-python-client/blob/master/docs/media.md). The upload code is the same across APIs (drive, sheets, docs, etc.) as long as you are using `google-api-python-client`. If you are using some other client library the correct way to do uploads may be different.

I'm going to close this issue out as the original issue seems to be resolved. Please open a new issue with the pages that are out of date.

Thank you!

**Comment by kylenstone** [comment]
@busunkim96 So the point is that the documentation you're linking on that site does not work.  Specifically: https://github.com/googleapis/google-api-python-client/blob/master/docs/media.md#resumable-media-chunked-upload

Exactly like the original comment on this thread, the code does not work unless `media.stream()` is added:

```
request = service.files().create(media_body=media, body={'name': 'filename'})
media.stream() ### this line doesn't exist in the guide... ###
response = None
while response is None:
  status, response = request.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)
print "Upload Complete!"
```
