### ISSUE TITLE
ad-exchange seller api client cound not filter with multiple fields?

### ISSUE THREAD

**Issue by saxsir** [googleapis/google-api-python-client#311]
Sample code(python) is below. 

    result = service.accounts().reports().generate(
            accountId='myaccount',
            startDate='today-1d', endDate='today',
            metric=['AD_REQUESTS'],
            dimension=['DATE', 'AD_TAG_CODE', 'DFP_AD_UNIT_ID', 'WINNING_BID_RULE_NAME'],
            filter="DFP_AD_UNIT_ID==10000000,AD_TAG_CODE==999999999"],
            maxResults=100).execute()

This code got http error response.

    HttpError: <HttpError 500 when requesting https://www.googleapis.com/adexchangeseller/v2.0/accounts/myaccount/reports?startDate=today-1d&endDate=today&metric=AD_REQUESTS&maxResults=100&filter=DFP_AD_UNIT_ID%3D%3D10000000%2CAD_TAG_CODE%3D%3D999999999&alt=json&dimension=DATE&dimension=AD_TAG_CODE&dimension=DFP_AD_UNIT_ID&dimension=WINNING_BID_RULE_NAME returned "">
   

In rest api document, 

Filtering  |  Seller REST API  |  Google Developers
https://developers.google.com/ad-exchange/seller-rest/reporting/filtering#OR

there is no description that how to filtering with multiple fields.
Is this specification or bug ??

(I sent feedback on the document page, but no response yet...)

Filtering with only `DFP_AD_UNIT_ID` field will work filne

```
 result = service.accounts().reports().generate(
            accountId='myaccount',
            startDate='today-1d', endDate='today',
            metric=['AD_REQUESTS'],
            dimension=['DATE', 'AD_TAG_CODE', 'DFP_AD_UNIT_ID', 'WINNING_BID_RULE_NAME'],
            filter="DFP_AD_UNIT_ID==10000000,DFP_AD_UNIT_ID==20000000"],
            maxResults=100).execute()
```

**Comment by darkash** [comment]
If i remember correctly, you need to supply the filter in a list of string, not a single string like your sample code
change this line
`"DFP_AD_UNIT_ID==10000000,AD_TAG_CODE==999999999"]`
to
`["DFP_AD_UNIT_ID==10000000", "AD_TAG_CODE==999999999"]`
