### ISSUE TITLE
File caching for the oauth2client >= 4.0.0 

### ISSUE THREAD

**Issue by xmedeko** [googleapis/google-api-python-client#325]
@tmatsuo proposed in #110 to cache ``discovery.build()``, however, #294 has stopped using cache outside of the GAE (appengine) environment (see also #299). E.g. the ``discovery.build()`` is not cached in the CGE environment. Is it possible to bring the file caching back, or provide some example of file cache (subclass of ``googleapiclient.discovery_cache.Cache``)?

**Comment by jonparrott** [comment]
Sure, mostly what needs to happen is that the current file cache needs to
be updated to not use oauth2client's locked file.

**Comment by Schweigi** [comment]
Is there a known workaround in the meantime?

**Comment by Schweigi** [comment]
I created a small workaround by using a in memory cache (see example below). Does anyone know if there should be a regular cache invalidation? Currently the memory cache is cleared on each deployment, I hope that's ok for the time being.

```
class MemoryCache(Cache):
    _CACHE = {}

    def get(self, url):
        return MemoryCache._CACHE.get(url)

    def set(self, url, content):
        MemoryCache._CACHE[url] = content
```

**Comment by xmedeko** [comment]
AFAIK the Google production API should not change (the same version of API), so the you do not need to invalidate the cache. However, the [`discovery_cache/__init__.py`](https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery_cache/__init__.py) defines the limit `DISCOVERY_DOC_MAX_AGE`  as one day.

+1 for a neat, simple `MemoryCache`. IMO it's good when you have a single, long running process.

If you want to share the cache among processes, (like running scripts by the cron,) you may copy the old good [oauth2client `locked_file.py`](https://github.com/google/oauth2client/blob/v3.0.0/oauth2client/contrib/locked_file.py) and then to plug it somehow with [`discovery_cache/file_cache.py`](https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery_cache/file_cache.py). Beware, the  `locked_file.py` is considered not 100% save, so you take the risk. (But works well in practice.) By "plugin somehow" I mean either copy & change the `discovery_cache/file_cache.py` to take your `locked_file.py` or to trick the Python to think your `locked_file.py` is from the `oauth2client.locked_file` package.

**Comment by xmedeko** [comment]
@jonparrott what about to change file lock to the `multiprocessing.RLock()` in the original `locked_file.py`? Would be it sufficient solution to accept back to the repo?

**Comment by jonparrott** [comment]
I think it's likely possible to do this without any sort of locking.

**Comment by xmedeko** [comment]
You mean a file cache, shared among multiple processes, without any locking? How to prevent data corruption, when 2 process write to the same file?

**Comment by jonparrott** [comment]
Likely using a folder containing a file for each cached discovery doc. No
locking needed. Worst case scenario two processes write the same file twice.

**Comment by xmedeko** [comment]
FYI to use the locked_file from oauth2client 3.0.0 without that package (it's not required since 1.7.3), just use the gist https://gist.github.com/xmedeko/e5293707e075d18c9dde8a574d2670e5 and call the `shim()` once.

**Comment by Chronial** [comment]
Based on [Schweigi's solution](https://github.com/google/google-api-python-client/issues/325#issuecomment-274349841), I wrote a simple file based cache to also cache across processes.
```py
import os.path
import hashlib
import tempfile

class DiscoveryCache:
    def filename(self, url):
        return os.path.join(
            tempfile.gettempdir(),
            'google_api_discovery_' + hashlib.md5(url.encode()).hexdigest())

    def get(self, url):
        try:
            with open(self.filename(url), 'rb') as f:
                return f.read().decode()
        except FileNotFoundError:
            return None

    def set(self, url, content):
        with tempfile.NamedTemporaryFile(delete=False) as f:
            f.write(content.encode())
            f.flush()
            os.fsync(f)
        os.rename(f.name, self.filename(url))
```

**Comment by timc13** [comment]
Is there a resolution for this?  I'm using https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib and OAuth has suddenly been broken for me because `oauth2client` module is not available

I am using GAE flex by the way.

**Comment by busunkim96** [comment]
I'm opting to close this as it's unlikely we will implement it in the future.

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.

**Comment by aawilson** [comment]
I don't know if this changed at some point, but I had to import `Cache` from `googleapiclient.discovery_cache.base` (presumably `googleapiclient.discovery_cache.file_cache` also works fine, but inheriting from the Base class is almost certainly the better idea)

**Comment by Kache** [comment]
An equivalent & simpler workaround is to set `cache_discovery=False`:

```py
discovery.build(api, version, http=http, cache_discovery=False)
```

Since according to [the source](https://github.com/googleapis/google-api-python-client/blob/167f8609eb16cbac77ca43720a18c860d130c1d6/googleapiclient/discovery.py#L383-L389) the "cache" is never reused in the "single, long running process" case.

**Comment by neomafo88** [comment]
> I created a small workaround by using a in memory cache (see example below). Does anyone know if there should be a regular cache invalidation? Currently the memory cache is cleared on each deployment, I hope that's ok for the time being.
> 
> In memory cache:
> 
> ```
> class MemoryCache(Cache):
>     _CACHE = {}
> 
>     def get(self, url):
>         return MemoryCache._CACHE.get(url)
> 
>     def set(self, url, content):
>         MemoryCache._CACHE[url] = content
> ```
> 
>  
> Usage:
> 
> ```
> http = ...
> service = discovery.build('calendar', 'v3', http=http, cache=MemoryCache())
> ```

googleapiclient.discovery_cache.base.Cache

**Comment by viktoratedgetier** [comment]
In case anyone uses the workaround from https://github.com/googleapis/google-api-python-client/issues/325#issuecomment-1328152084, beware of the **memory leak** it can cause in long-running processes. Better to put a bound onto it.

```
from cachetools import LRUCache
from googleapiclient.discovery_cache.base import Cache as DiscoveryCache

# Set a cache boundary to prevent a memory leak
_discovery_cache: LRUCache = LRUCache(maxsize=100)


class MemoryCache(DiscoveryCache):
    def get(self, url: str) -> Optional[str]:
        return _discovery_cache.get(url)

    def set(self, url: str, content: str) -> None:
        _discovery_cache[url] = content
```


Usage:
```
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

refresh_token = ...
credentials = Credentials.from_authorized_user_info(
      {
          "refresh_token": refresh_token,
          "client_id": GOOGLE_APP_CLIENT_ID,
          "client_secret": GOOGLE_APP_CLIENT_SECRET,
      }
  )
gmail_service = build("gmail", "v1", credentials=credentials, cache=MemoryCache())
```
