### ISSUE TITLE
Please get rid of the stale googleapiclient 1.2 from Pypi

### ISSUE THREAD

**Issue by diwu1989** [googleapis/google-api-python-client#33]
https://pypi.python.org/pypi?%3Aaction=search&term=google+api+client&submit=search
![image](https://cloud.githubusercontent.com/assets/380950/4696555/3cd51730-5813-11e4-889c-5293dd552788.png)

From what I can tell, that 1.2 library is an old version of this library somehow submitted under a different name. The main problem is that they are both endorsed by Google in the details and confused the hell out of me originally.

Please just take the other library out of Pypi completely, everyone should be relying on the google-api-python-client library instead.

**Comment by skelterjohn** [comment]
Should probably remove me from the project :) I no longer work for Google.
