### ISSUE TITLE
Running a Script through DCM Trafficking API - ANY SCRIPT.

### ISSUE THREAD

**Issue by jerinshirley** [googleapis/google-api-python-client#392]
I was told by the Google API team that my issue belonged here.

I am just trying to run any of the sample scripts posted here for Python v2.7. I've been using run_report.py. A browser would always open to allow access to the API, but the script would fail after that. I always receive the same error:
httplib.ResponseNotReady

I've tried using --noauth_local_webserver as well and received the same error. Considering I haven't been able to run anything since setting up the API, I think this is a set up problem, but Google API Support thinks this is a configuration issue with the script. Will someone please just tell me what the problem is and how to fix it?

**Comment by mcdonc** [comment]
Hi @jerinshirley .  I understand that you're trying to run a sample script unchanged?  I know it may sound pedantic, but can you paste the script you're trying to run as well as the output from your console when it fails?
