### ISSUE TITLE
cannot import name urllib

### ISSUE THREAD

**Issue by codersquid** [googleapis/google-api-python-client#42]
I updated my system from trusty to utopic and started getting this error not sure which version of what changed. I don't have time to dig in to it right now, but I wanted to make sure people are aware of it.

I went ahead and did what I needed by working with a trusty image.

```
[steve]sheila@yagi: ar14 » ./youtube.py                ~/dev/pyvideo/conferences/ar14  
Traceback (most recent call last):
  File "./youtube.py", line 10, in <module>
    from apiclient.discovery import build
  File "/home/sheila/dev/pyvideo/google-api-python-client/apiclient/__init__.py", line 16, in <module>
    from googleapiclient import channel
  File "/home/sheila/dev/pyvideo/google-api-python-client/googleapiclient/channel.py", line 62, in <module>
    from googleapiclient import errors
  File "/home/sheila/dev/pyvideo/google-api-python-client/googleapiclient/errors.py", line 27, in <module>
    from oauth2client import util
  File "/home/sheila/.virtualenvs/steve/local/lib/python2.7/site-packages/oauth2client/util.py", line 38, in <module>
    from six.moves import urllib
ImportError: cannot import name urllib
```

**Comment by isokrates** [comment]
I realise I'm a bit late to the party here (nearly three years late...), but I think I'm having the same/a similar issue with the `oauth2client` library. Would one of you mind explaining this to me? In the python interpreter, `from oauth2client import client` works fine, but when I try the same thing in my Flask application, I get:

`from oauth2client import client`
...
`File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 33, in <module>`
...
`from six.moves import urllib`
...
`ImportError: cannot import name urllib`

Any ideas what might be causing this? I have `six` 1.10.0 installed, but I'm curious about your comment that there might be a bundled, older copy of `six` being used... how might I check/fix this?

Thanks!

**Comment by jonparrott** [comment]
@isokrates you probably need to upgrade six.

**Comment by craigcitro** [comment]
@isokrates Just before the line that's raising the import error, do

    print('six: ' + six.__file__)

and you'll find out where your other copy is.

**Comment by isokrates** [comment]
@jonparrott my regular version of `six` is up to date (1.10.0), but you're probably right that there's another version somewhere that is not...

@craigcitro this is a great tip—thanks very much! I will do as you suggest :) how do I then upgrade that version?

**Comment by craigcitro** [comment]
@isokrates Depends on where it's installed, how it got installed, etc.

But based on past experience, I'd but 70% odds on `sudo easy_install -U six` fixing the problem.

**Comment by isokrates** [comment]
Cool. Thanks again for your help! :)

**Comment by YChebotaev** [comment]
Any help on this?

I have six version 1.14.0
Python 2.7 (strong requirement, cannot migrate to 3)
google-cloud-storage version 1.22.0 (because it's latest version with 2.7 support)

Same error:
```python
from google.cloud import storage
```

```shell
    from six.moves import urllib
ImportError: cannot import name urllib
```

**Comment by YChebotaev** [comment]
Guys? Help please with this ↑

**Comment by DeyDipankar** [comment]
I have the same issue of getting error on importing urlib. I just reinstall six with conda, and now I am able to import urlib from six.moves
