### ISSUE TITLE
KeyError 'rows' when using task scheduler

### ISSUE THREAD

**Issue by daocsm** [googleapis/google-api-python-client#420]
I have been working on an easy way to pull all the impression data from Google Search Console.
I have created a python script based off of the supplied example from Google. 
Everything was working perfectly! so I created a bat file to run all my clients data at once, each day and used windows task scheduler to run the bat file. 
The issue is, whenever task scheduler runs the .bat file, I get this error. 

`Traceback (most recent call last):
  File "impressions-data.py", line 150, in <module>
    main(sys.argv)
  File "impressions-data.py", line 86, in main
    print_web_table(web_response, file_path)
  File "impressions-data.py", line 113, in print_web_table
    rows = web_response['rows']
KeyError: 'rows'`

However, if I run the .bat file manually, everything works perfectly and no issues. 

Any thoughts on why task scheduler would cause this issue? and running it manually wouldn't?

Thanks.

**Comment by darkash** [comment]
Usually if KeyError happens, it's usually caused by your API request is too much on same IP in a short time or the server on Google side have trouble

but assuming that your bat file runs all the client on the same time at once, I guess it's the first case as it also happens on my side as well

Try supplying userIP or quotaUser parameter
https://developers.google.com/analytics/devguides/config/mgmt/v2/parameters

**Comment by busunkim96** [comment]
Hi @daocsm,

It looks like that KeyError is a result of  `web_response` not containing the field you were expecting. This sample checks to make sure there is a field `rows` in the response before trying to access the value. 
https://github.com/googleapis/google-api-python-client/blob/fef743a41e8f0e533469d621567f322a5f8465be/samples/searchconsole/search_analytics_api_sample.py#L159-L172

You can check to see if the request was successful by looking for `rows` and do some error handling or logging when it isn't in the response. This should help track down what's going wrong when you run your .bat file.

Please let us know if you have more concerns.
