### ISSUE TITLE
Can't INSERT into Google Fusion Tables by server-to-server interactions

### ISSUE THREAD

**Issue by tarasinf** [googleapis/google-api-python-client#428]
I try to work with Google Fusion Table using OAuth 2.0 for Server to Server (two-legged) by the next code:

```
from apiclient.discovery import build 
from oauth2client.service_account import ServiceAccountCredentials  

scopes = ['https://www.googleapis.com/auth/fusiontables'] 
credentials = ServiceAccountCredentials\
     .from_json_keyfile_name('***file-name***.json', scopes) 
fusiontables = build('fusiontables', 'v2', credentials=credentials)  
obj = fusiontables.query().sql(sql='select * from ***table-id***').execute()

```
Everything is OK when I read from the table, but when I try to insert some data:

```
obj = fusiontables.query().sql(
     sql="INSERT INTO ***table-id*** (Location, Number) VALUES('Paris', 1234)")\
     .execute()
```

I got the error:
`googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/fusiontables/v2/query?alt=json&sql=INSERT+INTO+***table-id***+%28Location%2C+Number%29+VALUES%28%27Paris%27%2C+1234%29 returned "Forbidden">
`

Question: does someone know what I am doing wrong to implement insertion into Google Fusion Table?Thanks.

**Comment by mattwhisenhunt** [comment]
Try adding `https://www.googleapis.com/auth/fusiontables.readonly` as a second scope.
