### ISSUE TITLE
Doubleclick Search Requests use Unescaped JSON

### ISSUE THREAD

**Issue by jmarshall9120** [googleapis/google-api-python-client#441]
I've also notified the API team of this.  Not sure if it's more relevant to them or this library.  

The problem is that the Double Click search API only accepts unescapped JSON in the request body for http requests. 

The documentation [here ](https://developers.google.com/doubleclick-search/v2/how-tos/reporting/asynchronous-requests) shows an example like such:

```
....authenticate your service.....
body = {"Name" : "JSON test", "Comment" : "This is a comment"}
SERVICE = discovery.build(API_NAME, API_VERSION, http=http)
request = SERVICE.reports().request(body=body)
fileResource = request.execute()

```
The request fails because of the .execute() method or the SERVICE.reports().request([str] body) constructor. 
Both the constructor and the method create a catch 22 that keeps the request from succeeding:

The constructor causes the JSON to escape.  Like: 
      ` request.body = {\\"Name" : \\"JSON test\\", \\"Comment\\" : \\"This is a comment\\"}`
The .execute() method won't pass an un-escaped JSON sting
The API doesn't see the JSON string if its escaped. 

So all requests fail using this library either due to:
1. API doesn't see the JSON because it's escaped.
2. .execute() method doesn't pass the JSON string to the request body.  

This should probably be fixed in the .execute() method - maybe a parameter for not escaping which can be added during the discovery.build() call. 

Anyway, this can also be worked around like: 
```
....authenticate your service.....
body = {"Name" : "JSON test", "Comment" : "This is a comment"}
SERVICE = discovery.build(API_NAME, API_VERSION, http=http)
request = SERVICE.reports().request(body=body)
resp, content = request.http.request(request.uri, method="POST", body=body, headers=request.headers)
```

Hope this helps

**Comment by mcdonc** [comment]
Someone with access to a Doubleclick Agency Manager will need to triage this.  I am assigning to @crwilcox provisionally to indicate this.

**Comment by busunkim96** [comment]
This appears to have been resolved. I do not have access to Doubleclick, but have verified that the server is parsing the body with the sample below.

```python
from __future__ import print_function
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/doubleclicksearch']

def main():
    """Shows basic usage of the Double Click Search API
    """
    creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    body = {"reportScope": {"agencyId": 1234}, "reportType": "keyword"}
    service = build('doubleclicksearch', 'v2', credentials=creds)
    resp = service.reports().request(body=body).execute()
    print(resp.json())

if __name__ == '__main__':
    main()
```

Exception:
```
(env) busunkim-macbookpro1:google-api-python-client busunkim$ python3 doubleclicksearch_v2.py
Traceback (most recent call last):
  File "doubleclicksearch_v2.py", line 40, in <module>
    main()
  File "doubleclicksearch_v2.py", line 36, in main
    resp = service.reports().request(body=body).execute()
  File "/Users/busunkim/github/google-api-python-client/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/busunkim/github/google-api-python-client/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/doubleclicksearch/v2/reports?alt=json returned "Report must have at least one column.">
```

----
**Reference**: 
* [Library Reference Documentation](http://googleapis.github.io/google-api-python-client/docs/dyn/doubleclicksearch_v2.reports.html#request)
* [Discovery document](https://www.googleapis.com/discovery/v1/apis/doubleclicksearch/v2/rest)
