### ISSUE TITLE
Invalid message body size

### ISSUE THREAD

**Issue by jleroy** [googleapis/google-api-python-client#510]
I retrieve the following cp936-encoded message using the Gmail API:

```
{
 [...]
 "payload": {
  "partId": "",
  "mimeType": "text/plain",
  "filename": "",
  "headers": [
    [...]
  ],
  "body": {
   "size": 173,
   "data": "NmY3ZTUyZGFi[...]Agg=="
  }
 },
 [...]
}
```

I want to check that the decoded data size match the "size" field returned by the API (using Python 3):

```
payload_body = msg['payload']['body']
msg_body = base64.urlsafe_b64decode(payload_body['data'])
msg_body_len = payload_body['size']
real_body_len = len(msg_body)

if not msg_body_len == real_body_len:
    print('Invalid message body length for message ID {message_id} ({real_size} bytes instead of {payload_size}).'.format(message_id=message_id, real_size=real_body_len, payload_size=msg_body_len))
```

Output: 

```
Invalid message body length for message ID 1639c31f21ea819b (193 bytes instead of 173).
````

This code works with `UTF-8` or `ISO 8859-1` encoded messages, but not with more complex encodings like `gb2312` or `cp936`. However, the [API documentation](https://developers.google.com/gmail/api/v1/reference/users/messages/attachments?hl=fr#resource) says that the "size" field returns the "number of bytes for the message part data (encoding notwithstanding)", so I don't understand what I'm doing wrong.

Any idea?

Thank you.

**Comment by mcdonc** [comment]
I suspect this is somehow related to the difference of the length of a decoded bytestring (in Python 3, it would be "str") and the encoded variant (bytes).  The docs indeed seem to say that the length is of the number of bytes needed to encode the value, not the number of codepoints produced after decoding.  I'm not sure if the docs are wrong, or if the result is, or neither.

It would be useful if you could supply the base64 encoded version of the actual payload that produces this result (including its type, whether it's str or bytes).

**Comment by jleroy** [comment]
@mcdonc I can't post the payload here as it contains some sensitive data. But I can send it to you in private?

**Comment by mcdonc** [comment]
@jleroy Absolutely.  Please send to chrismgoog@gmail.com

**Comment by mcdonc** [comment]
@jleroy had this to say in private communications:

```
OK, I think I've found the issue.

According to the API documentation, response is always UTF-8 encoded.
But the value of the "size" field seems to be computed *before* the
payload has been encoded to UTF-8:

 >>> len(base64.urlsafe_b64decode(payload_body['data']).decode('utf-8').encode('cp936'))
 173

So it seems to be an API bug?
```

**Comment by mcdonc** [comment]
I suspect that changing this on the backend, even though it's unexpected, would cause a bit of chaos, as others have undoubtedly figured this out and work around it by decoding from UTF-8 and encoding to the message encoding, comparing the length of the reencoded bytestring to the size purported in the payload body.  Although it's subobptimal, now that we understand it, I might suggest that we just change the bit of docs where it says size is  "number of bytes for the message part data (encoding notwithstanding)" to something like "number of bytes for the message part data after it has been reencoded to the target encoding" or somesuch.  Any suggestions about docs wording there?

**Comment by jleroy** [comment]
I don't think that updating the documentation is a good solution because there is no way to know the target encoding without retrieving and parsing the message's "Content-Type" header. 

Maybe adding a "size_utf8" field is a better solution.

**Comment by mcdonc** [comment]
I think that's a reasonable suggestion.  I'll try to figure out how to get
it to the backend team.

**Comment by mcdonc** [comment]
@theacodes can you help me get a suggestion to add a 'size_utf8' to the payload body to the GMail backend team?  I *think* the rationale here is that de-base64-encoding to check the length of the encoded message is much slower than just being able to rely on a value in the payload, maybe @jleroy can confirm.

**Comment by jleroy** [comment]
Any progress on this issue?

**Comment by parthea** [comment]
@jleroy Can you please share a code sample to re-create the problem?

**Comment by parthea** [comment]
I'm going to close off this issue due to inactivity but if you're still having trouble please re-open it with more information.
