### ISSUE TITLE
Batch Request returns 404 "Not Found"

### ISSUE THREAD

**Issue by iamlordaubrey** [googleapis/google-api-python-client#538]
Hi guys, I'm having a recent issue

```
def aggregate_response(request_id, response, exception):
    if exception is not None:
        # handle exception
        print('An exception occurred: ', exception)
    else:
        # handle response
        print('request_id is: ', request_id)
        print('response is: ', response)

def batch_processor(queryset):
    service = build('customsearch', 'v1')
    batch = service.new_batch_http_request(callback=aggregate_response)

    for result_instance in queryset:
        search_query = {
            'name': result_instance.name,
            'status': result_instance.status,
        }

        query = f"{search_query['name']} {search_query['status']}"
        # query is just a name string

        batch.add(service.cse().list(
            q=query,
            cx=os.environ.get("SEARCH_ENGINE_ID"),
            hl='en',
            lr='lang_en',
            num=3,
            sort='date',
            orTerms=search_query['name'],
            key=os.environ.get("SEARCH_API_KEY"),
        ))

    batch.execute()
```

I keep getting an exception:
An exception occurred:  <HttpError 404 when requesting https://www.googleapis.com/customsearch/v1?q={q}&cx={cx}&hl=en&lr=lang_en&num=3&sort=date&orTerms={orTerms}&key={key}&alt=json returned "Not Found">
However, clicking on the link https://www.googleapis.com/customsearch/v1?q={q}&cx={cx}&hl=en&lr=lang_en&num=3&sort=date&orTerms={orTerms}&key={key}&alt=json returns valid data.

I did some digging and I think the problem is related to the `batch_uri` / `_LEGACY_BATCH_URI = 'https://www.googleapis.com/batch'` (the trailing `/batch`) found in the `googleapiclient/http.py` file.

Going to https://www.googleapis.com/batch/customsearch/v1?q={q}&cx={cx}&hl=en&lr=lang_en&num=3&sort=date&orTerms={orTerms}&key={key}&alt=json returns "Not Found", however removing the trailing `/batch` from `_LEGACY_BATCH_URI` value doesn't fix it.

P.S.: This was working until recently.
Thanks.

**Comment by mcdonc** [comment]
Confirmed locally using the following:

```
from googleapiclient.discovery import build
#from oauth2client import file, client, tools

SE_ID = "XXXX"
SEARCH_API_KEY = "XXXX"

def aggregate_response(request_id, response, exception):
    if exception is not None:
        # handle exception
        print('An exception occurred: ', exception)
    else:
        # handle response
        print('request_id is: ', request_id)
        print('response is: ', response)

terms = ['pyramid', 'pylons']

def main():
    service = build('customsearch', 'v1')
    batch = service.new_batch_http_request(callback=aggregate_response)

    for query in terms:

        batch.add(service.cse().list(
            q=query,
            cx=SE_ID,
            hl='en',
            lr='lang_en',
            num=3,
            sort='date',
            orTerms=query,
            key=SEARCH_API_KEY,
        ))

    batch.execute()

if __name__ == '__main__':
    main()
    
```

**Comment by mcdonc** [comment]
The effective batch API URL constructed by BatchHttpRequest is:
```
https://www.googleapis.com/batch/customsearch/v1
```

This URI is NotFound, which is why the exception happens, I believe.

**Comment by iamlordaubrey** [comment]
Hi @mcdonc, @JustinBeckwith 
Thanks for all you've done so far. I'm new with these things (my first public issue ever); please what are the next steps?

**Comment by mcdonc** [comment]
@iamlordaubrey I've marked this ticket as "backend" and I hope that at some point this week or next we can escalate it to the backend team, once I figure out how to do that.  In the meantime, there isn't much you or I can do :)

**Comment by iamlordaubrey** [comment]
Ok, thanks. Fingers crossed 🤞

**Comment by busunkim96** [comment]
This appears to be resolved. I was able to get the expected results using the script above.

> Confirmed locally using the following:
> 
> ```
> from googleapiclient.discovery import build
> #from oauth2client import file, client, tools
> 
> SE_ID = "XXXX"
> SEARCH_API_KEY = "XXXX"
> 
> def aggregate_response(request_id, response, exception):
>     if exception is not None:
>         # handle exception
>         print('An exception occurred: ', exception)
>     else:
>         # handle response
>         print('request_id is: ', request_id)
>         print('response is: ', response)
> 
> terms = ['pyramid', 'pylons']
> 
> def main():
>     service = build('customsearch', 'v1')
>     batch = service.new_batch_http_request(callback=aggregate_response)
> 
>     for query in terms:
> 
>         batch.add(service.cse().list(
>             q=query,
>             cx=SE_ID,
>             hl='en',
>             lr='lang_en',
>             num=3,
>             sort='date',
>             orTerms=query,
>             key=SEARCH_API_KEY,
>         ))
> 
>     batch.execute()
> 
> if __name__ == '__main__':
>     main()
>     
> ```
