### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by nvllsvm** [googleapis/google-api-python-client#539]
Python 3.7 stable was released on June 27, 2018.

Todo:
- [x] Confirm working with Python 3.7
- [x] Add Python 3.7 to ``classifiers`` in setup.py

**Comment by mcdonc** [comment]
I'll add one more step:

- [ ] Change travis configuration to do CI against 3.7

At this time, however, Travis doesn't officially support 3.7 yet... https://github.com/travis-ci/travis-ci/issues/9815

**Comment by kapilt** [comment]
its not well documented, but travis does support 3.7,  example https://github.com/capitalone/cloud-custodian/blob/master/.travis.yml

**Comment by busunkim96** [comment]
Tests are being run with 3.7 on Kokoro, and 3.7 has been added to `setup.py`.
