### ISSUE TITLE
from oauth2client import client problems

### ISSUE THREAD

**Issue by quistian** [googleapis/google-api-python-client#554]
I have tried to run the calendar.py application from the samples directory. When I do, the line:

from oauth2client import client

Generates the following error:
 File "./calendar.py", line 23, in <module>
    from oauth2client import client
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 39, in <module>
    from oauth2client import transport
  File "/usr/local/lib/python2.7/site-packages/oauth2client/transport.py", line 17, in <module>
    import httplib2
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 43, in <module>
    import calendar
  File "/Users/russ/Dropbox/Src/Google-API/calendar.py", line 23, in <module>
    from oauth2client import client
ImportError: cannot import name client

I am using the following versions, both installed via pip:

% pip show oauth2client
Name: oauth2client
Version: 4.1.2
Summary: OAuth 2.0 client library
Home-page: http://github.com/google/oauth2client/
Author: Google Inc.
Author-email: jonwayne+oauth2client@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: pyasn1, pyasn1-modules, six, httplib2, rsa
Required-by:

%% pip show google-api-python-client
Name: google-api-python-client
Version: 1.7.4
Summary: Google API Client Library for Python
Home-page: http://github.com/google/google-api-python-client/
Author: Google Inc.
Author-email: UNKNOWN
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: httplib2, uritemplate, google-auth-httplib2, six, google-auth

**Comment by bgi** [comment]
I have the same issue, nice to see that no one reacts. Its annyoing as f***, I cant count the times I sat there trying to import some google libraries in app engine. Cant remember it going smoothly ever.

**Comment by bgi** [comment]
Okay, got it. When one googles this issue the the commonly proposed fix is: "pip install --upgrade oauth2client" and vendor in the lib directory. See the problem? The command should be "pip install --upgrade -t lib oauth2client" or else you vendor in nothing. I really love the attention to detail of some folks.

**Comment by mcdonc** [comment]
For the record, I was able to get this working in a Python virtual environment without issue by just running "pip install oauth2client" in that virtualenv.  Here's how that worked:

```
~/projects/gcloud $ virtualenv -ppython2.7 env_apiclient_554
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/chrism/projects/gcloud/env_apiclient_554/bin/python2.7
Also creating executable in /home/chrism/projects/gcloud/env_apiclient_554/bin/python
Installing setuptools, pip, wheel...done.
~/projects/gcloud $ cd google-api-python-client
~/projects/gcloud/google-api-python-client $ ../env_apiclient_554/bin/python setup.py install
running install
running bdist_egg
running egg_info
... elided ...
Finished processing dependencies for google-api-python-client==1.7.4
~/projects/gcloud/google-api-python-client $ cd samples/calendar_api/
~/projects/gcloud/google-api-python-client/samples/calendar_api $ ../../../env_apiclient_554/bin/python calendar_sample.py 
Traceback (most recent call last):
  File "calendar_sample.py", line 23, in <module>
    from oauth2client import client
ImportError: No module named oauth2client
~/projects/gcloud/google-api-python-client/samples/calendar_api $ cd ../../../env_apiclient_554
~/projects/gcloud/env_apiclient_554 $ bin/pip install oauth2client
Collecting oauth2client
... elided ...
Successfully installed oauth2client-4.1.3
~/projects/gcloud/env_apiclient_554 $ cd ../google-api-python-client/samples/calendar_api/
~/projects/gcloud/google-api-python-client/samples/calendar_api $ ../../../env_apiclient_554/bin/python calendar_sample.py 
~/projects/gcloud/google-api-python-client/samples/calendar_api $ ../../../env_apiclient_554/bin/python calendar_sample.py 
/home/chrism/projects/gcloud/env_apiclient_554/local/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access calendar.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=294068764625-bromhqr2m13ra81j92jvtoshsolhl4d1.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Created new window in existing browser session.
```
I'm not sure how we can make this better across the board for every possible configuration.  Often "system" Pythons have preexisting copies of libraries that the apiclient wants to use installed in nonstandard ways, requiring users to hack around them.  The answer is almost always "use a virtualenv" and maybe that should be recommended in the docs, but this particular issue is a subset of that larger problem.

**Comment by agiUnderground** [comment]
You driving me crazy google with your app engine imports.
