### ISSUE TITLE
Error with local dev_appserver.py on MacOSX macOS 10.13.6 (17G65)

### ISSUE THREAD

**Issue by pavelkrejsa** [googleapis/google-api-python-client#556]
Hi,
I moved my development from Cloud9 IDE to my MacBook Pro. Using homebrew instalation of Python 2.7.15, but the same problem was with vanilla MacOSX Python installation 2.7.10.

There is no problem on Cloud9 IDE (Ubuntu LTS), but when I run dev_appserver.py on my MacBook Pro locally, I get following error:

> WARNING  2018-08-08 19:45:39,946 devappserver2.py:124] *** Notice ***
> In a few weeks dev_appserver will default to using the Cloud Datastore Emulator. We strongly recommend you to enable this change earlier.
> To opt-in, run dev_appserver with the flag --support_datastore_emulator=True
> Read the documentation: https://cloud.google.com/appengine/docs/standard/python/tools/migrate-cloud-datastore-emulator
> Help us validate that the feature is ready by taking this survey: https://goo.gl/forms/UArIcs8K9CUSCm733
> Report issues at: https://issuetracker.google.com/issues/new?component=187272
> 
> INFO     2018-08-08 19:45:39,961 devappserver2.py:178] Skipping SDK update check.
> INFO     2018-08-08 19:45:40,174 api_server.py:274] Starting API server at: http://localhost:51551
> INFO     2018-08-08 19:45:40,358 dispatcher.py:270] Starting module "default" running at: http://localhost:8080
> INFO     2018-08-08 19:45:40,362 admin_server.py:152] Starting admin server at: http://localhost:8000
> INFO     2018-08-08 19:45:42,499 instance.py:294] Instance PID: 37004
> ERROR    2018-08-08 19:45:44,666 wsgi.py:263] 
> Traceback (most recent call last):
>   File "/Users/pavelkrejsa/Google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
>     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
>   File "/Users/pavelkrejsa/Google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
>     handler, path, err = LoadObject(self._handler)
>   File "/Users/pavelkrejsa/Google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
>     obj = __import__(path[0])
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/main.py", line 141, in <module>
>     class MainFilterForm(FlaskForm):
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/main.py", line 150, in MainFilterForm
>     int(pendulum.today().year),
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/pendulum.py", line 308, in today
>     return cls.now(tz).start_of('day')
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/pendulum.py", line 276, in now
>     dt = datetime.datetime.now(cls._local_timezone())
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/pendulum.py", line 92, in _local_timezone
>     return local_timezone()
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/tz/__init__.py", line 30, in local_timezone
>     return LocalTimezone.get()
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/tz/local_timezone.py", line 25, in get
>     name = cls.get_local_tz_name()
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/tz/local_timezone.py", line 60, in get_local_tz_name
>     return getattr(cls, 'get_tz_name_for_{}'.format(os))()
>   File "/Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/tz/local_timezone.py", line 66, in get_tz_name_for_darwin
>     output = subprocess.check_output(
> AttributeError: 'module' object has no attribute 'check_output'
> INFO     2018-08-08 19:45:44,691 module.py:880] default: "GET / HTTP/1.1" 500 -
> 

I was able to go up to /Users/pavelkrejsa/VividIT/iknowmytime-python/lib/pendulum/tz/local_timezone.p and I can see that on my Mac, problem is probably at this piece:
```
    @classmethod
    def get_tz_name_for_darwin(cls):
        tzname = None
        try:
            output = subprocess.check_output(
                "systemsetup -gettimezone",
                stderr=subprocess.STDOUT
            )

            tzname = output.replace(b'Time Zone: ', b'').strip()
        except OSError:
            pass

```

I have no idea how to fix it.

**Comment by mcdonc** [comment]
Somewhere in your Python's sys.path or within pendulum/tz or within the current working directory when you run your program, you have a module named "subprocess" (a file name subprocess.py or a directory with an ``__init__.py`` in it named subprocess) that is overriding the module of the same name in the Python stdlib.  You can fix it by renaming or deleting that module.
