### ISSUE TITLE
Need help on Oauth2 decorators used in Appengine code

### ISSUE THREAD

**Issue by karthick-ck** [googleapis/google-api-python-client#557]
Hi Team,

I have to read spreadsheet data in one of my appengine handler and have to send it in the response. 

I have used "oauth2client.appengine.OAuth2Decorator" to get OAuth tokens by which I can call the spreadsheet api. Now I am facing issue that the redirection to 'accounts.google.com' is failing due to 
"No 'Access-Control-Allow-Origin' header is present on the requested resource" error.

Can you anyone guide me how to do OAuth flow in appengine handlers ? 

Following is my appengine code snippet:

from oauth2client.appengine import OAuth2Decorator

decorator = OAuth2Decorator(
    client_id=settings.OAUTH2_CLIENT_ID,
    client_secret=settings.OAUTH2_CLIENT_SECRET,
    scope='https://www.googleapis.com/auth/spreadsheets')

class GetReviewCaseInfoHandler(BaseHandler):
  @decorator.oauth_required
  def get(self):
      ....
      ....

**Comment by busunkim96** [comment]
Hi Karthick, 

Please take a look at this [guide](https://developers.google.com/api-client-library/python/guide/google_app_engine) and the AppEngine [sample](https://github.com/googleapis/google-api-python-client/tree/master/samples/appengine).
