### ISSUE TITLE
Async requests with pagination

### ISSUE THREAD

**Issue by BoPengGit** [googleapis/google-api-python-client#566]
Hi,

I have a question on requesting the API client asynchronously. For example, for the Google Plus API, I already know I want to request 20 pages each time. Is there a way for me to do this asynchronously instead of making each request one at a time and requesting again with the nextpage token. I'm building a dashboard and this could be time consuming to wait to request the next page after getting back the nextpagetoken.

Thanks for the help!

**Comment by Fryuni** [comment]
This is not an issue with the client. Without making the request there is no way of knowing the token for the next one.  
All the paginated results must be requested sequentially.

Probably you already did this, but in case you didn't, you can up the number of items per response.
For activities and people you can change it up to 100, comments up to 500.
