### ISSUE TITLE
Does python client support proxy?

### ISSUE THREAD

**Issue by Folyd** [googleapis/google-api-python-client#569]
Hello,  you know the google APIs are blocked in China, so we can only access these APIs by proxy, but I don't know whether the python client support proxy setup? If yes, please tell me how. If no, could you please add the proxy feature? Thanks!

However, I can set up a global proxy manually by this way, but it a global proxy, other requests would go through with the proxy, which is unnecessary.
```python
import socket
from httplib2 import socks
import google_auth_oauthlib.flow

Socks5 proxy
socket.socket = socks.socksocket
socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 1086)

flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
        CLIENT_SECRETS_FILE, scopes=SCOPES)
flow.authorization_url(
        # Enable offline access so that you can refresh an access token without
        # re-prompting the user for permission. Recommended for web server apps.
        access_type='offline',
        # Enable incremental authorization. Recommended as a best practice.
        include_granted_scopes='true')
```

Hope there is any better way to handle the issue. 😃

**Comment by dengjiuhong** [comment]
face same problem,
anyone have solutions?

**Comment by lidatou1991** [comment]
I can visit google.com ( with shadowsocks) while the request time out error is raised if I ping www.googleapis.com

**Comment by llinfeng** [comment]
@Folyd, thank you for posting your script! I use Jupyter notebook mostly, and the following snippet from your code helped a lot! For Jupyter notebooks, all interpreters for different notebooks are naturally separated from each other. Then, the solution that you are not satisfied with should work perfectly for Jupyter notebooks.

```
import socket
from httplib2 import socks
import google_auth_oauthlib.flow

#Socks5 proxy
socket.socket = socks.socksocket
socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 1086)
```

PS: more on setting things up for those who stumble into this page on **Setting up the Shadowsocks Client** on Windows 10 machine ==> just be careful when one first sets up the Shadowsocks client. In the same _Edit Server_ window, one get to choose which **Proxy Port** to enable. To reuse the code snippet above, one need to change the Proxy Port to 1086. The default Proxy Port is 1080.

I my use case, the code snippet worked with a normal Windows 10 Shadowsocks client and Jupyter notebooks hosted on a WSL session.

**Comment by chromafunk** [comment]
I used to proxy via IP chains while I was in China, worked great.

**Comment by busunkim96** [comment]
I think you could accomplish this by passing an `httplib2.http` object with the `proxy_info` parameter.

See https://httplib2.readthedocs.io/en/latest/libhttplib2.html?highlight=proxy#httplib2.Http and https://httplib2.readthedocs.io/en/latest/libhttplib2.html?highlight=proxy#httplib2.ProxyInfo

**Comment by parthea** [comment]
Hi @Folyd,

I'm going to close this issue as guidance was provided in [this comment](https://github.com/googleapis/google-api-python-client/issues/569#issuecomment-511488575). If you're still having trouble please re-open this issue with additional information.

**Comment by mostafaghadimi** [comment]
I'm not using shadowsocks, but have the exact same problem, I would thankful if anyone could help me.

I have read the following links, which tell us how to set the proxy on Google APIs:
- [setting proxy using httplib2shim](https://stackoverflow.com/a/45826806/7310077)
- [client api proxy](https://stackoverflow.com/questions/34768833/python-client-api-behind-proxy)
- [official repository for httplib2shim](https://github.com/GoogleCloudPlatform/httplib2shim)
- [google proxy support link](https://code.google.com/archive/p/gdatacopier/wikis/ProxySupport.wiki)
- [google-api-python-client repository](https://github.com/googleapis/google-api-python-client/issues/569)

My problem is different from the other questions, since I am using `ServiceAccountCredentials` method from `oauth2client.service_account` package. The authentication to the API key is done with json file. (also `ServiceAccountCredentials.from_json_keyfile_name` method). Whenever I want to request to the google service I want to pass it from http proxy server, unfortunately there isn't any rich documentation for this purpose on the web (or maybe I couldn't find them).

**ga_base_config.yml**

```
PROXY:
  proxy_user: '<proxy_user>'
  proxy_pass: '<proxy_password>'
  proxy_host: '<proxy_host>'
  proxy_port: <port_no>
```

**main.py**

```
class GA:
    def __init__(self, root_dir):
        with open(os.path.join(root_dir, 'config/ga_base_config.yml'), 'r') as yaml_file:
            try:
                self.yaml_file = yaml.safe_load(yaml_file)
                print(self.yaml_file)
            except yaml.YAMLError as exc:
                print(exc)

        self.scopes = self.yaml_file['URL']['scope']
        self.proxy_info = self.yaml_file['PROXY']

        self.key_file_location = os.path.join(root_dir, self.yaml_file['KEY_FILE'])

    def initialize_analytics_reporting(self):
        """Initializes an Analytics Reporting API V4 service object.

        Returns:
          An authorized Analytics Reporting API V4 service object.
        """
        credentials = ServiceAccountCredentials.from_json_keyfile_name(
            self.key_file_location,
            self.scopes,
        )
        proxy = httplib2shim.Http(self.proxy_info)
        credentials.authorize(http=proxy)
        analytics = build(
            'analyticsreporting',
            'v4',
            credentials=credentials,
        )
        return analytics
```

**Comment by cesarmsj** [comment]
> @Folyd, thank you for posting your script! I use Jupyter notebook mostly, and the following snippet from your code helped a lot! For Jupyter notebooks, all interpreters for different notebooks are naturally separated from each other. Then, the solution that you are not satisfied with should work perfectly for Jupyter notebooks.
> 
> ```
> import socket
> from httplib2 import socks
> import google_auth_oauthlib.flow
> 
> #Socks5 proxy
> socket.socket = socks.socksocket
> socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 1086)
> ```
> 
> PS: more on setting things up for those who stumble into this page on **Setting up the Shadowsocks Client** on Windows 10 machine ==> just be careful when one first sets up the Shadowsocks client. In the same _Edit Server_ window, one get to choose which **Proxy Port** to enable. To reuse the code snippet above, one need to change the Proxy Port to 1086. The default Proxy Port is 1080.
> 
> I my use case, the code snippet worked with a normal Windows 10 Shadowsocks client and Jupyter notebooks hosted on a WSL session.

I tried to use it that way, but on PFSense's Squid Proxy it's showing:

NONE/000 error:transaction-end-before-headers
