### ISSUE TITLE
Filename is blank when importing cost data .csv file via Management API 

### ISSUE THREAD

**Issue by gregroberts** [googleapis/google-api-python-client#571]
This was originally raised as an issue against Google Analytics itself:

https://issuetracker.google.com/issues/35353754

It was found there that the issue is with the api client stripping the filename from the POST body, so I'm raising this as an issue here, potentially to get a better response.

**Comment by LindaLawton** [comment]
This is a known issue with the API and not related to this library [Management API Cost Data Upload .csv Doesn't Have Filename](https://issuetracker.google.com/issues/35353754)   Its been tracked here for several years  [unable to assign a file name when uploading data by Analytics API](https://github.com/googleapis/google-api-dotnet-client/issues/1087)

I am not sure how you expect to get a better response by posting it around the different libraries.    Client library teams cant fix issues with underlining APIs.

**Comment by gregroberts** [comment]
I don't understand your point. 

The issue on Google states the problem is specifically related to client libraries stripping the filename from the POST body.  

The discussion includes an example of using the API directly to avoid the issue.

The issue is with the client library, and you state as much in the .NET library issue you linked to.

**Comment by busunkim96** [comment]
@gregroberts Do you by chance have a short sample? Were you using MediaFileUpload?

```
  media = MediaFileUpload('cow.png', mimetype='image/png',
    chunksize=1024*1024, resumable=True)
  farm.animals().insert(
      id='cow',
      name='cow.png',
      media_body=media).execute()

```

Some more information from the issue tracker issue:

- Method: https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/uploads/uploadData

**Comment by busunkim96** [comment]
There's a short sample [here](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/uploads/uploadData#examples), if you have not already seen it. 

```
# Note: This code assumes you have an authorized Analytics service object.
# See the Data Import Developer Guide for details.


# This request uploads a file custom_data.csv to a particular customDataSource.
# Note that this example makes use of the MediaFileUpload Object from the
# apiclient.http module.
from apiclient.http import MediaFileUpload
try:
  media = MediaFileUpload('custom_data.csv',
                          mimetype='application/octet-stream',
                          resumable=False)
  daily_upload = analytics.management().uploads().uploadData(
      accountId='123456',
      webPropertyId='UA-123456-1',
      customDataSourceId='9876654321',
      media_body=media).execute()

except TypeError, error:
  # Handle errors in constructing a query.
  print 'There was an error in constructing your query : %s' % error

except HttpError, error:
  # Handle API errors.
  print ('There was an API error : %s : %s' %
         (error.resp.status, error.resp.reason))
```

Currently working on reproducing.

**Comment by busunkim96** [comment]
Was able to reproduce 'Unknown Filename' result with following sample:
```
from __future__ import print_function
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from httplib2 import Http
from oauth2client import file, client, tools


# If modifying these scopes, delete the file token.json.
SCOPES = ["https://www.googleapis.com/auth/analytics"]


def main():
    """Upload custom data to Google Analytics.
    """
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    store = file.Storage("token.json")
    creds = store.get()
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets("credentials.json", SCOPES)
        creds = tools.run_flow(flow, store)
    service = build("analytics", "v3", http=creds.authorize(Http()))

    # Call the Analytics API
    media = MediaFileUpload(
        "data.csv", mimetype="application/octet-stream", resumable=False
    )
    upload = (
        service.management()
        .uploads()
        .uploadData(
            accountId="144017141",
            webPropertyId="UA-144017141-1",
            customDataSourceId="AbuL8x04Qg2L4flXypb1ag",
            media_body=media,
        )
        .execute()
    )

    print(upload)


if __name__ == "__main__":
    main()
```

**Comment by busunkim96** [comment]
from __future__ import print_function
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from httplib2 import Http
from oauth2client import file, client, tools


# If modifying these scopes, delete the file token.json.
SCOPES = ["https://www.googleapis.com/auth/analytics"]


def main():
    """Upload custom data to Google Analytics.
    """
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    store = file.Storage("token.json")
    creds = store.get()
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets("credentials.json", SCOPES)
        creds = tools.run_flow(flow, store)
    service = build("analytics", "v3", http=creds.authorize(Http()))

    # Call the Analytics API
    media = MediaFileUpload(
        "data.csv", mimetype="application/octet-stream", resumable=False
    )
    upload = (
        service.management()
        .uploads()
        .uploadData(
            accountId="144017141",
            webPropertyId="UA-144017141-1",
            customDataSourceId="AbuL8x04Qg2L4flXypb1ag",
            media_body=media,
        )
        .execute()
    )

    print(upload)


if __name__ == "__main__":
    main()

**Comment by LindaLawton** [comment]
This is a known issue in all of the Google client libraries as far as I know.  [Management API Cost Data Upload .csv Doesn't Have Filename](https://issuetracker.google.com/issues/35353754)

Its a consequence of the client libraries stripping the filename from POST body information

**Comment by gregroberts** [comment]
No longer have access to the codebase, but the code above is exactly what I was doing.

**Comment by alvarogomezuria** [comment]
This is still reproducible. Any workaround available?

**Comment by busunkim96** [comment]
@alvarogomezuria You can avoid this by talking to the REST API directly. See https://b.corp.google.com/issues/35353754#comment7

**Comment by alvarogomezuria** [comment]
Thanks for the heads up!
Rather not to talk to the REST API directly. I'll keep an eye here! Hopefully it will be resolved soon

**Comment by alvarogomezuria** [comment]
Sorry to insist, but i'd like to know if there is any updates/anyone working on this. 
Thanks in advance

**Comment by busunkim96** [comment]
Hi @alvarogomezuria. If you have a support contract with Google, please reach out that way for faster resolution. I opened another issue internally to ask the Analytics team about their discovery document. I don't think it is something we can fix on the client library side, unfortunately.

Internal issue 138960059

**Comment by ivanff** [comment]
A year passed, and the mistake remained.
Is it so difficult to test the code that Google develops

**Comment by busunkim96** [comment]
Closing this as there is no action that can be taken on the library side until the API surface itself is updated. Please reference https://issuetracker.google.com/issues/35353754 for status.
