### ISSUE TITLE
Google Plus API slow response times for large request due to max results of 20.

### ISSUE THREAD

**Issue by BoPengGit** [googleapis/google-api-python-client#572]
I'm trying to grab 200 Google Plus Activities posts for a dashboard I'm creating. But there is a max limit of 20 posts per request, and a next page token is given. Because I have to use the nextpagetoken from the previous response to make the next request, I'm not sure how I can make the requests in parallel. It takes about 1 second to get a response, so for 10 requests this is taking around 10 seconds, which is a very long time for a search result of a dashboard to load.

Do anybody have any suggestions?

Thanks!

**Comment by busunkim96** [comment]
Hi @BoPengGit,

There is an [optional query parameter](https://developers.google.com/+/web/api/rest/latest/activities/list ) called `maxResults` that defaults to 20. It can be set to values between 1 and 100 (inclusive). Try increasing the value; you should be able to get your 200 posts faster.
