### ISSUE TITLE
Regarding cloud print

### ISSUE THREAD

**Issue by sandguardian** [googleapis/google-api-python-client#574]
Hi,

I tried to use cloudprint in python with
`from googleapiclient.discovery import build`

But cannot find proper service name and version for cloud print on https://developers.google.com/api-client-library/python/apis/.

Anyone with samples to use cloud print in python?

Thanks

**Comment by busunkim96** [comment]
Hi @sandguardian,

Unfortunately, Cloud Print does not have client libraries. Here is the current [documentation ](https://developers.google.com/cloud-print/docs/appDevGuide)on interacting with the API. There are also some Python samples [here](https://developers.google.com/cloud-print/docs/pythonCode) on working with cloudprint, although they seem to be outdated.
