### ISSUE TITLE
Receive warnings "ResourceWarning: unclosed file" when using googleapiclient.http.MediaFileUpload

### ISSUE THREAD

**Issue by wangxf123456** [googleapis/google-api-python-client#575]
On google-api-python-client/googleapiclient/http.py:552, a file is opened. But this file is never closed. So I receive the following warning:

ResourceWarning: unclosed file <_io.BufferedReader name=<file_name> media_body = http.MediaFileUpload()

**Comment by busunkim96** [comment]
Hi @wangxf123456,

Thank you for reporting this! Would you be willing to submit a PR to fix it?

**Comment by wangxf123456** [comment]
Sure I can do this.
