### ISSUE TITLE
User does not have sufficient permissions for this profile

### ISSUE THREAD

**Issue by redhawk19** [googleapis/google-api-python-client#583]
Hi,

I am getting following error after giving site verification code, Please help to get rid of this issue. 
> Authentication successful.
> Arg, there was an API error : 403 : User does not have sufficient permissions for this profile

Secondly let me know how could i get current ActiveUsers details alongwith rt:deviceCategory.

Thank you!

**Comment by redhawk19** [comment]
Anyone please help me in order to find out the solution ?

**Comment by busunkim96** [comment]
Hello! Would you be able to provide us with some more details by filling out this form? 


#### Environment details

  - OS:
  - Python version:
  - pip version:
  - `google-api-python-client` version:

#### Steps to reproduce

  1. ?
  2. ?

**Comment by LindaLawton** [comment]
>403 : User does not have sufficient permissions for this profile

Is an error message form the Google analytics real-time API.  This message has nothing to do with the Python library.  The user you are logging in with must have access to the profile that you are trying to request data from.   In the event you are requesting data using a service account.   Remember that it needs to be pre approved.  Go to the google analytics website add the service account email address as a user grant it read access at the account level and it will be about to access the data.
