### ISSUE TITLE
cache should handle appengine memcache 1000000 bytes limitation

### ISSUE THREAD

**Issue by benamar** [googleapis/google-api-python-client#586]
discovery_cache is crashing with exception
ValueError: Values may not be more than 1000000 bytes in length; received 1544709 bytes

perhap's multi_set cache keys should be used?

**Comment by benamar** [comment]
Can some one give some help please,
I find a fix to overcome the limitation, create a branch and a pull request, but as you may guess, it says I need reviewers to merge it, unfortunately I don't see how to find or add a reviewer?

**Comment by sduskis** [comment]
@googleapis/yoshi-python or @busunkim96, can someone help with this issue?

**Comment by busunkim96** [comment]
See #588.

**Comment by SurferJeffAtGoogle** [comment]
https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/appengine_memcache.py is specifically designed for caching discovery documents.  Is there a discovery document greater than 1 MB?

**Comment by busunkim96** [comment]
Memcache is an API specific to AppEngine Standard Python 2, and the public docs actively encourage folks to [move to Python 3](https://cloud.google.com/appengine/docs/standard/python/refdocs/google.appengine.api.memcache). 

It looks like compute is the only API to exceed the 1MB limit. 

```
compute:alpha 2634264
compute:beta 2318325
compute:v1 2050938
```

The next largest APIs are around .6 MB.
```
dfareporting:v3.3 611532
dfareporting:v3.4 621106
drive:v2.1beta 572228
```

Given the limited impact I am opting to close this issue. If you're running into issues with caching, I'd recommend disabling the cache, or storing the desired discovery document in datastore and using `build_from_document`.

**Disabling caching:**
```py
from googleapiclient import discovery

client = discovery.build("compute", "alpha", cache_discovery=False)
```

**[`build_from_document`](https://github.com/googleapis/google-api-python-client/blob/1a754ffd1a3281f7c7039de197c8b379149a6839/googleapiclient/discovery.py#L298)**
```py
from googeapiclient import discovery

discovery_doc = ""  # store doc as string in database
client = discovery.build_from_document(discovery_doc)
```
