### ISSUE TITLE
drive api - get all files not share with me

### ISSUE THREAD

**Issue by VikramTiwari** [googleapis/google-api-python-client#595]
No matter which sample query parameter I use, I can't seem to files which are just mine. Query response always includes files which are shared with me.

  - OS: OSX
  - Python version: 3.7.0
  - pip version: 18.1
  - `google-api-python-client` version: 1.7.4

Queries that I have tried:
- `q: "not sharedWithMe"`
- `q: "!sharedWithMe"`
- `q: "sharedWithMe=false"`
- `q: "sharedWithMe!=true"`
- `q: "sharedWithMe not"`

Either I get the error
```
{
    "errorCode": 400,
    "error": [
        {
            "domain": "global",
            "reason": "invalid",
            "message": "Invalid Value",
            "locationType": "parameter",
            "location": "q"
        }
    ]
}
```

or the response contains shared files. Seems like an issue with the upstream API itself.

docs: https://developers.google.com/drive/api/v3/search-parameters

**Comment by busunkim96** [comment]
Hi @VikramTiwari,

This is the intended behavior, and a bug has been filed for updating the documentation. If you are looking for files that you own (were not shared with you by someone else) `q: 'me' in owners` should work. If you have additional questions, please let us know. 

Thanks!
