### ISSUE TITLE
__file__ is None

### ISSUE THREAD

**Issue by shakna-israel** [googleapis/google-api-python-client#604]
#### Environment details

  - OS: CentOS 7
  - Python version: 3.7.1
  - pip version: 10.0.1
  - `google-api-python-client` version: 1.7.4

#### Steps to reproduce

```python
 for name, module in sys.modules.items():
     if getattr(module, '__file__', '') is None:
         print("Module with broken __file__: ", name)
```

```
> Module with broken __file__: google
```

> __file__ is optional. If set, this attribute’s value must be a string. The import system may opt to leave __file__ unset if it has no semantic meaning (e.g. a module loaded from a database). [Source](https://docs.python.org/3/reference/import.html#__file__)

```__file__``` being a ```None``` is a bit unexpected, and causes a problem with one of my dependencies.

**Comment by tseaver** [comment]
Trying to reproduce:

```bash
$ python3.7 -m venv /tmp/gapic/604
$ /tmp/gapic/604/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-18.1 setuptools-40.6.3 wheel-0.32.3
$ /tmp/gapic/604/bin/pip install google-api-python-client==1.7.4
...
Installing collected packages: httplib2, uritemplate, pyasn1, rsa, six, cachetools, pyasn1-modules, google-auth, google-auth-httplib2, google-api-python-client
Successfully installed cachetools-3.0.0 google-api-python-client-1.7.4 google-auth-1.6.1 google-auth-httplib2-0.0.3 httplib2-0.12.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 rsa-4.0 six-1.12.0 uritemplate-3.0.0
$ /tmp/gapic/604/bin/python -c "import google; print(google.__file__); print(google.__path__)"
None
_NamespacePath(['/tmp/gapic/604/lib/python3.7/site-packages/google'])
$ ls -F /tmp/gapic/604/lib/python3.7/site-packages/google
auth/  oauth2/
```

Note that there is no `__init__.py` installed:  Python is inferring the package's existence here, via [PEP 420](https://www.python.org/dev/peps/pep-0420).  See the [PyPA guide to namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/).
