### ISSUE TITLE
Possible invalid request generated by client

### ISSUE THREAD

**Issue by littlebenlittle** [googleapis/google-api-python-client#608]
It appears the client is generating an invalid request. I'm not sure if this is an issue with the client itself or with the endpoint. I have also opened a [stackoverflow question](https://stackoverflow.com/questions/53917186/python-client-for-compute-engine-returns-required-field-resource-not-specifie).

#### Environment details

  - OS: Ubuntu 18.04
  - Python version: 3.6.7
  - pip version: pip3 9.0.1
  - `google-api-python-client` version: 1.7.4

#### Steps to reproduce

    from apiclient.discovery import build
    
    compute = build('compute', 'v1')
    cmd = compute.instances().insert(
        project='my-project'
        zone='us-central1-c',
        body=config)
    cmd.execute()
    
    HttpError: <HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-c/instances?alt=json
    returned "Required field 'resource' not specified">

`config` is a json string conforming to [the specification in the documentation](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert#request-body).

**Comment by busunkim96** [comment]
Hi @littlebenlittle. 

I'm able to get the same error by passing an empty config: 
```
from googleapiclient.discovery import build

compute = build('compute', 'v1')
config = {}

cmd = compute.instances().insert(
    project='my-project-1',
    zone='us-central1-c',
    body={})
cmd.execute()
```
I was also able to create an instance with the config you provided in your stackoverflow question. 

```
from googleapiclient.discovery import build

compute = build('compute', 'v1')
config = {
  "name": "my-instance",
  "machineType": "zones/us-central1-c/machineTypes/n1-standard-1",
 
  "disks": [
      {
          "boot": "True",
          "autoDelete": "True",
          "initializeParams": {
              "sourceImage": "https://www.googleapis.com/compute/v1/projects/gce-uefi-images/global/images/ubuntu-1804-bionic-v20181203a"
          }
      }
  ],
 
  "networkInterfaces": [{
      "network": "global/networks/default",
      "accessConfigs": [
          {"type": "ONE_TO_ONE_NAT", "name": "External NAT"}
      ]
  }],
 
  "serviceAccounts": [{
      "email": "default",
      "scopes": [
            "https://www.googleapis.com/auth/devstorage.read_only",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring.write",
            "https://www.googleapis.com/auth/servicecontrol",
            "https://www.googleapis.com/auth/service.management.readonly",
            "https://www.googleapis.com/auth/trace.append"
      ]
  }],
 
  "metadata": {
      "items": [{
          "key": "startup-script-uri",
          "value": "gs://my-bucket/my-startup.sh"
      }]
  }
}
cmd = compute.instances().insert(
    project='admin-sdk-224423',
    zone='us-central1-c',
    body=config)
cmd.execute()
```
Can you take a look to make sure `config` is being defined correctly? If you haven't looked at it already [this script](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/compute/api/create_instance.py) shows how to create a Compute Engine instance.

**Comment by littlebenlittle** [comment]
It looks I was sending a string as `config` instead of a dict and that was causing the problem.

**Comment by tseaver** [comment]
@littlebenlittle Glad you've found a resolution!

**Comment by VinayKadalagi** [comment]
>  config = {
        'name': "test-instance"
    }
    compute.instances().insert(
        project=GCP_PROJECT,
        zone=ZONE,
        body=config,
        sourceInstanceTemplate="global/instanceTemplates/instance-template-1").execute()

Working code which might help someone

**Comment by busunkim96** [comment]
@VinayKadalagi If you're experiencing a problem please open a new issue with more details. Thanks!
