### ISSUE TITLE
There is no documentation how to sign URL for GCS with your new client

### ISSUE THREAD

**Issue by symonsoft** [googleapis/google-api-python-client#609]
Please provide documentation on how I can create signed URL with new client.

**Comment by tseaver** [comment]
@symonsoft Just for clarity, is the "new" client you are referring to the one provided by the `google-cloud-storage` package?  If so, that package is maintained in a [different repository](https://github.com/googleapis/google-cloud-python/), and its docs are at https://googleapis.github.io/google-cloud-python/latest/storage/ (see particularly the [docs for `Blob.generate_signed_url`](https://googleapis.github.io/google-cloud-python/latest/storage/blobs.html#google.cloud.storage.blob.Blob.generate_signed_url)).

**Comment by symonsoft** [comment]
Found the solution. Came here for help because several manuals were referencing to this project
