### ISSUE TITLE
Add _iter methods as an improvement upon _next methods

### ISSUE THREAD

**Issue by bmccutchon** [googleapis/google-api-python-client#610]
**Is your feature request related to a problem? Please describe.**
When working with APIs whose results span multiple pages (using `pageToken`), this long-winded and potentially error-prone pattern occurs:
```python
req = some_api.list()
while req:
  page = req.execute()
  # Do something with page
  req = some_api.list_next(previous_request=req, previous_response=page)
```
 **Describe the solution you'd like**
In addition to generating `_next` methods (done [here](https://github.com/googleapis/google-api-python-client/blob/9d779cc2497e12cf23695b57b45d35bdf1ae9d91/googleapiclient/discovery.py#L1063)), add `_iter` methods that return an iterator over the pages. Then, the idiom would be reduced to:
```python
for page in some_api.list_iter():
  # Do something with page
```
 **Describe alternatives you've considered**
Some APIs return pages that look like `{"nextPageToken": [token], "items": [A list of items]}` (for example, the Cloud Deployment Manager API's [`deployments().list()`](https://developers.google.com/resources/api-libraries/documentation/deploymentmanager/v2/python/latest/deploymentmanager_v2.deployments.html#list)). For those, if the proposal above is implemented, the pattern might look like this:
```python
for page in some_api.list_iter():
  for item in page["items"]:
    # Do something with item
```
In this case, it would be even more convenient to return an iterator over the individual items rather than the pages, skipping the `page` variable above (that is, changing the return type of `_iter`):
```python
for item in some_api.list_iter():
  # Do something with item
```
However, this is only a little more convenient and may not be possible for all APIs using `pageToken`.

**Comment by busunkim96** [comment]
@bmccutchon thank you for filing an issue! I am opting to close this as this library is in maintenance mode and it's not likely that we would actually implement this.

(From README.md)
> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.
