### ISSUE TITLE
How can I retrieve more than 100 results per query

### ISSUE THREAD

**Issue by AsserAboElkhair** [googleapis/google-api-python-client#615]
When I use [`CSE: list`](https://developers.google.com/custom-search/v1/cse/list) I get an error when I set parameter `num=11` or more, I need to retrieve 1,000 results, so I read about `start=number_of_starting_page` but that also limit my search to 100 and that's in not enough, how can I increase this number?

**Comment by busunkim96** [comment]
Hi @AsserAboElkhair, the max # of results a limitation imposed by the CSE API, so there's nothing we can do on the client library side.

Please look into contacting the CSE team directly: https://developers.google.com/custom-search/docs/support
