### ISSUE TITLE
Calendar API: Don't get `items` in events().list() incremental sync response if event is `all day`.

### ISSUE THREAD

**Issue by trojek** [googleapis/google-api-python-client#623]
#### Environment details

  - OS: Ubuntu 18.10
  - Python version: 3.7.1
  - pip version: I use pipenv
  - `google-api-python-client` version: 1.7.8

#### Steps to reproduce

1. Start watch calendar 
`cal_API.events().watch(calendarId=cal_id, body=settings).execute()`

Correct situation:
2. Add new event (via web browser calendar app) with **date and time**. 
I get Google Calendar API push notification, then execute: 
`cal_API.events().list(calendarId=cal_id, syncToken=sync_token).execute()`
In response I get an object with `items` key and value which containes added event.

Incorrect situation:
3.  Add new event (via web browser calendar app) only with **date**. 
I get Google Calendar API push notification, then execute: 
`cal_API.events().list(calendarId=cal_id, syncToken=sync_token).execute()`
In response I get an object with `items` key with empy value.

I think that this is a bug in the Google Calendar API. There is one more situation: If I create an event with **date and time** and get information about it via notification channel and then I update it to the event only with **date** I get information about it. Then If I updated previously updated event to have **date and time** I don't get information about the changes (but as previously I get a notification).

**Comment by busunkim96** [comment]
Hi @trojek, would you be able to provide a code snippet that shows the issue?

**Comment by trojek** [comment]
Hi @busunkim96. What do you mean by the code which shows the issue? The way how I consume data from the notification URL is provided in the problem description. When I get a hit from google I make a call to API: `cal_API.events().list(calendarId=cal_id, syncToken=sync_token).execute()` and I get response as in documentation: https://developers.google.com/calendar/v3/reference/events/list but the `items` list is empty in case if I added or modify event which is `all-day` (don't have `dateTime` field).
I assume that there could be some problem with the way how I store the `sync token` but I do it the same way regardless if I add an event with time or not.

**Comment by trojek** [comment]
I found where was the problem. If your scope: 'role' is 'freeBusyReader' (in ACL while getting access to calendar) you will not see any information about events without time. This is a bug related to Google Calendar API, not Python library.

**Comment by WixoLeo** [comment]
So is there a fix for this? the role is set to "See All Event Details" yet I still don't get the all-day events
