### ISSUE TITLE
Expose bearer token generation

### ISSUE THREAD

**Issue by andyljones** [googleapis/google-api-python-client#624]
Working with the GCP the past few days, I've found twice that I need to get my own bearer token to use services loosely connected to the main API. The first time was [connecting to Kubernetes inside a GKE cluster](https://stackoverflow.com/questions/54410410/authenticating-to-gke-master-in-python/54621644#54621644), and the second time was using the [Docker registry API](https://cloud.google.com/container-registry/docs/advanced-authentication#access_token) for the Container Registry. I've ended up writing this little function to get me the token I need:

```python
def token(*scopes):
    credentials = googleapiclient._auth.default_credentials()
    scopes = [f'https://www.googleapis.com/auth/{s}' for s in scopes]
    scoped = googleapiclient._auth.with_scopes(credentials, scopes)
    googleapiclient._auth.refresh_credentials(scoped)
    return scoped.token
```

but the use of the private `_auth` field means it could break any time you update this repo. So, questions:

  * Is there any better way to get a bearer token from whatever credentials googleapiclient has lying around?
  * If not, could you expose something like `_auth` publicly so I don't have to use a private field to get the token?

Thanks!

**Comment by busunkim96** [comment]
Hello @andyljones,

Please take a look at [google-auth](https://google-auth.readthedocs.io/en/latest/user-guide.html), the Google authentication library for Python.

**Comment by andyljones** [comment]
Aha, thanks very much!
