### ISSUE TITLE
thread safe or not?

### ISSUE THREAD

**Issue by frankwaltz** [googleapis/google-api-python-client#626]
contra to #568 (only a few months old now), I am _not_ having a problem with thread safety with the following pseudocode:

```
from googleapiclient.discovery import build
from google.oauth2 import service_account
from threading import Thread

def threaded(...):
  cred = service_account.Credentials.from_service_account_file(f, scopes=scopes)
  cred = cred.with_subject(subject)

  service = build('drive', 'v3', credentials=cred)
  request = service.files().list(...)
  response = service.execute()
```

I was reading https://developers.google.com/api-client-library/python/guide/thread_safety which claims this won't work, that I need to pass a thread-specific http instance to build() or execute(). However when I follow either approach (custom requestBuilder, or call execute() with a new http), my credentials are ignored and execute() runs without creds at all. This gets a 403 "Daily Limit for Unauthenticated Use Exceeded.".

If I diverge slightly from that doc and manually pass an http instance to `build()`, ie `build(..., http=httplib2.Http())`, I get `ValueError: Arguments http and credentials are mutually exclusive.`.

This led me to https://github.com/googleapis/google-auth-library-python/issues/190#issuecomment-391328728 so I instrumented `googleapiclient/http.py:build_http()` and verified that because each thread uses its own `google.oauth2.service_account.Credentials` object, each thread also gets its own thread-specific `httplib2.Http` object. Thus, my simple code above that does not explicitly instantiate an `httplib2.Http` object, is indeed thread-safe (to the extent thread-unsafety is limited to httplib2).

**Can someone confirm my understanding?**

If this is correct, then

- https://developers.google.com/api-client-library/python/guide/thread_safety is in error. Wouldn't most uses of the API require credentials and thus the simplest fix is to use a thread-specific credentials object? At the minimum the page should be updated to note that thread-specific  credentials are a fine solution.

- the docstring for `discovery.py:build()` should be updated to reflect that credentials can also be a `google.oauth2.service_account.Credentials` object (in addition the the other 2 types mentioned).

Lastly I'll note that the APIs used in #568 are different than what I'm using. In that issue, the reporter is using `apiclient.discovery.build` and `oauth2client.service_account` whereas I am using `oogleapiclient.discovery.build` and `google.oauth2.service_account`. Yet he reported the issues to this repo so I don't know how closely those APIs are related.

**Comment by Chronial** [comment]
Your code does not contain any threading, so you question is not quite clear. Are you starting threads that run `threaded`? That is expected to work – it's sharing the `service` object across threads that's not safe.

**Comment by frankwaltz** [comment]
ok got it. I now also grok the bit in the docs that one should `override construction of [the http instance] within the service object`.

**Comment by hongquan** [comment]
Tried using this API client in multi-thread environment and the program crashed, so I confirmed that it is not thread-safe.

I have to call `build()` in each thread, so that each thread has its own api client object, to fix the crash.

**Comment by iCodeCoolStuff** [comment]
@hongquan does doing this result in an actual performance increase over using a single build instance on a single thread?

**Comment by hongquan** [comment]
@iCodeCoolStuff Yes, using it in multi-threaded way let your app calls more API requests in a same time window -> Quicker done the job.

But please note that Google API has quota, so make sure to not let your number of requests exceed that quota.
