### ISSUE TITLE
KeyError: 'path' intermittent error

### ISSUE THREAD

**Issue by ivan-aguirre** [googleapis/google-api-python-client#630]
We've been facing an intermittent error when trying to use oauth2 services. It was working fine until we deployed a new version on GAE. Notice that we haven't changed anything related to this code or the google libraries versions.

That's the exception:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./route/auth.py", line 37, in google_auth_callback
    user = service.userinfo().get().execute()
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 1121, in methodResource
    schema=schema)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 1026, in __init__
    self._set_service_methods()
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 1061, in _set_service_methods
    self._add_basic_methods(self._resourceDesc, self._rootDesc, self._schema)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 1091, in _add_basic_methods
    methodName, methodDesc, rootDesc, schema)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 712, in createMethod
    maxSize, mediaPathUrl) = _fix_up_method_description(methodDesc, rootDesc, schema)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 580, in _fix_up_method_description
    path_url = method_desc['path']
KeyError: 'path'
```
#### Environment details

  - OS: Google App Engine Flexible, `debian:stretch-slim` docker image
  - Python version: 2.7.15
  - pip version: 19.0.3
 - versions:
`google-api-core`==1.6.0
`google-api-python-client`==1.7.7
`google-auth`==1.6.1
`google-auth-httplib2`==0.0.3

#### Steps to reproduce

That's the code, the error raises from `service.userinfo().get().execute()` .
The error is intermittent and I haven't figured out an specific scenario.

```python
import httplib2
from googleapiclient.discovery import build
from oauth2client.client import AccessTokenCredentials

credentials = AccessTokenCredentials(<SOME ACCESS TOKEN>,
                                         user_agent=str(request.user_agent))
http = httplib2.Http()
http = credentials.authorize(http)

service = build("oauth2", "v2", http=http, developerKey=<MY API KEY>)

user = service.userinfo().get().execute()

**Comment by ngandhy** [comment]
Just started getting this myself. Looks like Google is slowly releasing a breaking change

**Comment by AdeyinkaAdegbenro** [comment]
This is happening to me too!

**Comment by ivan-aguirre** [comment]
@ngandhy @AdeyinkaAdegbenro 

Which version you are using?

**Comment by seyisulu** [comment]
@ivan-aguirre 

This started with version 1.6.2. An upgrade to the latest version 1.7.8 did not solve it.
We first noticed this on a staging project on GAE but now the error happens on our production instance.

**Comment by ngandhy** [comment]
@ivan-aguirre 
google-api-python-client==1.7.4
google-auth==1.6.1
google-auth-httplib2==0.0.3

Any luck figuring it out? Seems to be intermittent

**Comment by salvador-bynd** [comment]
Having the same issue!

**Comment by salvador-bynd** [comment]
Clearing the App engine memcache solved the issue.
Will keep an eye on it.

**Comment by ngandhy** [comment]
is everyone getting it on service.userinfo().get().execute() ?

**Comment by yuri-wisestamp** [comment]
Clearing app engine cache fixed it for me. Are we expected to have more of this breaking awesomeness any time soon?

**Comment by ivan-aguirre** [comment]
That's interesting, my application does not use GAE's memcache.
It may be used by some internal GAE stuff...

**Comment by ngandhy** [comment]
@yuri-wisestamp - considering @ivan-aguirre and I don't use Appengine, I'm assuming it'll kick up again at some point and def seems to be cache related. 

I've tried multiple solutions that help for a bit but starts erroring again within 12-24 hours (again possibly pointing to a cache issue).

The most promising solution that has worked for a few days now was to create my own cache instead of using the built in discovery cache.

`class RedisGoogleDiscoveryCache(googleapiclient.discovery_cache.base.Cache):
    def get(self, url):
		rc = redis_conn.get('RDGC:%s' % url)
		if rc:
			return json.loads(rc)
		return None

    def set(self, url, content):
		if content:
			redis_conn.set('RDGC2:%s' % url, json.dumps(content))

def _get_google_client(refresh_token, library, version):
	credentials = _get_http_credentials(refresh_token)
	return discovery.build(library, version=version, credentials=credentials, cache=RedisGoogleDiscoveryCache()) 

`
Hope this helps some of you!

**Comment by ivan-aguirre** [comment]
@ngandhy, in fact I use app engine flexible but I don't directly use memcache services from my code.

**Comment by busunkim96** [comment]
Are any of you folks still encountering this? Does it only occur with the OAuth2 API, or have you seen this happen with other APIs?

**Comment by yuri-wisestamp** [comment]
Happened to me just now.
App Engine Standard, Python 2.7

**Comment by yuri-wisestamp** [comment]
@busunkim96 
Happened to me just now.
App Engine Standard, Python 2.7

**Comment by busunkim96** [comment]
Closing as this seems to have resolved itself.

If you are experiencing this problem, please open a [new issue](https://github.com/googleapis/google-api-python-client/issues/new/choose) referencing this one. Thanks!
