### ISSUE TITLE
Cannot insert ACL rule for some domains

### ISSUE THREAD

**Issue by treethought** [googleapis/google-api-python-client#634]
#### Environment details

  - OS: MacOs
  - Python version: 2.7
  - pip version: 19.0.3
  - `google-api-python-client` version: 1.7.8

#### Steps to reproduce

  1. Authenticate with service account setup for delegated domain wide authority
  2. Create delegated credentials (either with oauth2client or google-auth - I've tried both)
  3. Insert new ACL rule for a given calendar resource with role: reader and scope type: domain

There are three total domains that I am trying to insert a new ACL rule for across 2 different calendar resources.

Calendar resource A (belongs to domain_a.com) should gain the following rules:
   - reader role for domain_b  -> successful
   - reader role for domain_c  -> 404

Calendar resource B (belongs to domain_b) should gain the following rules:
  - reader role for domain_a -> successful
  - reader role for domain_c  -> 404

I have even tried this using the API explorer for my completely separate personal calendar without any service accounts and I am able to add domain_a and domain_b as ACL rules, but not domain_c.

The response is 404 Not found. Can anyone provide some insight on why I might be getting 404? The resources definitely exist as I am able to insert new rules for some domains and list the current ACL rules.

**Comment by busunkim96** [comment]
Hello,

If I understand correctly, domain_a and domain_b are able to gain access to each other's calendars, and domain_c is not? Is there anything different about domain_c?

I do see one note about G Suite domains in the Calendar API documentation that may be impacting you:

https://developers.google.com/calendar/concepts/sharing
> For G Suite users, there are also domain settings that might restrict the maximum allowed access. For example, suppose your domain has a setting that only allows free-busy calendar sharing. In this case, even if you grant writer access to the public, users outside the domain will only see the free-busy details.

**Comment by treethought** [comment]
Thanks for the response @busunkim96.

Not quite, it's not only that domain_c is not able to access the calendars. It's that I cannot add a new `type: domain` `role:reader` ACL rule with `value:domain_c` for any calendar at all.

The issue is that I am trying to insert the ACL rule applying to calendar resources in both domain_a and domain_b and I get a 404 when _creating the rule_.

To be clear:
- I AM able to insert a new ACL rule on domain_a/domain_b calendar resources for _other_ domains that are NOT `value:domain_c`

- I am NOT able to insert a new ACL rule with `value:domain_c` on **any** calendar resource (a/b or other test calendars)

This leads me to believe there is something wrong when the API attempts to grant access to domain_c, though I don't know why the response would be 404

**Comment by busunkim96** [comment]
@treethought Sorry for the delay! 

This looks like an issue with the underlying API, not the client library. I'm not sure what's special about `domain_c` from the info you've provided, but the calendar team should be able to help you debug this further.

https://developers.google.com/calendar/support
