### ISSUE TITLE
Site restricted custom search

### ISSUE THREAD

**Issue by fasilpv** [googleapis/google-api-python-client#635]
Hi there,

Is it possible to invoke site restricted custom search api (https://developers.google.com/custom-search/v1/site_restricted_api) using google-api-python-client? If so, please let me know how to do that?

**Comment by busunkim96** [comment]
Hi fasilpv, 

It looks like this is possible. Please take a look at the documentation: https://developers.google.com/resources/api-libraries/documentation/customsearch/v1/python/latest/customsearch_v1.cse.siterestrict.html

**Comment by bob0the0mighty** [comment]
The documentation says it's possible, but there doesn't appear to be any supporting source.

**Comment by busunkim96** [comment]
@bob0the0mighty Are you looking for a sample showing something in particular?

**Comment by bob0the0mighty** [comment]
I didn't realize it works when calling as the documentation states.

**Comment by busunkim96** [comment]
Alright, please feel free to open another issue if the API isn't responding as expected. Thanks!

**Comment by 2legit** [comment]
Hi, can you let me know how I would be able to navigate from the CSE site, i.e. https://developers.google.com/custom-search/ to the page linked to above? I.e. https://developers.google.com/resources/api-libraries/documentation/customsearch/v1/python/latest/customsearch_v1.cse.siterestrict.html? I've gone through the former without ever comping across any mention of the latter. In this case it would've been helpful to know that cse() has not just the list() method but also a siterestrict() that can be called to use the siterestricted API.

Lastly, is there any indication from the response that I'm indeed using the restricted mode? As far as I can tell, the exact same response comes back from cse().list() as does cse().siterestrict().list().  Other than I guess checking in the GCP console but I assume there's probably a better/easier way?

Thanks!

**Comment by busunkim96** [comment]
@2legit Thank you for the feedback! We've moved around our documentation, so now it lives in this repo. This is roughly the path you'd follow to get from the  Custom Search API documentation to the reference documentation for Python.

* https://developers.google.com/custom-search/v1/libraries ("Libraries and Samples" on the left). 
* this repository
* docs/README 
* ref docs by API https://github.com/googleapis/google-api-python-client/blob/master/docs/dyn/index.md
* custom search docs: http://googleapis.github.io/google-api-python-client/docs/dyn/customsearch_v1.html


Here's what I found in the API documentation about restricted search. If this doesn't answer your question, please reach out to [Custom Search support](https://developers.google.com/custom-search/docs/support).

https://developers.google.com/custom-search/v1/site_restricted_api
> About the Custom Search Site Restricted JSON API
> If your Custom Search Engine is restricted to only searching specific sites (10 or fewer), you can use the Custom Search Site Restricted JSON API. This API is similar to the Custom Search JSON API except this version has no daily query limit. To use this version, confirm that you see 10 or fewer sites to search in the “Sites to Search” section of your Custom Search Engine control panel, the are no global top level domain patterns, and that “Search the entire web” is set to OFF.
> 
> When using the Custom Search Site Restricted JSON API endpoint, be mindful that if your Custom Search Engine configuration is changed so that it does not conform with the site restriction rules above, the Custom Search Site Restricted JSON API may not return the expected results.
>

**Comment by enerai** [comment]
> Hi there,
> 
> Is it possible to invoke site restricted custom search api (https://developers.google.com/custom-search/v1/site_restricted_api) using google-api-python-client? If so, please let me know how to do that?

Sure. You can do it.
Two reference: 
https://stackoverflow.com/questions/37083058/programmatically-searching-google-in-python-using-custom-search
http://googleapis.github.io/google-api-python-client/docs/dyn/customsearch_v1.cse.html

The first link tells how you can use the Python API; the second link tells that which method of the service objective you can use for restricted google custom search.

Code sample:
```
service = build("customsearch", "v1", developerKey=<your_api_key>)

res = service.cse().siterestrict().list(
    q=query_word,
    cx=<your_custom_search_id>,
).execute()
```

**Comment by whatsananne** [comment]
> > Hi there,
> > Is it possible to invoke site restricted custom search api (https://developers.google.com/custom-search/v1/site_restricted_api) using google-api-python-client? If so, please let me know how to do that?
> 
> Sure. You can do it.
> Two reference:
> https://stackoverflow.com/questions/37083058/programmatically-searching-google-in-python-using-custom-search
> http://googleapis.github.io/google-api-python-client/docs/dyn/customsearch_v1.cse.html
> 
> The first link tells how you can use the Python API; the second link tells that which method of the service objective you can use for restricted google custom search.
> 
> Code sample:
> 
> ```
> service = build("customsearch", "v1", developerKey=<your_api_key>)
> 
> res = service.cse().siterestrict().list(
>     q=query_word,
>     cx=<your_custom_search_id>,
> ).execute()
> ```

Hi,
When using something very similar to that code sample, I keep receiving:
```
    res = service.cse().siterestrict().list(
AttributeError: 'Resource' object has no attribute 'siterestrict'
```
I do not receive this error all of the time, but most. Without `siterestrict()`, I do not receive this error at all. Is there any reason why?

To run a restricted search, is it necessary to include this command, or is it sufficient to have 10 or fewer sites in the "Sites to Search" section, and the "Search the entire web" option set to OFF.

Thanks

**Comment by busunkim96** [comment]
@whatsananne Please open a new issue with your question. It's easier for repo maintainers to keep track of open issues. Thanks!
