### ISSUE TITLE
Can't catch 400 errors

### ISSUE THREAD

**Issue by VikramTiwari** [googleapis/google-api-python-client#636]
#### Environment details

  - OS: Ubuntu
  - Python version: 3.7
  - pip version: 19.0.3
  - `google-api-python-client` version: 1.7.7

![Screen Shot 2019-03-18 at 9 05 22 PM](https://user-images.githubusercontent.com/1330677/54579661-c2f71800-49c1-11e9-9e31-ceb7dc1847fd.png)
Here's a screenshot of metrics dashboard for google sheets. You can see that most requests are fine with 200 but a few of them are 404 and 429s. When I see 429 error happen here in console, I can see it being thrown in the my code and thus I can catch it.

But I haven't been able to see where these 404s are happening thus haven't been able to catch them at all! Is there something I am missing?

code is as simple as:
```
try:
    sheet_data = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range=str(tab_metadata['name']),
        majorDimension='ROWS').execute()
except Exception as e:
    print(e)
```

**Comment by VikramTiwari** [comment]
I was able to catch 404s but still unable to catch `400` errors.

**Comment by busunkim96** [comment]
Hi,

You mention 404s and 429s in your original post and 400s in your second one. Just to clarify, you're able to catch 404s and 429s, but unable to catch 400s?

**Comment by VikramTiwari** [comment]
Yes! Sorry, updated the issue to reflect that. I still can't catch 400 errors though.

**Comment by busunkim96** [comment]
The library is setup to retry certain errors:
* 5xx
* 429
* 403s (that are about rate limits specifically)
* SSL errors
* Socket timeouts
* specific socket errors (WSAETIMEDOUT', 'ETIMEDOUT', 'EPIPE', 'ECONNABORTED')
* httplib2.ServerNotFound

https://github.com/googleapis/google-api-python-client/blob/d43e0ffbc82aaf59a9d81d777ea7da80d2d53260/googleapiclient/http.py#L85-L191
So it's possible for an error code to show up on the console that doesn't raise an exception in your code.

But if something isn't on that list, status codes >= 300 should raise `googleapliclient.errors.HttpError`.
https://github.com/googleapis/google-api-python-client/blob/d43e0ffbc82aaf59a9d81d777ea7da80d2d53260/googleapiclient/http.py#L855-L857

Were you seeing `400` responses in the console? I don't see them in your original screenshot. Was there anything else you could see? Log statements, for instance?

**Comment by VikramTiwari** [comment]
Hey @busunkim96 thanks for the follow up. I don't have that code with me now. I was seeing the errors being logged on the cloud console. If I run into it again, I will reopen the issue.
