### ISSUE TITLE
Return all OrderId using Google Play Developer API

### ISSUE THREAD

**Issue by EmiCarrizo** [googleapis/google-api-python-client#637]
Hello, I am trying to manage subscriptions made by the In-App Billing API. Right now i want to retrieve all orders, just like it can be seen in the google play console. 
I can get the last orderId, using the token to get subcription info:
```
def get_credential():
    # Getting the credentials...
    return credentials

def get_google_payment(token):
    credential = get_credential()
    service = build("androidpublisher", "v3", credentials=credential)
    request = service.purchases().subscriptions().get(packageName="com.company.app", token=token, subscriptionId='subId')
    response = request.execute()
    return json.dumps(response)  # A JSON with all subcription info is returned
```
My question is, there's a method to get ALL orderIds, or am i using the only way the get them?

**Comment by busunkim96** [comment]
Hi @EmiCarrizo. google-api-python-client generates libraries based off the discovery document. [reference docs](https://developers.google.com/android-publisher/api-ref/#Purchases.subscriptions) and [discovery document](https://developers.google.com/android-publisher/api-ref/#Purchases.subscriptions).  It looks like the API doesn't have a method for getting all orders, so it won't be possible with the client library.

I'm looking into the right place to direct your question.

**Comment by busunkim96** [comment]
@EmiCarrizo, questions with the Google Play Developer API are best directed to the [Google Play developer support](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en). Please reach out to them with your question. Thanks!
