### ISSUE TITLE
Stopping VM instance in object destructor raises exception:  ssl.SSLError: Underlying socket connection gone

### ISSUE THREAD

**Issue by skebanga** [googleapis/google-api-python-client#640]
I have a simple class `Test` below which starts a Google Compute Engine VM and then stops it by either calling a function (**explicit**), or relying on object destruction, via `__del__` (**implicit**).

    class Test:
        def __init__(self):
            os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'secret.json'
            self._compute = googleapiclient.discovery.build('compute',
                                                            'v1',
                                                            cache_discovery=False)
            print('starting vm')
            req = self._compute.instances().start(project='test-project',
                                                  zone='us-east1-b',
                                                  instance='test-vm',
                                                  requestId=uuid.uuid1())
            self.execute(req)
            self._running = True
    
        def stop(self):
            print('stopping vm')
            req = self._compute.instances().stop(project='test-project',
                                                 zone='us-east1-b',
                                                 instance='test-vm',
                                                 requestId=uuid.uuid1())
            self.execute(req)
            self._running = False
    
        def execute(self, req):
            print(f'method({req.methodId})')
            resp = req.execute()
            while resp['status'] != 'DONE':
                time.sleep(1)
                resp = req.execute()
            return resp
    
        def __del__(self):
            if self._running:
                print('stopping in destructor')
                self.stop()
    
The `Test` class is interacted with as follows:

    if __name__ == '__main__':
        print('start test')
        t = Test()
    
        print('vm running, wait 5 seconds')
        time.sleep(5)
    
        if len(sys.argv) == 2 and sys.argv[1] == 'stop':
            t.stop()
    
        print('test done')

When using the **explicit** method (ie: calling `t.stop()` **before** the object starts being destructed), the VM stops fine:

    $ ./test.py stop
    start test
    starting vm
    method(compute.instances.start)
    vm running, wait 5 seconds
    stopping vm
    method(compute.instances.stop)
    test done

However, when using the **implicit** method (ie: relying on `t` going out of scope, and having `Test::__del__` called), I get an exception thrown from within the `googleapiclient` stack:

    $ ./test.py 
    start test
    starting vm
    method(compute.instances.start)
    vm running, wait 5 seconds
    test done
    stopping in destructor
    stopping vm
    method(compute.instances.stop)
    Exception ignored in: <bound method Test.__del__ of <__main__.Test object at 0x7fe091720320>>
    Traceback (most recent call last):
      File "./test.py", line 46, in __del__
      File "./test.py", line 32, in stop
      File "./test.py", line 37, in execute
      File "/src/test/.venv/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
      File "/src/test/.venv/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
      File "/src/test/.venv/lib/python3.6/site-packages/googleapiclient/http.py", line 183, in _retry_request
      File "/src/test/.venv/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
      File "/src/test/.venv/lib/python3.6/site-packages/google_auth_httplib2.py", line 198, in request
      File "/src/test/.venv/lib/python3.6/site-packages/httplib2/__init__.py", line 1926, in request
      File "/src/test/.venv/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
      File "/src/test/.venv/lib/python3.6/site-packages/httplib2/__init__.py", line 1502, in _conn_request
      File "/usr/lib/python3.6/http/client.py", line 1239, in request
      File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
      File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
      File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
      File "/usr/lib/python3.6/http/client.py", line 986, in send
      File "/usr/lib/python3.6/ssl.py", line 975, in sendall
      File "/usr/lib/python3.6/ssl.py", line 944, in send
      File "/usr/lib/python3.6/ssl.py", line 642, in write
    ssl.SSLError: Underlying socket connection gone (_ssl.c:2067)

#### Environment details

  - OS: Ubuntu 18.04
  - Python version: 3.6
  - pip version: 19.0.3
  - `google-api-python-client` version: 1.7.8

**Comment by busunkim96** [comment]
I think you might be running into this:

> `__del__()` can be executed during interpreter shutdown. As a consequence, the global variables it needs to access (including other modules) may already have been deleted or set to None. Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the `__del__()` method is called.

https://docs.python.org/3/reference/datamodel.html#object.__del__

You can make sure the compute resources get cleaned up consistently by using a context manager. Here is a modification of the code you provided above with `__enter__` and `__exit__` methods. I don't have much experience with context managers, so please read the [official documentation](https://docs.python.org/3/library/stdtypes.html#typecontextmanager) if you go this route. :smiley: 


```python
import os
import uuid
import time

from googleapiclient import discovery

class Test:
    def __init__(self):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "secret.json"
        self._compute = discovery.build("compute", "v1", cache_discovery=False)

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print("stopping in __exit__")
        self.stop()

    def start(self):
        print("starting vm")
        req = self._compute.instances().start(
            project="test-project",
            zone="us-east1-b",
            instance="test-vm",
            requestId=uuid.uuid1(),
        )
        self.execute(req)
        self._running = True

    def stop(self):
        print("stopping vm")
        req = self._compute.instances().stop(
            project="test-project",
            zone="us-east1-b",
            instance="test-vm",
            requestId=uuid.uuid1(),
        )
        self.execute(req)
        self._running = False

    def execute(self, req):
        print(f"method({req.methodId})")
        resp = req.execute()
        while resp["status"] != "DONE":
            time.sleep(1)
            resp = req.execute()
        return resp


if __name__ == "__main__":
    with Test() as t:
        print("vm running, wait 5 seconds")
        time.sleep(5)

    print("test done")
```

```
$ python3 make-vm.py
starting vm
method(compute.instances.start)
vm running, wait 5 seconds
stopping vm
method(compute.instances.stop)
stopping in __exit__
stopping vm
method(compute.instances.stop)
test done
```

Apologies for the long delay here, but hopefully this is useful to someone.

**Comment by skebanga** [comment]
@busunkim96 thank you for this - very useful!
