### ISSUE TITLE
Add "preview accept all" when downloading documents using export_media(fileId=doc_id, mimeType=type)

### ISSUE THREAD

**Issue by adam-ah** [googleapis/google-api-python-client#642]
**Feature request**

I'm using the official Google Drive Python API to download Google Documents using the following command:

```
export_media(fileId=doc_id, mimeType='text/plain')
```
It works well, although I have two problems:

- The downloaded documents show the document _before_ all recommended changes
- The comments are added at the end of the document in a [a]...[b]... format.

Feature request:

Add a flag to ```export_media``` so I can define what view of the document I'd like to download: all changes accepted, all changes rejected, with comments, without comments.

**Comment by busunkim96** [comment]
Hi @adam-ah, thank you for filing an issue! I'm opting to close this as it's unlikely we will implement it in the future. 

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.

**Comment by adam-ah** [comment]
That's fine if you don't want to implement this @busunkim96, but could you help me to understand whether the API itself supports this or not, irrespective of the python client? I presume the API itself is still an active project?
