### ISSUE TITLE
Django Sample project missing

### ISSUE THREAD

**Issue by ferrucc-io** [googleapis/google-api-python-client#648]
This sample link is broken:
https://github.com/googleapis/google-api-python-client/blob/master/samples/django_sample

Is there a Django sample project or it's still a work in progress?

If there is one consider fixing the link in this page: 
https://github.com/googleapis/google-api-python-client/blob/master/samples/README.md

**Comment by busunkim96** [comment]
We've removed the Django sample. I will remove the link in the README, thank you!
