### ISSUE TITLE
Getting all calendars of organisation users 

### ISSUE THREAD

**Issue by shilomagen** [googleapis/google-api-python-client#649]
Hi,
I'm trying to figure out if as an organisation admin I can get all my users calendar and meeting.
Is it possible? Could not find any documentation for it.

Thanks!

**Comment by busunkim96** [comment]
Hi @shilomagen, you would want to use a service account with domain-wide delegation. There is a bit about that in the Calendar API documentation: https://developers.google.com/calendar/concepts/domain#accessing_domain_calendars_as_an_app

**Comment by shilomagen** [comment]
Thank you @busunkim96 !
