### ISSUE TITLE
Special header required to update deployments in deployment manager.

### ISSUE THREAD

**Issue by bchess** [googleapis/google-api-python-client#654]
#### Environment details

  - OS: MacOS 10.14.4
  - Python version: 3.7.3
  - pip version: 19.1.1
  - `google-api-python-client` version: 1.7.8

#### Steps to reproduce

I originally filed support case # 19148710. In that case, the Deployment Manager team confirmed this issue and the tech asked me to file an issue here.

I'm attempting to add a new label to an existing deployment:

```
service = build('deploymentmanager', 'v2')
deployment_get_response = service.deployments().get(project=project, deployment=deployment_name).execute()
labels = deployment_get_response.get('labels', [])
labels.append({'key': 'new-label', 'value': 'new-value'})
body = {
        'name': deployment_name,
        'labels': labels,
        'description': deployment_get_response['description'],
        'fingerprint': deployment_get_response['fingerprint']
    }
service.deployments().update(
        project=project,
        deployment=deployment_name,
        body=body
).execute()
````
The update() call results in an HTTP 400 `"Invalid value for field 'resource.target': ''.  Deployment must have a target with UPDATE if it is not already in preview."`

I can recreate this same error when using the "Try this API" at the API reference page at https://cloud.google.com/deployment-manager/docs/reference/latest/deployments/update

Interestingly, the gcloud CLI tool works when I do this:
`gcloud deployments update my-deployment --update-labels new-label=new-value`

Looking into the HTTP logs, it appears that the gcloud command includes an additional header `X-Cloud-DM-Patch: True` which is not included when using the python API nor the "Try this API" page on the API references.

If I inject this header myself, the call runs successfully. Currently there's no documentation about this header, though you'll see it is used in https://github.com/google-cloud-sdk/google-cloud-sdk/blob/5514f695e0f3068d72f6ee7ee0de57e89aa259d1/lib/surface/deployment_manager/deployments/update.py#L285. In case #191418710, the team confirmed that the header is required.

**Comment by busunkim96** [comment]
Hi @bchess. This library is in maintenance mode, so we will fix critical bugs and security issues but will not add new features. 

It sounds like overriding the header is working for you. I also checked this issue internally and it looks like there is work to update the documentation.

Closing this out for now, but let us know if you have any other concerns.
