### ISSUE TITLE
google contact duplicated entries // query

### ISSUE THREAD

**Issue by eloiup** [googleapis/google-api-python-client#668]
Hi!

I am using this API to edit & create contacts at **Google Contacts**.

So far I am able to:

Retrieve N contacts.
Create a contact.

However when I create a contact, if the contact is already in the base, it creates a duplicated contact.
I would like to avoid that.

I can remove duplicated contacts through the GUI. However that is not ideal.

Is there any way to prevent to create a contact if duplicated?
I see google generates a random unique ID for the contact when its created, would I be able to specify a custom ID?
Else, can I query a contact by a meta information, such as name/phonenumber? That way I could avoid creating a new contact if it already exists.

I tried looking for such examples on this git, stackoverflow, google documentation, but failed to. It seems like a common enough use of the API, unsure why these arent on the official docs.

I appreciate any help or references,

Ty.

**Comment by busunkim96** [comment]
Hi @eloiup! Any idea if this happens only when you use the Python library? In that case, it might be a bug with our API. If it happens with direct HTTP requests, this question is probably better suited for someone who works on the Google Contacts API.

**Comment by tseaver** [comment]
@eloiup Does the duplication happen if you use e.g., `curl` to create a contact, following the [Contacts API doc](https://developers.google.com/contacts/v3/#creating_contacts)?

**Comment by busunkim96** [comment]
@eloiup  There are currently no ways to prevent a duplicate contact from being created.

You can use the People API to query contacts based on different parameters like phone number. [documentation](https://developers.google.com/people/api/rest/v1/people/get)

> Note: For read and write access to users' contacts, use the People API, which provides both contact and profile information using JSON instead of the older GData protocol.

**Comment by eloiup** [comment]
@busunkim96 @tseaver only tried with the python library

if i do the same insert command twice it creates two identical entries except by the unique id which is generated by google.

```
token_path = 'token.pickle'

if os.path.exists(token_path):
    with open(token_path, 'rb') as token:
        creds = pickle.load(token)

service = build('people', 'v1', credentials=creds)

body = create_input_json()

service.people().createContact(body=body).execute()
```

results in a new entry where

`... 'source': {'type': 'CONTACT', 'id': '*ID*}}, ...`

ID is auto generated.

It would be useful if the api user cld specify the unique ID, which would overwrite old contact information or prevent duplicated entries.

**Comment by eloiup** [comment]
> @eloiup There are currently no ways to prevent a duplicate contact from being created.
> 
> You can use the People API to query contacts based on different parameters like phone number. [documentation](https://developers.google.com/people/api/rest/v1/people/get)
> 
> > Note: For read and write access to users' contacts, use the People API, which provides both contact and profile information using JSON instead of the older GData protocol.

thank you.

Is there a python example/reference on such requests/queries?

**Comment by busunkim96** [comment]
It looks like I was mistaken. Querying in the People API has been requested but is not yet implemented. [see issue](https://b.corp.google.com/issues/73864682)

The Contacts API supports querying by parameters, but the list of query parameters is limited. [link](https://developers.google.com/contacts/v3/#retrieving_contacts_using_query_parameters)

Please put in a feature request to the Contacts API team if this is of interest:
https://b.corp.google.com/issues?q=componentid:344199%20status:open&s=modified_time:desc
