### ISSUE TITLE
DevSite Import: Using OAuth 2.0 for Installed Applications

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-python-client#679]
Notice: This DevSite page will soon be deleted per [b/133171590](http://b/133171590). Please add this sample to GitHub if it is relevant still:

https://developers.google.com/api-client-library/python/auth/installed-app

---

# DevSite Import: Using OAuth 2.0 for Installed Applications

<div class="devsite-article-body clearfix
            " itemprop="articleBody">
    

<section>

<p>The Google APIs Client Library for Python supports using OAuth 2.0 in applications that are
installed on a device such as a computer, a cell phone, or a tablet. Installed
apps are distributed to individual machines, and it is assumed that these apps
cannot keep secrets. These apps might access a Google API while the user is
present at the app, or when the app is running in the background.</p>
<figure id="fig1">
  <img src="https://developers.google.com/accounts/images/device-auth-decision-installedapp.png" style="float:right" width="340px" height="355px" alt="If you are developing for Android or iOS, use Google+ Sign-In.">
</figure>
<p>This document is for you if:</p>
<ul>
  <li>You are writing an installed app for a platform other than Android or iOS,
      and</li>
  <li>Your installed app will run on devices that have a system browser and rich
      input capabilities, such as devices with full keyboards.</li>
</ul>
<p>If you are writing an app for Android or iOS, use <a href="https://developers.google.com/identity">Google
Sign-In</a> to authenticate your users. The Google Sign-In button manages the
OAuth 2.0 flow both for authentication and for obtaining authorization to Google
APIs. To add the Google Sign-In button, follow the
steps for <a href="https://developers.google.com/identity/sign-in/android">Android</a> or
<a href="https://developers.google.com/identity/sign-in/ios">iOS</a>.</p>
<p>If your app will run on devices that do not have access to a system browser,
or devices with limited input capabilities (for example, if your app will run on
game consoles, video cameras, or printers), then see
<a href="https://developers.google.com/accounts/docs/OAuth2ForDevices">Using OAuth 2.0 for Devices</a>.</p>

</section>

<section>

<ol class="toc">
  <li><a href="#overview">Overview</a></li>
  <li><a href="#creatingcred">Creating application credentials</a></li>
  <li><a href="#creatingclient">Configuring the client object</a>
      <ul>
        <li><a href="#choosingredirecturi">Choosing a redirect URI</a></li>
      </ul>
  </li>
  <li><a href="#sendingtogoogle">Sending users to to Google's OAuth 2.0 server</a></li>
  <li><a href="#handlingresponse">Handling the OAuth 2.0 server response</a></li>
  <li><a href="#callinganapi">Calling Google APIs</a></li>
  <li><a href="#example">Complete example</a></li>
</ol>

</section>

<section>

<h2 id="overview"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Overview</h2>
<p>To use OAuth 2.0 in a locally-installed application, first create application
credentials for your project in the API Console.</p>

<p>Then, when your application needs to access a user's data with a Google API,
your application sends the user to Google's OAuth 2.0 server. The OAuth 2.0
server authenticates the user and obtains consent from the user for your
application to access the user's data.</p>

<p>Next, Google's OAuth 2.0 server sends a single-use authorization code to your
application, either in the title bar of the browser or in the query string of an
HTTP request to the local host. Your application exchanges this authorization
code for an access token.</p>

<p>Finally, your application can use the access token to call Google APIs.</p>

<p>This flow is similar to the one shown in the <a href="https://developers.google.com/api-client-library/python/auth/web-app">Using
OAuth 2.0 for Web Server Applications</a>, but with three differences:</p>
<ul>
  <li>When creating a client ID, you specify that your application is an
      Installed application. This results in a different value for the
      <code>redirect_uri</code> parameter.</li>
  <li>The client ID and client secret obtained from the API Console
      are embedded in the source code of your application. In this context, the
      client secret is obviously not treated as a secret.</li>
  <li>The authorization code can be returned to your application in the title
      bar of the browser or in the query string of an HTTP request to the local
      host.</li>
</ul>

</section>

<section>

<h2 id="creatingcred"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Creating application credentials</h2>
<p>All applications that use OAuth 2.0 must have credentials that identify the
application to the OAuth 2.0 server. Applications that have these credentials
can access the APIs that you enabled for your project.</p>
<p>To obtain application credentials for your project, complete these steps:</p>
<ol>
  

  <li>Open the <a href="https://console.developers.google.com/apis/credentials">Credentials page</a> in the API Console.</li>

  <li>If you haven't done so already, create your OAuth 2.0 credentials by
      clicking <b>Create new Client ID</b> under the <b>OAuth</b> heading and
      selecting the <b>Installed application</b> type. Next, look for your
      application's client ID and client secret in the relevant table.</li>
</ol>
<p>Download the client_secrets.json file and securely store it in a location
that only your application can access.</p>
<aside class="note"><b>Important:</b> Do not store the client_secrets.json file
in a publicly-accessible location, and if you share the source code to your
application—for example, on GitHub—store the client_secrets.json
file outside of your source tree to avoid inadvertently sharing your client
credentials.</aside>

</section>

<section>

<h2 id="creatingclient"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Configuring the client object</h2>
<p>Use the client application credentials that you created to configure a client
object in your application. When you configure a client object, you specify the
scopes your application needs to access, along with a redirect URI, which will
handle the response from the OAuth 2.0 server.</p>

<section>
<h3 id="choosingredirecturi">Choosing a redirect URI</h3>
<p>When you create a client ID in the
<a href="https://console.developers.google.com/">Google API Console</a>, two
<code>redirect_uri</code> parameters are created for you:
<code>urn:ietf:wg:oauth:2.0:oob</code> and <code>http://localhost</code>. The
value your application uses determines how the authorization code is returned to
your application.</p>

<h4>http://localhost</h4>
<p>This value signals to the Google Authorization Server that the authorization
code should be returned as a query string parameter to the web server on the
client. You can specify a port number without changing the
<a href="https://console.developers.google.com/">Google API Console</a> configuration. To receive the
authorization code using this URI, your application must be listening on the
local web server. This is possible on many, but not all, platforms. If your
platform supports it, this is the recommended mechanism for obtaining the
authorization code.</p>
<p class="note"><b>Note</b>: In some cases, although it is possible to listen,
other software (such as a Windows firewall) prevents delivery of the message
without significant client configuration.</p>

<h4>urn:ietf:wg:oauth:2.0:oob</h4>
<p>This value signals to the Google Authorization Server that the authorization
code should be returned in the title bar of the browser, with the page text
prompting the user to copy the code and paste it in the application. This is
useful when the client (such as a Windows application) cannot listen on an HTTP
port without significant client configuration.</p>
<p>When you use this value, your application can then detect that the page has
loaded, and can read the title of the HTML page to obtain the authorization
code. It is then up to your application to close the browser window if you want
to ensure that the user never sees the page that contains the authorization
code. The mechanism for doing this varies from platform to platform.</p>
<p>If your platform doesn't allow you to detect that the page has loaded or read
the title of the page, you can have the user paste the code back to your
application, as prompted by the text in the confirmation page that the OAuth 2.0
server generates.</p>

<h4>urn:ietf:wg:oauth:2.0:oob:auto </h4>
<p>This is identical to urn:ietf:wg:oauth:2.0:oob, but the text in the
confirmation page that the OAuth 2.0 server generates won't instruct the user to
copy the authorization code, but instead will simply ask the user to close the
window.</p>
<p>This is useful when your application reads the title of the HTML page (by
checking window titles on the desktop, for example) to obtain the authorization
code, but can't close the page on its own.</p>
</section>

<h3 id="creating-the-object">Creating the object</h3>

<p>To create a client object from the client_secrets.json file, use the
<code>flow_from_clientsecrets</code> function. For example, to request
read-only access to a user's Google Drive:</p>
<pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="kwd">from</span><span class="pln"> google_auth_oauthlib</span><span class="pun">.</span><span class="pln">flow </span><span class="kwd">import</span><span class="pln"> </span><span class="typ">InstalledAppFlow</span><span class="pln"><br><br>flow </span><span class="pun">=</span><span class="pln"> </span><span class="typ">InstalledAppFlow</span><span class="pun">.</span><span class="pln">from_client_secrets_file</span><span class="pun">(</span><span class="pln"><br>&nbsp; &nbsp; </span><span class="str">'client_secret.json'</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; scopes</span><span class="pun">=[</span><span class="str">'https://www.googleapis.com/auth/drive.metadata.readonly'</span><span class="pun">])</span></pre>

<p>Your application uses the client object to perform OAuth 2.0 operations, such
as generating authorization request URIs and applying access tokens to HTTP
requests.</p>

</section>

<section>

<h2 id="sendingtogoogle"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Sending users to Google's OAuth 2.0 server</h2>
<p>Use either the <code>run_console</code> or <code>run_local_server</code>
   function to direct the user to Google's OAuth 2.0 server:</p>

<ul>
  <li>
    <p>The <code>run_console</code> function instructs the user to open
       the authorization URL in their browser. After the user authorizes
       the application, the authorization server displays a web page with
       an authorization code, which the user then pastes into the
       application. The authorization library automatically exchanges the
       code for an access token.</p>
    <pre><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div></div>credentials = flow.run_console()</pre>
  </li>
  <li>
    <p>The <code>run_local_server</code> function attempts to open the
       authorization URL in the user's browser. It also starts a local
       web server to listen for the authorization response. After the user
       completes the auth flow, the authorization server redirects the user's
       browser to the local web server. That server gets the authorization
       code from the browser and shuts down, then exchanges the code for
       an access token.</p>
    <pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="pln">credentials </span><span class="pun">=</span><span class="pln"> flow</span><span class="pun">.</span><span class="pln">run_local_server</span><span class="pun">(</span><span class="pln">host</span><span class="pun">=</span><span class="str">'localhost'</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; port</span><span class="pun">=</span><span class="lit">8080</span><span class="pun">,</span><span class="pln"> <br>&nbsp; &nbsp; authorization_prompt_message</span><span class="pun">=</span><span class="str">'Please visit this URL: {url}'</span><span class="pun">,</span><span class="pln"> <br>&nbsp; &nbsp; success_message</span><span class="pun">=</span><span class="str">'The auth flow is complete; you may close this window.'</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; open_browser</span><span class="pun">=</span><span class="kwd">True</span><span class="pun">)</span></pre>
  </li>
</ul>

<p>Google's OAuth 2.0 server authenticates the user and obtains consent from
   the user for your application to access the requested scopes.</p>

</section>

<section>

</section>

<section>

<h2 id="callinganapi"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Calling Google APIs</h2>

<p>Use the authorized <code>Http</code> object to call Google APIs by
completing the following steps:</p>
<ol>
  <li>Build a service object for the API that you want to call. You build a
      a service object by calling the <code>build</code> function with the
      name and version of the API and the authorized <code>Http</code>
      object. For example, to call version 2 of the Drive API:
      <pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="kwd">from</span><span class="pln"> googleapiclient</span><span class="pun">.</span><span class="pln">discovery </span><span class="kwd">import</span><span class="pln"> build<br><br>drive_service </span><span class="pun">=</span><span class="pln"> build</span><span class="pun">(</span><span class="str">'drive'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'v3'</span><span class="pun">,</span><span class="pln"> credentials</span><span class="pun">=</span><span class="pln">credentials</span><span class="pun">)</span></pre></li>
  <li>Make requests to the API service using the
  <a href="https://developers.google.com/api-client-library/python/start/get_started#build">interface
  provided by the service object</a>. For example, to list the files in the
  authenticated user's Google Drive:
  <pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="pln">files </span><span class="pun">=</span><span class="pln"> drive_service</span><span class="pun">.</span><span class="pln">files</span><span class="pun">().</span><span class="pln">list</span><span class="pun">().</span><span class="pln">execute</span><span class="pun">()</span></pre>
  </li>
</ol>

</section>

<section>

<h2 id="example"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Complete example</h2>
<p>The following example requests access to the user's Google Drive files.
   If the user grants access, the code retrieves and prints a JSON-formatted
   list of the five Drive files that were most recently modified by the user.
</p>
<pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="kwd">import</span><span class="pln"> os<br></span><span class="kwd">import</span><span class="pln"> pprint<br><br></span><span class="kwd">import</span><span class="pln"> google</span><span class="pun">.</span><span class="pln">oauth2</span><span class="pun">.</span><span class="pln">credentials<br><br></span><span class="kwd">from</span><span class="pln"> googleapiclient</span><span class="pun">.</span><span class="pln">discovery </span><span class="kwd">import</span><span class="pln"> build<br></span><span class="kwd">from</span><span class="pln"> googleapiclient</span><span class="pun">.</span><span class="pln">errors </span><span class="kwd">import</span><span class="pln"> </span><span class="typ">HttpError</span><span class="pln"><br></span><span class="kwd">from</span><span class="pln"> google_auth_oauthlib</span><span class="pun">.</span><span class="pln">flow </span><span class="kwd">import</span><span class="pln"> </span><span class="typ">InstalledAppFlow</span><span class="pln"><br><br>pp </span><span class="pun">=</span><span class="pln"> pprint</span><span class="pun">.</span><span class="typ">PrettyPrinter</span><span class="pun">(</span><span class="pln">indent</span><span class="pun">=</span><span class="lit">2</span><span class="pun">)</span><span class="pln"><br><br></span><span class="com"># The CLIENT_SECRETS_FILE variable specifies the name of a file that contains</span><span class="pln"><br></span><span class="com"># the OAuth 2.0 information for this application, including its client_id and</span><span class="pln"><br></span><span class="com"># client_secret.</span><span class="pln"><br>CLIENT_SECRETS_FILE </span><span class="pun">=</span><span class="pln"> </span><span class="str">"client_secret.json"</span><span class="pln"><br><br></span><span class="com"># This access scope grants read-only access to the authenticated user's Drive</span><span class="pln"><br></span><span class="com"># account.</span><span class="pln"><br>SCOPES </span><span class="pun">=</span><span class="pln"> </span><span class="pun">[</span><span class="str">'https://www.googleapis.com/auth/drive.metadata.readonly'</span><span class="pun">]</span><span class="pln"><br>API_SERVICE_NAME </span><span class="pun">=</span><span class="pln"> </span><span class="str">'drive'</span><span class="pln"><br>API_VERSION </span><span class="pun">=</span><span class="pln"> </span><span class="str">'v3'</span><span class="pln"><br><br></span><span class="kwd">def</span><span class="pln"> get_authenticated_service</span><span class="pun">():</span><span class="pln"><br>&nbsp; flow </span><span class="pun">=</span><span class="pln"> </span><span class="typ">InstalledAppFlow</span><span class="pun">.</span><span class="pln">from_client_secrets_file</span><span class="pun">(</span><span class="pln">CLIENT_SECRETS_FILE</span><span class="pun">,</span><span class="pln"> SCOPES</span><span class="pun">)</span><span class="pln"><br>&nbsp; credentials </span><span class="pun">=</span><span class="pln"> flow</span><span class="pun">.</span><span class="pln">run_console</span><span class="pun">()</span><span class="pln"><br>&nbsp; </span><span class="kwd">return</span><span class="pln"> build</span><span class="pun">(</span><span class="pln">API_SERVICE_NAME</span><span class="pun">,</span><span class="pln"> API_VERSION</span><span class="pun">,</span><span class="pln"> credentials </span><span class="pun">=</span><span class="pln"> credentials</span><span class="pun">)</span><span class="pln"><br><br></span><span class="kwd">def</span><span class="pln"> list_drive_files</span><span class="pun">(</span><span class="pln">service</span><span class="pun">,</span><span class="pln"> </span><span class="pun">**</span><span class="pln">kwargs</span><span class="pun">):</span><span class="pln"><br>&nbsp; results </span><span class="pun">=</span><span class="pln"> service</span><span class="pun">.</span><span class="pln">files</span><span class="pun">().</span><span class="pln">list</span><span class="pun">(</span><span class="pln"><br>&nbsp; &nbsp; </span><span class="pun">**</span><span class="pln">kwargs<br>&nbsp; </span><span class="pun">).</span><span class="pln">execute</span><span class="pun">()</span><span class="pln"><br><br>&nbsp; pp</span><span class="pun">.</span><span class="pln">pprint</span><span class="pun">(</span><span class="pln">results</span><span class="pun">)</span><span class="pln"><br><br></span><span class="kwd">if</span><span class="pln"> __name__ </span><span class="pun">==</span><span class="pln"> </span><span class="str">'__main__'</span><span class="pun">:</span><span class="pln"><br>&nbsp; </span><span class="com"># When running locally, disable OAuthlib's HTTPs verification. When</span><span class="pln"><br>&nbsp; </span><span class="com"># running in production *do not* leave this option enabled.</span><span class="pln"><br>&nbsp; os</span><span class="pun">.</span><span class="pln">environ</span><span class="pun">[</span><span class="str">'OAUTHLIB_INSECURE_TRANSPORT'</span><span class="pun">]</span><span class="pln"> </span><span class="pun">=</span><span class="pln"> </span><span class="str">'1'</span><span class="pln"><br>&nbsp; service </span><span class="pun">=</span><span class="pln"> get_authenticated_service</span><span class="pun">()</span><span class="pln"><br>&nbsp; list_drive_files</span><span class="pun">(</span><span class="pln">service</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;orderBy</span><span class="pun">=</span><span class="str">'modifiedByMeTime desc'</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;pageSize</span><span class="pun">=</span><span class="lit">5</span><span class="pun">)</span></pre>

</section>

  </div>

**Comment by grant** [comment]
The docs are now added to the `docs/` folder.
Fixed with #706.

**Comment by davidsansome** [comment]
The docstrings in `flow.py` still links to https://developers.google.com/api-client-library/python/auth/installed-app and need to be updated to point to `docs/oauth-installed.md`
