### ISSUE TITLE
DevSite Import: Client Secrets

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-python-client#681]
Notice: This DevSite page will soon be deleted per [b/133171590](http://b/133171590). Please add this sample to GitHub if it is relevant still:

https://developers.google.com/api-client-library/python/guide/aaa_client_secrets

---

## Client Secrets

<div class="devsite-article-body clearfix
            " itemprop="articleBody">
    

<section>
  <p>
    The Google APIs Client Library for Python uses the
    client_secrets.json file format for storing the
    <code>client_id</code>, <code>client_secret</code>, and other OAuth 2.0 parameters.
  </p>
</section>

<section id="client_secrets">
  <p>
    The client_secrets.json
    file format is a <a href="http://www.json.org/">JSON</a> formatted file
    containing the client ID, client secret, and other OAuth 2.0 parameters.
    Here is an example client_secrets.json file for a web application:
  </p>
  <pre><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div></div>{
  "web": {
    "client_id": "asdfjasdljfasdkjf",
    "client_secret": "1912308409123890",
    "redirect_uris": ["https://www.example.com/oauth2callback"],
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token"
  }
}</pre>
  <p>
    Here is an example client_secrets.json file for an installed application:
  </p>
  <pre><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div></div>{
  "installed": {
    "client_id": "837647042410-75ifg...usercontent.com",
    "client_secret":"asdlkfjaskd",
    "redirect_uris": ["http://localhost", "urn:ietf:wg:oauth:2.0:oob"],
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token"
  }
}</pre>
  <p>
    The format defines one of two client ID types:
  </p>
  <ul>
    <li><code>web</code>: Web application.</li>
    <li><code>installed</code>: Installed application.</li>
  </ul>
  <p>
    The <code>web</code> and <code>installed</code> sub-objects have the following mandatory members:
  </p>
  <ul>
    <li>
      <code>client_id</code> (string):
      The client ID.
    </li>
    <li>
      <code>client_secret</code> (string):
      The client secret.
    </li>
    <li>
      <code>redirect_uris</code> (list of strings):
      A list of valid redirection endpoint URIs.
      This list should match the list entered for the client ID on the
      <a href="https://code.google.com/apis/console#:access">API Access pane</a>
      of the Google APIs Console.
    </li>
    <li>
      <code>auth_uri</code> (string):
      The authorization server endpoint URI.
    </li>
    <li>
      <code>token_uri</code> (string):
      The token server endpoint URI.
    </li>
  </ul>

  <p>All of the above members are mandatory. The following optional parameters may appear:</p>

  <ul>
    <li> <code>client_email</code> (string) The service account email associated with the client. </li>
    <li> <code>auth_provider_x509_cert_url</code> (string) The URL of the public x509 certificate, used to verify the signature on JWTs, such as ID tokens, signed by the authentication provider. </li>
    <li> <code>client_x509_cert_url</code> (string) The URL of the public x509 certificate, used to verify JWTs signed by the client. </li>
  </ul>

  <p>
    The following examples show how use a <b>client_secrets.json</b> file
    to create a <code>Flow</code> object in either an installed application
    or a web application:
  </p>
  <section class="kd-tabbed-horz ui-datasection-main" id="client-secret-examples"><div class="kd-buttonbar kd-tabbar-horz"><header class="kd-tabbutton selected" kd-data-id=":Installed app" aria-label="Installed app, selected" role="button" tabindex="0" data-ds-scope="code">Installed app</header><header class="kd-tabbutton" kd-data-id=":Web server app" aria-label="Web server app" role="button" tabindex="0" data-ds-scope="code">Web server app</header><a class="devsite-overflow-menu-button kd-tabbutton" style="display: none;">More</a></div><article class="selected">
      
    <pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="kwd">from</span><span class="pln"> google_auth_oauthlib</span><span class="pun">.</span><span class="pln">flow </span><span class="kwd">import</span><span class="pln"> </span><span class="typ">InstalledAppFlow</span><span class="pln"><br></span><span class="pun">...</span><span class="pln"><br>flow </span><span class="pun">=</span><span class="pln"> </span><span class="typ">InstalledAppFlow</span><span class="pun">.</span><span class="pln">from_client_secrets_file</span><span class="pun">(</span><span class="pln"><br>&nbsp; &nbsp; </span><span class="str">'</span><em><span class="str">path_to_directory</span></em><span class="str">/client_secret.json'</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; scopes</span><span class="pun">=[</span><span class="str">'https://www.googleapis.com/auth/calendar'</span><span class="pun">])</span></pre>
    </article><article>
      
    <pre class="prettyprint"><div class="devsite-code-button-wrapper"><div class="devsite-code-button gc-analytics-event material-icons devsite-dark-code-button" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Dark code theme" aria-label="Dark code theme" data-title="Dark code theme"></div><div class="devsite-code-button gc-analytics-event material-icons devsite-click-to-copy-button" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" tabindex="0" role="button" data-tooltip-align="b,c" data-tooltip="Click to copy" aria-label="Click to copy" data-title="Click to copy"></div></div><span class="kwd">import</span><span class="pln"> google</span><span class="pun">.</span><span class="pln">oauth2</span><span class="pun">.</span><span class="pln">credentials<br></span><span class="kwd">import</span><span class="pln"> google_auth_oauthlib</span><span class="pun">.</span><span class="pln">flow<br><br>flow </span><span class="pun">=</span><span class="pln"> google_auth_oauthlib</span><span class="pun">.</span><span class="pln">flow</span><span class="pun">.</span><span class="typ">Flow</span><span class="pun">.</span><span class="pln">from_client_secrets_file</span><span class="pun">(</span><span class="pln"><br>&nbsp; &nbsp; </span><span class="str">'</span><em><span class="str">path_to_directory</span></em><span class="str">/client_secret.json'</span><span class="pun">,</span><span class="pln"><br>&nbsp; &nbsp; scopes</span><span class="pun">=[</span><span class="str">'https://www.googleapis.com/auth/calendar'</span><span class="pun">])</span><span class="pln"><br><br>flow</span><span class="pun">.</span><span class="pln">redirect_uri </span><span class="pun">=</span><span class="pln"> </span><span class="str">'https://www.example.com/oauth2callback'</span></pre>
    </article></section>
</section>

<section id="motivation">
  <h2 id="motivation"><a href="#top_of_page" class="devsite-back-to-top-link material-icons" data-tooltip-align="b,c" data-tooltip="Back to top" aria-label="Back to top" data-title="Back to top"></a>Motivation</h2>
  <p>
  Traditionally providers of OAuth endpoints have relied upon cut-and-paste as
  the way users of their service move the client id and secret from a
  registration page into working code. That can be error prone, along with it
  being an incomplete picture of all the information that is needed to get OAuth
  2.0 working, which requires knowing all the endpoints and configuring a
  Redirect Endpoint. If service providers start providing a downloadable
  client_secrets.json file for client information and client libraries start
  consuming client_secrets.json then a large amount of friction in implementing
  OAuth 2.0 can be reduced.
  </p>
</section>

  </div>

**Comment by grant** [comment]
The docs are now added to the `docs/` folder.
Fixed with #706.

**Comment by davidsansome** [comment]
The docstrings in `flow.py` and `helpers.py` still link to https://developers.google.com/api-client-library/python/auth/aaa_client_secrets and need to be updated to point to docs/client-secrets.md
