### ISSUE TITLE
DevSite Import: Using Django

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-python-client#689]
Notice: This DevSite page will soon be deleted per [b/133171590](http://b/133171590). Please add this sample to GitHub if it is relevant still:

https://developers.google.com/api-client-library/python/guide/django

---

# Using Django

<section>
  <p>
    The Google APIs Client Library for Python has special support for the
    <a href="https://www.djangoproject.com/">Django</a>
    web framework.
    In particular, there are classes that simplify the OAuth 2.0 protocol steps.
    This document describes the Django-specific classes available for working with
    <a href="/api-client-library/python/guide/aaa_oauth#flows">Flow</a>,
    <a href="/api-client-library/python/guide/aaa_oauth#credentials">Credentials</a>, and
    <a href="/api-client-library/python/guide/aaa_oauth#storage">Storage</a> objects.
  </p>
</section>

<section id="Flows">
  <h2>Flows</h2>
  <p>
    Use the
    <a href="https://oauth2client.readthedocs.io/en/latest/source/oauth2client.contrib.django_orm.html#oauth2client.contrib.django_orm.FlowField">oauth2client.contrib.django_orm.FlowField</a>
    class as a Django model field so that <code>Flow</code> objects can easily be stored.
    When your application is simultaneously going through OAuth 2.0 steps for many users,
    it's normally best to store per-user <code>Flow</code> objects before the first redirection.
    This way, your redirection handlers can retrieve the <code>Flow</code> object already created for the user.
    In the following code,
    a model is defined that allows <code>Flow</code> objects to be stored and keyed by <code>User</code>:
  </p>
  <pre class="prettyprint">
from django.contrib.auth.models import User
from django.db import models
from oauth2client.contrib.django_orm import FlowField
...
class FlowModel(models.Model):
  id = models.ForeignKey(User, primary_key=True)
  flow = FlowField()</pre>
</section>

<section id="Credentials">
  <h2>Credentials</h2>
  <p>
    Use the
    <a href="https://oauth2client.readthedocs.io/en/latest/source/oauth2client.contrib.django_orm.html#oauth2client.contrib.django_orm.CredentialsField">oauth2client.contrib.django_orm.CredentialsField</a>
    class as a Django model field so that <code>Credentials</code> objects can easily be stored.
    Similar to <code>Flow</code> objects, it's normally best to store per-user <code>Credentials</code> objects.
    In the following code,
    a model is defined that allows <code>Credentials</code> objects to be stored and keyed by <code>User</code>:
  </p>
  <pre class="prettyprint">
from django.contrib.auth.models import User
from django.db import models
from oauth2client.contrib.django_orm import CredentialsField
...
class CredentialsModel(models.Model):
  id = models.ForeignKey(User, primary_key=True)
  credential = CredentialsField()</pre>
</section>

<section id="Storage">
  <h2>Storage</h2>
  <p>
    Use the
    <a href="https://oauth2client.readthedocs.io/en/latest/source/oauth2client.contrib.django_orm.html#oauth2client.contrib.django_orm.Storage">oauth2client.contrib.django_orm.Storage</a>
    class to store and retrieve <code>Credentials</code> objects
    using a model defined with a <code>CredentialsField</code> object.
    You pass the model, field name for the model key, value for the model key,
    and field name to the <code>CredentialsField</code> constructor.
    The following shows how to create, read, and write <code>Credentials</code> objects
    using the example <code>CredentialsModel</code> class above:
  </p>
  <pre class="prettyprint">
from django.contrib.auth.models import User
from oauth2client.contrib.django_orm import Storage
from your_project.your_app.models import CredentialsModel
...
user = # A User object usually obtained from request.
storage = Storage(CredentialsModel, 'id', user, 'credential')
credential = storage.get()
...
storage.put(credential)</pre>
</section>

**Comment by busunkim96** [comment]
@grant Thanks for the heads up! We deleted the Django sample from this repo a while back, so I don't think we have any concerns.

**Comment by grant** [comment]
The docs are now added to the `docs/` folder.
Fixed with #706.

**Comment by matej2** [comment]
Why was Django example removed? Did this libary lost support for Django?

**Comment by akashsenta13** [comment]
Do we have any doc for django integration ?
