### ISSUE TITLE
Documentation not accessible.

### ISSUE THREAD

**Issue by jerrythomas** [googleapis/google-api-python-client#693]
The documentation links are all redirected to this repository. The following links are from the readme 

* [Developer Documentation](https://developers.google.com/api-client-library/python/start/get_started)
* [full documentation for this library](https://developers.google.com/api-client-library/python/)

All of them redirect to https://github.com/googleapis/google-api-python-client
Even the links for the documentation on [Google API client libraries](https://developers.google.com/api-client-library/) redirects to this repo. 
* https://developers.google.com/api-client-library/python/
* https://developers.google.com/api-client-library/python/start/get_started
* https://developers.google.com/api-client-library/python/samples/samples

#### Steps to reproduce

  1. Click on the links in the readme. All of them redirect to this repo.

Samples are actually here
https://github.com/googleapis/google-api-python-client/tree/master/samples

I couldn't find documentation similar to the one for [java](https://developers.google.com/api-client-library/java/). Can you correct the links so that the documentation is accessible?

**Comment by busunkim96** [comment]
Hi @jerrythomas, we're in the process of removing documentation on that site, and have open issues on this repo to add documentation here.

Thank you for filing an issue!

**Comment by doransmestad** [comment]
Any recommendations in the meanwhile?  I'd like to use this project to interact with the Google APIs, but no available documentation makes this a bit challenging.  Is there a place we can find the documentation while it is being migrated?   Thanks

**Comment by busunkim96** [comment]
Hi @doransmestad, if you're looking for the generated ref docs they are currently available under:
`https://googleapis.github.io/google-api-python-client/docs/dyn/{api_name}_{version}`

*Examples:
https://googleapis.github.io/google-api-python-client/docs/dyn/accesscontextmanager_v1beta
https://googleapis.github.io/google-api-python-client/docs/dyn/customsearch_v1

For other docs (auth guide, for example), there are currently PRs open on this repo that have the contents of those.

We know this isn't ideal, and we're working on getting the GH pages site up to date.

Thank you all for your patience!

**Comment by csudcy** [comment]
Hey @busunkim96, I had a look through PRs but couldn't see any which look like they're for adding docs; it looks like there are some recent merges which update docs though so maybe the links in the root readme just need updating?

@doransmestad in the meantime, I've found this sample most helpful: https://github.com/googleapis/google-api-python-client/blob/master/samples/appengine/

**Comment by busunkim96** [comment]
My mistake, the docs are currently in issues (labeled `type: docs`) and all made on June 6th.

Here's the App Engine one:
https://github.com/googleapis/google-api-python-client/issues/688

**Comment by grant** [comment]
With PR #706, I think we can close this and redirect developers to our new API `docs/` pages! 🎉 

https://github.com/googleapis/google-api-python-client/tree/master/docs

Pardon with the delay for moving these docs, and let up know if there's anything else we should do.

**Comment by busunkim96** [comment]
Should be closed with #702. There *will* be more cleanup in the future, but the docs are accessible again. Please see https://github.com/googleapis/google-api-python-client/blob/master/docs/README.md for a list of guides and reference documentation.
