### ISSUE TITLE
GitHub Pages Outdated

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-python-client#694]
The GitHub pages are outdated and haven't been updated recently.
Last update was July 2018.

Example:

http://googleapis.github.io/google-api-python-client/docs/dyn/drive_v3.html

(branch `gh-pages`)

APIs like Sheets should be included or this branch should be removed.

**Comment by busunkim96** [comment]
@grant Is there another place that hosts the Python docs?

**Comment by grant** [comment]
@busunkim96 Not that I know of. I just reported the issue. I don't maintain the library.

**Comment by busunkim96** [comment]
Closed by #701
