### ISSUE TITLE
Pypi Project Description

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-python-client#698]
The Pypi package has a description that is very old and not useful.

> The Google API Client for Python is a client library for accessing the Plus, Moderator, and many other Google APIs.

https://pypi.org/project/google-api-python-client/1.7.9/

For example, the G+ API is deprecated.

This should be updated to something more useful. It's hard to tell that this is the real pypi package!

**Comment by parthea** [comment]
Hi @grant,

I'm going to close off this issue as it looks like the description has been updated. See https://pypi.org/project/google-api-python-client/
