### ISSUE TITLE
Setting loglevel with logging.basicConfig raises import error when calling googleapiclient.discovery.build

### ISSUE THREAD

**Issue by sflis** [googleapis/google-api-python-client#703]
Running the sample script found at https://developers.google.com/sheets/api/quickstart/python in isolation was fine but when tried to access a spreadsheet in one of my projects where multiple other packages are imported I got: 
``` shell
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/sflis/software/anaconda3/envs/SSM-analysis/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sflis/software/anaconda3/envs/SSM-analysis/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sflis/software/anaconda3/envs/SSM-analysis/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sflis/software/anaconda3/envs/SSM-analysis/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/sflis/software/anaconda3/envs/SSM-analysis/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
```
Eventually I traced it down to the `logging` module and setting the logging level with `basicConfig`, which was done in one of the import of my project. 

#### Environment details

  - OS: Ubuntu (4.18.0-21-generic #22~18.04.1-Ubuntu)
  - Python version: 3.6.8
  - conda version: 4.5.11
  - pip version: 19.0.2
  - `google-api-python-client` version: 1.7.9
 

#### Steps to reproduce
Minimal example to reproduce the bug:
``` python
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request


import logging
logging.basicConfig(level=logging.INFO) ####this is the culprit line####

creds = None

datafolder = "/path/to/data/folder"
tokenfile = os.path.join(datafolder,'token.pickle')
credfile = os.path.join(datafolder,'credentials.json')

scopes = ['https://www.googleapis.com/auth/spreadsheets.readonly']
if os.path.exists(tokenfile):
    with open(tokenfile, 'rb') as token:
        creds = pickle.load(token)
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            credfile, scopes)
        creds = flow.run_local_server()

    with open(tokenfile, 'wb') as token:
        pickle.dump(creds, token)
service = build('sheets', 'v4', credentials=creds)

```
By removing the line with `logging.basicConfig(level=logging.INFO)` no import error is raised on the last line of the script. I assume that `logging.basicConfig` should be safe to use with `googleapi`?

Thanks!

**Comment by loozhengyuan** [comment]
I'm currently facing this exact issue as well. From what I understand, `oauth2client` is [deprecated](https://github.com/googleapis/oauth2client) by Google too.

**Comment by busunkim96** [comment]
Hi @sflis, apologies for the long delay.

This is working as intended. The warning is showing the chain of exceptions, which why it disappears if logging isn't enabled.

https://github.com/googleapis/google-api-python-client/blob/8496ebe7e4c282371c831cabdeb390855ff0d270/googleapiclient/discovery_cache/__init__.py#L23-L45

`basicConfig(level=logging.INFO)` changes the logging level for the root logger, so all logs from the library are being surfaced up to you.

**Comment by sflis** [comment]
Hi @busunkim96, 
> Hi @sflis, apologies for the long delay.
  No problem!

> This is working as intended. The warning is showing the chain of exceptions, which why it disappears if logging isn't enabled.

I'm not sure I follow this. The problem I encountered was that when setting the logging level with `basicConfig` an _exception_ was raised otherwise there was no exception. It might very well be that the exception still occurred but was caught on a lower level when the root logging level was not changed. 

I understand that the warnings are being surfaced up to me by changing the logging level however I think it's unrelated to the import errors seemingly caused by setting the log level with  `basicConfig`.

**Comment by busunkim96** [comment]
The log you pasted appears to show one warning and one info message.  This function determines if there is a cache for the discovery document.  If all the imports fail by throwing exceptions, the function returns `None` to indicate there is no cache.

The exceptions are being shown in the log because of [`exc_info`](https://docs.python.org/3/library/logging.html#logging.Logger.debug), but it looks like they're already being caught and handled correctly. https://github.com/googleapis/google-api-python-client/blob/8496ebe7e4c282371c831cabdeb390855ff0d270/googleapiclient/discovery_cache/__init__.py#L44
```
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
<Exception info here>
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
```
