### ISSUE TITLE
Python == 2.7

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-python-client#704]
The read me states that

># Deprecated Python Versions
>Python == 2.7

It does not appear to work with Python == 2.7.  (link to question on [SO](https://stackoverflow.com/q/56731694/1841839))

Should this note be removed from the [readme](https://github.com/googleapis/google-api-python-client/edit/master/README.md)?  to me deprecation means that it should still work just be removed soon.

**Comment by busunkim96** [comment]
Python 2.7 is deprecated, but we intend to drop support for Python 2.7 on January 1, 2020.

The stack trace points to an incompatibility in httplib2. httplib2 started releasing py3 wheels on [PyPI ](https://pypi.org/project/httplib2/#history) a few months ago. (starting with 0.12.3) 

The python2 version appears to be available in the `.tar.gz`.  If they install from the tarfile or pin an older version of httplib2 the library should still work with Python 2.7.

**Comment by prakhargurunani** [comment]
@busunkim96 `Python==2.7` still exists in `README.md` as depreciated. Since it is now not supported (since 1st jan 2020), should it not be removed from the docs (or a no longer supported message be given)?

**Comment by parthea** [comment]
This will be fixed in #961

**Comment by prakhargurunani** [comment]
@parthea Ok 🙂.
