### ISSUE TITLE
Old changes made to google sheet files (before 2017) not downloaded by http.MediaIoBaseDownload

### ISSUE THREAD

**Issue by ying-va7yyz** [googleapis/google-api-python-client#708]
#### Environment details

  - OS: Ubuntu 16.04
  - Python version: 2.7
  - pip version: 19.02
  - `google-api-python-client` version: 1.7.9

#### Steps to reproduce

  1. Find an old file created/modified before 2017 (the one I have was created on Sep 7, 2016, and modified on Sep 8, 2016)
  2. Call http.MediaIoBaseDownload to download the file
  3. Check the downloaded file, it will be the original version from Sep 7, 2016 instead of the modified version from Sep 8, 2016.
  4. Make some changes to the file on google drive and redownload it through API will give a hybrid version, which includes the latest changes you just made over the original file, while changes made on Sep 8, 2016 still missing.
  5. If you show the change history of that file from the Google Drive APP in a browser, you do see the changes on Sep 8, 2016 in history.

Thanks!

**Comment by busunkim96** [comment]
@ying-va7yyz 

Thank you for reporting! Did this every work correctly? If so, when did it stop working?

I think this is most likely an issue with the backend API. Please reach out to the [Sheets API support](https://developers.google.com/sheets/api/support) team.

**Comment by ying-va7yyz** [comment]
Thanks for your reply. This is something I just noticed and am not sure how it behaved in the past. I've submitted a bug report to Sheets API support: https://issuetracker.google.com/137251486

**Comment by parthea** [comment]
Hi @ying-va7yyz,

I'm going to close off this issue due to inactivity but if you're still having trouble please re-open it with more information.
