### ISSUE TITLE
groupssettings get(): missing attribute value: id

### ISSUE THREAD

**Issue by babywonderland** [googleapis/google-api-python-client#715]
I'm getting an error trying to get settings for a group:
`googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/groups/v1/groups/00nmf14n31fm1c2?alt=json returned "Missing/Invalid attribute value: id">
`

I'm following along with https://github.com/googleapis/google-api-python-client/blob/master/samples/groupssettings/groupsettings.py trying to retrieve settings for a group. I'm using a service account, but otherwise it's pretty much the same as what's in the sample. Here's the code:
```
from googleapiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials

credentials = ServiceAccountCredentials.from_json_keyfile_dict(
    json.load("secret.json"),
    scopes=["https://www.googleapis.com/auth/apps.groups.settings"])
credentials = credentials.create_delegated("admin_user@example.com")
service = build("groupssettings", "v1", credentials=credentials)
service.groups().get(groupUniqueId="00nmf14n31fm1c2").execute()

```

This is Python 3.6 using google-api-python-client v1.7.9 and the error is repeatable on different computers, so it must be an error in googleapiclient.discovery.build() I guess? I tried see if I could trace down what build() is doing, but it seems to be pulling configuration from Google that just returns 404 when I try to view it in a browser.

Can build() be fixed? Or is this an error on the server side with Google? (If it's the latter, I have no idea how to get them to fix it. Does anybody else know?)

**Comment by babywonderland** [comment]
Okay, I solved my own problem. (Sorry for the noise! I tried to solve this on my own for a while before opening an issue.)

The directory API says to use the group-id wherever possible because the group email can change. The groups settings API apparently does not support using the group-id, so what it calls the "id" is really the group email. And the "missing id attribute" error, somewhat misleadingly, is the error one gets when the group email isn't valid.

The fix for my code snippet is as simple as:
`service.groups().get(groupUniqueId="groupemail@example.com").execute()`

**Comment by busunkim96** [comment]
@babywonderland Thank you for posting your solution! Glad you got it figured out. If you're able to, could you provide this feedback to the [GSuite Admin SDK team](https://developers.google.com/admin-sdk/groups-settings/support)? It looks like they maintain this API.

**Comment by brian-suarez-spothero** [comment]
Thank you @babywonderland ! That worked
