### ISSUE TITLE
events api insert / update reminders useDefault not working

### ISSUE THREAD

**Issue by tiok-cek1** [googleapis/google-api-python-client#717]
when i update an event, reminders to useDefault True, event not updating.

payload contains
```
'reminders': {
                'useDefault': True,
},
```

i've tested on insert, also encountered this problem

**Comment by busunkim96** [comment]
Hi @tiok-cek1, this sounds like a problem with the underlying events API. Have you had the chance to test this using the REST API or a client in another language?

**Comment by tiok-cek1** [comment]
i've just tried REST API. the same, not working. returned API useDefault false
i tried "overrides", returned API are updated. maybe "useDefault" API bug.

**Comment by busunkim96** [comment]
@tiok-cek1 That sounds like something the backend Calendar API team should look at. Could you please file an issue at https://issuetracker.google.com/issues/new?component=191627&template=824103?

Thank yoU!

**Comment by tiok-cek1** [comment]
submitted, thanks
https://issuetracker.google.com/issues/137790091

**Comment by busunkim96** [comment]
Closing here as the issue has been moved to issuetracker. Please file a new issue if you are still experiencing issues.
