### ISSUE TITLE
README.md link to docs is a self redirect

### ISSUE THREAD

**Issue by telenieko** [googleapis/google-api-python-client#719]
Hi,

README.md has a link to "full documentation for this library" that points to https://developers.google.com/api-client-library/python/ but that page is a redirect back to the README.md

> wget --max-redirect 0 https://developers.google.com/api-client-library/python/ -O -
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
> ERROR: could not open HSTS store at '/home/marc/.wget-hsts'. HSTS will be disabled.
> --2019-07-17 19:01:07--  https://developers.google.com/api-client-library/python/
> Resolving developers.google.com (developers.google.com)... 172.217.22.78, 2a00:1450:4001:816::200e
> Connecting to developers.google.com (developers.google.com)|172.217.22.78|:443... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: https://github.com/google/google-api-python-client [following]

I guess the link should be pointing to the README.md in the docs folder. Or be removed and rewrite the paragraph in favour of the Documentation heading that follows that.

**Comment by busunkim96** [comment]
Yep! Sorry about the documentation - there's a PR out right now to clean that up. See #702

**Comment by busunkim96** [comment]
Closed via #702. The README link now points to the docs/README.
