### ISSUE TITLE
Google Drive REST API does not return all revisions.

### ISSUE THREAD

**Issue by ktbernoulli** [googleapis/google-api-python-client#725]
Ubuntu 18.04 LTS, Python 3.7.3
 `google-api-python-client` version: 1.7.9
drive API version: v3

Direct Code being Used:
`sheet = '1vZCO2IDzb2PXC5A6y0qljUryoV5eqrB06wAVqpRB5_I'`
`version = drive.revisions().list(fileId = sheet, fields = '*').execute()`
Returns only 6 lines of revisions when the file has history all the way back to April. ):

In contrast, `sheet = '1l2R7v65ZgN721qO27dU-5Tf84226jXuj1mnVcMh9ew4'`
returns all the way to June 11st (document was created June 4th but close enough).

What is going on? Is this common? How do I get more revisions to be listed?

Thank you very much <3

**Comment by busunkim96** [comment]
Hi @ktbernoull Does this also happen when you use the REST API directly? You can test this by using the API Explorer 'Try this API' on the right side of [this page](https://developers.google.com/drive/api/v3/reference/revisions/list)

**Comment by ktbernoulli** [comment]
Yes, this happens when I use the explorer, too ):

**Comment by busunkim96** [comment]
I'll have to direct you to[Drive Support](https://developers.google.com/drive/api/v3/support) for this, as we don't manage the backend for the API. 

We'd appreciate it if you could link the issue you end up opening for any folks who find this in the future.

Thanks!
