### ISSUE TITLE
google-api-python-client does not honor `no_proxy` environment variable

### ISSUE THREAD

**Issue by MaT1g3R** [googleapis/google-api-python-client#726]
#### Environment details

  - OS: Ubuntu 18.04
  - Python version: 3.6.8
  - pip version: 19.1.1
  - `google-api-python-client` version: 1.7.9

#### Steps to reproduce

We have a squid proxy running; The squid is not able to talk to google apis/metadata server.

```
export no_proxy=metadata.google.internal,.googleapis.com
export http_proxy=http://squid:3128
export https_proxy=http://squid:3128
```

We expect the `no_proxy` env var is honored.
This is an issue with [httplib2](https://github.com/httplib2/httplib2), we've already sent a PR to them here: https://github.com/httplib2/httplib2/pull/140

**Comment by temoto** [comment]
Hello. Sorry, the problem was caused by my bad code. Fix is merged in httplib2 master.

**Comment by temoto** [comment]
And now it's released as 0.13.1 on PyPI. Sorry for inconvenience.

**Comment by busunkim96** [comment]
@temoto Thank you for the quick fix!

**Comment by temoto** [comment]
Just to be clear: @MaT1g3R did all the work.

**Comment by busunkim96** [comment]
Thank you @MaT1g3R! :tada:
