### ISSUE TITLE
Update samples to use google-auth, google-auth-oauthlib

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-api-python-client#731]
Most of the samples and docs still use oauth2client, which is deprecated. They should use google-auth and google-auth-oauthlib. The [Google Docs sample](https://github.com/gsuitedevs/python-samples/blob/master/docs/quickstart/quickstart.py) is a good example.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
