### ISSUE TITLE
get() method don't retrieve "externalIds" key

### ISSUE THREAD

**Issue by gustavo-sdo** [googleapis/google-api-python-client#735]
Hey there, i'm trying to see the _'externalIds'_ key registered to my users, but this key is not returned by the get() method of the API... 

Here's my code:
```python
import httplib2
from apiclient.discovery import build
from oauth2client.file import Storage

...
store = Storage(MY_CREDENTIAL_FILE)
credentials = store.get()

http = credentials.authorize(httplib2.Http())
service = build('admin', 'directory_v1', http=http)
service.users().get(userKey='example@mydomain.com').execute()
```
A dict is returned with some keys like _'kind'_, _'id'_, _'name'_, _'suspended'_... but not _'externalIds'_...
Is it a bug?
Is there another way to get this value? 

I searched the web and found no solution to this issue.
I also don't see anything in the [documentation](https://developers.google.com/admin-sdk/directory/v1/reference/users/get) about this...

**Comment by busunkim96** [comment]
Hi @gustavo-sdo! It looks like you have a question about the backend API. Please reach out to the [support channels](https://developers.google.com/admin-sdk/directory/support) for GSuite Admin SDK.

**Comment by tseaver** [comment]
@gustavo-sdo the docs for [retrieving a user as a non-admin](https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#retrieve_users_non_admin) suggest that some fields of the resource may be omitted from the response for non-admin users.  Is it possible that the credentials you are using don't have the appropriate scope for admin access?

**Comment by busunkim96** [comment]
@gustavo-sdo have you been able to look into whether or not your credentials have admin access?

**Comment by gustavo-sdo** [comment]
> @gustavo-sdo have you been able to look into whether or not your credentials have admin access?

> Is it possible that the credentials you are using don't have the appropriate scope for admin access?

Hi @busunkim96 @tseaver, thanks for your attention...
I asked our infra guy to test using an admin user and he said this specific key (_externalIds_) doesn't returned to him too :/

I also checked through the [Try this API](https://developers.google.com/admin-sdk/directory/v1/reference/users/get) section in web documentation and there I am not successful either. So I think this is not a problem with google-api-python-client specifically.

**Comment by busunkim96** [comment]
That's unfortunate. Do you know if any other admin-only keys are missing?

Has the service account has been delegated domain-wide authority? There are instructions on this page.
https://developers.google.com/admin-sdk/directory/v1/guides/delegation

If that does not work, please file an issue on the [Directory API issue tracker](https://issuetracker.google.com/issues/new?component=191635&template=823904)

**Comment by gustavo-sdo** [comment]
> Do you know if any other admin-only keys are missing?

This is the list of all keys returned by api:
['kind', 'id', 'etag', 'primaryEmail', 'name', 'isAdmin', 'isDelegatedAdmin', 'lastLoginTime', 'creationTime', 'agreedToTerms', 'suspended', 'archived', 'changePasswordAtNextLogin', 'ipWhitelisted', 'emails', 'customerId', 'orgUnitPath', 'isMailboxSetup', 'isEnrolledIn2Sv', 'isEnforcedIn2Sv', 'includeInGlobalAddressList']

Of the fields I use to create a new account user, only 'externalIds' don't appear above.

> Has the service account has been delegated domain-wide authority?

Yes, it was tried with a full access user...

I'll check more and if I can't find a solution or alternative for my issue, I open a ticket.
thank you again @busunkim96 :)
