### ISSUE TITLE
Allow using max/min parameter values from discovery file

### ISSUE THREAD

**Issue by jay0lee** [googleapis/google-api-python-client#740]
API discovery files can publish a max/min value for integer parameters. For example, here's a section of the Admin SDK for users.list() maxResults parameter:

    "maxResults": {
           "type": "integer",
           "description": "Maximum number of results to return. Default is 100. Max allowed is 500",
           "format": "int32",
           "minimum": "1",    
           "maximum": "500",
           "location": "query"
          },
as far as I can tell, the Python library currently makes no use of maximum and minimum here.

I'm looking for some guidance here, what I'd like to be able to do is make an API call like:

    users.list(maxResuls='maximum')

and have maxResults set to 500 by the library (or 1,000 should Google push the maxResults value for the API). Is it bad practice though to allow maxResults to be a string or an integer? Recommendations as to how i might implement this?

I'm also aware I could do something like:

    maxResults = service._rootDesc['resources']['users']['methods']['list']['parameters']['maxResults'].get('maximum')

but that seems rather messy and disconnected from the actual API method being called.

**Comment by jay0lee** [comment]
FYI here's a sample script that demonstrates ability to set maxResults="maximum". It only needs an API key that has Youtube API enabled.

[test.py.txt](https://github.com/googleapis/google-api-python-client/files/3498007/test.py.txt)

**Comment by parthea** [comment]
Hi @jay0lee ,

Are you interested to re-open your PR with unit tests added?

**Comment by jay0lee** [comment]
Not sure how useful it'd be as most of the new OP APIs I've looked at don't seem to set maximum any longer.

**Comment by parthea** [comment]
I'm going to close this off based on the last comment but please re-open this issue if there are improvements we can make!
