### ISSUE TITLE
a typo in the document

### ISSUE THREAD

**Issue by stephen-a2z** [googleapis/google-api-python-client#744]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - If you have a question, post on Stackoverflow under the `google-api` tag.
  - If you are reporting an issue or requesting a feature for a G Suite API, please use their [public issue tracker](https://gsuite-developers.googleblog.com/2017/03/a-new-issue-tracker-for-g-suite.html)

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Python version:
  - pip version:
  - `google-api-python-client` version:

#### Steps to reproduce

  1. 
![image](https://user-images.githubusercontent.com/32169422/63075062-d6071780-bf62-11e9-8ab0-4cadcad6f2c3.png) 
https://github.com/googleapis/google-api-python-client/blob/master/docs/start.md

  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by tseaver** [comment]
Thanks for the report!
