### ISSUE TITLE
Returning 403 when i try to reply some users reviews

### ISSUE THREAD

**Issue by joaopgom** [googleapis/google-api-python-client#748]
Hi, 

The API is returning an error "Forbbiden 403" when i try reply some reviews from google play, apparently i can't reply some users.
The users can block the developers to not get a reply? There's an another reason for this errors for especific reviews?

**Comment by busunkim96** [comment]
@joaopgom Could you let us know which API you are using? A code sample would also be very helpful in diagnosing the issue. If you are getting a 403, it sounds like the credentials you have do not have sufficient permissions.

Questions about the Google Play Developer API are best directed to the [Google Play developer support](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en). Please reach out to them with your question. Thanks!

**Comment by joaopgom** [comment]
@busunkim96 i'm doing basicly this:

`from googleapiclient.discovery import build`
`service = build('androidpublisher', 'v3', credentials=my_credentials)`
`result = service.reviews().reply(packageName=my_package_name, reviewId=my_review_id, body={'replyText': reply_text}).execute()`

I'm replying all reviews the same way, same credentials are past, but almost 5% of my reviews i can't, cause im get this error 403.

Thanks!

**Comment by busunkim96** [comment]
Hiya, that sounds like a backend error. 

Please reach out to [Google Play developer support](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en). They have [chat support](https://support.google.com/googleplay/android-developer/contact/pre_chat_survey?cfnti=escalationflow.chat&cft=1) M-F and [email support ](https://support.google.com/googleplay/android-developer/contact/publishing) provided within 48 hours.
