### ISSUE TITLE
How to enable Etag caching support?

### ISSUE THREAD

**Issue by youmee** [googleapis/google-api-python-client#749]
Hello. I just can't realise how to use ETags in requests with this library?

How to pass ETag to `request.execute()` stage or somewhere else.

I want to rid of repetitive requests and save my API quota.

**Comment by busunkim96** [comment]
Hi @youmee. You can pass additional headers to the request object. 

https://github.com/googleapis/google-api-python-client/blob/0ba1ca4435aab90bea35a155a2875fa0842b8023/googleapiclient/http.py#L753-L775

**Comment by tmccombs** [comment]
I'm not sure I follow how you would use that. Where would you pass additional headers to the request? Typically you wouldn't create the request directly. Are you saying you should do something like:

```
request = HttpRequest(request.http, request.postproc, request.uri, request.method, request.body, {**request.headers, 'If-none-match': etag, request.methodId, request.resumable)
```
?

Or could I just do something like
```
request.headers['if-none-match'] = etag
```
?

**Comment by nick-catalist** [comment]
I'm going crazy trying to figure out how to use etags in `googleapiclient` and every issue I find is like this where you're given a non-answer and then it's immediately closed.

If I try to do something like 

```
service.events().update(headers={}) 
```

when building a request from a discovery client, I get "unexpected keyword argument `headers` ...
