### ISSUE TITLE
Python client library for Google shopping content API authentication issue

### ISSUE THREAD

**Issue by castnow123** [googleapis/google-api-python-client#754]
I setup a merchant center and a service account to access shopping content API but I cannot authenticate using Python client library.  upon investigating the issue I found that the requirements.txt asks to install google-auth-httplib2, google-auth-httplib2 & google-api-python-client but inside common.py the scripts is trying to import google_auth_httplib2 and googleapiclient. The same issue is inside auth.py which uses google_auth_oauthlib. I tried to change the scripts to match the requirements but that gave new errors. please setup a test merchant center and debug to see the issue. Thanks

**Comment by busunkim96** [comment]
@castnow123 Package names are not the same as the import names.

On pip the package names are:
* google-auth-httplib2
* google-auth
* google-api-python-client

Imports are
* google_auth_httplib2
* google.auth
* googleapiclient

Could you please tell us what errors specifically you're getting?

**Comment by castnow123** [comment]
@busunkim96 this is the error message:

 raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/content/v2/accounts/authinfo?alt=json returned "Insufficient Permission">

can you try to authenticate using test account to replicate the issue?

**Comment by busunkim96** [comment]
Looks like there are no problems installing the library then.

You filed an issue earlier on this repo #751. Did you file an issue on the [Google Content API for Shopping forum]( https://groups.google.com/forum/#!forum/google-content-api-for-shopping)? If you did, could you please link to it?

**Comment by castnow123** [comment]
[https://groups.google.com/forum/#!topic/google-content-api-for-shopping/aAokeZ67ezM](url)

I tried to run this command python3 -m shop
ping.content.products.list but received this error message, so different issues between python2 &3:

 import google_auth_httplib2
ImportError: No module named 'google_auth_httplib2'

**Comment by castnow123** [comment]
@busunkim96 
Look at Python shopping authentication error in this list: https://groups.google.com/forum/#!forum/google-content-api-for-shopping

**Comment by castnow123** [comment]
@busunkim96 

https://groups.google.com/d/topic/google-content-api-for-shopping/aAokeZ67ezM/discussion

**Comment by busunkim96** [comment]
@castnow123 Please go to [API Explorer](https://developers.google.com/apis-explorer/#p/content/v2.1/content.orders.list?merchantId=139978797&_h=11&) and make a request with a merchantId. Do you get the same 403 error?

I get 403s across the board for most of the methods that actually require a merchantId. I suspect something's gone wrong with the backend, but it'd be nice to confirm. 

Short example:
```python
from __future__ import print_function
from googleapiclient.discovery import build
from google.oauth2 import service_account

def main():
    creds = service_account.Credentials.from_service_account_file(
    'service-account.json')
    service = build('content', 'v2.1', credentials=creds)
    resp = service.orders().list(merchantId=123456789).execute()
    print(resp)

if __name__ == '__main__':
    main()
```

**Comment by castnow123** [comment]
if I use the link you gave me it gives 403 error but if I use the API explorer in this link it works fine:

https://developers.google.com/shopping-content/v2/quickstart

you can try both tools with my merchant id 139657381

**Comment by busunkim96** [comment]
@castnow123 That method (products().list()) also works fine with the Python Client.

```python
from __future__ import print_function
from googleapiclient.discovery import build
from google.oauth2 import service_account

def main():
    creds = service_account.Credentials.from_service_account_file(
    'service-account.json')
    service = build('content', 'v2', credentials=creds)
    resp = service.products().list(merchantId=123456789).execute()
    print(resp)

if __name__ == '__main__':
    main()
```

How about [this method](https://developers.google.com/shopping-content/v2/reference/v2.1/returnpolicy/list)?

**Comment by castnow123** [comment]
did not work. I got this error: This error may be due to using an insufficient credential type. Try using OAuth 2.0.

**Comment by busunkim96** [comment]
Continuing discussion at https://groups.google.com/d/topic/google-content-api-for-shopping/aAokeZ67ezM/discussion

**Comment by busunkim96** [comment]
This looks to have been resolved. Please open a new issue if you are still experiencing problems.
