### ISSUE TITLE
How to Manage the List of Email Addresses Associated with an Android Testing Track?

### ISSUE THREAD

**Issue by noelstieglitz** [googleapis/google-api-python-client#756]
#### Environment details
  - OS: Windows 10
  - Python version: 3.7
  - pip version: 19.03
  - `google-api-python-client` version: 1.7.11

In the Google Play Console, there is a section dedicated to managing email lists:
![ManageEmailLists](https://user-images.githubusercontent.com/1135723/64864994-55d9dd80-d606-11e9-97b7-c5b485621481.png)

How do I manage the email list via the Google API Python Client?

That section makes HTTP `POST` calls to https://play.google.com/apps/publish/testersemaillist?account={account}, which does not seem to be intended for use outside of Google.

Those email lists are used to drive which users have access to the various testing tracks (ie - Closed Alpha, etc.).  The only API calls I found even remotely related to manage users for testing tracks was the endpoint (https://developers.google.com/android-publisher/api-ref/edits/testers#resource):

`service.edits().testers().get(editId=edit_id, packageName=package_name, track=custom_track).execute()`

This provides a way to manage the Google Groups or Google+ Communities associated with the testing tracks, but we are using the Google Play Email Lists rather either of those options (both of which have some downsides relative to the email list).  Side note - it looks like Google+ isn't even supported anymore for new tracks.

Please let me know if I should post this somewhere else (or as a feature request rather than a bug, if it doesn't exist).  Here is my question on SO: https://stackoverflow.com/questions/57698409/is-it-possible-to-manage-the-google-play-console-email-list-programmatically-via

**Comment by busunkim96** [comment]
Hi @noelstieglitz!

Google Play developer support's preferred way to get in touch is described on [this page](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en). They should be able to get you in touch with the right folks.

**Comment by noelstieglitz** [comment]
Thanks @busunkim96 , I submitted a request through the Google Play Developer support page.
