### ISSUE TITLE
Update Users Photos returning 400 missing required fields. Docs show only 1 required field

### ISSUE THREAD

**Issue by koskorya** [googleapis/google-api-python-client#765]
#### Environment details

  - OS: Ubuntu xenial
  - Python version: 3.5.2
  - pip version: 19.3
  - `google-api-python-client` version: 1.7.11
```
photo = base64.b64decode(corpPhoto)
image = base64.urlsafe_b64encode(photo)

strPayload = json.dumps(str({"photoData": image}))
payload = json.loads(strPayload)
googleServiceBuild.users().photos().update(userKey='EMAIL', body=payload).execute()
```

Returns
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/admin/directory/v1/users/EMAIL/photos/thumbnail?alt=json returned "Missing required field">
```

debugging payload variable shows 

```
"{'photoData': b'_9j_4AAQSkZJRg....Z'}"
```

The [docs](https://developers.google.com/admin-sdk/directory/v1/reference/users/photos/update) show only the `photoData` as a required field. I even tried including the `height`, `width`, and `mimeType` but still received the same response as above. The googleServiceBuild is able to properly make get calls so I don't believe anything is wrong with the build. 

Anything noticeably wrong with my code?

**Comment by busunkim96** [comment]
Hi @koskorya,

There's a fix that should expose the more specific error message (about which fields are missing), but a release hasn't been cut yet. Can you try installing the library from head?

1. make a new virtualenv `virtualenv env`
2. activate the virtualenv `source env/bin/activate`
3. clone this repo: `git clone https://github.com/googleapis/google-api-python-client.git`
4. install library from source
    ```cd google-api-python-client
    python3 -m pip install .
    ```

**Comment by koskorya** [comment]
Thanks for the prompt response @busunkim96 ,

After cloning and pip installing I am still receiving the same error message as before.

**Comment by koskorya** [comment]
Looks like the versions are the same on github as what was pip installed too

**Comment by busunkim96** [comment]
Could you try passing the body as a dict after you've encoded the photo data? You should be able to pass a plain dictionary as `body`.

```python
photo = base64.b64decode(corpPhoto)
image = base64.urlsafe_b64encode(photo)

body={"photoData": image}
googleServiceBuild.users().photos().update(userKey='EMAIL', body=body).execute()
```

**Comment by koskorya** [comment]
I receive the error
```
...v8A6CF-J__Z' is not JSON serializable
```

**Comment by koskorya** [comment]
Just for clarification, this is the response error I receive from the google api after the payload has been executed :)

**Comment by koskorya** [comment]
Any updates on this?

**Comment by busunkim96** [comment]
Hi,

I did a bit more investigation. The body is turned into JSON and bytes are not JSON serializable. See [this stackoverflow question](https://stackoverflow.com/questions/40000495/how-to-encode-bytes-in-json-json-dumps-throwing-a-typeerror).

Could you try:

```
photo = base64.b64decode(corpPhoto)
image = base64.urlsafe_b64encode(photo)

body={"photoData": image.decode('ascii')} 
googleServiceBuild.users().photos().update(userKey='EMAIL', body=body).execute()
```

I can confirm that in this case the request makes it to the backend service. (I get an error about the userKey being bad instead of about the payload). Could you try this and inspect the photo to see if it makes it there intact?

**Comment by koskorya** [comment]
Sorry but I'm receiving this response back now

```'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "parseError",\n    "message": "This API does not support parsing form-encoded input."\n   }\n  ],\n  "code": 400,\n  "message": "This API does not support parsing form-encoded input."\n }\n}\n'```

**Comment by koskorya** [comment]
Hi @busunkim96 I see my error now. I converted the photo payload to be sent as a string and also included the headers the `'Content-Type': 'application/json'` and now I successfully am able to update the photos. Sorry for the confusion!

**Comment by busunkim96** [comment]
@koskorya Glad to hear you were able to get it to work! Thank you for taking the time to let us know what fixed it for you. That should help anyone who runs into similar problems in the future. 😄
