### ISSUE TITLE
Google Calendar API 'quickstart.py' runs with Python 2.7.15+, but not with Python 3.6.8

### ISSUE THREAD

**Issue by JaroKuiken** [googleapis/google-api-python-client#774]
![GoogleCalendarAPI_Issue](https://user-images.githubusercontent.com/50826688/68021031-9bc72f80-fca0-11e9-80b1-f402d331b888.png)
I followed the Quickstart guide for the Python version of the Google Calendar API. And i got the next upcoming 10 events from my calendar, so that works. However this code runs with 'python' which corresponds to Python 2.7.15+ on my device. And i need to integrate this in a project that runs with 'python3', on my device this is Python 3.6.8. When i run 'python3 quickstart.py' instead of 'python quickstart.py' i get this error:
Traceback (most recent call last):
  File "CalendarAPI.py", line 5, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
I've tried a couple of things by googling around, but didnt manage to fix it, help?

**Comment by busunkim96** [comment]
Hi @JaroKuiken. 

I think most likely you've installed `google-api-python-client` for Python 2 but not Python 3.

Please run the command below to install the package:

```python3 -m pip install google-api-python-client```

**Comment by JaroKuiken** [comment]
Youre right, that was the problem. And this worked to fix it, thanks! But now im getting a unicoding error:

`python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 58, in <module>
    main()
  File "quickstart.py", line 28, in main
    creds = pickle.load(token)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)`

And im not sure how to fix this

**Comment by busunkim96** [comment]
You might want to try deleting the token file.

It looks like the sample you're referencing lives in the https://github.com/gsuitedevs/python-samples. Please open an issue there if that does not resolve your issue.

Thanks!
