### ISSUE TITLE
Documentation for people v1 API `create_contact` has unused kwarg `parent`

### ISSUE THREAD

**Issue by edilson-silva** [googleapis/google-api-python-client#775]
I am trying to create a contact, but I am getting the following error message.

**Exception Class:** TypeError
**Exception Message:** Got an unexpected keyword argument "parent"

**Lib version:** 1.2

```python
import httplib2
from apiclient.discovery import build
from oauth2client.file import Storage

storage = Storage('session.dat')
credentials = storage.get()

http = httplib2.Http()
credentials.authorize(http)

created_contacts = list()

new_contact = {
    'names': [
        {
            'displayName': 'Test Contact',
            'givenName': 'Test Contact',
            'displayNameLastFirst': 'Test Contact'
        }
    ],
    'phoneNumbers': [
        {
            'value': '+55 11 99999-9999',
            'canonicalForm': '+55 11 99999-9999'
        }
    ]
}

contact_info = build(serviceName='people', version='v1', http=http) \
    .people() \
    .createContact(parent='people/me', body=new_contact) \
    .execute()
```

**Comment by busunkim96** [comment]
@edilson-silva 

Oddly `parent` is listed as a kwarg but there is no more information about it in the [generated docs](http://googleapis.github.io/google-api-python-client/docs/dyn/people_v1.people.html#createContact).  It also isn't in the [REST documentation](https://developers.google.com/people/api/rest/v1/people/createContact). That may be a bug in the documentation generator. Can you try removing `parent`?

This is unrelated to the question, but please use a different library for credentials storage as oauth2client is deprecated.

**Comment by bertin0** [comment]
I experience the same issue unfortunately.

**Comment by busunkim96** [comment]
@bertin0 can you try sending a request without `parent`?

```python

contact_info = build(serviceName='people', version='v1', http=http) \
    .people() \
    .createContact(body=new_contact) \
    .execute()
```

**Comment by bertin0** [comment]
I just checked and it seems to work. Thanks for the workaround. (Why didn't I think about this?)

**Comment by busunkim96** [comment]
Thanks for reporting back! It looks like this is a documentation bug.
