### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by JaroKuiken** [googleapis/google-api-python-client#776]
So ive been trying to integrate the Google Calendar API quickstart code into python 3 for a few days now. Seeing some progress, but i now have an error with unicoding that i cant manage to fix.
![image](https://user-images.githubusercontent.com/50826688/68092806-561c8980-fe8f-11e9-92b3-0eb7621b9c0f.png)
From the googling ive done i think its something to do with the open() function and how that can 
sometimes go wrong with unicoding if the file has certain weird characters in it? Im not sure though
This is my code:
![image](https://user-images.githubusercontent.com/50826688/68094263-cf6fa880-fe9e-11e9-979a-444a6e3076cd.png)
Language: Python 3.6.8
OS: Windows 10

**Comment by busunkim96** [comment]
Hi @JaroKuiken,

As I mentioned in #774, it might be worth deleting `token.pickle` and re-running the script.

If that does not work, please open your issue on https://github.com/gsuitedevs/python-samples/issues.

Thanks!
