### ISSUE TITLE
Alerts API returns 400 Error Part 2

### ISSUE THREAD

**Issue by 4ndygu** [googleapis/google-api-python-client#777]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - If you have a question, post on Stackoverflow under the `google-api` tag.
  - If you are reporting an issue or requesting a feature for a G Suite API, please use their [public issue tracker](https://gsuite-developers.googleblog.com/2017/03/a-new-issue-tracker-for-g-suite.html)

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Darwin 18.6.0
  - Python version: 3.6.5
  - pip version: 19.2.3
  - `google-api-python-client` version:1.7.8

#### Steps to reproduce

  1. This is a clone of this issue: https://github.com/googleapis/google-api-python-client/issues/645
   2. My SA was made through the `Using OAuth 2.0 for Server to Server Applications` documentation provided as further reading to the original documentation page. I granted domain-wide access to the service account from the Servie Account panel and used that to grab the client ID. 

Code:
```
from googleapiclient.discovery import build
from google.oauth2 import service_account

class AlertCenterExtractor:

    def __init__(self):

        # build servie and scopes
        self.scopes = ["https://www.googleapis.com/auth/apps.alerts"]
        self.credentials = service_account.Credentials.from_service_account_file(
                "SERVICEACCOUNT.JSON", scopes=self.scopes)
        self.service = build('alertcenter', 'v1beta1', credentials=self.credentials).alerts()

    """ Gets alerts and writes them to output directory. """
    def get_alerts(self):
        recent_alerts = self.service.list(customerId="my_customer_id").execute()

if __name__ == '__main__':
    alert_center_class = AlertCenterExtractor()
    alert_center_class.get_alerts()
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @4ndygu. Thank you for opening a new issue.

Would you be able to show us the error you are seeing?

**Comment by 4ndygu** [comment]
Yeah - sorry! 

Here's the specific HttpError I get: 
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://alertcenter.googleapis.com/v1beta1/alerts?alt=json&customerId=C01wf96l3 returned "Request contains an invalid argument.">
```

I print the resp and the content, and this shows up:
```
{'status': '400', 'content-length': '285', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 04 Nov 2019 17:39:33 GMT', 'x-frame-options': 'SAMEORIGIN', 'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000', 'content-type': 'application/json; charset=UTF-8'}
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by iuhfiajfoisjfdisaj** [comment]
Is this a bug with the API itself and not the code? If you do a plain request, with no arguments you'll still get the invalid argument error.

```
GET /v1beta1/alerts HTTP/1.1
Host: alertcenter.googleapis.com
accept: application/json
Accept-Encoding: gzip, deflate
user-agent: (gzip)
Content-Length: 0
authorization: Bearer [ REDACTED ]
Connection: close
```

```
HTTP/1.1 400 Bad Request
Vary: Origin
Vary: X-Origin
Vary: Referer
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2019 14:28:05 GMT
Server: ESF
Cache-Control: private
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
Connection: close
Content-Length: 127

{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by busunkim96** [comment]
@iuhfiajfoisjfdisaj Thank you for the repo! If that's true it may be a backend issue. Could you also show us the body of your request?

**Comment by iuhfiajfoisjfdisaj** [comment]
@busunkim96 that's the entire request! :) Other than the redacted authorization code.

**Comment by 4ndygu** [comment]
Hi! Is there any workaround we can take at the moment for crawling GSuite Admin alerts?

**Comment by busunkim96** [comment]
Since this is a G Suite issue, I unfortunately wasn't able to debug further. I've moved this issue to https://issuetracker.google.com/issues/144282691. Someone on the G Suite team will respond there.

**Comment by Popsiclestick** [comment]
I am also currently running into this issue. Looks like the issue tracker has had some movement. That being said. The problem for this user doesn't appear to be incorrect domain-wide delegation, but even if it was. Presenting itself with a `400` and `Request contains an invalid argument` doesn't seem ideal.

**Comment by busunkim96** [comment]
@Popsiclestick would you mind commenting on the issue (or adding a +1) to indicate you are also impacted?

**Comment by iuhfiajfoisjfdisaj** [comment]
I have it working! I follow the google person's comments and added in 'subject=myemail@mydomain.com'. Small test case that works for me:

```
import json
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2 import service_account

def main():
    scopes = ["https://www.googleapis.com/auth/apps.alerts"]
    credentials = service_account.Credentials.from_service_account_file("serviceacccreds.json", subject="fd@spellbook.io", scopes=scopes)
    service = build('alertcenter', 'v1beta1', credentials=credentials).alerts()

    recent_alerts = service.list().execute().get("alerts", [])

    print(json.dumps(recent_alerts, indent=2))


if __name__ == '__main__':
    main()
```

**Comment by 4ndygu** [comment]
Thanks! I tried this code snippet, but it breaks still for me. If I'm using a GCP Service Account, could that be the problem? I've granted the scopes in GSuite to the client ID provided.

**Comment by iuhfiajfoisjfdisaj** [comment]
No idea. Here's screenshots of the account I'm using. I can't remember how I created the account originally as it was a while ago. Also make sure you've enabled the API in the first place :) 

![2019-11-15_17-09-16_screenshot](https://user-images.githubusercontent.com/1183106/68957669-cfd74000-07ca-11ea-82fa-2fa0eaa0f211.png)
![image](https://user-images.githubusercontent.com/1183106/68957724-ea111e00-07ca-11ea-9176-654b190cceee.png)

**Comment by 4ndygu** [comment]
Hi! this ended up working for us too - It seems i chose the wrong subject. Thanks!
