### ISSUE TITLE
Possible false positive?  “The insertion index cannot be within a grapheme cluster”

### ISSUE THREAD

**Issue by bsolomon1124** [googleapis/google-api-python-client#783]
From https://stackoverflow.com/q/58824877/7954504.

#### Environment details

  - OS: Ubuntu 18.04
  - Python version: 3.7.4
  - pip version: 19
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce

I'm stumped by a 400-status when using the Google Docs API to write certain Unicode characters to a Google Doc:

> HttpError: <HttpError 400 when requesting https://docs.googleapis.com/v1/documents/xxxxxxxxx:batchUpdate?alt=json returned "Invalid requests[0].insertText: The insertion index cannot be within a grapheme cluster.">

I've managed to boil this down to its smallest example.  The routine below attempts to insert (in order):

- The string of Thai characters `'ถ้ามีลูกแล้วไม่ส่งเรียนพิเศษอะไรเลย จะเป็นอะไรไหมครับ'`
- A newline, above/before the string above

Code:

```python
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/drive.file",
    "https://www.googleapis.com/auth/drive.appdata",
    "https://www.googleapis.com/auth/drive.metadata",
]

credentials = Credentials.from_service_account_file("data/gdocscredentials.json", scopes=SCOPES)
svc = build("docs", "v1", credentials=credentials).documents()

requests = [ 
    {
        "insertText": {
            "location": {
                #  The zero-based index, in UTF-16 code units
                "index": 1
            }, 
            "text": "ถ้ามีลูกแล้วไม่ส่งเรียนพิเศษอะไรเลย จะเป็นอะไรไหมครับ"
        }
    },
    {"insertText": {"location": {"index": 1}, "text": "\n"}}

]
svc.batchUpdate(
    documentId="xxxxxxxxx",
    body={"requests": requests}
).execute()
```

So, the error alludes to the Thai string containing (or being) a grapheme cluster.  The [docs refer to this](https://developers.google.com/docs/api/concepts/rules-behavior):

> The API may implicitly adjust the location to prevent insertions within Unicode grapheme clusters. When this happens, the text is inserted immediately after the grapheme cluster.

**How do I properly correct this error**?

Google [mentions that](https://developers.google.com/docs/api/how-tos/move-text_) _indexes are measured in UTF-16 code units_. But that doesn't seem like it should matter here since this code snippet is using the 'work backwards' approach that is itself recommended by the same documentation page.

**Comment by busunkim96** [comment]
Hi @bsolomon1124. I suspect this might be a question for the backend team. Have you had the chance to test this with other client libraries or the REST API directly?

**Comment by bsolomon1124** [comment]
I have not @busunkim96 .  What would be an example of a different client library where this would come into play?

**Comment by busunkim96** [comment]
@bsolomon1124 There are client libraries in other languages (Node, Java, Ruby, etc.). That said, I think the backend team will have a better answer for you. Let me move this to the appropriate issue tracker.
