### ISSUE TITLE
Googleapiclient not working with Python3 code

### ISSUE THREAD

**Issue by bansalniranjan** [googleapis/google-api-python-client#785]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - If you have a question, post on Stackoverflow under the `google-api` tag.
  - If you are reporting an issue or requesting a feature for a G Suite API, please use their [public issue tracker](https://gsuite-developers.googleblog.com/2017/03/a-new-issue-tracker-for-g-suite.html)

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: CentOS Linux release 7.7.1908 (Core)
  - Python version: 3.6.8
  - pip version: pip 9.0.3
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce

  1. We are using googleapiclient and getting following error:
STDERR>   File "/var/spool/rightlink/scripts/rll-749091021/__script-2", line 61, in <module>
STDERR>     ilbFramer = gcelb.GceILBFramer()
STDERR>   File "/var/spool/rightlink/scripts/rll-749091021/gcelb.py", line 54, in __init__
STDERR>     self.service.instances().get(project=self.project, zone=self.zone, instance=self.instance_id))[
STDERR>   File "/usr/local/lib/python3.6/site-packages/googleapiclient/discovery.py", line 740, in method
STDERR>     if re.match(regex, pvalue) is None:
STDERR>   File "/usr/lib64/python3.6/re.py", line 172, in match
STDERR>     return _compile(pattern, flags).match(string)
STDERR> TypeError: expected string or bytes-like object

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @bansalniranjan,

Can you verify that the types of the arguments you are passing are all strings or bytes?

```python
 self.service.instances().get(project=self.project, zone=self.zone, instance=self.instance_id))[
```

* self.project
* self.zone
* self.instance_id

Could you also share a bit more of your code? It would make it easier to narrow down the issue.
