### ISSUE TITLE
Unescaped <iframe> tag causes broken rendering on youtube_v3.videos.html documentation page

### ISSUE THREAD

**Issue by michaelperret** [googleapis/google-api-python-client#791]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - If you have a question, post on Stackoverflow under the `google-api` tag.
  - If you are reporting an issue or requesting a feature for a G Suite API, please use their [public issue tracker](https://gsuite-developers.googleblog.com/2017/03/a-new-issue-tracker-for-g-suite.html)

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: All
  - Python version: N/A
  - pip version: N/A
  - `google-api-python-client` version: N/A

#### Steps to reproduce

  1. Visit http://googleapis.github.io/google-api-python-client/docs/dyn/youtube_v3.videos.html
  2. Notice that only half of the `insert` method details are rendered before a phantom iframe breaks rendering for the rest of the page. This means that no methods below will be rendered properly either (ie: try to get details for `list` http://googleapis.github.io/google-api-python-client/docs/dyn/youtube_v3.videos.html#list)

#### Basic investigation:

   - The tag in question is present here https://github.com/googleapis/google-api-python-client/blob/master/docs/dyn/youtube_v3.videos.html#L389 (though a quick search shows 5 distinct results which will likely cause the issue on this page alone)

#### Potential remediation:

  - I believe these (and other HTML tags) should be wrapped in `<pre>` tags to preserve the raw text display without affecting rendering.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
@michaelperret Thanks for filing an issue! It looks like something's incorrect with our docs generation script.

**Comment by michaelperret** [comment]
👍 Happy to help! Thanks for the title update, could have been a bit more verbose upon reflection

**Comment by parthea** [comment]
Hi @michaelperret, 

I'm going to close this issue as it appears to be resolved.
