### ISSUE TITLE
Google Tag Management discovery API - Unrelated exception raised

### ISSUE THREAD

**Issue by SergeiLF** [googleapis/google-api-python-client#795]
Using client for Google Tag Management API 

`google-api-python-client==1.7.11`

`  serviceName = 'tagmanager'
    serviceName = 'v2'`

I got seems like unrelated exception when trying to list GTM container in GTM account 

` File "/env/lib/python3.7/site-packages/googleapiclient/discovery.py", line 743, in method (name, pvalue, regex)) TypeError: Parameter "parent" value "/accounts/999999999” does not match the pattern "^accounts/[^/]+$"`

Looks like initial issue is what user hits api call quota limit  and should it raise HttpError with HTTPStatus.TOO_MANY_REQUESTS

**Comment by busunkim96** [comment]
@SergeiLF would you be able to provide a longer sample? 

From looking at the error message, it looks like the format of `parent` needs to  be tweaked. Can you try changing `/accounts/999999999` to `accounts/999999999` (removing the leading forward slash)?

**Comment by SergeiLF** [comment]
@busunkim96 Thank you for your reply, yes this is solved my problem. 

Apparently new discovery file was pushed, which introduced this regex pattern for accounts path. So this my ( wrong ) path stopped work in some cases before and since yesterday everything stopped to work. I removed leading slash.
