### ISSUE TITLE
"Dependency for development" - Pycrypto remains unmaintained and buggy: use pycryptodome instead as suggested by pycrypto's offcial repository, please update the readme file for this repo!

### ISSUE THREAD

**Issue by Curiouspaul1** [googleapis/google-api-python-client#797]
Pycrypto's official repository doesn't seem to have been maintained, as such they have advised that users install Pycryptodome instead, as it creates a package with the same namespace as pycrypto, and can sync with source codes on pycrypto.
![image](https://user-images.githubusercontent.com/45743339/72294543-0cea7200-3656-11ea-8eb0-fa3d575bd873.png)

**Comment by busunkim96** [comment]
Thanks for taking the time to file an issue! It looks like we don't use it anymore (see discussion in #692) so I'll open a PR shortly to delete it any mentions of it in requirements files and READMEs.
