### ISSUE TITLE
oauth2 token is not refreshing itself

### ISSUE THREAD

**Issue by saasforge** [googleapis/google-api-python-client#807]
I'm trying to upload files to Google Drive but the problem is even if I configured the offline access I can't get the access after the access_token is expired.

From here: https://google-auth.readthedocs.io/en/latest/user-guide.html#user-credentials

> If you obtain a refresh token, you can also specify the refresh token and token URI to allow the credentials to be automatically refreshed:
> 
> credentials = google.oauth2.credentials.Credentials(
>     'access_token',
>     refresh_token='refresh_token',
>     token_uri='token_uri',
>     client_id='client_id',
>     client_secret='client_secret')

#### Environment details

  - OS: Win 7
  - Python version: Python 3.6.8
  - pip version: pip 19.3.1
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce
When I configure the obtaining consent from the user I do this code:

```
 script.onload = function() {
            gapi.load('auth2', ()=>{
                const clientId = window.googleClientId;
                const scope = 'https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.file';
                let config = {
                    clientId: clientId,
                    scope: scope
                };
                this.googleAuth = gapi.auth2.init(config);
 });
```
Then
`this.googleAuth.grantOfflineAccess() // Obtain the auth code`

 I then change this code to the tokens:

```
from oauth2client import client
    json_path = os.path.join(static_folder_path, "client_secrets.json")
    credentials = None
    try:
        credentials = client.credentials_from_clientsecrets_and_code(
            json_path,
            scopes,
            auth_code)
    except Exception as ex:
        print(ex)
        return None
    return {
        'access_token': credentials.access_token,
        'refresh_token': credentials.refresh_token
    }
```
But when I try to make upload itself it works only during one hour:

```
credentials = google.oauth2.credentials.Credentials(user_access_token,
                                                        refresh_token = user_refresh_token,
                                                        token_uri = 'https://oauth2.googleapis.com/token',
                                                        client_id = get_config_var('GOOGLE_CLIENT_ID'),
                                                        client_secret = get_config_var('GOOGLE_CLIENT_SECRET')
    )

drive_service = build('drive', 'v3', credentials=credentials)
fd = io.BytesIO(file_bytes)
body = {'name': file_name, 'mimeType': 'application/pdf'}
media_body = MediaIoBaseUpload(fd = fd, mimetype='application/pdf')
file = drive_service.files().create(body=body,
                                            media_body=media_body,
                                            fields='id').execute()
```
After one hour, I have the following exception:

`('invalid_client: Unauthorized', '{\n  "error": "invalid_client",\n  "error_description": "Unauthorized"\n}')`

From here https://github.com/googleapis/google-api-python-client/issues/605#issuecomment-447958017 it says I don't need to do anything special and the client will refresh the token itself. But there is no any indication on what should be done and how it should work "itself". Please help!

**Comment by busunkim96** [comment]
Hi @saasforge,

You are using oauth2client, not google-auth. oauth2client is the previous auth client and is now deprecated. I am not sure if oauth2client had support for automatically refreshing tokens.

To form credentials with google-auth and then pass them to google-api-pytohn client you would do something like this:

You do not need to fill out all the fields in the Credentials. See https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials for which are required.
```python
from google.oauth2 import credentials
from googleapiclient import discovery

credentials = credentials.Credentials(
    "access_token",
    refresh_token="refresh_token",
    token_uri="token_uri",
    client_id="client_id",
    client_secret="client_secret",
)

service = discovery.build("drive", "v3", credentials=credentials)
```

**Comment by saasforge** [comment]
Thanks for your response!

> You are using oauth2client, not google-auth. oauth2client is the previous auth client and is now deprecated. I am not sure if oauth2client had support for automatically refreshing tokens.

What is the difference between my and your code? I use google-auth too:
```

credentials = google.oauth2.credentials.Credentials(user_access_token,
                                                        refresh_token = user_refresh_token,
                                                        token_uri = 'https://oauth2.googleapis.com/token',
                                                        client_id = get_config_var('GOOGLE_CLIENT_ID'),
                                                        client_secret = get_config_var('GOOGLE_CLIENT_SECRET')
    )

drive_service = build('drive', 'v3', credentials=credentials)
```
Your code: 

> 
> ```python
> from google.oauth2 import credentials
> from googleapiclient import discovery
> 
> credentials = credentials.Credentials(
>     "access_token",
>     refresh_token="refresh_token",
>     token_uri="token_uri",
>     client_id="client_id",
>     client_secret="client_secret",
> )
> 
> service = discovery.build("drive", "v3", credentials=credentials)
> ```

**Comment by busunkim96** [comment]
Would you mind pasting a full code snippet instead? I'm a bit confused on which bits of code you're combined. I was under the impression you were using oauth2client because of:

```
from oauth2client import client
    json_path = os.path.join(static_folder_path, "client_secrets.json")
    credentials = None
    try:
        credentials = client.credentials_from_clientsecrets_and_code(
            json_path,
            scopes,
            auth_code)
    except Exception as ex:
        print(ex)
        return None
    return {
        'access_token': credentials.access_token,
        'refresh_token': credentials.refresh_token
    }```

**Comment by saasforge** [comment]
Right, I thought you were talking about the second part what is done using google-auth.

Maybe you just tell me instead how I could implement the same functionality of the first part (exchanging the authorization code for access and refresh tokens) using google-auth only? Because the code you gave is about only the second part when you already obtained the tokens but not about exchanging.

Thanks!

**Comment by saasforge** [comment]
Thanks for your response!

> You are using oauth2client, not google-auth. oauth2client is the previous auth client and is now deprecated. I am not sure if oauth2client had support for automatically refreshing tokens.

What is the difference between my and your code? I use google-auth too:
```

credentials = google.oauth2.credentials.Credentials(user_access_token,
                                                        refresh_token = user_refresh_token,
                                                        token_uri = 'https://oauth2.googleapis.com/token',
                                                        client_id = get_config_var('GOOGLE_CLIENT_ID'),
                                                        client_secret = get_config_var('GOOGLE_CLIENT_SECRET')
    )

drive_service = build('drive', 'v3', credentials=credentials)
```
Your code: 

> 
> ```python
> from google.oauth2 import credentials
> from googleapiclient import discovery
> 
> credentials = credentials.Credentials(
>     "access_token",
>     refresh_token="refresh_token",
>     token_uri="token_uri",
>     client_id="client_id",
>     client_secret="client_secret",
> )
> 
> service = discovery.build("drive", "v3", credentials=credentials)
> ```

**Comment by saasforge** [comment]
I accidentally closed the issue (thinking it would work to cancel comment :-0 ) sorry.

**Comment by parthea** [comment]
Hi @saasforge,

I'm sorry that it took so long to respond. I wasn't able to re-produce the problem. I'm going to close this issue due to inactivity but if you're still having trouble please re-open the issue.
