### ISSUE TITLE
chromeosdevices not handling customerId

### ISSUE THREAD

**Issue by daveisagit** [googleapis/google-api-python-client#810]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - If you have a question, post on Stackoverflow under the `google-api` tag.
  - If you are reporting an issue or requesting a feature for a G Suite API, please use their [public issue tracker](https://gsuite-developers.googleblog.com/2017/03/a-new-issue-tracker-for-g-suite.html)

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows 10
  - Python version: 3.7
  - pip version: 19.3
  - `google-api-python-client` version: 1.7.11

#### Steps to reproduce
from googleapiclient.discovery import build
from google.oauth2 import service_account
SCOPES = ['https://www.googleapis.com/auth/admin.directory.device.chromeos']
SERVICE_ACCOUNT_FILE=os.path.join(dir_path,'my-path')
credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)
credentials = credentials.with_subject('my-impersononation')
service = build('admin', 'directory_v1', credentials=credentials)    

Then A
results = service.chromeosdevices()
gives TypeError: Missing required parameter "customerId"

Now B
results = service.chromeosdevices(customerId='##myId##')
gives: TypeError: methodResource() got an unexpected keyword argument 'customerId'

**Comment by daveisagit** [comment]
FYI, same issue also with service.mobiledevices

**Comment by busunkim96** [comment]
Hi @daveisagit, I'm not able to replicate the error. The discovery doc may have been fixed since you opened the issue. Would you mind trying again?

```python
from googleapiclient import discovery

service = discovery.build("admin", "directory_v1")
results = service.chromeosdevices()
```

**Comment by daveisagit** [comment]
Hi, turns out the customerId is parameter to list() and not service.chromeosdevices().
So it works fine using
results = service.chromeosdevices().list(customerId='##myId##')
Sorry for my misunderstanding.
Thanks
Dave
