### ISSUE TITLE
get_current_user() py2 userid different than google admin directory user id

### ISSUE THREAD

**Issue by koskorya** [googleapis/google-api-python-client#818]
#### Environment details

  - OS: Ubuntu
  - Python version: 2.7 vs 3.7
  - pip version:
  - `google-api-python-client` version:

#### Steps to reproduce

  1. Currently migrating a python2.7 app on google app engine to python 3.7
  `from google.appengine.api.users import get_current_user` returns a `User` object with a property  ```"user_id": {
      "stringValue": "101342104126303287634"
    }```
2. When I query the same user with the google admin directory api, I receive the response`'id': '108828824026963599070'`

Why are these id's different if they are the same google user?

Thanks!

**Comment by parthea** [comment]
Hi @koskorya,

I'm going to close this issue due to inactivity. If you're still having trouble please re-open it with more information.
