### ISSUE TITLE
"Policy members must be of the form "<type>:<value>" error returned when calling "SetIAmPolicy"

### ISSUE THREAD

**Issue by qxh5696** [googleapis/google-api-python-client#819]
Hi, 

When I try using the `service.projects().setIamPolicy(...)` function  I get the error above and I haven't been able to find any other resources that could help.  
This is my first time leaving a bug report so please be excuse me if I forget any relevant information, I'm trying to give as many details as possible that doesn't disclose any sensitive information.  

#### Environment details

  - OS: macOS Mojave
  - Python version: 3.7.4
  - pip version: pip 19.3.1 
  - `google-api-python-client` version: 1.7.4

I have the same code as in the Google Cloud documentation example for this function (
[code here](https://cloud.google.com/resource-manager/reference/rest/v1/projects/setIamPolicy?apix_params=%7B%22resource%22%3A%22thoughtlabs%22%2C%22body_resource%22%3A%7B%22policy%22%3A%7B%22bindings%22%3A%5B%7B%22role%22%3A%22roles%2Fresourcemanager.organizationAdmin%22%2C%22members%22%3A%5B%22qadir%40altitudenetworks.com%22%5D%7D%5D%2C%22etag%22%3A%22BwWXuH%2FZgpc%3D%22%2C%22version%22%3A1%7D%7D%7D)) except I of course have the resource set to the value that I need and I am filling out the `set_iam_policy_request_body`. 

The structure of my `set_iam_policy_request_body` is of the following form:
```
set_iam_policy_request_body ={
    "policy":{
        "bindings":[{
            "role":"roles/resourcemanager.organizationAdmin",
            "members":["qxh5696@company.com"]   
        }],
        "etag":"BwWXuH/Zgpc=",
        "version":1
    }
}
```

Executing the request gives me this full error: 
```
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-72-b287313a569d> in <module>
     18 request = service.projects().setIamPolicy(resource=resource, body=
     19                                                set_iam_policy_request_body)
---> 20 response = request.execute()
     21 print(response)

~/.local/share/virtualenvs/local_dev-a5dmjvDN/lib/python3.7/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131         return positional_wrapper
    132 

~/.local/share/virtualenvs/local_dev-a5dmjvDN/lib/python3.7/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    840       callback(resp)
    841     if resp.status >= 300:
--> 842       raise HttpError(resp, content, uri=self.uri)
    843     return self.postproc(resp, content)
    844 

HttpError: <HttpError 400 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/resource:setIamPolicy?alt=json returned "Policy members must be of the form "<type>:<value>".">
```

When I run `getIAMPolicy` I get a successful request, and when I run try running the `setIamPolicy` function in the "Try This API" pane on its documentation page (with the same information of course), I don't get a 400 error. 

Any help on this issue would be appreciated.

Thanks!

**Comment by busunkim96** [comment]
Hi @qxh5696.

It looks like you need to specify a type for each member.

See the JSON example below (from https://cloud.google.com/resource-manager/reference/rest/Shared.Types/Policy)

```json
{
  "bindings": [
    {
      "role": "roles/resourcemanager.organizationAdmin",
      "members": [
        "user:mike@example.com",
        "group:admins@example.com",
        "domain:google.com",
        "serviceAccount:my-project-id@appspot.gserviceaccount.com"
      ]
    },
    {
      "role": "roles/resourcemanager.organizationViewer",
      "members": ["user:eve@example.com"],
      "condition": {
        "title": "expirable access",
        "description": "Does not grant access after Sep 2020",
        "expression": "request.time < timestamp('2020-10-01T00:00:00.000Z')",
      }
    }
  ],
  "etag": "BwWWja0YfJA=",
  "version": 3
}
```
