### ISSUE TITLE
Google Calendar API Documentation Missing

### ISSUE THREAD

**Issue by jason-cf** [googleapis/google-api-python-client#821]
#### Environment details

  - OS: MacOS Catalina
  - Python version: 3.6.9
  - pip version: 19.3.1
  - google-api-python-client==1.7.11
  - google-auth-httplib2==0.0.3
  - google-auth-oauthlib==0.4.1
  - google-auth==1.10.1

#### Steps to reproduce

  1. It states here https://developers.google.com/calendar/v3/sync that a GoogleJsonResponseException will be returned in Java if a sync token can not be returned. Currently I have the following:

```
events = service.events().list(calendarId='primary', syncToken=sync_token, pageToken=page_token).execute()
except Exception as e:
    if 'code' in e and e.code == 410:	#sync token was invalidated, full sync required
        #clear token, call full sync
```
Is there documentation in python for how an invalidated sync token is handled?
<br><br><br>

  2. Is there python documentation that shows the client library automatically refreshing the access token after .execute()? For example, doing the following appears to show the client library automatically refreshing my access token:

```
credentials = pickle.loads(user.google_api_credentials)	
print(credentials.valid) #false
event_results = service.events().list(calendarId='primary', singleEvents=True).execute()
print(credentials.valid) #true after calling .execute() in the line above. 
```
Does this confirm using the python library will guarantee automatic refreshing of the access_token without requiring extra code?
<br><br><br>

**Comment by busunkim96** [comment]
@jason-cf Could you let us know which auth library you are using?

**Comment by jason-cf** [comment]
hey @busunkim96, I'm using the following:

google-api-python-client==1.7.11
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-auth==1.10.1

**Comment by jason-cf** [comment]
@busunkim96 thanks for taking my issue. I know the documentation can take a while, but could you give me a hint on what an error response should look like for an invalidated sync token? Any valid, sample python code would do too. That'd help me get back on track again. Greatly appreciate your time.

**Comment by busunkim96** [comment]
Ah sorry, I originally thought you were working with an OAuth2 token but I see there is a Calendar API specific `syncToken`. 

The regular auth token will be refreshed for you, but the library will not refresh the `syncToken`. You should continue to handle that yourself by looking at the response code.

http://googleapis.github.io/google-api-python-client/docs/dyn/calendar_v3.events.html#list is the current documentation for the Calender Events API.

**Comment by jason-cf** [comment]
@busunkim96, awesome you could confirm 'question 2' for me. That's really helpful. Thank you!

I'm still a little confused about the `syncToken` though. I'm still not totally sure what type of error the `google-api-python-client` will return. In the java example, `GoogleJsonResponseException` is thrown with a status code https://developers.google.com/calendar/v3/sync, but for the python library, I only see these error types https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/errors.py

It appears from the documentation that all errors, including `syncToken` errors should take the form of https://developers.google.com/calendar/v3/errors

Does this mean we'd need to get the 410 status code like this:

```
events = service.events().list().execute()
except googleapiclient.error.Error as e:
    if 'code' in e and e.code == 410:
        #clear token, call full sync
```

I guess, how exactly, would I extract the 410 Gone response with the google-api-python-client? A code example would be super helpful.

**Comment by busunkim96** [comment]
Here are a few links that might be helpful:

This library uses httplib2. I believe you can use `resp` to get `resp.status` (the actual status code).
https://github.com/googleapis/google-api-python-client/blob/4c84c2c93735e5cff8d67dd4eee2035ac7526195/googleapiclient/errors.py#L40
https://httplib2.readthedocs.io/en/latest/libhttplib2.html#response-objects

I'll try to circle back to this this week, but didn't want to hold you up any longer.

**Comment by jason-cf** [comment]
Hi @busunkim96, your response has been very helpful to get me going again! I'll give this a try in my code! Thanks again!

**Comment by danlo9** [comment]
@jason-cf Did you have any success figuring out how to extract the error type? Does the code from Feb 13 work?

**Comment by jason-cf** [comment]
Hi @danlo9,

Yup, @busunkim96 got the answer for me. This is how my code looks:

```
try:
  #attempt incremental sync
except RefreshError as e:
  #signout because token was invalidated
except HttpError as e:
  if e.resp.status == 410:
     #remove sync token, do a full sync


```

**Comment by danlo9** [comment]
@jason-cf Thanks. This might be a silly question, but what is `RefreshError`?

Also, when I do
```python
try:
    service.events().list(calendarId="primary", syncToken=sync_token, pageToken=page_token).execute()
except urllib.error.HTTPError as e:
    print(e.resp.status)
```
I am still not catching the error. Is there something I am missing?

**Comment by jason-cf** [comment]
Try these imports:

```
from googleapiclient.errors import HttpError
from google.auth.exceptions import RefreshError
```

To the best of my knowledge, `RefreshError` happens when the sync token is invalided for any number of reasons such as the user changes their password, manually revokes permissions, or they've used the same token for 6 months. 

You'll need to account for `RefreshError` in your code as well. When we get a `RefreshError`, we sign them out of google calendar and give the user a message that they need to reconnect.
