### ISSUE TITLE
python docker support

### ISSUE THREAD

**Issue by exptaelee** [googleapis/google-api-python-client#826]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

does this api and oauth work with python docker image?  I've deployed docker image with credential.json but when container executes the python code, it prompts to go authorize:

```
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=.....
```

**Comment by busunkim96** [comment]
Hi @exptaelee,

 It is possible to use this library inside of a docker image. Regardless of what environment you are in, you will need to have valid credentials to use APIs.

For applications, it is generally recommended you use a service account instead, but some APIs that require access to user data do not support this.

Here is some more reading:
* [Using OAuth 2.0 for Web Server Applications](https://developers.google.com/identity/protocols/OAuth2WebServer)
* [OAuth 2.0 for Service Accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount)

**Comment by exptaelee** [comment]
@busunkim96 I am trying to get googlesheet data.  Does it also require service account?

**Comment by busunkim96** [comment]
You will need to use user credentials. Please reference the instructions at https://developers.google.com/identity/protocols/OAuth2WebServer. Thanks!

**Comment by dharmendrakariya** [comment]
> @busunkim96 I am trying to get googlesheet data. Does it also require service account?

did you figure out bro? Having same kind of requirement!
