### ISSUE TITLE
Proper way to create a service documentation discrepancy 

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-python-client#830]
The documentation [Drive python quickstart](https://developers.google.com/drive/api/v3/quickstart/python) and [Sheets python quickstart](https://developers.google.com/sheets/api/quickstart/python)

Have two different ways of building the services.  Which one is the best practice?

    serviceDrive = build('drive', 'v3', http=creds.authorize(Http()))
    serviceSheets = build('sheets', 'v4', credentials=creds)

**Comment by busunkim96** [comment]
@LindaLawton I'd recommend the latter. `serviceSheets = build('sheets', 'v4', credentials=creds)`.

When I view the drive quickstart it seems to use the `credentials=creds` as well. Perhaps it's been updated recently?

**Comment by LindaLawton** [comment]
yeah very recently because it wasn't updated when i posted :)
