### ISSUE TITLE
Does this Library support the Google Cloud Run API? 

### ISSUE THREAD

**Issue by Thorbenl** [googleapis/google-api-python-client#831]
I was wonderin if this client supoprts the Google Cloud Run API. This doesnt seem to be well documented. I also cant use the API explorer to explore the Google Cloud Run API.

**Comment by busunkim96** [comment]
Yes it does. 

See http://googleapis.github.io/google-api-python-client/docs/dyn/run_v1.html. 

You can build a client by doing:

```py
from googleapiclient import discovery

client = discovery.build("run", "v1")
```

What are you looking to do?

**Comment by intjelic** [comment]
OK, we can build one, but why there isn't a package like `google-cloud-run` to remain consistent with the other APIs ? Just a question though, I'm new to this and I'm trying to make sense of how everything is organized. Did I miss something obvious ? Thanks!

**Comment by busunkim96** [comment]
@intjelic We don't have 100% coverage of the APIs via the `google-cloud-*` packages at the moment. It doesn't look like we have a gRPC based client for the Cloud Run API.

@averikitsch Do you know if there are any plans for Cloud Run libraries?

**Comment by averikitsch** [comment]
There are no plans to generate a `google-cloud-*` library for Cloud Run. Cloud Run is built upon the Knative spec; therefore the API matches the declarative nature of Kubernetes, for example [create a service via the API](https://cloud.google.com/run/docs/reference/rest/v1/namespaces.services/create). I have experience using this library if you have any questions.
