### ISSUE TITLE
Is there an api to review and launch an already uploaded apk on the store?

### ISSUE THREAD

**Issue by SebaRossi94** [googleapis/google-api-python-client#836]
Hello i've been doing some research and testing with the set of apis provided by androidpublisher v3, specifically with the edits tool.
I was able to succesfully upload an apk to an already created app on the google play console by creating a new versio but i wasn't able to actually review and launch this newly created version.
Is there an api to do this specific action? I haven't been able to find it.
So far i had to enter the console through a web browser and do this manually, so any help is welcomed.
Thanks in advance

**Comment by busunkim96** [comment]
Hi @SebaRossi94, I'm not sure if there's an API with support with that. Please reach out to [Google Play Support](https://support.google.com/googleplay/answer/7100415?hl=en) with your question.

Thanks!
