### ISSUE TITLE
discovery is urlencoding google_api and causing 404 not found

### ISSUE THREAD

**Issue by mvfpoa** [googleapis/google-api-python-client#838]
Hi,

When I try to create an event, the url become encoded: calendarId changes from some@calendar.com to some%40calendar.com. Google reports 404.

#### Environment details

Ubuntu DiscoDingo
Python 3.7.3
pip 20.0.2
google-api-python-client==1.7.12
httplib2==0.17.0

#### Steps to reproduce

1. run the following code:
```javascript
import google.auth
from googleapiclient.discovery import build

SCOPES=['https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/gmail.send']

cred, _ = google.auth.default(scopes=SCOPES)

cred = cred.with_subject('my@domain.com')

service = build('calendar', 'v3', credentials=cred)

body = {'attendees': None, 
        'end': {'dateTime': '2020-03-20T09:30:00+00:00'}, 
        'extendedProperties': {'private': None}, 
        'id': '123123', 
        'location': None, 
        'privateCopy': False, 
        'start': {'dateTime': '2020-03-20T08:00:00+00:00'}, 
        'summary': 'Ensaio', 
        'transparency': 'opaque'}

print(service.events().insert(calendarId='teste@test.com', body=body, sendUpdates='externalOnly').execute())
```
2. expect to see google api response, but the following message comes:

venv/lib/python3.7/site-packages/googleapiclient/http.py", line 898, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/teste%40test.com/events?sendUpdates=externalOnly&alt=json returned "Not Found">

Thanks!

**Comment by busunkim96** [comment]
Hi @mvfpoa, the url encoding is working as intended (the http request would be invalid otherwise). Can you confirm that the credentials you are using have permissions to that calendar? You will get a 404 if the credentials don't have sufficient permissions?

**Comment by mvfpoa** [comment]
Instead of using discovery, I am using `print(AuthorizedSession(cred).post("https://www.googleapis.com/calendar/v3/calendars/equipe@overviewtour.com/events?sendUpdates=externalOnly&alt=json", json=body))` and it works flawlessly.
Is there any other library dependency which might be involved in my particular problem, so we can check versions?

**Comment by mvfpoa** [comment]
I decided to have a shot again in the sample code and the returning error changed completely. Now it says 409 "The requested identifier already exists.". I removed my custom Id from json, and the event was created as expected. I think the problem was solved some other way, and was related to the short id i was trying to create.
I am marking it closed for instance.
