### ISSUE TITLE
HttpError 409 : The requested identifier already exists

### ISSUE THREAD

**Issue by spady7** [googleapis/google-api-python-client#846]
Hi, I'am using this library in a python script that updates google calendar importing iCal event from exchange calendar.
I noticed that everytime i delete a event on google calendar, script report following error:

> Traceback (most recent call last):
  File "sync.py", line 269, in <module>
    service.events().insert(calendarId=CALENDAR_ID, body=gcal_event).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/calendar/v3/calendars/email%40gmail.com/events?alt=json returned "The requested identifier already exists."

>During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "sync.py", line 272, in <module>
    service.events().update(calendarId=CALENDAR_ID, eventId=gcal_event['id'], body=gcal_event).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/email%40gmail.com/events/040000008200e00074c5b7101a82e00800000000a919fe59b1e1d501000000000000000010000000f7c9feba25262d43acb8813e44de5cbc15831936001583366400?alt=json returned "Forbidden"

Deleted event are also deleted into "Bin".
From now i cannot use that G calendar anymore. Always get this error. If i create a new calendar, script works without errors.
First time i delete an event, issue raise again.
Any idea?

regards

**Comment by busunkim96** [comment]
Hi,

The first error seems to be the result of the event already existing. You mention deleting an event, but the script seems to be inserting events?  Can you please clarify when you're seeing this error? A more complete code sample would also be helpful.

**Comment by parthea** [comment]
Hi @spady7,

I'm going to close this issue but if you're still having trouble please re-open it with additional information.

**Comment by mohalhashem** [comment]
This issue happens when I delete an event and then try to add a new event that has the same iCalUID. I think it's a bug.

**Comment by akulbe-tnm** [comment]
I'm hitting this exact same issue. We're importing an .ics file into a brand new calendar, and I end up hitting this after several events import successfully.
