### ISSUE TITLE
Add gmail api sample

### ISSUE THREAD

**Issue by gabriel-caixeta** [googleapis/google-api-python-client#849]
There is no sample code for the Gmail API in this repository.

**Comment by busunkim96** [comment]
Hi @gabriel-caixeta. The GSuite API samples live in a different repository. There is a published quickstart [here](https://developers.google.com/gmail/api/quickstart/python). If you'd like to see more samples, please file an issue at [gsuitedevs/python-samples](https://github.com/gsuitedevs/python-samples/issues). Thanks!

**Comment by gabriel-caixeta** [comment]
Hi @busunkim96 , I hadn't seen that, will take a look at the documentation over gsuitedevs.
Thanks!
