### ISSUE TITLE
Batch request for oauth2 token refresh requests returns 400 Bad Request. "Invalid grant_type: refresh_token\n"

### ISSUE THREAD

**Issue by himalr** [googleapis/google-api-python-client#853]
Hi, I'm having a similar issue like #605 with batch requests. single requests are working without any issues. I've also tried different URLs such as https://oauth2.googleapis.com/batch and https://oauth2.googleapis.com/token

Pay attention to the "error_description". it says, "Invalid grant_type: refresh_token\n". notice the trailing new line. no, I'm not adding a new line by mistake.  there's only one `0A` after "refresh_token" according to my debugger proxy.

- OS: Windows 10 (x64)
- Python: 3.7 (x64)
- pip: 20.0.2
- google-api-python-client: 1.8.0

```python

# I'm generating the batch request like this
from  googleapiclient.http import HttpRequest, BatchHttpRequest

batch = BatchHttpRequest(batch_uri="https://oauth2.googleapis.com/batch")

HttpRequest(httplib2.Http(), uri='https://www.googleapis.com/oauth2/v4/token',
    method='POST', body=urllib.parse.urlencode({...}),
    headers={'content-type': 'application/x-www-form-urlencoded; charset=utf-8'} 
    # same without charset part.
)

```

**Request**

>POST https://www.googleapis.com/batch/oauth2/v4 HTTP/1.1
Host: www.googleapis.com
Content-Length: 646
content-type: multipart/mixed; boundary="===============1760440384997082996=="
user-agent: Python-httplib2/0.15.0 (gzip)
accept-encoding: gzip, deflate
>
>--===============1760440384997082996==
Content-Type: application/http
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-ID: <0ae71ae8-f29d-49c2-8f7e-2825e5390c0a + 1>
>
>POST /oauth2/v4/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
MIME-Version: 1.0
Host: www.googleapis.com
content-length: 268
>
>refresh_token=1%2F%2F0xxx-xxx-xxx&client_id=xxx-xxx.apps.googleusercontent.com&client_secret=xxx&grant_type=refresh_token
--===============1760440384997082996==--

**Response**

>HTTP/1.1 200 OK
Content-Type: multipart/mixed; boundary=batch_Ar3M4Bkc_au_CKOR3z5hQgUHTAueQTIY
Vary: Origin
Vary: X-Origin
Vary: Referer
Date: Thu, 26 Mar 2020 13:11:08 GMT
Server: ESF
Cache-Control: private
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
Content-Length: 410
>
>
>--batch_Ar3M4Bkc_au_CKOR3z5hQgUHTAueQTIY
Content-Type: application/http
Content-ID: <response-0ae71ae8-f29d-49c2-8f7e-2825e5390c0a + 1>
>
>HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Vary: Origin
Vary: X-Origin
Vary: Referer
>
>{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type: refresh_token\n"
}
--batch_Ar3M4Bkc_au_CKOR3z5hQgUHTAueQTIY--

Thanks

**Comment by busunkim96** [comment]
Hi @himalr, thanks for opening an issue.

You mention that there's an extra `0A` being sent in the request. Perhaps I'm misunderstanding, but isn't  `U+000A` the [newline character](https://en.wikipedia.org/wiki/Newline)?

Does executing the same request as a single (non-batch) request work as intended?

Could you show us how you're constructing the body in more detail?

```py
    body = urllib.parse.urlencode({
               "refresh_token": "assertion",
               "client_id': "client_id",
               "client_secret': "client_secret",
               "grant_type": "refresh_token"
           })
```

**Comment by himalr** [comment]
Hello @busunkim96, thanks for looking into this. 

Yes, it's the newline character, but I believe there should be one before the boundary string, right?

Yes, I can execute the request generated using the same method individually without any issue.

This is how that part (refresh_token[\n]--===============) looks like in the request in hex.

>726566726573685F746F6B656E0A2D2D3D3D3D3D3D3D3D3D3D3D3D3D3D3D3D

```python
request = HttpRequest(http=httplib2.Http(), postproc=_postproc_cb,
    uri='https://oauth2.googleapis.com/token',
    method='POST',
    body=urllib.parse.urlencode({
        'refresh_token': credentials.refresh_token,
        'client_id': credentials.google_app.client_id,
        'client_secret': credentials.google_app.client_secret,
        'grant_type': 'refresh_token'
    }),
    headers={'content-type': 'application/x-www-form-urlencoded'})
```

Please let me know if you need any additional details or want me to test something. thanks again.

**Comment by parthea** [comment]
Hi @himalr,

I'm going to close off this issue due to inactivity. If you're still having trouble, please re-open it and we can take a look.
