### ISSUE TITLE
Uploading a Google Apps Script file

### ISSUE THREAD

**Issue by dpdani** [googleapis/google-api-python-client#855]
Hello, I have this piece of code and I would expect it to upload a Google Apps Script file, as I believe I'm specifying the correct mime type.
What happens instead is that it uploads a Google Docs file which does have the correct contents.

```python
drive_service.files().create(
    body={
        'name': "...",
        'mimeType': 'application/vnd.google-apps.script',
    },
    media_body=MediaFileUpload(path, mimetype='text/plain'),
    fields='id',
).execute()
```

I found a slightly similar [issue](https://github.com/googleapis/google-api-nodejs-client/issues/680) on the NodeJS client repo, but I couldn't really get it to work on the Python client.
Also, it most probably doesn't apply to my problem, since I do receive a 200 response.

#### Environment details

  - OS: Linux
  - Python version: 3.8
  - pip version: 20.0.2
  - `google-api-python-client` version: 1.8.0

**Comment by busunkim96** [comment]
Could you try specifying the mimeType in `media_body` instead?

```py
drive_service.files().create(
    body={
        'name': "...",
    },
    media_body=MediaFileUpload(path, mimetype='application/vnd.google-apps.script'),
    fields='id',
).execute()

**Comment by dpdani** [comment]
It seems I can't put anything other than `text/plain` in that mime type, because every other value I've tested returns a 400 response.

Here's the traceback:
```
Traceback (most recent call last):
  ...
  File "...", line 150, in upload_file
    f = drive_service.files().create(
  File ".../.venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File ".../.venv/lib/python3.8/site-packages/googleapiclient/http.py", line 898, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart returned "Bad Request">
```

**Comment by dpdani** [comment]
Hello,

I'm sorry to just ping this conversation, but this is holding my work back.
Is there any update on this issue?

**Comment by busunkim96** [comment]
Apologies for the late response. I unfortunately haven't had the bandwith to look further.

 Could you try testing this out with the "Try this API" on the right hand side of [this page](https://developers.google.com/drive/api/v3/reference/files/create) and let me know if this works as expected with the REST API? This will help narrow down if the issue is with the API or the library.

**Comment by dpdani** [comment]
I'm struggling to work with the API Explorer: I don't quite understand how to select a file to upload from its interface.

**Comment by busunkim96** [comment]
Hi, sorry for the delay. I've tested the code below and it works for me. It looks like you need to pass a specific mimetype for `MediaFileUpload`. 

If you're interested in uploading other types of files you can figure out the correct MimeType for the file upload object by referencing [G Suite documents and corresponding export MIME types](https://developers.google.com/drive/api/v3/ref-export-formats).

```py
drive_service = discovery.build("drive", "v3", credentials=creds)

path = "example.gs"
drive_service.files().create(
    body={
        'name': "example.gs",
        'mimeType': 'application/vnd.google-apps.script',
    },
    media_body=MediaFileUpload(path, mimetype='application/vnd.google-apps.script+json'),
    fields='id',

).execute()
```

**Comment by dpdani** [comment]
Hi, I've never found that documentation page, thank you for pointing me in the right direction.

Maybe it should be referenced from [this doc page](https://developers.google.com/drive/api/v3/manage-uploads)?

Also, why is the `+json` only needed in the MediaFileUpload argument and not in the body dict?
If you wouldn't have pointed that out to me I would probably have never figured it out.

**Comment by dpdani** [comment]
I wrote the previous response without testing first and unfortunately, I couldn't get your snippet to run. I'm still getting a 400 response from Google, even with the git version of your library instead of the PyPI one.

**Comment by busunkim96** [comment]
Are you passing a valid AppScript file? The `+json` comes from the apps script file format being JSON, I believe. 

Here's the one that I used:

example.gs
```json
{
   "files": [
      {
         "id": "795bfe7b-1095-40fe-9dab-37c516db01db",
         "name": "appsscript",
         "type": "json",
         "source": {
            "timeZone": "America/Los_Angeles",
            "dependencies": {},
            "exceptionLogging": "STACKDRIVER",
            "runtimeVersion": "V8"
         }
      },
      {
         "id": "c248e656-319c-46a8-88ab-6da545bf7d16",
         "name": "Code",
         "type": "server_js",
         "source": "function myFunction() {\n  console.log(\"Hello World!\")\n}\n"
      }
   ]
}
```

For the documentation, would you mind scrolling to the bottom of the page and submitting feedback via the "Send Feedback" button? That is the best way for the current owner of the page to see the feedback. https://developers.google.com/drive/api/v3/manage-uploads#import_to_google_docs_types_

**Comment by kyrlon** [comment]
I am also having this issue. Using the python-client , I am attempting to upload a simple text file to GoogleDrive as a GoogleScript file, however it continues to be created as a GoogleDoc instead. From the reference [here](https://developers.google.com/drive/api/v3/manage-uploads#tabpanel-python:~:text=plain%20text%20(special%20MIME%20type)%2C%20JSON), "plain text (special MIME type), JSON" is not explicit on other types of MIME that can be used to make a plain text file into a GS file in my drive folder.

**Comment by dpdani** [comment]
Yes, you were having the same issue as me.
Make sure you set the mime type to `application/vnd.google-apps.script+json`.
This should fix your issue.
