### ISSUE TITLE
siterestrict() AttributeError

### ISSUE THREAD

**Issue by whatsananne** [googleapis/google-api-python-client#864]
#### Environment details

  - OS: MacOS
  - Python version: 3.6.8
  - pip version: 19.1.1
  - `google-api-python-client` version:

#### Steps to reproduce
Hello,

When I use the following code:

```
service = build("customsearch", "v1", developerKey=<your_api_key>)
res = service.cse().siterestrict().list(
    q=query_word,
    cx=<your_custom_search_id>,
).execute()
```
I receive the following error:
```
    res = service.cse().siterestrict().list(
AttributeError: 'Resource' object has no attribute 'siterestrict'
```

Strangely, I do not receive this error all the time, but most of the time (unclear of a specific percentage). Without siterestrict(), I do not receive this error at all. Is there any reason why? I do have my CSE set to have fewer than 10 sites in the "Sites to Search section" and "Search the entire web" option set to OFF.

Furthermore, what are some steps to makeTo run a restricted search, is it necessary to include this command, or is it sufficient to have 10 or fewer sites in the "Sites to Search" section, and the "Search the entire web" option set to OFF?

**Comment by busunkim96** [comment]
How often do you see the error? 

The only way for that error to exist would be the `siterestrict` resource not existing in the discovery document.

**Comment by whatsananne** [comment]
Hi,
Honestly, pretty randomly. Sometimes every 200 calls, sometimes every other call. When I run without siterestrict(), I never receive the error.

I've been going off the documentation from from [here](https://developers.google.com/custom-search/v1/reference/rest/v1/siterestrict). Can you point me to where I should be looking in the discovery document?

**Comment by busunkim96** [comment]
Hi @whatsananne,

The Python library pulls a JSON representation of the API from https://www.googleapis.com/discovery/v1/apis/customsearch/v1/rest and constructs a service client. So if a resource is disappearing, it would mean either:

* There is something non-deterministic about `discovery.build()`
* The published discovery document itself is changing.

I tested this out with a script that repeatedly builds the service until it encounters the AttributeError. It looks like it is actually the second case - the discovery document sometimes has both `cse` and `siterestrict` as top-level resources instead of placing `siterestrict` under `cse`.   I am filing a bug with the API team to ask them to investigate.

```py
import json

import requests 
from googleapiclient import discovery

DISCOVERY_URL = "https://www.googleapis.com/discovery/v1/apis/customsearch/v1/rest"

for i in range(0, 100000):
    resp = requests.get(DISCOVERY_URL)
    discovery_doc = resp.json()
    service = discovery.build_from_document(discovery_doc)
    try:
      service.cse().siterestrict()
    except AttributeError:
      with open("bad_siterestrict_v1.json", "w") as f:
        f.write(json.dumps(discovery_doc))
        break

```



As a workaround, you can save a good copy fo the discovery doc from https://www.googleapis.com/discovery/v1/apis/customsearch/v1/rest and use `discovery.build_from_document()`

```py
import json
from googleapiclient import discovery

with open("customsearch_v1.json") as f:
    document = json.load(f)

service = discovery.build_from_document(document)
```

When did you start experiencing this behavior?

**Comment by busunkim96** [comment]
Googlers, see internal issue 155117315.

The infrequency of the error appearing seems to be a result of new discovery docs being rolled out gradually.

**Comment by whatsananne** [comment]
Thank you so much advice, I will try to that workaround. I began using the API about 10 days ago, and this error began occurring right away.

**Comment by salty-horse** [comment]
This started happening for me today on a single server.
`build('androidpublisher', 'v3')` didn't have `purchases().subscriptions()`.

I replaced that line with this, which works for some reason:
```
DISCOVERY_URL = "https://www.googleapis.com/discovery/v1/apis/androidpublisher/v3/rest"
discovery_doc = requests.get(DISCOVERY_URL).json()
build_from_document(discovery_doc)
```

**Comment by busunkim96** [comment]
@salty-horse Most likely android publisher is rolling out a new discovery doc. Did the failure occur multiple times?

**Comment by salty-horse** [comment]
The error occurred consistently for the hour I spent investigating it.
Any idea why my workaround  works? Is the URL I'm downloading "manually" different than the one the library is using?

**Comment by busunkim96** [comment]
Discovery docs are rolled out gradually, so it's normal to see two different versions at the same time. When I was debugging the CSE error I only got the newer discovery doc once every ten thousand or so requests.

I've reached out to some folks on the Android Publisher team to ask them if they have any recent discovery doc rollouts.

**Comment by busunkim96** [comment]
@salty-horse It looks like that must have been a transient error. I confirmed with the backend folks that they haven't rolled out a new discovery doc recently.

Please open a new issue if you start experiencing problems.
