### ISSUE TITLE
Missing docs for projects().locations().flexTemplates() in dataflow_v1b3 API

### ISSUE THREAD

**Issue by mik-laj** [googleapis/google-api-python-client#865]
Hello,

On the page: http://googleapis.github.io/google-api-python-client/docs/dyn/dataflow_v1b3.projects.locations.html
There is a lack of documentation for projects().locations().flexTemplates()

However, this resource is available in the API.
```python
from googleapiclient.discovery import build
dataflow_service = build('dataflow', 'v1b3')
projects_resource = dataflow_service.projects()
locations_resource = projects_resource.locations()
flex_templates_resource = locations_resource.flexTemplates()

print(flex_templates_resource.launch.__doc__)
```

Best regards,
Kamil

**Comment by alvyjudy** [comment]
The document for ``flexTemplates()`` (shown in screenshots below) appears to be missing under ``doc/dyn/`` directory. After running the ``describe.py`` script on my computer, the file was restored:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/53921639/81224467-bf539580-8fb5-11ea-9c9e-e930e0106b61.png">

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/53921639/81224482-c5e20d00-8fb5-11ea-955e-fd8cfcf11099.png">


Should I submit a PR to update the docs?

**Comment by busunkim96** [comment]
This appears to have been resolved in the most recent regeneration.
