### ISSUE TITLE
Apps Script projects().deployments().update() method seems to be dropping original `entryPoints` of the deployment

### ISSUE THREAD

**Issue by AhtiAhde** [googleapis/google-api-python-client#866]
- OS: macOS 10.15.3
  - Python version: 3.6.8
  - pip version: 20.0.2
  - `google-api-python-client` version: 1.8.0

#### Steps to reproduce

  1. Create an Apps Script project, connect it to GCP project
  2. Create a deployment with Execution API

### Expected Behaviour

After a lot of digging, it seems like if I want to generate things with Apps Script I should update the contents of the App Script project to match whatever I want to create, make a new version from it, update the Execution API deployment to match that version and then use the Execution API scripts().run(). This works if I do deployment manually on the UI, but if I do the deployment by using projects().deployments().update(), the scripts().run() will give me 404.

I can successfully run the scripts().run() with the updated scripts if I do the deployment manually in the UI.

### The Bug

The manually generated deployment looks like this with the Python projects().deployments().list():
```
{'deploymentId': 'deployment id X', 'deploymentConfig': {'scriptId': 'script id X', 'versionNumber': 18, 'manifestFileName': 'appsscript', 'description': 'oneplatform api meta-version'}, 'updateTime': '2020-04-18T14:58:26.807Z', 'entryPoints': [{'entryPointType': 'EXECUTION_API', 'executionApi': {'entryPointConfig': {'access': 'MYSELF'}}}]}
```

If I use the Python projects().deployments().update(), I get:
```
{'deploymentId': 'deployment id X', 'deploymentConfig': {'scriptId': 'script id Y', 'versionNumber': 19, 'manifestFileName': 'appsscript', 'description': 'oneplatform api meta-version'}, 'updateTime': '2020-04-18T14:58:26.807Z',}
```

So the deployment id X and script id Y remain the same as expected, the version number is incremented by one as intended, but the `entryPoints` will be deleted by the update.

After doing some research on this one, it seems like other API clients are also suffering from similar issues as if the API itself would always drop all `entryPoints` when updating the version number of a deployment by using the update or when creating a new deployment with fresh version number.

**Comment by AhtiAhde** [comment]
The GCP project I am connecting the Apps Script project has been made in 2018, if that helps. I remember there were some differences regarding how new your GCP project was.

**Comment by busunkim96** [comment]
Hi @AhtiAhde. You mentioned other API clients - did you test this out with other language client libraries? If this is happening across languages it is most likely a problem with the API itself, and we'll have to file an issue for the backend folks.

**Comment by kpoman** [comment]
This is happening too with the clasp command that uses the update method for deployments. It drops the entrypoint for, say, webapps, thus making them inaccessible (having to go to the online Apps Script editor). Very annoying.

**Comment by busunkim96** [comment]
@kpoman It looks like this is an API problem. Please file an issue with the Apps Script API folks. https://developers.google.com/apps-script/api/support

**Comment by eswidler** [comment]
@AhtiAhde Did you ever end up filing a bug on this?  I'm currently using the ruby client and don't see any way to update the WebAppConfig.  Even the REST API doesn't appear to show that as an updatable param when creating a deployment.  You can apparently read the current WebAppConfig though on the deployments [https://developers.google.com/apps-script/api/reference/rest/v1/projects.deployments](https://developers.google.com/apps-script/api/reference/rest/v1/projects.deployments)

I want to change the access of the webapp, but it looks like the only way to do that currently is through the UI.
