### ISSUE TITLE
AttributeError: module 'googleapiclient' has no attribute '__version__'

### ISSUE THREAD

**Issue by davidstrouk** [googleapis/google-api-python-client#870]
When importing new version of google-api-python-client
`from apiclient import discovery`
i'm getting the error
`AttributeError: module 'googleapiclient' has no attribute '__version__'`

https://github.com/googleapis/google-api-python-client/blob/84d45619d753cb04d957651886231034194058b6/apiclient/__init__.py#L22

i guess this happens since you have removed `__version__` var from `googleapiclient/__init__.py`

https://github.com/googleapis/google-api-python-client/commit/f706cfd821ab7457e5db37abfc3619772657dd0e#diff-b926d296d4c856bcbf877809e4523562L15

can you please fix? @busunkim96 @mik-laj @crwilcox 

Traceback:
```    from apiclient import discovery
  File "/usr/local/lib/python3.7/site-packages/apiclient/__init__.py", line 22, in <module>
    __version__ = googleapiclient.__version__
AttributeError: module 'googleapiclient' has no attribute '__version__'

**Comment by mik-laj** [comment]
Thanks for the report.
https://github.com/googleapis/google-api-python-client/blob/master/apiclient/__init__.py#L22

**Comment by busunkim96** [comment]
@davidstrouk Thanks for the report!  As an FYI, we generally recommend you import from `googleapiclient` now. You shouldn't have to make any other changes.

```py
from googleapiclient import discovery
```

**Comment by ravana69** [comment]
Gend mar do google ki bkc
