### ISSUE TITLE
AttributeError: 'Resource' object has no attribute 'management'

### ISSUE THREAD

**Issue by kumaF** [googleapis/google-api-python-client#880]
In `google-api-python-client` v4 im getting this error when im trying to get the account summery.

```
analytics = discovery.build('analyticsreporting', 'v4', credentials=credentials)
account_summaries = analytics.management().accountSummaries().list().execute()
```

with v3 it's working fine but Im basically using v4 for my dev process.

```
analytics = discovery.build('analytics', 'v3', credentials=credentials)
account_summaries = analytics.management().accountSummaries().list().execute()
```

**Comment by busunkim96** [comment]
Hi,

The `v4` API is not a drop in replacement for all the `v3` APIs. See https://developers.google.com/analytics/devguides/reporting/core/v4#choosing_which_version_of_the_analytics_reporting_api_to_use

> The Analytics Reporting API v4 is separate from other v3 APIs (e.g., Management API, Metadata API, etc.) and requires a separate client library. This may be a consideration for staying with API v3 if you are building an application (i.e., an mobile application) with space constraints.

**Comment by kumaF** [comment]
Thanks for the clarification. Actually I was using both v3 and v4 in the process. I just needed to confirm is there any available option in v4. Thanks, @busunkim96
