### ISSUE TITLE
Bad link on main page

### ISSUE THREAD

**Issue by rmcloughlin** [googleapis/google-api-python-client#881]
On this page:  https://github.com/googleapis/google-api-python-client there is this line at the top (above the code listing):

_The official Python client library for Google's discovery based APIs.  http://google.github.io/google-api-python-client_

The link is insecure and it immediately redirects.  The link should be https://googleapis.github.io/google-api-python-client/ (I think).

**Comment by danoscarmike** [comment]
@rmcloughlin thanks for surfacing this. I've updated the link to a more useful page in the docs folder.
