### ISSUE TITLE
YouTube Data API Build Function doesn´t work

### ISSUE THREAD

**Issue by leonardoparis** [googleapis/google-api-python-client#883]
#### Environment details
  - OS type and version: Windows
  - Python version: 3.6
  - pip version: 19.3.1
  - `google-api-python-client` version: When running the this command `_pip show google-api-python-client_` it shows **1.7.12** but in my code I do !pip install _google-api-python-client --upgrade_ and the version becomes **1.8.2**

#### Steps to reproduce
I will try to keep this as short as possible, so I will focus right in the beginning of the code where the error message occurs:

  1. On Colab, install the google api python client, put your previously obtained api credentials and connection information and create the youtube object to start fetching the comments using below code (code section);

  2. When you do this for the first time, everything goes well. But if Colab disconnects or if you try to execute the exactly same code in next day, it gives the following error:

```
UnknownApiNameOrVersion                   Traceback (most recent call last)
<ipython-input-21-064a9ae417b9> in <module>()
     13 
     14 
---> 15 youtube = googleapiclient.discovery.build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)
     16 youtube
     17 

1 frames
/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options)
    241                 raise e
    242 
--> 243     raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
    244 
    245 

UnknownApiNameOrVersion: name: youtube  version: V3
```

#### Code example

```
!pip install google-api-python-client --upgrade

import os
import googleapiclient.discovery

DEVELOPER_KEY = "you_api_key"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"

youtube = googleapiclient.discovery.build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)
youtube
```

#### Stack trace
I don´t know waht Stack trace is, even when I looked for in Google. I´m very sorry for this.

Regards.

**Comment by danoscarmike** [comment]
@leonardoparis thanks for submitting this issue! We're tracking a very similar issue #882 - the problem being with the underlying discovery service which the Python library depends on. Check out the conversation in #882 for a temporary workaround until we run this down. Thanks again.

**Comment by danoscarmike** [comment]
Closing this issue now. Let's continue the discussion in #882.
