### ISSUE TITLE
"name contains" queries seem very flaky...

### ISSUE THREAD

**Issue by jamestwebber** [googleapis/google-api-python-client#884]
At first we thought it was only matching on a prefix, but after doing a few tests I found it even more confusing. It seems like `name contains` really isn't reliable?

#### Environment details

  - OS type and version: OS X, Linux
  - Python version: `3.7.6`
  - pip version: `20.0.2`
  - `google-api-python-client` version: `1.8.0`

#### Steps to reproduce

  1. Put a bunch of files in a drive folder.
  2. Try to search for them based on stuff in their names.

#### Code example

```python
# example
folder_id = "...[omitted]..."

# make some test files
for n in (
    "ASDAS_casfa-1341_asdas.csv",
    "123_asdasdas-SDASDA-xcbvcbv.xlsx",
    "fdsfs_asdasd-1231_asda.csv"
):
    with drive.put_file(drive_service, folder_id, n, binary=False):
        ...

for q in ('ASDAS', 'SDASDA', 'asda', 'sd-1231'):
    query = (
        f"'{folder_id}' in parents"
        f" AND trashed = false"
        f" AND name contains '{q}'"
    )
    print(
        drive_service.files()
        .list(q=query, pageSize=4)
        .execute()["files"]
    )
```

#### Results
Generates the output:

```
python
[{'kind': 'drive#file', 'id': '1YbHpV4QMJrn0eFuyo7jE4nwTwFvFoqZl', 'name': 'ASDAS_casfa-1341_asdas.csv', 'mimeType': 'text/csv'}]
[{'kind': 'drive#file', 'id': '10pwge2EK3rl40XPe-_WlEIeKbrGaDbUM', 'name': '123_asdasdas-SDASDA-xcbvcbv.xlsx', 'mimeType': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}]
[{'kind': 'drive#file', 'id': '1YbHpV4QMJrn0eFuyo7jE4nwTwFvFoqZl', 'name': 'ASDAS_casfa-1341_asdas.csv', 'mimeType': 'text/csv'}]
[]
```
Note that the third query should match all the files, while the last should return one.

**Comment by busunkim96** [comment]
Hi!

It looks like this is feedback related to the Drive API itself. Please follow the instructions [here](https://developers.google.com/drive/api/v3/support) to file an issue with the Drive API.

Thanks!
