### ISSUE TITLE
Batch request can't be completed using python 3.0?

### ISSUE THREAD

**Issue by AETDDraper** [googleapis/google-api-python-client#888]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Any (Colab etc)
  - Python version: `3.6.2`
  - pip version: `pip --version`
  - `google-api-python-client` version: `pip show google-api-python-client`

#### Steps to reproduce

  1. Code as below
  2.  AttributeError: module 'http' has no attribute 'request'

#### Code example

```#BATCH REQUESTS
course_id = '80789130110'
def callback(request_id, response, exception):
    if exception is not None:
        print ('Error adding user "{0}" to the course course: {1}'.format(
            request_id, exception))
    else:
        print ('User "{0}" added as a student to the course.'.format(
            response.get('profile').get('name').get('fullName')))
batch = service.new_batch_http_request(callback=callback)
for student_email in student_emails:
    student = {
        'userId': student_email
    }
    request = service.courses().students().create(courseId=course_id,
                                                  body=student)
    batch.add(request, request_id=student_email)
batch.execute(http=http)
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
@AETDDraper Hi,

I have a few more questions:

* Which API are you using? (you should see this in `discovery.build(...)`
* What version of the library are you using? `pip show google-api-python-client`

In addition, could you provide a more full stack trace so we can see where the error is being raised?

**Comment by AETDDraper** [comment]
Apologies added a different HTTP library and works fine. The documentation in the Google API is using a python 2.7 library.

**Comment by busunkim96** [comment]
Hi @AETDDraper,

 Is this working correctly for you now? If so, please close the issue.
