### ISSUE TITLE
Batch Request: 429 Backoff

### ISSUE THREAD

**Issue by AETDDraper** [googleapis/google-api-python-client#896]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I am running a Batch request for Google Classroom to get a list of all the assignments and currently hitting the API and reaching over 600 requests per minute. 

Is there a way to run back off within executing the batch API?

**Comment by busunkim96** [comment]
@AETDDraper You can specify the maximum number of retries on individual request objects (it defaults to 0). 

```py
service.foo().list().execute(num_retries=5)
```

https://github.com/googleapis/google-api-python-client/blob/43fc0cf47ac1b1e90cd52422bc5abdbbf1a8e456/googleapiclient/http.py#L846

Backoff logic:

https://github.com/googleapis/google-api-python-client/blob/43fc0cf47ac1b1e90cd52422bc5abdbbf1a8e456/googleapiclient/http.py#L160-L171
