### ISSUE TITLE
Classroom: Can't change ownerId using courses().patch

### ISSUE THREAD

**Issue by MaKTaiL** [googleapis/google-api-python-client#898]
#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.8.2
  - pip version: 20.1
  - `google-api-python-client` version: 1.8.2

#### Steps to reproduce

  1. Trying to update ownerId of a Classroom results in error `400: Request contains an invalid argument`
  2. Using the web api from https://developers.google.com/classroom/reference/rest/v1/courses/patch works just fine
  3. New owner is already a teacher in the course I'm trying to update

#### Code example

```python

id = 89400224434
email = 'email@email.com'
body = {
    'ownerId': email
}
classroom.courses().patch(id=id, body=body, updateMask='ownerId').execute()
```

**Comment by busunkim96** [comment]
@MaKTaiL Are you able to update other fields (description, room, etc.) via the library?

**Comment by MaKTaiL** [comment]
Yes, I just tried changing the 'name' and 'section' of a class (using `updateMask="name,section") and it worked.

**Comment by busunkim96** [comment]
Apologies, one more question: You can update the `ownerId` with no problem when you send a request directly to the REST API?

**Comment by MaKTaiL** [comment]
Yes. When I try to use the tool directly from the API page it works. (https://developers.google.com/classroom/reference/rest/v1/courses/patch). I believe it has something to do with the Python Client not recognizing "ownerId" as a valid updateMask and/or a valid field in the body of the request.

**Comment by MaKTaiL** [comment]
The only way to change the `ownerId` of a class is by using the `courses.patch()` request. `courses.update()` does not support it (according to the course resource page: https://developers.google.com/classroom/reference/rest/v1/courses#Course)

> ownerId:
> This must be set in a create request. Admins can also specify this field in a patch course request to transfer ownership. In other contexts, it is read-only.

**Comment by busunkim96** [comment]
Sorry, I tried to reproduce this myself but am having trouble getting the permissions correct for the two owners. Could you try turning on [httplib2 logging](https://github.com/googleapis/google-api-python-client/blob/master/docs/logging.md#http-traffic) and inspecting the requests for anything odd?

```
import httplib2
httplib2.debuglevel = 4
```

**Comment by MaKTaiL** [comment]
Hi. I do not use OAuth2. I'm currently using a service account on a GSuite environment. 

```Python
from google.oauth2 import service_account

SERVICE_ACCOUNT_FILE = 'service.json'

CLASSROOM_SCOPES = ['https://www.googleapis.com/auth/classroom.courses']

credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE)
classroom_creds = credentials.with_scopes(CLASSROOM_SCOPES).with_subject('admin@domain.com')
classroom = build('classroom', 'v1', credentials=classroom_creds)
```

**Comment by busunkim96** [comment]
Ah I see. I don't have ready access to a gsuite organization.

Would you mind increasing the httplib2 logging level in your script and pasting what you see here (minus any identifying info like auth tokens and emails)? This is the most straightforward way to check that the library is sending the correct HTTP request.

```py
import httplib2
httplib2.debuglevel = 4
```

This is what I see (reply is 403 because of unresolved permission issues).

```
connect: (classroom.googleapis.com, 443)
send: b'PATCH /v1/courses/102178419572?updateMask=ownerId&alt=json HTTP/1.1\r\nHost: classroom.googleapis.com\r\naccept: application/json\r\naccept-encoding: gzip, deflate\r\nuser-agent: (gzip)\r\nx-goog-api-client: gdcl/1.8.3 gl-python/3.7.6\r\ncontent-type: application/json\r\ncontent-length: 39\r\nauthorization: Bearer <token>\r\n\r\n'
send: b'{"ownerId": "user@gmail.com"}'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Vary: Origin
header: Vary: X-Origin
header: Vary: Referer
header: Content-Type: application/json; charset=UTF-8
header: Content-Encoding: gzip
header: Date: Thu, 14 May 2020 19:09:04 GMT
header: Server: ESF
header: Cache-Control: private
header: X-XSS-Protection: 0
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: Transfer-Encoding: chunked
```

**Comment by MaKTaiL** [comment]
Oh god, I just figured out the issue. It was totally my fault. When I activated your log I found out I was not reading the email variable correctly. It is now working as intended. I'm sorry I wasted your time, I feel really stupid right now, hahahahaha.

**Comment by busunkim96** [comment]
No problem, thanks for the update!
