### ISSUE TITLE
Remove file cache dependency for HttpMock or add cache that doesn't require oauth2client

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-api-python-client#907]
https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery.py#L354-L357

https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/file_cache.py#L41

HttpMock currently requires file_cache.

We should remove the file cache requirement for HttpMock or add some other fallback cache that doesn't require oauth2client.

**Comment by parthea** [comment]
With version 2.0 of google-api-python-client, discovery.build() will retrieve discovery documents from the client library itself rather than fetching them over the internet so caching is less important. I'm going to close this off as obsolete but please re-open it if necessary.

cc @busunkim96
