### ISSUE TITLE
Not able to add oAuth2.0 while creating enterprise.generateSignupUrl

### ISSUE THREAD

**Issue by rajmani17234** [googleapis/google-api-python-client#908]
This is my code:-
import requests

class Workingwithapi:

        def generatesignupUrl(self):
                API_ENDPOINT = "https://www.googleapis.com/androidenterprise/v1/enterprises/signupUrl"

                data = {
                        'callbackUrl': 'https://console.cloud.google.com/freetrial/signup/tos?_ga=2.48272614.1773331467.1589037178-1754419521.1588923374&_gac=1.205245988.1588949758.EAIaIQobChMI96v2i8Ok6QIVxHwrCh0qmQ9CEAAYASAAEgKMi_D_BwE'

                 
                }

                r = requests.post(url=API_ENDPOINT, data=data)

                pastebin_url = r.text

                print("The information is :%s" % pastebin_url)

object1 = Workingwithapi()
object1.generatesignupUrl()

Im trying to get a response for the generateSignupUrl but not able to see the response due to this error :-    

The information is :{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Login Required.",
        "domain": "global",
        "reason": "required",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}

**Comment by busunkim96** [comment]
@rajmani17234 Is there a tutorial you were following? You don't seem to be using this library (`google-api-python-client`) in your code.

If you're looking for documentation on using OAuth2 with Google APIs, please see https://developers.google.com/identity/protocols/oauth2

**Comment by rajmani17234** [comment]
hey @busunkim96  could you please send your email-id where in I can  talk to you about this entire tutorial i'm encountering the issue

**Comment by busunkim96** [comment]
Could you paste the link here?

**Comment by rajmani17234** [comment]
https://developers.google.com/android/work/play/emm-api/create-enterprise

So i'm following this tutorial where in the enrollment (https://developers.google.com/android/work/play/emm-api/create-enterprise#enrollment_process) section i'm trying to do the first step

**Comment by parthea** [comment]
Hi @rajmani17234,

I'm going to close off this issue due to inactivity. If you're still having trouble, please re-open it and we can take a look.
