### ISSUE TITLE
bigquerydatatransfer_v1.projects.transferConfigs.html#list doesn't support locations/{location_id} but its documentation says so

### ISSUE THREAD

**Issue by daureg** [googleapis/google-api-python-client#909]
#### Environment details

  - OS type and version: Ubuntu 16.04
  - Python version: Python 3.7.6
  - pip version: pip 20.1
  - `google-api-python-client` version: 1.8.3

#### Steps to reproduce

  1. Try to list the transfer configs of a project located in Europe
  2. The result is empty

#### Code example

```python
from google.oauth2 import service_account
import googleapiclient.discovery

SCOPES = ['https://www.googleapis.com/auth/bigquery', "https://www.googleapis.com/auth/cloud-platform"]
SERVICE_ACCOUNT_FILE = os.path.expanduser('~/work/boost/BQ_service_account.json')

credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
bqadmin = googleapiclient.discovery.build('bigquerydatatransfer', 'v1', credentials=credentials)

print(bqadmin.projects().transferConfigs().list(parent=f"projects/{c.project_id}/locations/eu").execute())
```

#### Stack trace
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-87-102c3d42ef1d> in <module>
      8 bqadmin = googleapiclient.discovery.build('bigquerydatatransfer', 'v1', credentials=credentials)
      9 
---> 10 print(bqadmin.projects().transferConfigs().list(parent=f"projects/{c.project_id}/locations/europe").execute())

~/.pyenv/versions/3.7.6/lib/python3.7/site-packages/googleapiclient/discovery.py in method(self, **kwargs)
    780                         raise TypeError(
    781                             'Parameter "%s" value "%s" does not match the pattern "%s"'
--> 782                             % (name, pvalue, regex)
    783                         )
    784 

TypeError: Parameter "parent" value "projects/spartan-thunder-179007/locations/eu" does not match the pattern "^projects/[^/]+$"
```

If I try with `parent=f"projects/{c.project_id}`, I get an empty dict. However, running this command in my shell:

```bash
bq ls --transfer_config --transfer_location=eu --project_id=spartan-thunder-179007 --max_results=50
```
returns the results I expect. Furthermore, [the documentation of the `transferConfigs.list()` method](http://googleapis.github.io/google-api-python-client/docs/dyn/bigquerydatatransfer_v1.projects.transferConfigs.html#list) reads:

```
Args:
  parent: string, Required. The BigQuery project id for which data sources
  should be returned: `projects/{project_id}` or
  `projects/{project_id}/locations/{location_id}` (required)
```

**Comment by mik-laj** [comment]
You use wrong method. You should use projects.locations.transferConfigs.list method.

**Comment by daureg** [comment]
it works indeed with the method you mentioned, thank you @mik-laj.
I'll leave the issue since I feel the documentation is a bit misleading.

**Comment by busunkim96** [comment]
I'm not too sure how much we'll be able to do about this as the documentation is generated from the discovery document. Perhaps we can ask the API team to tweak the resource descriptions? 

Will leave this open as a docs issue.

**Comment by parthea** [comment]
I'm going to close this issue as it is recommend to move to the `google-cloud-bigquery-datatransfer` library [here](https://github.com/googleapis/python-bigquery-datatransfer).
