### ISSUE TITLE
Automate publishing of `docs/dyn`

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-api-python-client#914]
These docs are manually updated by refreshing the docs/dyn directory in `master` and `gh-pages`, but this should really be automated to run nightly.

**Comment by mik-laj** [comment]
It's very annoying when the documentation is out of date.  👍  Can I help you in this task?

**Comment by parthea** [comment]
Hi @busunkim96! 

Please can you check if this issue is obsolete and wheter PR #1059 related?

**Comment by busunkim96** [comment]
Yes, this was closed by #1059.
