### ISSUE TITLE
Not all calendar events being returned by using `events().list`

### ISSUE THREAD

**Issue by WixoLeo** [googleapis/google-api-python-client#927]
## Environment details

  - OS type and version: MacOS Catalina 10.15.4
  - Python version: 3.7.5
  - pip version: 20.1.1
  - `google-api-python-client` version: 1.8.4

#### Steps to reproduce

  1. Create google service account
  2. Download credentials json
  3. Create a new calendar https://calendar.google.com/calendar/r
  4. Create 2 types of events, **the specific hour event** and the **all day event**
  5. Share that calendar with the service-account's email
  6. Write down the id of the calendar 
       Should look something like this: blablabla_j4h5k3jh5kj345kjh@group.calendar.google.com
  7. Add the contents of the credentials and the calendar id to the code example
  8. Run the example and it will return only 1 event (**specific hour event**), when expected 2, so **all day event** was missing from the response...

#### Code example

```python
from google.oauth2 import service_account
from googleapiclient.discovery import build
from datetime import datetime, timedelta


def get_events(calendar_id: str, secrets: dict):
    SCOPES = ['https://www.googleapis.com/auth/calendar']
    SUBJECT = secrets['client_email']
    credentials = service_account.Credentials.from_service_account_info(
        secrets, scopes=SCOPES)
    delegated_credentials = credentials.with_subject(SUBJECT)
    service = build(
        'calendar', 'v3', credentials=delegated_credentials, cache_discovery=False)

    now = (datetime.utcnow() - timedelta(days=2)).isoformat() + 'Z'
    time_max = (datetime.utcnow() + timedelta(days=2)).isoformat() + 'Z'
    events = service.events().list(calendarId=calendar_id, timeMin=now, timeMax=time_max, maxResults=10,
                                   orderBy='startTime', singleEvents=True, showHiddenInvitations=True).execute()
    return events.get('items', [])


secrets = {
    # credentials goes here
}

calendarId = # your calendar id here

print(get_events(calendarId, secrets))
```

I've tried looking it up on google and stackoverflow, found nothing except that someone created a similar issue which was never really resolved.
There fore I am creating a new issue with the code example.

Thank you! <3

**Comment by busunkim96** [comment]
Hi @WixoLeo,

Thank you for filing an issue. Would you mind trying a similar request through API Explorer ('Try this API' UI on [this page](https://developers.google.com/calendar/v3/reference/events/list)) and letting us know if you have the same issue?

This will help us narrow down if the issue is with the API or with the library.

**Comment by busunkim96** [comment]
I see you posted in #623 

> So is there a fix for this? the role is set to "See All Event Details" yet I still don't get the all-day events (did anyone report this issue to google api?)

I think you likely want a scope with more permissions ('reader' at minimum) to see the all-day events. 

'freeBusyReader' provides access to free/busy information, and all day events do not impact free/busy availability.

https://developers.google.com/calendar/v3/reference/acl#resource

**Comment by WixoLeo** [comment]
> I see you posted in #623
> 
> > So is there a fix for this? the role is set to "See All Event Details" yet I still don't get the all-day events (did anyone report this issue to google api?)
> 
> I think you likely want a scope with more permissions ('reader' at minimum) to see the all-day events.
> 
> 'freeBusyReader' provides access to free/busy information, and all day events do not impact free/busy availability.
> 
> https://developers.google.com/calendar/v3/reference/acl#resource

![image](https://user-images.githubusercontent.com/52653470/83487084-11071700-a4b3-11ea-8954-4ec4561e4152.png)

The account is set to "Read all event details"
Unless you're talking about something else?

**Comment by WixoLeo** [comment]
> This will help us narrow down if the issue is with the API or with the library.

I did that, (but not with service-account since this api is setup for a oauth2) and I do get the expected 2 events.
Both second email and service account is set to "See all event details"

**Comment by WixoLeo** [comment]
Are there any news regarding this issue?

**Comment by busunkim96** [comment]
Hi @WixoLeo,

I'm not sure what the relationship of that UI option is to the ACLs. Please try inserting an ACL for the account you are using with role 'reader'.

https://developers.google.com/calendar/v3/reference/acl/insert#python

There is more general documentation about the Calendar ACLs [here](https://developers.google.com/calendar/concepts/sharing)

**Comment by WixoLeo** [comment]
So is it a bug or what do we do about it?

**Comment by busunkim96** [comment]
Hi @WixoLeo,

I just tried this (sharing a calendar with a service account email) and am not able to reproduce the issue. I can see both the hourly and all day event.

I see you're adding a subject to the credentials in your script, which I don't think is necessary in this case. Can you try with the plain service account credentials?


```py
SCOPES = ['https://www.googleapis.com/auth/calendar'] 
credentials = service_account.Credentials.from_service_account_info(secrets, 
   scopes=SCOPES)
service = build('calendar', 'v3', credentials=credentials, cache_discovery=False)
```

**Comment by WixoLeo** [comment]
Hello @busunkim96 
I've tried it, and it made no difference. Since you got it working, then probably I am doing something wrong. I will make a short video showing exactly what I am doing from scratch (from creating service account and a calendar)
Maybe that will help.

**Comment by WixoLeo** [comment]
Alright. I've recreated my steps but with my calendar instead of organisation's calendar. And it worked, it returned the expected result.
I think the reason it didn't work is because organisation strictly forced every calendar to be visible with only "Free/Busy" events.
However as you saw there, I did give the account permission to view all the event details. So I guess it's a bug in google calendar it's self.. Not sure where to report it..

Thank you for your help!

**Comment by busunkim96** [comment]
Thanks for the update @WixoLeo! I'm sure it will help someone else running into the same issue.

The best place to raise product related bugs is the [issue tracker](https://developers.google.com/calendar/support#bugs).

**Comment by PenzinAlexander** [comment]
Hello everyone. 
Faced the same issue. Did someone got a solution for this?

**Comment by CrandellWS** [comment]
+1

**Comment by CrandellWS** [comment]
yelp for me i just need to set the maxResults parameter as to not limit my results to only 250 which I still assume must be the default.

Thank you everybody....most specially for speaking opening to the public even when you think no one is listening cause thankfully we can read it later
