### ISSUE TITLE
Issue with maximum file size for deobfuscation file

### ISSUE THREAD

**Issue by mrmike** [googleapis/google-api-python-client#942]
#### Environment details

  - OS type and version: macOS Catalina 10.15.3
  - Python version: `3.7.5`
  - pip version: `20.1.1`
  - `google-api-python-client` version: `1.9.3`

#### Steps to reproduce

  1. Try to send deobfuscation file larger than 30MB
  2. Use `Edits.deobfuscationfiles: upload` method. Code example included below.
  3. Client returns `MediaUploadSizeError`. According to the [docs](https://developers.google.com/android-publisher/api-ref/edits/deobfuscationfiles/upload) maximum file size is 300MB. 

#### Code example

```python
service.edits().deobfuscationfiles().upload(
    editId=edit_id,
    packageName=PACKAGE_NAME,
    apkVersionCode=version_code,
    deobfuscationFileType="proguard",
    media_body=MediaFileUpload(mapping_file, "application/octet-stream"),
)
```

#### Stack trace
```
googleapiclient.errors.MediaUploadSizeError: Media larger than: 31457280
```

Thanks!

**Comment by busunkim96** [comment]
Hi @mrmike,

Which API are you using?

**Comment by mrmike** [comment]
Hi @busunkim96 

I'm using API v3

**Comment by busunkim96** [comment]
Ah sorry, I should have been more specific. I think you're using the Google Play Developer API? I think this may have been fixed correctly

The maxSize (314572800) looks correct in the discovery document. Would you mind trying again? I think this may have been fixed recently.

https://www.googleapis.com/discovery/v1/apis/androidpublisher/v3/rest
```json
        "deobfuscationfiles": {
          "methods": {
            "upload": {
              "description": "Uploads a new deobfuscation file and attaches to the specified APK.",
              "scopes": [
                "https://www.googleapis.com/auth/androidpublisher"
              ],
              "path": "androidpublisher/v3/applications/{packageName}/edits/{editId}/apks/{apkVersionCode}/deobfuscationFiles/{deobfuscationFileType}",
              "flatPath": "androidpublisher/v3/applications/{packageName}/edits/{editId}/apks/{apkVersionCode}/deobfuscationFiles/{deobfuscationFileType}",
              "mediaUpload": {
                "accept": [
                  "application/octet-stream"
                ],
                "protocols": {
                  "simple": {
                    "multipart": true,
                    "path": "/upload/androidpublisher/v3/applications/{packageName}/edits/{editId}/apks/{apkVersionCode}/deobfuscationFiles/{deobfuscationFileType}"
                  }
                },
                "maxSize": "314572800"
              },
```

**Comment by mrmike** [comment]
Yes, I'm using Google Play Developer API. I have tried again and script works now.

It looks like there was a problem with incorrect maxSize value. Before the discovery document was returning `31457280.

Issue can be closed. Thanks!
