### ISSUE TITLE
Documentation does not explain how to create service account files

### ISSUE THREAD

**Issue by pcolmer** [googleapis/google-api-python-client#946]
https://github.com/googleapis/google-api-python-client/blob/master/docs/oauth-server.md makes reference to `SERVICE_ACCOUNT_FILE` but doesn't explain where it comes from or what it contains.

Digging deeper leads me to https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#google.oauth2.service_account.Credentials which says:

"To create credentials using a Google service account private key JSON file"

but that doesn't explain how or where to get the file from either.

I did end up discovering https://stackoverflow.com/questions/46287267/how-can-i-get-the-file-service-account-json-for-google-translate-api which also confirms that if I haven't got the JSON file, I've got to create a new service account :(.

It would help if the documentation made the steps to setting up the service account clearer ...

**Comment by busunkim96** [comment]
https://cloud.google.com/iam/docs/creating-managing-service-account-keys is the best source for general information on obtaining service accounts. The auth documentation also touches on it briefly https://google-auth.readthedocs.io/en/latest/user-guide.html#service-account-private-key-files.

There's definitely lots of room to make this clearer though, thank you for taking the time to file a bug!

**Comment by prakhargurunani** [comment]
@busunkim96 Can I add this in docs ?

**Comment by mik-laj** [comment]
@busunkim96 Any response?
