### ISSUE TITLE
Admin API - Users: update Request - Error 409: Entity already exists

### ISSUE THREAD

**Issue by CoreyGriffin** [googleapis/google-api-python-client#949]
#### Environment details
  - Python version: `3.7`
  - `google-api-python-client` version: `1.7.7`

#### Steps to reproduce

All of a sudden running into `409` errors when making user update requests ... having the same issue with the [google-api-go-client](https://github.com/googleapis/google-api-go-client) ([x-post](https://github.com/googleapis/google-api-go-client/issues/556))

The context here is account deprovisioning so current order of operations from our perspective is:
- Set `suspended` to `true`
- Set `"includeInGlobalAddressList"` to `false`
- Remove any aliases
- Change the primary email
- Send `Users: update` request
- Send `Users.aliases: delete` request to remove original email

The request seems to succeed and actually make the changes to the account in G Suite but then returns `googleapi: Error 409: Entity already exists., duplicate`. This is relatively new behavior so not sure if it is a result of a change on the API side.

## Expected Response
- `200 Status Code` 
- updated `User Resource`

## Actual Response
- Updates **are** made in G Suite
- `409 Status Code`
- `Error: 409: Entity already exists., duplicate`.

Any ideas here...seems like the update call should be idempotent but maybe we're running into a race condition when we make the update call on the backend?

#### Code example

```python
        new_primary_email = "x-{}".format(self.user_email)
        body = {
            "primaryEmail": new_primary_email,
            "suspended": True,
            "includeInGlobalAddressList": False,
        }
        account_update_status = self.gsuite_directory.update_user(
            user_key=self.user_email, 
            body=body
        )
        if account_update_status:
            log.info(
                f"Successfully updated the account for {self.user_email})

       # Remove the old email alias since we renamed the email during update
        alias_status = self.gsuite_directory.delete_alias(
            user_key=new_primary_email, 
            old_email=self.user_email,
        )
```

#### Stack trace
```
'<HttpError 409 when requesting https://www.googleapis.com/admin/directory/v1/users/email%40domain.com?alt=json returned "Entity already exists.">'
```

Checked for existing issues... https://github.com/googleapis/google-api-python-client/issues/846 seems somewhat related but is for a different API...appears to be the same side effects though

**Comment by busunkim96** [comment]
It looks like this is most likely a backend issue, since nothing has changed in the client library. Please file an issue on the [Admin SDK Issue Tracker](https://issuetracker.google.com/savedsearches/566232).
