### ISSUE TITLE
Google Drive Python API: Batch Uploading of Files

### ISSUE THREAD

**Issue by mhdadk** [googleapis/google-api-python-client#950]
I am aware of [this](https://developers.google.com/drive/api/v3/batch) note in regards to batch uploading of files:

> Note: Currently, Google Drive does not support batch operations for media, either for upload or download.

So the only way of uploading a large number of files is using a large number of HTTP requests? Something like:
```python
from googleapiclient.http import MediaFileUpload
for file, metadata in zip(files, metadatas):
    media = MediaFileUpload(file, chunksize = -1, resumable = True)
    drive.files().create(body = metadata, media_body = media).execute()
```
According to [this](https://developers.google.com/drive/api/v3/batch#overview):
> Each HTTP connection that your client makes results in a certain amount of overhead.

I want to make the process of uploading a large number of files as efficient as possible. How can I do that given the constraints mentioned above?

Thanks a lot for the help.

**Comment by busunkim96** [comment]
Yes, you will have to use a separate HTTP request for each file since the API does not support batching.

 Please read the note on [thread safety](https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md#thread-safety) if you end up using multiple threads.
