### ISSUE TITLE
FR: sample code for version history download of specific range on specific sheet

### ISSUE THREAD

**Issue by covh** [googleapis/google-api-python-client#954]
# Feature request

Example python code how to 
(1) download all revisions of a specific googlesheet id, and then  
(2) download a certain range (here: A3:E12)
(3) from a specific sheet ("tab") (here SHEETNAME)
(4) in a specific version (here: 252)  
(5) of all (or selected) older revisions of that googlesheet-id.

Thank you very much!

-----------

 **feature request related to a problem:**
Download hundreds of *older versions* (version history) of the same googlesheet, that has been heavily worked on during several months. It is a multi-sheet document, and I need only one "tab" (sheet) with the name SHEETNAME, and in that only a certain range (e.g. A3:E12).

 **Describe the solution you'd like**
One snapshot CSV per day would suffice, perhaps the last one in the evening.

 **Describe alternatives you've considered**
* spreadsheets/export?id=... = https://docs.google.com/spreadsheets/export?id={id}&revision=252&exportFormat=CSV&range=A3:E12&sheet=SHEETNAME
* spreadsheets/d/{id}/gviz/tq ... = https://docs.google.com/spreadsheets/d/{id}/gviz/tq?tqx=out:csv&sheet=SHEETNAME&range=A3:E12&revision=252

somehow those approaches do not seem to work, because either the SHEETNAME is ignored, or the specific revision.

I've made a beginning [here](https://github.com/covh/covviz/blob/8a057ed4964e65ceb90964df414e5bbf416f6df4/src/googlePython.py#L118-L126) but got stuck with the above question.

---

[ As a smaller side problem, I seem to be able to download the revision history of my own sheet, but not the revision history of someone else's sheet, or what am I doing wrong? ]

---

Thanks a lot

**Comment by busunkim96** [comment]
Hi @covh,

GSuite samples belong in https://github.com/gsuitedevs/python-samples. Please file an issue there. Thanks!

**Comment by avneradania1** [comment]
Same here, trying to find a way to download an Excel with specific revision, but did not find any option in Google API
