### ISSUE TITLE
Resumable upload / example with .next_chunck() ?

### ISSUE THREAD

**Issue by yohplala** [googleapis/google-api-python-client#955]
Hello,
I would like to implement properly resumable upload with error management, as hinted [here](https://github.com/googleapis/google-api-python-client/blob/master/docs/media.md#resumable-media-chunked-upload).

```python
media = MediaFileUpload('pig.png', mimetype='image/png', resumable=True)
request = farm.animals().insert(media_body=media, body={'name': 'Pig'})
response = None
while response is None:
  status, response = request.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)
print "Upload Complete!"

except apiclient.errors.HttpError, e:
  if e.resp.status in [404]:
    # Start the upload all over again.
  elif e.resp.status in [500, 502, 503, 504]:
    # Call next_chunk() again, but use an exponential backoff for repeated errors.
  else:
    # Do not retry. Log the error and fail.
```

I think I have found a suitable example from which starting, considering following piece of code, presented [here](https://www.peterbe.com/plog/best-practice-with-retries-with-requests).

```python
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry


def requests_retry_session(
    retries=3,
    backoff_factor=0.3,
    status_forcelist=(500, 502, 504),
    session=None,
):
    session = session or requests.Session()
    retry = Retry(
        total=retries,
        read=retries,
        connect=retries,
        backoff_factor=backoff_factor,
        status_forcelist=status_forcelist,
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount('http://', adapter)
    session.mount('https://', adapter)
    return session
```
Well, I will see.
First, let's come back on code presented in Google API doc.
Please, is it possible to have some clarifications about this 'insert()' method here?
`request = farm.animals().insert(media_body=media, body={'name': 'Pig'})`

Currently, my code is looking like all the code that do not implement error handling:
```python
media = MediaFileUpload(filepath + fileName, resumable=True)
file = drive.files().create(body=file_metadata,
                            media_body=media,
                            fields='name,id').execute()
```
I have had a look into the 'files' documentation [here](https://developers.google.com/resources/api-libraries/documentation/drive/v3/python/latest/drive_v3.files.html).
I cannot find any hint about an 'insert()' method.
As far as I understand, it is this method that will return an object with a next_chunk() method, right?

Please, could someone shed some light on this topic?
Thanks for your help,
Bests,

**Comment by yohplala** [comment]
Am I right in understand that `.insert()` is specific to Google API v2, and deprrecated in v3?
If yes, please, is it possible to clarify if Google API v3 handles by itself error codes (and make retries by itself if relevant)?

Thanks for the information!
Bests,

**Comment by busunkim96** [comment]
Hi @yohplala,

> I think I have found a suitable example from which starting, considering following piece of code, presented here.

This library doesn't use requests, so I don't think you'll be able to use that here.

> I have had a look into the 'files' documentation here.
> I cannot find any hint about an 'insert()' method.
> As far as I understand, it is this method that will return an object with a next_chunk() method, right?

The `insert` method is an example method on the hypothetical API, so you can substitute it the real method for the API you are working on.

> Am I right in understanding that .insert() is specific to Google API v2, and deprecated in v3?
> If yes, please, is it possible to clarify if Google API v3 handles by itself error codes (and make retries by itself if relevant)?


v2 vs v3 of the Drive API should not make a difference here. There is some retry logic which you can see [here](https://github.com/googleapis/google-api-python-client/blob/48f503fbae07b4b80773f526c16ea30e0e65806b/googleapiclient/http.py#L136).

I'm not clear on what the issue is, would you mind clarifying?

**Comment by yohplala** [comment]
Hi @busunkim96 ,
Thank you very much for your reply, I really appreciate.
Yes, ok I realize, some information are missing.
And with your comment you already answered partly my question.

Ok, so my question now resumes to : "Is `retry()` already implemented in Google Drive API v3 when uploading a media"?

#### Use of 'next_chunck()' to upload a media
```python
from google.oauth2 import service_account
from googleapiclient import discovery, http

# Get authorization
credentials = service_account.Credentials.from_service_account_file('/home/me/Documents/code/store3.json')
scoped_credentials = credentials.with_scopes(['https://www.googleapis.com/auth/drive'])
drive = discovery.build('drive', 'v3', credentials=scoped_credentials)

# Request
file_name = '/home/me/Documents/code/let_get_crazy.txt'
folder_id = '1M_YMEVrrYRj0lZCQMNL_Ey6vndPE7LgY'
media = http.MediaFileUpload(file_name, resumable=True)
file_metadata = {'name': 'let_get_crazy.txt', 'parents': [folder_id]}
request = drive.files().create(body=file_metadata, media_body=media, fields='id')

while response is None:
  status, response = request.next_chunk()
print("Upload Complete!")
```
Thanks for pointing out `_retry_request()` method [here](https://github.com/googleapis/google-api-python-client/blob/48f503fbae07b4b80773f526c16ea30e0e65806b/googleapiclient/http.py#L136).
Coming back to the piece of code available from documentation:
```python
except apiclient.errors.HttpError, e:
  if e.resp.status in [404]:
    # Start the upload all over again.
  elif e.resp.status in [500, 502, 503, 504]:
    # Call next_chunk() again, but use an exponential backoff for repeated errors.
  else:
    # Do not retry. Log the error and fail.
```
When looking at the `next_chunk()` method from `HttpRequest` class, I see it already accepts a `num_retries` parameter.
Re-using bits of code from the example above, does this mean that all `e.resp.status in [500, 502, 503, 504]` are already handled by `next_chunk()` method and that I should then only retry from scratch in case of `e.resp.status in [404]`?

Thanks for the information, and thanks again for your 1st answer.
Have a good evening,
Bests

**Comment by yohplala** [comment]
Hello,

Please, is it possible to have this information: which error codes are currently handled in `next_chunk()` methods of the `http` object?
(such as the one returned with `drive.files().create()` function or `http.MediaIoBaseDownload()` class instanciation)

Thanks for your help!
Bests,

**Comment by busunkim96** [comment]
Hi,

Here's is the logic to determine which error codes are retried: https://github.com/googleapis/google-api-python-client/blob/48f503fbae07b4b80773f526c16ea30e0e65806b/googleapiclient/http.py#L91-L133
