### ISSUE TITLE
Thread safety with v3 ensured by default?

### ISSUE THREAD

**Issue by yohplala** [googleapis/google-api-python-client#956]
Hello,

I was trying to 'implement' (or let's say 'copy') code from [this documentation page](https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md#thread-safety) to ensure thread safety.

When doing so, and running following code, I get an error message.

```python
credentials = service_account.Credentials.from_service_account_file('/home/me/Documents/code/app-storage3.json')
scoped_credentials = credentials.with_scopes(['https://www.googleapis.com/auth/drive'])

# To ensure thread safety:
# https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md#thread-safety
# Create a new Http() object for every request
def build_request(http, *args, **kwargs):
  new_http = httplib2.Http()
  return HttpRequest(new_http, *args, **kwargs)

drive = build('drive', 'v3', credentials=scoped_credentials, requestBuilder=build_request)
results = drive.files().list(pageSize=10, fields="nextPageToken, files(id, name)").execute()
items = results.get('files', [])
```

Error message:
```python
HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files?pageSize=10&fields=nextPageToken%2C+files%28id%2C+name%29&alt=json returned "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.">
```

However, everything works just fine with:
```python
credentials = service_account.Credentials.from_service_account_file('/home/me/Documents/code/app-storage3.json')
scoped_credentials = credentials.with_scopes(['https://www.googleapis.com/auth/drive'])

drive = build('drive', 'v3', credentials=scoped_credentials)
results = drive.files().list(pageSize=10, fields="nextPageToken, files(id, name)").execute()
items = results.get('files', [])
```

Reading @theacodes ' comment from [this ticket](https://github.com/googleapis/google-auth-library-python/issues/190):
`when using google-auth with google-api-python-client you only need to specify the credentials to discovery - you do not need to construct your own http instance`

So am I right in understanding that, similar to [my previous ticket](https://github.com/googleapis/google-api-python-client/issues/955), this documentation applies to Google API v2, but not v3?

If so, then for v3, is there any risk vs multi-threading?

thanks for your feedback,
Bests

**Comment by busunkim96** [comment]
`v2` vs `v3` of the Drive API should not make a difference here.

I believe you are seeing an error because the HTTP instance provided by `build_request` is not authorized with credentials. 

For comparison here is the default flow:
https://github.com/googleapis/google-api-python-client/blob/66bb32cc70353296dbf1876ae8c22baf6562cfb9/googleapiclient/discovery.py#L376-L384

You can reference the code in https://github.com/googleapis/google-api-python-client/blob/48f503fbae07b4b80773f526c16ea30e0e65806b/googleapiclient/_auth.py to create an authorized http instance.

**Comment by yohplala** [comment]
@busunkim96 
Thanks again for your help.

Ok, so, from [_auth_py](https://github.com/googleapis/google-api-python-client/blob/48f503fbae07b4b80773f526c16ea30e0e65806b/googleapiclient/_auth.py), I see, I can try to use either method:
- `http = google_auth_httplib2.AuthorizedHttp(credentials, http=build_http())`
- or `http = credentials.authorize(build_http())`

Well, in each case, I get a different error message.

### `http = google_auth_httplib2.AuthorizedHttp(credentials, http=build_http())`
```python
from google.oauth2 import service_account
from googleapiclient import discovery, http

# Get authorization
credentials = service_account.Credentials.from_service_account_file('/home/me/Documents/code/store3.json')
scoped_credentials = credentials.with_scopes(['https://www.googleapis.com/auth/drive'])

def build_request(creds):
  new_http = creds.authorize(build_http())
  return http.HttpRequest(new_http)

drive = discovery.build('drive', 'v3', credentials=scoped_credentials, requestBuilder=build_request(scoped_credentials))
```
Error:
`AttributeError: 'Credentials' object has no attribute 'authorize'`

### `credentials.authorize(build_http())`
```python
from google.oauth2 import service_account
from googleapiclient import discovery, http

# Get authorization
credentials = service_account.Credentials.from_service_account_file('/home/me/Documents/code/store3.json')
scoped_credentials = credentials.with_scopes(['https://www.googleapis.com/auth/drive'])

import google_auth_httplib2
def build_request(creds):
  return google_auth_httplib2.AuthorizedHttp(creds, http=http.build_http())

drive = discovery.build('drive', 'v3', credentials=scoped_credentials, requestBuilder=build_request(scoped_credentials))
results = drive.files().list(pageSize=10, fields="nextPageToken, files(id, name)").execute()
```
(notice the error message appears with the one last additional line)
Error:
`TypeError: 'AuthorizedHttp' object is not callable`

Hmmm, I am lost.
Please, do you know where the trouble may come from?
Thanks for your help.
Bests

**Comment by yohplala** [comment]
Ok, finally succeeded with following piece of code:
```python
from googleapiclient import _auth
new_http = _auth.authorized_http(scoped_credentials)
drive = discovery.build('drive', 'v3', credentials=scoped_credentials)

# For listing
results = drive.files().list(pageSize=10, fields="nextPageToken, files(id, name)")\
                       .execute(http=new_http)
items = results.get('files', [])
```
Thanks for your help,
Bests,

**Comment by busunkim96** [comment]
Good to hear you were able to get this to work, and thank you for providing a code sample! I'm sure it will help someone else running into the same issue.
