### ISSUE TITLE
How do I add members to a google group in batches using python

### ISSUE THREAD

**Issue by vitaminx** [googleapis/google-api-python-client#958]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

How do I add members to a google group in batches using python

I am a GSuite account
Add google group members with web version
Keep making mistakes
The same error occurs when uploading CSV files

How can I use python to add members to google groups in batches, using google's api

**Comment by busunkim96** [comment]
Hi,

I think you're asking about batch requests. You can read documentation on that at https://github.com/googleapis/google-api-python-client/blob/master/docs/batch.md

Are you running into errors?

**Comment by parthea** [comment]
Hi @vitaminx, 

I'm going to close this issue but if you're still having trouble please re-open it with additional information.
