### ISSUE TITLE
Add etag support when using service account

### ISSUE THREAD

**Issue by dbenader** [googleapis/google-api-python-client#974]
#### Environment details

  - OS type mac:
  - Python version: python 3.7
  - pip version: pip 20.1.1
  - `google-api-python-client` version: Version: 1.7.11

There does not seem to be a clear way to utilize etags in conjunction with google.oauth2.service_account

**credentials = service_account.Credentials.from_service_account_info(SERVICE_ACCOUNT, scopes=SCOPES)
youtube = googleapiclient.discovery.build('youtube', 'v3', credentials=credentials)**

If i pass a custom http object like so:
**youtube = googleapiclient.discovery.build('youtube', 'v3', http=http, credentials=credentials)**

I receive this error:

_ValueError('Arguments http and credentials are mutually exclusive.')_

**Comment by busunkim96** [comment]
Hi @dbenader,

If you use an `http` object, you cannot pass a credentials object. The http instance should be authorized with the credentials. You can see how the library constructs the http instance [here](https://github.com/googleapis/google-api-python-client/blob/66bb32cc70353296dbf1876ae8c22baf6562cfb9/googleapiclient/_auth.py#L79-L104).

```py
from googleapiclient.http import build_http
import google_auth_httplib2


http = google_auth_httplib2.AuthorizedHttp(credentials, http=build_http())
```

**Comment by parthea** [comment]
I'm going to close this off as a resolution was found and we already have an example with the above code in [thread_safety.md](https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md).
