### ISSUE TITLE
resource manager project.project_id doesn't match the value from restful API.

### ISSUE THREAD

**Issue by shanwei8** [googleapis/google-api-python-client#978]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-python-client/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

When I use asset inventory API, search_all_iam_policy and search_all_resource, I noticed some of the project_id doesn't match the value with restful client, or the beta version client created by discovery.build 

  - OS type and version:
  - Python version: `python --version` 3.7 
  - pip version: `pip --version`
  - `google-api-python-client` version: `pip show google-api-python-client`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment]
Hi @shanwei8, can you provide some code samples?

**Comment by shanwei8** [comment]
Hi @busunkim96,  sorry for the delay. I didn't provide the example mainly because I don't have a public/shared GCP project that I can run as an example. all I worked with is production project which I can't share.
But you can easily test it with any project number you have on your hand:

```
# project_id = XXX  
client = from google.cloud.resource_manager.client import Client
project  = client.fetch_project(project_id)
same_project = client.fetch_project(project.project_number)

assert(same_project.project_number == project.project_number)
assert(same_project.project_id != project.project_id)
```

**Comment by shanwei8** [comment]
hey @busunkim96 , https://cloud.google.com/asset-inventory/docs/resource-name-format
Google updated the resource manager project_id to project_number_or_id : )

**Comment by parthea** [comment]
Hi @shanwei8 , I'm going to close this issue as it seems to be resolved. If you're still having trouble please re-open this issue with additional information.
