### ISSUE TITLE
Pylint does not recognise that Resource has 'reports' member

### ISSUE THREAD

**Issue by HFulcher** [googleapis/google-api-python-client#982]
While this does not impact runtime I'm trying to wrap my head around why Pylint does not recognise that the created service has a 'reports' function underneath it. Is this something to do with it generating these functions on the fly? 

#### Environment details

  - OS type and version: macOS Catalina - 10.15.4 (19E266)
  - Python version: `3.8.3`
  - pip version: `20.1.1`
  - `google-api-python-client` version: `1.10.0`

#### Code example

```python
    service = discovery.build('analyticsreporting',
                              'v4', credentials=credentials)
    output = service.reports()
```

#### Pylint output
```
Instance of 'Resource' has no 'reports' member
```

**Comment by busunkim96** [comment]
Hi @HFulcher,

Yes, the resources/functions don't exist until `discovery.build` is called, so linters will likely raise warnings.

**Comment by HFulcher** [comment]
Hi @busunkim96 that makes sense thanks for answering :)
