### ISSUE TITLE
Implement use of cache in Google API python client

### ISSUE THREAD

**Issue by yohplala** [googleapis/google-api-python-client#985]
Hi,

Use of a cache is given as a performance improvement tip in [Performance](https://github.com/googleapis/google-api-python-client/blob/master/docs/performance.md) page.
`You should turn on caching at the httplib2 level.`

However, the only way I see it implemented is directly in Google API python client itself, in [build_http(), L1906](https://github.com/googleapis/google-api-python-client/blob/d059ad881c7ae58c67931c48788d0bd7343ab16c/googleapiclient/http.py#L1906) sources.

If I am understanding well, this line should be replaced with:
```python
def build_http(path: str = None):
    ...
    if path is None:
        http = httplib2.Http(timeout=http_timeout)
    else:
        http = httplib2.Http(timeout=http_timeout, cache=path)
```

Please, is this update feasible, and if yes, can you carry it out?
Thanks for your help.
Have a good day,
Bests,

**Comment by busunkim96** [comment]
Hi @yohplala,

You should be able to pass a `http` object to `discovery.build` with caching enabled. 

https://github.com/googleapis/google-api-python-client/blob/d059ad881c7ae58c67931c48788d0bd7343ab16c/googleapiclient/discovery.py#L179

**Comment by yohplala** [comment]
@busunkim96 
Hi, thanks for the reply.
Thing is that I would like to manage both caching, thread-safety, and authorization within this `http`object.
This starts to be complicated.

You may remember our other discussion regarding thread-safety in #956 
I encoutnrered the problem of how providing required authorization to my `http`object.
In the end, I could manage it by using `_auth.authorized_http()`.
And within authorized_http()`, the function `build_http()` is used.
Hence my demand above to be enable caching directly within this function.

I don't see how I can follow your recommandation while still providing required authorization to my `http object?
`Please, would you be able to map your recommandation on this working code that currently manages both thread-safety and authorization? (coming from #956 )

###Current code with thread-safety, but without caching:
```python
from googleapiclient import _auth

# Initialization step: run once at the start
drive = discovery.build('drive', 'v3', credentials=scoped_credentials)

# Multi-threaded part of the code
new_http = _auth.authorized_http(scoped_credentials)
results = drive.files().list(pageSize=10, fields="nextPageToken, files(id, name)").execute(http=new_http)
items = results.get('files', [])
```

Thanks for your help!
Bests

**Comment by yohplala** [comment]
Hi,
I actually submitted my trouble to `httplib2` project, and got the answer.
If anyone is interested in the topic, here is [the ticket](https://github.com/httplib2/httplib2/issues/173).
Closing.
Bests,
