### ISSUE TITLE
applicationName parameter says "meet" is not allowed despite it having worked a day ago.

### ISSUE THREAD

**Issue by sakibstark11** [googleapis/google-api-python-client#999]
I have been using the activities API to get google meet data and it has worked flawlessly till now but yesterday I noticed that I was getting an error, 
`Parameter "applicationName" value "meet" is not an allowed value in "['APPLICATION_NAME_UNDEFINED', 'ACCESS_TRANSPARENCY', 'ADMIN', 'CALENDAR', 'CHAT', 'DRIVE', 'GCP', 'GPLUS', 'GROUPS', 'GROUPS_ENTERPRISE', 'JAMBOARD', 'LOGIN', 'MEET', 'MOBILE', 'RULES', 'SAML', 'TOKEN', 'USER_ACCOUNTS', 'CONTEXT_AWARE_ACCESS', 'CHROME']"`
Weird part is that I have not changed anything. I tried making the application name to 'MEET' but that does not do anything, I suppose something has changed but the doc still says that the application name should be meet.
Here is how I am running the code
`service = build('admin', 'reports_v1', credentials=CREDENTIALS_report)
results = service.activities().list(userKey='all', applicationName='meet', filters="meeting_code=={}".format(meet_code), eventName="call_ended").execute()
`
Extra details
**centos 7**
**python 3.6**

**Comment by vinodc** [comment]
We are seeing the same when attempting to access the Reports API (https://developers.google.com/admin-sdk/reports/v1/reference/activities/list):

`File "/home/celery/celery_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 885, in method#012    % (name, value, str(enums))#012TypeError: Parameter "applicationName" value "drive" is not an allowed value in "['APPLICATION_NAME_UNDEFINED', 'ACCESS_TRANSPARENCY', 'ADMIN', 'CALENDAR', 'CHAT', 'DRIVE', 'GCP', 'GPLUS', 'GROUPS', 'GROUPS_ENTERPRISE', 'JAMBOARD', 'LOGIN', 'MEET', 'MOBILE', 'RULES', 'SAML', 'TOKEN', 'USER_ACCOUNTS', 'CONTEXT_AWARE_ACCESS', 'CHROME']"`

The values returned from https://www.googleapis.com/discovery/v1/apis/admin/reports_v1/rest are inconsistent. "enum" is sometimes lower-case, and sometimes upper-case. While this appears to be returning the right response more often now, the SDK caches the response, so a fixed version doesn't take effect until the file cache is manually cleared.

**Comment by sakibstark11** [comment]
> We are seeing the same when attempting to access the Reports API (https://developers.google.com/admin-sdk/reports/v1/reference/activities/list):
> 
> `File "[...]/lib/python3.6/site-packages/googleapiclient/discovery.py", line 885, in method % (name, value, str(enums)) TypeError: Parameter "applicationName" value "drive" is not an allowed value in "['APPLICATION_NAME_UNDEFINED', 'ACCESS_TRANSPARENCY', 'ADMIN', 'CALENDAR', 'CHAT', 'DRIVE', 'GCP', 'GPLUS', 'GROUPS', 'GROUPS_ENTERPRISE', 'JAMBOARD', 'LOGIN', 'MEET', 'MOBILE', 'RULES', 'SAML', 'TOKEN', 'USER_ACCOUNTS', 'CONTEXT_AWARE_ACCESS', 'CHROME']"`
> 
> The values returned from https://www.googleapis.com/discovery/v1/apis/admin/reports_v1/rest are inconsistent. "enum" is sometimes lower-case, and sometimes upper-case. While this appears to be returning the right response more often now, the SDK caches the response, so a fixed version doesn't take effect until the file cache is manually cleared.
> 
> For others reading this, on Linux systems, you can check whether you have the corrupted or clean version by searching for capitalized values:
> 
> ```
> cat /tmp/google-api-python-client-discovery-doc.cache  |
>     jq -r '.["https://www.googleapis.com/discovery/v1/apis/admin/reports_v1/rest"][0]' | 
>     jq . | grep DRIVE
> ```
> 
> Just deleting the file stored in the system's temp-file directory and restarting processes should be sufficient for the SDK to re-populate the file with what is hopefully the right version, depending on what is returned by the API endpoint.

I dont have that file in my temp at all. I tried uninstalling and reinstalling and that does not seem to do anything as well.

**Comment by sakibstark11** [comment]
So, after removing all google lib files from `/home/{user}/.local/lib/python3.6/site-packages` and reinstalling them, it works.
